### ISSUE TITLE
Separate API for deploying and exporting flatpaks

### ISSUE THREAD

**Issue by smspillaz** [flatpak/flatpak#1011]
It'd be nice to be able to deploy and then export a flatpak in two separate steps.

Our use case is that we want to integrate flatpak deployments with the system updater to migrate away from having apps installed in the system ostree to having flatpak manage those apps instead. However, we can't just install the apps either before or after the update completes because then you'll either end up with two copies of the same app, or a period of time where the app is not installed (and might never be installed, if you have a flaky connection).

We were thinking that we could implement this by "deploying" (but not "exporting") the flatpaks such that there isn't any user-visible change until the user reboots and we "export" the newly installed flatpaks on early boot later on.

(Bonus points: encapsulating deployment process in a "transaction", such that if a single deployment fails, we roll back the entire transaction. Probably out of scope for this issue, however).

Thoughts?

**Comment by pwithnall** [comment]
> Probably out of scope for this issue, however

Not out of scope, in the sense that any API design should be aware of the need for transaction support. We don’t want to box ourselves into an API corner by not supporting transactions to start with.

**Comment by alexlarsson** [comment]
flatpak install/update has a `--no-deploy` option, this will pull the file data into the local depo, but not deploy it. You can then flatpak install/update --no-pull, which will install from the local repo, not going to the upstream repo.

Is this enough to do what you need?

**Comment by cosimoc** [comment]
I think we'd want those commands to be accessible through the library API as well for our use case, but it does sound close to what we need.

A difference from what @smspillaz was proposing and this API is that we could also do the deployment before the OS upgrade, just avoid exporting the app assets such as the desktop file until the last minute to make the app visible to the OS. I don't have a strong preference for either of the approaches though.

**Comment by alexlarsson** [comment]
libflatpak has equivalent APIs with the FLATPAK_UPDATE_FLAGS_NO_DEPLOY and FLATPAK_UPDATE_FLAGS_NO_PULL flags.

**Comment by alexlarsson** [comment]
The difference between pulled and deployed is already confusing enough that i'd rather not add another weird mode.

**Comment by pwithnall** [comment]
> A difference from what @smspillaz was proposing and this API is that we could also do the deployment before the OS upgrade, just avoid exporting the app assets such as the desktop file until the last minute to make the app visible to the OS. I don't have a strong preference for either of the approaches though.

There are differences in complexity (deploying is more complex than exporting, so there are more things to go wrong; although I don’t *think* any of them are likely in the same sense that pulling the content from the internet is prone to failure); and there is possibly an issue around pruning the repository. @alexlarsson, if an app is pulled into the OSTree repo, but not deployed or exported, is it going to get pruned from the repo at some point?

---

We want this for a feature to automatically install given flatpaks when doing an OS update, so the intended workflow is:
 1. eos-updater downloads OS updates into the local OSTree repository
 2. eos-updater extracts metadata from the OS updates and sees that flatpaks A, B and C need to be installed (presumably because they are no longer provided as part of the OS)
 3. eos-updater downloads apps A, B, C into the local OSTree repository
 4. If the downloads all succeeded, eos-updater deploys the OS updates into the sysroot and deploys apps A, B, C
 5. If that all succeeded, eos-updater commits the OS deployment
 6. On reboot into the new OS sysroot deployment, eos-updater deploys flatpaks A, B, C so they can be started by the user
 7. On reboot into the old OS sysroot deployment, eos-updater undeploys flatpaks A, B, C (because they are provided as part of this old OS deployment) — we need to make sure that they don’t get pruned before we next boot into the new OS sysroot deployment

(To be clear, step 7 is quite unlikely, but developers might do it, and it provides an interesting example for the robustness of the implementation.)

**Comment by smspillaz** [comment]
>  @alexlarsson, if an app is pulled into the OSTree repo, but not deployed or exported, is it going to get pruned from the repo at some point?

I think in our case, it may actually be possible to get around this problem by just wrapping the existing APIs - we can maintain our own list of pulled-but-not-yet-deployed flatpaks and then do the pruning ourselves if we hit a case where one wasn't deployed for some reason.

Of course, this presupposes an API libflatpak to prune a given flatpak from the local repository and I'm not sure if that exists.

**Comment by alexlarsson** [comment]
The old commit may be pruned at some time if we pull a newer one to the repo, but the old deployed version is not removed until we actually deployed a new version.

If you want to ensure it is not pruned you could maybe create a temporary commit to it.

**Comment by alexlarsson** [comment]
Flatpak automatically runs prune OSTREE_REPO_PRUNE_FLAGS_REFS_ONLY depth=0 after each successful install/update.
