### ISSUE TITLE
Requested extension org.gnome.Sdk.Locale is only partially installed

### ISSUE THREAD

**Issue by Jehan** [flatpak/flatpak#1059]
I am trying to make a runtime based on GNOME runtime. The SDK locale is installed:

> $ flatpak install --user gnome org.gnome.Sdk.Locale/x86_64/3.24
> org.gnome.Sdk.Locale/x86_64/3.24 already installed, skipping

But then when I run flatpak-builder, it tells me:

> error: Requested extension org.gnome.Sdk.Locale is only partially installed
> Error: Child process exited with code 1

What does it mean? Why is it partially installed? And how to install what is missing?

**Comment by Jehan** [comment]
P.S.: the manifest is there:
[org.gimp.Sdk-dev.json.txt](https://github.com/flatpak/flatpak/files/1346533/org.gimp.Sdk-dev.json.txt)

Basically I am trying to make GIMP dependencies (the ones not in the GNOME runtime, or with too low version) into a runtime based on GNOME one because I am annoyed by the build time when the cache is sometimes not hit (for a reason or another).

**Comment by alexlarsson** [comment]
I hope you don't plan to distribute this runtime? Because that is far more timeconsuming than waiting for a few builds. You have to do things like glibc security updates and regular updates to things like mesa for hardware support.

The cache hit issue will be better once we hit 0.10 which should be soon, but if you still want to go with this approach i would recommend using a base app approach instead. Here is an example electron base app: https://github.com/flathub/io.atom.electron.BaseApp/blob/master/io.atom.electron.BaseApp.json and here is an example app based on it: https://github.com/flathub/com.discordapp.Discord/blob/master/com.discordapp.Discord.json

As for the issue, you only have auto-installed locale info for your locale installed, but to build a new sdk you need info for all locales. You can get this by `flatpak update --user --subpath= org.gnome.Sdk.Locale` (or by uninstalling and manually installing it).

**Comment by alexlarsson** [comment]
Note that in general the workflow for creating runtimes is a bit more complex and a bit less well documented than for apps.

**Comment by Jehan** [comment]
> I hope you don't plan to distribute this runtime?

I was planning to (not "distribute" as advertize it for other projects to use but for the GIMP flatpak to automatically use it through the flatpakref) because I didn't know the concept of baseapp and this was the only solution I could think about to deal with this issue of crazy build times. Also that was not the only reason: I wanted to be able to share dependencies between builds (for instance if I did a stable, a dev and a nightly branch of the GIMP flatpak…).

Anyway now that I know about BaseApps, I'll use this. This same example was actually already given to me yesterday on #flatpak IRC. Maybe you should advertize this feature a little more, especially if that's the preferred way of sharing dependencies, because that was the first time I heard of it and I don't think this is discussed anywhere on the website/docs of flatpak.
