### ISSUE TITLE
Provide system- and user-wide policies

### ISSUE THREAD

**Issue by DemiMarie** [flatpak/flatpak#1135]
For example, provide a means of enforcing that no program installed by Flatpak has access to the user home directory.

**Comment by alexlarsson** [comment]
There are two things here. a) We want to make it so that at least certain permissions are listed and have to be acked before install/update. b) Even when installed one could override such permissions. 

a) Is planned, but not worked on atm
b) You can currently do this by app, using flatpak override, but it may make sense to have a global override too.

**Comment by matthiasclasen** [comment]
We have this now - during install and update, permissions are listed
