### ISSUE TITLE
comments / plans RE: cross-distribution "snap" packages by Ubunty ?

### ISSUE THREAD

**Issue by jokeyrhyme** [flatpak/flatpak#116]
Read this today:
- http://arstechnica.com/information-technology/2016/06/goodbye-apt-and-yum-ubuntus-snap-apps-are-coming-to-distros-everywhere/

Now that both flatpak and snap are cross-distribution, is there an opportunity here to collaborate?

Are there features from snap that could be included in flatpak? Vice versa?

**Comment by ximion** [comment]
Since even the attempt of many engineers to make Snappy use AppStream for metadata failed (by a decision from higher up), and Ubuntu's Snappy spec is pretty much set in stone, I highly doubt that any collaboration is possible.
Maybe for the sandbox this would be possible, if it can be used properly without the bundling part of Flatpak.

**Comment by alexlarsson** [comment]
We try to collaborate on the higher level things like the portals, however on the lower levels things are different enough that we can't realistically share anything
