### ISSUE TITLE
Misleading information about isolation / sandboxing

### ISSUE THREAD

**Issue by kravemir** [flatpak/flatpak#1204]
In gnome-software, Skype application is labelled as sandboxed:

![screenshot from 2017-11-26 00-12-27](https://user-images.githubusercontent.com/1643935/33235706-9106d71e-d23e-11e7-90b2-044a2d590197.png)

BUT, the configuration of Skype application allows full read access to home directory. This is very undesirable, as personal data are the most precious thing in computer, and they should be protected against unauthorized access.

User installing application labelled as sandboxed would think, that the application can't steal any his personal data (documents, photos,... ).

Please. If application isn't completely sandboxed regarding file-system access, then don't mark it as such. More appropriate label would be **Read only access to your/personal data**. Which would warn users, that application could act as spyware.

**Comment by directhex** [comment]
There's probably a discussion to be had about sandboxing vs. usability in this regard. For example, let's say you want to send a photo to a friend via Skype. Should that be impossible, as you propose? Or, should there be a popup, like on iPhone, where an app has to wait before being granted access to non-sandbox directories (rather than always having directories baked into the json permitted)? How do you meaningfully represent "sandboxed, except..." without overwhelming users (as shown by Android's useless list of 30-40 permissions per app).

It's a complex design decision.

**Comment by kravemir** [comment]
Yes, it's complex design decision. There are many ways to solve it. And, multiple ways can coexist.

However, I'm not asking to solve security of an access to user data. Just, don't mislead people with label sandboxed, if application can access private data of users.

I just want to be aware, that application could access my private data. For example, it wouldn't be good, if NDA covered data would be stolen. Or, some private photos of couples.

**Comment by TingPing** [comment]
I agree it is a bad idea to use that wording in GNOME-Software this early. There were mock-ups about showing more details about what exactly is allowed per-app which is in the right direction but again I think it is easy to make it seem more secure than it really is. Anyway this is still a discussion for GNOME-Software and its designers rather than flatpak.

**Comment by woprandi** [comment]
That would be nice to at least be able to override ourselves the default permssions (--nofilesystem ?) but apparently it doesn't work when it's define in the manifest

**Comment by TingPing** [comment]
@woprandi That is a separate issue, `flatpak override --user --nofilesystem=/foo/bar/ org.example.App` *should* work.

**Comment by woprandi** [comment]
@TingPing I tested --nofilesystem=home for gedit and it didn't work

**Comment by amtlib-dot-dll** [comment]
@TingPing It won't work +1

```shell
$ flatpak run --command=ls --nofilesystem=host --nofilesystem=home org.gnome.Builder
$ flatpak run --command=ls org.gnome.Builder
Desktop  Documents  Downloads  Music  Pictures	Public	Templates  Videos
$ flatpak override --user --nofilesystem=host --nofilesystem=home org.gnome.Builder
$ cat .local/share/flatpak/overrides/org.gnome.Builder 
[Context]
filesystems=
$ flatpak run --command=ls org.gnome.Builder
Desktop  Documents  Downloads  Music  Pictures	Public	Templates  Videos
```

I think the `override` feature is somehow crippled. ☹️

**Comment by mwleeds** [comment]
Recent versions of GNOME Software do a much better job communicating how well sandboxed Flatpak apps are, and the `override` command works these days.

**Comment by mwleeds** [comment]
Recent versions of GNOME Software do a much better job communicating how well sandboxed Flatpak apps are, and the `override` command works these days.
