### ISSUE TITLE
Reading errno fails in Flatpak

### ISSUE THREAD

**Issue by Kekun** [flatpak/flatpak#1213]
I encountered a very strange looking error: reading `errno` before writing to stdout fails and silently returns early.

I encountered it here: https://gitlab.gnome.org/aplazas/libmanette/blob/master/src/manette-mapping.c#L108

The first read of `errno` will silently fail and immediately return (hence testing none of the cases), the caller will somehow interpret this as returning `FALSE` and print an error message, then any subsequent read of `errno` will work just fine.

Putting a `g_message()` or a `g_critical()` just before this line makes it work. Putting a g_message() or a g_critical() just before this line makes it work.
Putting a `fprintf()` to `stderr` or `stdout`, with or without a newline *doesn't* make it work.

A user of GNOME Games (which uses libmanette) managed to change the behavior of libmanette in a similar way by simply forwarding the output of the application to some file.

Out of Flatpak it works just fine, there seems to be something fishy with errno and stdout (or stderr?) in Flatpak.

**Comment by alexlarsson** [comment]
You can't "fail" reading errno, its jus a (thread local) variable. I guess you mean it returns something unexpected. There is a bug in your code, where it relies on errno to no be set to in case the conversion succeeds. However, that is not how strtol() works. It only sets errno in error cases. If you want to rely on it being clear you need to clear it before calling strtol.

Now, obviously there is some difference in behaviour here because in the flatpak case errno is set due to an earlier failure when entering this function. It might be interesting to see what that was (i recommend running it under strace), however this is a generic bug that can be hit for other reasons too.

**Comment by Kekun** [comment]
Thanks! I thought that standard functions using `errno` would always set it, even in case of success. Setting it to 0 before calling `strtol()` indeed fixes the problem. :)
