### ISSUE TITLE
in China I download metadata so fucking slow!!!

### ISSUE THREAD

**Issue by mobi12** [flatpak/flatpak#1285]

**Comment by amtlib-dot-dll** [comment]
It would be better if mirror sites be provided like the Fedora DNF repo and the Debian/Ubuntu APT repo

**Comment by mwleeds** [comment]
This isn't a flatpak issue so it belongs on the [flathub](https://github.com/flathub/flathub) repo. But Flathub is in the process of getting a CDN so this should improve in the near future anyway.

**Comment by geokon-gh** [comment]
Not withstand the crude issue title.. this is still an outstanding problem. Flathub is incredibly slow and by extension flatpak is unresponsive out here. When you try to tab complete a line in flatpak everything just hangs/freezes for a minute. It would be ideal if the package list was preloaded/cached somehow so it didn't need to go ping a server each time you hit TAB. At the very least some visual feedback that it's "thinking" would be welcome. I can't think of any other CLI app that will ping a server on TAB though

The flathub website as well takes a few minutes to load. Generally the cause is over-reliance on Google assets (fonts, JS, CDN, Analytics). Even Freedesktop.org has this issue... I pointed it out to them and they fixed it but then reverted back to using Google assets for some reason. Not very end user friendly to send their data to Google

**Comment by amtlib-dot-dll** [comment]
Although `dl.flathub.org` uses Fastly as CDN, notice that many CDN providers cannot offer global content delivery. A common solution is to set up additional servers in those areas, or pay local CDN providers for better service. For example, the official homepage of Mathworks is [`www.mathworks.com`](https://www.mathworks.com/) which is provided by Akamai, and when accessed from Mainland China, users will be redirected to [`ww2.mathworks.cn`](https://ww2.mathworks.cn/) which is hosted by Akamai local agents. A far more better solution is to allow mirror sites, hosted by college volunteers, as a large portion of OSS users come from colleges.

**Comment by matthiasclasen** [comment]
Could you file this as an issue against flathub, please  ?

**Comment by itsnotsaved** [comment]
https://github.com/flatpak/flatpak/issues/4874
