### ISSUE TITLE
Creating .desktop files after installation

### ISSUE THREAD

**Issue by mavit** [flatpak/flatpak#1289]
Should it be possible for Flatpak applications to create additional `.desktop` items at runtime, or would this defeat sandboxing?

This question is prompted by the following.  When Steam installs a game, it creates a `.desktop` file for that game so it can be launched directly rather than having to find it via the Steam GUI.  Under Flatpak, these `.desktop` files wind up in `~/.var/app/com.valvesoftware.Steam/.local/share/applications`, where they are ignored.  Even if they were found, they would need munging to force them to call `flatpak` rather than `/usr/bin/steam`.

**Comment by TingPing** [comment]
Steam already defeats the sandboxing so there could be some package specific workaround for that.

**Comment by alexlarsson** [comment]
For practical reasons the exports can only happen during install, because installing desktop files is a privileged action that requires host access. For example you don't want anyone to export a desktop file saying Exec=rm -rf $HOME. Also, for system-installed apps you would need root write permissions to add the desktop files.

**Comment by TingPing** [comment]
The discussion about a portal for autostart is the same as this also. Requesting a desktop file be made on the host. No reason to believe Steam would use such a portal even if it existed though and would still require some hacky solution.
