### ISSUE TITLE
flatpak sandboxing isn't working as expected

### ISSUE THREAD

**Issue by rubrik** [flatpak/flatpak#1340]
I am trying to use the flatpak Nextcloud sync client which requires X, network, and I would like to restrict access to just the sync folder which is at {{~/Nextcloud}} for me.

The json file is https://github.com/flathub/org.nextcloud.Nextcloud/blob/master/org.nextcloud.Nextcloud.json and I am trying to make it more restrictive, first with run, and then with an override. I didn't get that far yet.

Here is that I did:

```
# install
$ flatpak install --from https://flathub.org/repo/appstream/org.nextcloud.Nextcloud.flatpakref
..

# run ls to see what it can see
$ flatpak run --command=ls org.nextcloud.Nextcloud
Desktop Downloads Music

# run ls, with no access to home
$ flatpak run --nofilesystem=home --command=ls org.nextcloud.Nextcloud
$ 

# so far so good

# now run the full app
$ flatpak run --nofilesystem=home org.nextcloud.Nextcloud

# and the app can see all my files
```

Unfortunately the app seems to be sandboxed (ls example), but isn't. Is this expected?

Also could you please point me to the docs for what `--nofilesystem=host` does? It's not blocking access to what I expect. Many thanks.

**Comment by mwleeds** [comment]
Could you say why you think the app has more filesystem access than it
should? If it's using the Documents portal you'll be able to see the host
filesystem from that "Open File" window, but that's running on the host and
the app only gets access to the file(s) you specify.

On Jan 24, 2018 11:25 AM, "rubrik" <notifications@github.com> wrote:

I am trying to use the flatpak Nextcloud sync client which requires X,
network, and I would like to restrict access to just the sync folder which
is at {{~/Nextcloud}} for me.

The json file is https://github.com/flathub/org.nextcloud.Nextcloud/blob/
master/org.nextcloud.Nextcloud.json and I am trying to make it more
restrictive, first with run, and then with an override. I didn't get that
far yet.

Here is that I did:

# install
$ flatpak install --from
https://flathub.org/repo/appstream/org.nextcloud.Nextcloud.flatpakref
..

# run ls to see what it can see
$ flatpak run --command=ls org.nextcloud.Nextcloud
Desktop Downloads Music

# run ls, with no access to home
$ flatpak run --nofilesystem=home --command=ls org.nextcloud.Nextcloud
$

# so far so good

# now run the full app
$ flatpak run --nofilesystem=home org.nextcloud.Nextcloud

# and the app can see all my files

Unfortunately the app seems to be sandboxed (ls example), but isn't. Is
this expected?

Also could you please point me to the docs for what --nofilesystem=host
does? It's not blocking access to what I expect. Many thanks.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/flatpak/flatpak/issues/1340>, or mute the thread

**Comment by rubrik** [comment]
Wow that really was unexpected! But it makes sense now.

I suppose what makes it all the more confusing, is that Nextcloud doesn't complain at all. The application does not complain about `~/Nextcloud` not existing, and it isn't being created in my home dir.

I guess this line is responsible:

`--filesystem=xdg-run/Nextcloud:create`

but I can't find out where the mapping for all of these xdg-* macros goes to.

Any ideas?

**Comment by TingPing** [comment]
> but I can't find out where the mapping for all of these xdg-* macros goes to.

`echo $XDG_RUNTIME_DIR`
