### ISSUE TITLE
apt-get complains about a weak digest on Debian

### ISSUE THREAD

**Issue by ghost** [flatpak/flatpak#135]
Hello @ll,
I was interested in testing this package along with LibreOffice. I followed the instructions to add the Debian repo to my sources.list after I downloaded the gpg file and adding it via "apt-key add /path/to/key". But now, if I run "apt-get update", I get the warning
<quote>
W: https://sdk.gnome.org/apt/debian/dists/jessie/InRelease: Signature by key 6A2B067FB5E17A1A3FC8A0DAEB6216DDB76C70E9 uses weak digest algorithm (SHA1)
</quote>
and am not able to install flatpack ... :( I found http://wiki.debian.org/Teams/Apt/Sha1Removal and https://juliank.wordpress.com/2016/03/15/clarifications-and-updates-on-apt-sha1 with regard to this weak digest message in the past, and would like to ask you, if it is possible to rebuild your Debian packages with a stronger hash algorithm than SHA1, please.
Sorry for the inconvenience
Thomas.

**Comment by smcv** [comment]
> rebuild your Debian packages

That's not actually necessary; all that's necessary to solve this is to regenerate and re-sign the Release and InRelease files.

**Comment by alexlarsson** [comment]
How do i go about doing that?
I'd like to note that https://sdk.gnome.org/apt/debian/dists/jessie/InRelease contains a SHA256 line. Isn't that enough?

**Comment by smcv** [comment]
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1
```

That's the hash that apt is complaining about here. https://wiki.debian.org/Teams/Apt/Sha1Removal says:

> Fixing half-broken repositories
>
> The repository owner needs to pass --digest-algo SHA512 or --digest-algo SHA256 (or another SHA2 algorithm) to gpg when signing the file. Repositories with DSA keys need to be migrated to RSA first.
> 
> Migrating from DSA to RSA is best done by signing the repository with two keys (old and new one) and shipping the new one to the users. A relatively safe way to ship the key would be to embed it in the package. Some months after those changes, it is OK to drop the old key from the repository and the users machines (if shipped with a package).

(Sorry, I don't know the precise details of how to sign a repository with multiple keys.)

If you're doing a key transition to a (2k or 4k) RSA key anyway, it's probably a good idea to generate a "role key" for the repository, rather than having to sign it with your personal key every time: that gives you some flexibility in terms of being able to hand over apt repository maintenance to someone else by giving them the secret part of the "role key".

**Comment by smcv** [comment]
Here is the advice that the Debian keyring team give for generating new personal keys, which also seems good for role keys: https://keyring.debian.org/creating-key.html

If you're generating a "role key", sign it with your personal key so that there's a trust path; the same if you take the opportunity to generate a larger personal key as well.

**Comment by mwleeds** [comment]
Closing this since Debian Jessie is end-of-life.

**Comment by smcv** [comment]
For anyone finding this issue: the better way to install flatpak on Debian is to use [the official package that is part of Debian](https://tracker.debian.org/pkg/flatpak) (possibly using `-backports` if the version in a stable distribution is considered too old).
