### ISSUE TITLE
bwrap: Can't mkdir parents for /run/host/usr: Permission denied

### ISSUE THREAD

**Issue by ghost** [flatpak/flatpak#1357]
I've got the error message in the title when I tried to run two flatpaks:

- [org.gnome.Evince](https://github.com/flathub/org.gnome.Evince/issues/3)

- [org.libreoffice.LibreOffice](https://github.com/flathub/org.libreoffice.LibreOffice/issues/8)

I've installed them from flathub on a 64bit manjaro. Deleting their folders from ~/.var/app doesn't help.

**Comment by trialism** [comment]
I've made a new flatpak for myself today and it has the same issue: https://pastebin.com/A44KFTnW

The interesting thing is that I've these on two installations: one in virtualbox and one on my PC. In virtualbox these apps work. On the PC they don't. The installations are totally identical and I keep as much in sync as I can.
My theory is that `~/.local/share/flatpak` or its cache somewhere can get corrupted. When I've tried to rename a repo's alias I've uninstalled the apps and yet I couldn't reinstall them properly because it was missing the repo with the old name. I could only do the renaming after deleting `~/.local/share/flatpak` completely and reinstalling *everything*. This means the cache doesn't respect the removal which can cause issues like this.

**Comment by mwleeds** [comment]
@trialism Did you build flatpak yourself or use your distro's package?

**Comment by trialism** [comment]
@mwleeds I've installed it from manjaro's repo.

**Comment by trialism** [comment]
It also affects org.videolan.VLC now.

**Comment by ZeroPointEnergy** [comment]
The same issue with Gentoo when using OpenRC. I just did the tutorial today and it fails with the same error message:
`bwrap: Can't mkdir parents for /var/run/user/1000/.dbus-proxy/: No such file or directory`

The issue may come from the fact that there is a symlink in the path:
```
$ echo $XDG_RUNTIME_DIR                                   
/var/run/user/1000
ls -al /var/run
lrwxrwxrwx 1 root root 4 Dec 31  2015 /var/run -> /run
```

A workaround is to simply set XDG_RUNTIME_DIR to the right path:
`XDG_RUNTIME_DIR=/run/user/1000 flatpak run org.gimp.GIMP`

**Comment by jvanraaij** [comment]
This issue is old, but I ran into the same problem. It seems to be caused by having a symlink in / that points to /, like `ln -s / /breakeverything`. I replicated this on my rather hacked-together Gentoo install as well as on an updated stock Fedora Workstation 29 VM (flatpak 1.0.5-2.fc29):

    // added flathub via discover, installed org.vim.Vim (though any app does it)
    [testuser@localhost ~]$ flatpak run org.vim.Vim --version | head -n1
    VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov 12 2018 10:22:42)
    [testuser@localhost ~]$ sudo ln -s / /breakeverything
    [testuser@localhost ~]$ flatpak run org.vim.Vim --version | head -n1
    bwrap: Can't mkdir parents for /run/host/usr: Permission denied

If you give your regular user write rights to /run in the host, it appears to succeed at making /run/host inside of the host OS and bwrap will start complaining about being unable to create various "files" that are actually already-existing wayland/systemd/dbus/pulseaudio sockets inside of the host /run. Not sure what's happening there, all I know is that it seems to be breaking things in the host when it should be setting up the namespace.

**Comment by ppavacic** [comment]
Same problem on UnityHub. I've accidently ran 
"sudo flatpak run com.unity.UnityHub"

since then I can't run it without sudo.

**Comment by mwleeds** [comment]
Hmm, I guess we can have `flatpak run` refuse to work as root, but e.g. Kali Linux [used to](https://www.kali.org/news/kali-default-non-root-user/) run everything as root, so I wonder if we need a more nuanced check than that.

**Comment by TingPing** [comment]
Can check if its ran under `sudo` (it sets a few env vars), but still allow it ran as root otherwise.

**Comment by ppavacic** [comment]
Why not just have warning till it's fixed. "Flatpaks shouldn't be ran as root. Run 'sudo flatpak my.app.id --allow-root' if you want to run it anyways".

**Comment by RobLoach** [comment]
> Why not....

"Why not" questions are the worst. It alleviates any ownership, and shifts responsibility.... Why not just fix the whole thing?!

A better statement would be....

> I believe having a warning until it's fixed could be helpful. Something like "Flatpaks shouldn't be ran as root. Run 'sudo flatpak my.app.id --allow-root' if you want to run it anyway".

:wink:

**Comment by TingPing** [comment]
I've pushed a commit that handles the sudo case.

**Comment by asmexcaliburwoods** [comment]
Regarding https://github.com/flatpak/flatpak/issues/1357#issuecomment-438861140 - there is an obvious workaround of deleting that symlink:

 * I had `/ROOT` symlink pointing to `/`;
 * I deleted it (`rm -v /ROOT`)
 * Flatpak now works like a charm!

**Comment by smcv** [comment]
> If you give your regular user write rights to /run in the host

In case it's not obvious: never do this. Write access to `/run` is root-equivalent.

**Comment by smcv** [comment]
#5213 should avoid this, by refusing to export (the target of) a symlink to `/`.
