### ISSUE TITLE
Consider application installation on separate internal media

### ISSUE THREAD

**Issue by hadess** [flatpak/flatpak#137]
After packaging a bunch of big games, my flatpak directory is getting a bit big. Should we allow installing applications on removable media? Note, just the applications, not the data created within each app afterwards, just the read-only stuff.

**Comment by alexlarsson** [comment]
This is also related with endless having two disks in their hardware (regular + sd card) and they wish to spread things.

I'm thinking we could do something like --installation=/some/dir which is a more freeform version of --user and --system allowing you to specify any directory.

**Comment by hadess** [comment]
Maybe slightly more automatic in that you'd add a dot-file after having formatted it in a way that supports flatpak's use? (eg. dot-file when you've formatted it read-write with symlinks support, etc.)

**Comment by mariospr** [comment]
> This is also related with endless having two disks in their hardware (regular + sd card) and they wish to spread things.
>
> I'm thinking we could do something like --installation=/some/dir which is a more freeform version of --user and --system allowing you to specify any directory.

I've been playing around with this idea the past 2-3 days and got a proof-of-concept that implements this option (allowing only one "custom" installation directory only for now) that worked well in my environment. 

So far, my current implementation allows to do things such as:
* Configuring remotes under that alternative location. e.g.:
```
flatpak remote-add --installation=/alternative/path <repo> <uri>
```
* Install / uninstall apps into that location, after configuring the remote. e.g.:
```
flatpak install --installation=/alternative/path <repo> <app-id>
```
* Running installed appsin the custom installation directory:
```
# Contrary to apps installed with --user, you do need to specify the path with `run`
flatpak run --installation=/alternative/path <app-id>
```
* Querying information about the apps in the custom installation directory:
```
flatpak info --installation=/alternative/path <app-id>
```
* Listing apps in the custom installation directory:
```
flatpak list --installation=/alternative/path
```
* Listing repositories configured in the custom installation directory:
```
flatpak remote-list --installation=/alternative/path
```

You can see the code in https://github.com/mariospr/flatpak/commits/custom-installation. Please feel free to take a look to it and let me know what you think. For now I only touched the code at `app/` and `common` so this has only been tested with command line flatpak commands. However, as we plan to use this new functionality from gnome-software, I wouldn't be surprised if there was any need to adapt / extend the public API, but I haven't looked into that yet.

Last, I was actually going to file an issue but found this one, which I think we can use even if "removable media" seems a subset of the more generic idea at hand :)

**Comment by alexlarsson** [comment]
I think you need to add --installation= when the desktop/service files are being rewritten too. Otherwise you will only be able to launch them from the commandline. I.e. here:
 https://github.com/mariospr/flatpak/blob/custom-installation/common/flatpak-dir.c#L2286

**Comment by mariospr** [comment]
> I think you need to add --installation= when the desktop/service files are being rewritten too. Otherwise you will only be able to launch them from the commandline. I.e. here:
https://github.com/mariospr/flatpak/blob/custom-installation/common/flatpak-dir.c#L2286

Good point, just added that now: https://github.com/mariospr/flatpak/commit/80fd8f6e8fb9a4dbf45b5c3dc2936a12a0f8e91c

**Comment by mariospr** [comment]
I had an interesting discussion with @hughsie today about this, where I showed the proof-of-concept patches I had for flatpak (in the context of using them from GNOME Software) and we ended up with some ideas on how to implement this, that I'd like to share here to get some feedback:

  * Instead of limiting ourselves to write it for 1 external installation, we could think of making it more generic and allow to define a list of different installations:
    * They could be defined in an optional configuration file (e.g. /etc/flatpak/flatpak.conf)
    * We could encode priorities too for every installation, so that commands like 'run' could use it to decide where to look first (e.g. check external installation 1 first, then user, then system)
    * Would still need to handle system and user installations for backward compatibility with --system and --user commands
    * A --installations parameter could still be kept, that would specify external installations by ID (matching the configuration file)
  * In order to handle external installations properly it would be nice to have a FlatpakContext object (this would likely apply even if we only support one "custom" external installation):
    * That would allow us to define the external installation and then retrieve it/them whenever needed, as it's now done for system and user installations via flatpak_dir_get_user() and flatpak_dir_get_system()
    * On startup the context would be populated with the system and user installations + any additional external location as configured
    * Public API would be added to query flatpak for the available installations 
  * GNOME Software would use this public API to handle user, system and external installations
    * The relevant flatpak plugin would query the list of flatpak installations and handled them considering their priorities
    * If the use case to install something to a specific location is implemented, GNOME Software would force itself to use the specific installation associated to that location
    * The gs-plugin-flatpak-<system|user> plugins could be maybe merged in one single plugin only

Now, besides these specific details, I think there are still a few open questions (such as "should we allow defining multiple additional installations? Or just one?") but I hope this is a better start point.

How does this sound?

**Comment by joaquimrocha** [comment]
Hey, a couple of comments chained below:

> We could encode priorities too for every installation, so that commands like 'run' could use it to decide where to look first (e.g. check external installation 1 first, then user, then system)

I thought this had already been established as the way to go. We keep a list of the paths and the order they follow will be the priority they're checked.

> On startup the context would be populated with the system and user installations + any additional external location as configured

This is a bit different from what I talked with @alexlarsson . The idea we discussed is to have the list of installation paths configured and make the system option just point to the highest priority path in the list: essentially --system is just a convenience pointer to the default/highest-priority path.

This idea should also simplify the implementation as we no longer have to care about custom, system or user every time we need the path, instead we assign the system internally to whatever path has been given in the CLI (with the --install-path) or to the highest priority one, when undefined. 

> The relevant flatpak plugin would query the list of flatpak installations and handled them considering their priorities

Yes. Maybe actually little changes are needed to Flatpak if the default system option points to whatever is the highest priority path in the list. Unless we want to check if e.g. there's enough space in that default location.

> If the use case to install something to a specific location is implemented, GNOME Software would force itself to use the specific installation associated to that location

Okay, in this case we need of course to tweak the flatpak plugin a bit more.

> The gs-plugin-flatpak- plugins could be maybe merged in one single plugin only

I thought about this but I am still not sure if it's as easy as it sounds. The flatpak system plugin is the one where we should add any alternative paths logic.

> Now, besides these specific details, I think there are still a few open questions (such as "should we allow defining multiple additional installations? Or just one?") but I hope this is a better start point.
> 
> How does this sound?

What is multiple additional installations?

As I mentioned, I think that the cleanest approach to this is to think that the system installations may have paths defined beyond what's the default one. Those paths are configured in a file that belongs to flatpak in */etc/flatpak.d/...* defining a priority according to where in the list each path is.
When the user installs an app, they can specify the path using something like *--install-path* (maybe --system-path is even more clear to understand). When using remove/run/udpate without a specified path (and without *--user*) means that flatpak goes through the list of configured paths until the app is found (like it does between user/system currently).

I hope I have shared everything I talked with Alex correctly. @alexlarsson please confirm :smile:

**Comment by mariospr** [comment]
>> We could encode priorities too for every installation, so that commands like 'run' could use it to decide where to look first (e.g. check external installation 1 first, then user, then system)
>
> I thought this had already been established as the way to go. We keep a list of the paths and the order they follow will be the priority they're checked.

Yes, I think that's similar to what you mentioned the other day in our private phabricator and this does not contradices that, I think. Actually I forgot to mention here that @hughsie and me also talked about a drop-in flatpak.d directory, which is similar I thinkg to what you talked to @alexlarsson on LAS, I think, so we're pretty much on the same page.

What I was not that sure about is that this was already established as the way to go, I thought it was more an idea to explore, but maybe my perception is different to yours, being in LAS :-). In any case, thanks for clarifying.

>> On startup the context would be populated with the system and user installations + any additional external location as configured
>
> This is a bit different from what I talked with @alexlarsson . The idea we discussed is to have the list of installation paths configured and make the system option just point to the highest priority path in the list: essentially --system is just a convenience pointer to the default/highest-priority path.

I did not know about that, at least not in that level of detail, but makes sense to me.

> This idea should also simplify the implementation as we no longer have to care about custom, system or user every time we need the path, instead we assign the system internally to whatever path has been given in the CLI (with the --install-path) or to the highest priority one, when undefined.

When you say "we assign the system internally to whatever path has been given in the CLI"... you mean making flatpak consider just whatever is passed, right? Something similar to what happens now when you explicitly specify --system or --user. 

>> The relevant flatpak plugin would query the list of flatpak installations and handled them considering their priorities
>
> Yes. Maybe actually little changes are needed to Flatpak if the default system option points to whatever is the highest priority path in the list. Unless we want to check if e.g. there's enough space in that default location.

I don't think checking whether there's enough space should be a responsibility of flatpak, seems to me like a task better suited for the client using the public API, such as GNOME Software, or the CLI.

>> If the use case to install something to a specific location is implemented, GNOME Software would force itself to use the specific installation associated to that location
>
> Okay, in this case we need of course to tweak the flatpak plugin a bit more.

Sure

>> The gs-plugin-flatpak- plugins could be maybe merged in one single plugin only
>
> I thought about this but I am still not sure if it's as easy as it sounds. The flatpak system plugin is the one where we should add any alternative paths logic.

I haven't said it's going to be easy, but the truth is that the gs-plugin-flatpak-system and gs-plugin-flatpak-user plugins are already practically identical and mostly rely on gs-flatpak, where most code is already shared with some specific bits depending on the scope.

So it should be possible to merge some stuff I think, specially if we start asking flatpak for a list of available installations and using them generically (even though we migh still have to treat user installations in a separate way).

>> Now, besides these specific details, I think there are still a few open questions (such as "should we allow defining multiple additional installations? Or just one?") but I hope this is a better start point.
>>
>> How does this sound?
>
> What is multiple additional installations?

At the moment, my hackish `custom-installations` branch allows to specify only one extra custom installation, to be used on top of the system and user ones, but instead of constraining ourselves to only that we may want to enable defining more than 1 extra installations (via conf files, as discussed above), which is what I meant by "multiple additional installations" 

> As I mentioned, I think that the cleanest approach to this is to think that the system installations may have paths defined beyond what's the default one. Those paths are configured in a file that belongs to flatpak in /etc/flatpak.d/... defining a priority according to where in the list each path is.
When the user installs an app, they can specify the path using something like --install-path (maybe --system-path is even more clear to understand). When using remove/run/udpate without a specified path (and without --user) means that flatpak goes through the list of configured paths until the app is found (like it does between user/system currently).

Makes sense to me.

> I hope I have shared everything I talked with Alex correctly. @alexlarsson please confirm :smile:

I definitely understood things better now (thanks!), but any additional feedback will always be helpful.

**Comment by joaquimrocha** [comment]
> I don't think checking whether there's enough space should be a responsibility of flatpak, seems to me like a task better suited for the client using the public API, such as GNOME Software, or the CLI.

I agree. It may however check that the path exists but @alexlarsson should know better what to do on failure? i.e. when a path doesn't exist, use the next in the list or just fail? (I'd go for the former as paths may be removable media)

> When you say "we assign the system internally to whatever path has been given in the CLI"... you mean making flatpak consider just whatever is passed, right? Something similar to what happens now when you explicitly specify --system or --user.

I meant what I later described below: there shouldn't be system + user + custom but rather that the system path is either a path taken from the conf file, passed in by the user in the CLI, or a default one.

Thanks for doing this work @mariospr !

**Comment by alexlarsson** [comment]
So, here is how i think it should work: We add a config file (or many for .d style snippets) that flatpak (and libflatpak) reads. This allows you to define multiple "system-like" repos (i.e. not owned by the user). One of these are configured to be the default one. If you lack configuration you get one in /var/lib/flatpak. If none is configured as default we pick one (say the first or whatever), which will be the /var/lib/flatpak one if you lack config.

Now, some commands already look for things in both user and system installations, for instance "flatpak run", and "flatpak list". These would now look in all the configured system paths as well as the user. At least in the CLI, for the library API we need to have a way to enumerate all installations and the default in order to do something like "flatpak list", although sometimes its automatic even for the library (e.g. when finding a runtime dependency).

In some cases it is however not possible to look at all possible installations. In particular, not when you're writing to it such as in "flatpak install". In the CLI this means we have to add a new argument to pick installation. --system would mean the default system one, or you could explicitly give an installation. I like the idea of the configuration giving them names, so you can do --installation=$name. For the library this part would be easy, as you already pass the FlatpakInstallation object to these methods.

I don't think flatpak should be in the business of implementing policy wrt where things should be installed though (be it based on free space or otherwise). That should happen on a higher level.

**Comment by mariospr** [comment]
It makes a lot of sense to me too, thanks @joaquimrocha and @alexlarsson for the detailed feedback.

I haven't touched this at all in the past few days due to other things (me remotely attending the Web Engines Hackfest, mainly) but I'll be co-working with @hughsie tomorrow and will focus on this task again for 1-2 days, so this information arrived just in time.

After that, I'm planning to devote 1-2 days per week to this, let's see if I manage to do it :)

**Comment by hadess** [comment]
I have a bunch of questions related to how the feature would work, rather than how it will be implemented. As far as I'm concerned, I don't really care about how it's implemented, as long as it works as designed :)

- Do we want to allow having application data, or the applications themselves on the external disk, or both? Consider the use cases of a music player with user-added music, a map application with offline maps for the former use case, games with loads of assets for the latter, and maybe extensible games for the "both combined" case.

- Should installations on external disks be specific to one machine? Eg. do you want to be able to take the SD card and move it a different machine, or as it could contain user-data, or paid-for apps, should it be bound to a single machine? Making it moveable would allow installation where/when network is available, which might not be where it would be used.

- If apps and their storage can be moved between machines, how do prioritise applications available internally and on-disk? What if the same application is installed in both, do we prefer the internal or external app, the newest? What if the external app is preferred and it's a rogue version of the app?

- If applications can be moved, how do you identify applications? Do we ask users to check the GPG keys when the application is launched? Can we trust to parse the application's data from a random SD card?

- How would preparing an external disk for application installation work? Would some part of the system ask when storage space is low on the main disk? Would the external disk need to be formatted in a special way? Can users still use the external disk in their phones or media players after it's been setup?

I think those are all questions that need to be answered, and we need to make it clear what the security implications are of using applications stored on external disks.

**Comment by mariospr** [comment]
> I have a bunch of questions related to how the feature would work, rather than how it will be implemented. As far as I'm concerned, I don't really care about how it's implemented, as long as it works as designed :)

I don't think I have clear answers to all these questions, but I definitely have some comments I think might be useful to continue the discussion.

> Do we want to allow having application data, or the applications themselves on the external disk, or both? 

The question about the app data being relocatable is an interesting one, but I think it's something that could be tackled separately maybe? As I understand it, we're talking here about moving the location of the flatpak installation (OSTree repo, configured remotes, installed apps/runtimes) only, and the appdata would be a matter of relocating stuff that normally goes under `~/.var`, right? 

> Should installations on external disks be specific to one machine?

I think I would not make it specific in principle to a particular machine, but maybe that's something that can be configurable so that it can adapt to different cases? I'm thinking here of asynchronously installing apps that were downloaded / installed in connected devices into offline computers, maybe distributing certain "heavy" apps as SD Cards (e.g. encyclopedia-like apps) and things like that for which not having installations tied to particular machines would be convenient.

Now, if we wanted to make them specific we could perhaps use the D-Bus machine-id to somehow sign the external installation / apps installed there, so that they get verified each time flatpak tries to run them. But again I think that this is something that can be tackled separately too.

> If apps and their storage can be moved between machines, how do prioritise applications available internally and on-disk? What if the same application is installed in both, do we prefer the internal or external app, the newest? What if the external app is preferred and it's a rogue version of the app?

Maybe we could leverage the drop-in configuration files @alexlarsson and @joaquimrocha mentioned above (e.g. /etc/flatpak.d) so that we can define variables that help with this prioritization?

So perhaps we could define an optional `priority=<int>`key-value pair that could be defined in those files for a given installation path and use that in case it's present (otherwise falling back to whatever order the system installations are defined). How does that sound?

> If applications can be moved, how do you identify applications? Do we ask users to check the GPG keys when the application is launched? Can we trust to parse the application's data from a random SD card?

I think having GPG signed repos configured there might be enought for this, no?

> How would preparing an external disk for application installation work?

So far I was assuming that whatever FS is in there should be compatible with what OSTree needs to work (e.g. symlinks, hardlinks).

> Would some part of the system ask when storage space is low on the main disk?

You could maybe extend gnome-settings-daemon's housekeeping plugin to help with this, or gnome-software. Or both :)

> Would the external disk need to be formatted in a special way?

As far as I understand it right, it should be a FS allowing the features that OSTree require to work.

> Can users still use the external disk in their phones or media players after it's been setup?

If those devices can only read FS's like FAT or NTFS, I guess it's unlikely unless there's some solution that allows some "hybrid" setup that I'm not aware of.

> I think those are all questions that need to be answered, and we need to make it clear what the security implications are of using applications stored on external disks.

I think they are important but at the same time I'm not sure they all need to be answered in detail right now. Instead, I think we can start iterating over the basic idea having these considerations in mind, and then add more features later on.

Does that make any sense?

**Comment by magcius** [comment]
I have a related, perhaps separate, request. For build systems and build servers, it's convenient to "start fresh" from no repo when doing a build. I would like some sort of `--repo` argument or `FLATPAK_REPO` override envvar so I can work in a fresh repo every single time.

The `FLATPAK_SYSTEM_DIR` envvar is close, but even if the directory is writable by the user, we still require polkit access. Perhaps we just fix that bug instead, though.

**Comment by mariospr** [comment]
@magcius Sorry for the so late reply (and slow progress on this in general), been busy with several things and had no time to reply.

At the moment I'm following the approach outlined by @alexlarsson and have a partial implementation that basically picks configuration files in a drop-in directory /etc/flatpak/installations.d and uses it to internally consider a list of system installations... and that seems to work for the commands I've tried it with (e.g. install, list, run) but I still haven't finished adding support for all of them and can't be used yet.

However, this should be useful to address your needs once it's ready, as you'd basically drop a file in that drop-in dir defining where you want to have the desired installation to live and then passing --installation=<name> for the commands you run should be enough (providing you take care of cleaning up the directory once you're done, flatpak won't do that for you)

**Comment by magcius** [comment]
I don't like that. I would like build processes to be as isolated and independent as possible. Using system-global configuration seems exactly like what I don't want to do.

**Comment by magcius** [comment]
Anyway, I suppose I'll file a second bug because it probably wouldn't be handled by this.

**Comment by mariospr** [comment]
@magcius Ah, I see. Well, then a separate issue probably makes sense, yes.

**Comment by magcius** [comment]
Filed #405

**Comment by hadess** [comment]
@mariospr I'm not very happy at the answers, no. The problem isn't whether some feature can be implemented later, but rather whether something is in scope or not. There are security ramifications for nearly all my questions, so we need to have clear answers on what is in and out of scope, and figure out the security implications of those choices.

I'd rather use this feature than move my /home to a removable media (with all the possible problems it could cause), but we need to make sure that the security implications are understood, whatever the implementation.

**Comment by hadess** [comment]
We discussed this today with @mariospr and the problem Endless is experiencing is slightly different from my original request. I was interested in [Portable Applications](https://en.wikipedia.org/wiki/Portable_application) so I could have games on a USB drive, or *removable* SD card. I'd generate apps to be installed on my desktop machine, install to the drive, move drive to the machine (or any machine). This would obviously require much more work than what Endless needs.

Endless is interested in having the base system, and default runtimes, on one internal disk. The applications would be on a separate, less reliable, internal disk (which happens to be an SD card, but not a "removable one" in that sense). This would require adding a third source for flatpaks, in addition to the home directory and the system-wide directory. This third location would not be any different from the system-wide directory in terms of trust.

The tooling needed here is about having a 3rd possible location, and how to prioritise it when launching applications (home > system > third location?), where to install the applications given some policy (small ones in the system dir, big ones in the third location, what about small apps that become big on update, etc.).

**Comment by mariospr** [comment]
@hadess Nice write-up! As an additional clarification, just to mention that my current WIP implementation is based on [the previous comments from @alexlarsson](https://github.com/flatpak/flatpak/issues/137#issuecomment-249848405), meaning I'm not limiting it to a third location, but making it configurable so that you can have more than one additional installation if you please.

But @hadess has made a very important point on that, regardless this adds one or more possible additional installations, those should be treated with the same level of trust than /var/lib/flatpak.

Now about the policy to decide where an app should be installed, my current thinking is that it should probably fall outside of flatpak itself (e.g. GNOME Software in our cases) but we'll see.

**Comment by mariospr** [comment]
Finally pushed a PR up for review here: https://github.com/flatpak/flatpak/pull/418

There are quite a few open questions, though, such as what information we want to include on those configuration files, how to prioritize the installations and probably many other things, but for now I hope this will be enough to continue the discussion over something a bit more specific.

**Comment by hadess** [comment]
The "Custom installations" section of https://blogs.gnome.org/mclasen/2018/08/26/about-flatpak-installations/ explains how to install to a removable disk, which is good enough for me.
