### ISSUE TITLE
Can't install flatpak app in Linux Mint

### ISSUE THREAD

**Issue by rebelxt** [flatpak/flatpak#1370]
Linux Mint Mate 64bit 18.3 currently up to date
flatpak 0.10.0-alexlarsson1~xenial

When attempting to install any flatpak app, this happens:

> $ flatpak install -vv flathub org.libreoffice.LibreOffice
XA: Opening system flatpak installation at path /var/lib/flatpak
Required runtime for org.libreoffice.LibreOffice/x86_64/stable (org.gnome.Platform/x86_64/3.24) is not installed, searching...
Found in remote flathub, do you want to install it? [y/n]: y
XA: Transaction: install/update flathub:runtime/org.gnome.Platform/x86_64/3.24[$old]
XA: No installations directory in /etc/flatpak/installations.d. Skipping
XA: Transaction: install/update flathub:runtime/org.freedesktop.Platform.ffmpeg/x86_64/1.6[$old]
XA: Transaction: install/update flathub:runtime/org.gnome.Platform.Locale/x86_64/3.24[/en]
XA: Transaction: install flathub:app/org.libreoffice.LibreOffice/x86_64/stable[*]
XA: Updating remote metadata for flathub
Installing: org.gnome.Platform/x86_64/3.24 from flathub
[####                ] Downloading: 24.3 MB/200.4 MB (1.1 MB/s)                
Usage:
  flatpak install [OPTION...] COMMAND
  _... more usage info_
error: While pulling runtime/org.gnome.Platform/x86_64/3.24 from remote flathub: Writing object 2e70a2c3e87d711e89998b75581037c040793037a483b3319961e1165a27e097.file: fsetxattr(user.ostreemeta): Operation not supported

I tried installing 4 different apps, each failed with the same error. Is there any other information I can get to help figure this out?

**Comment by mwleeds** [comment]
Post what file system you're using (ext4, btrfs, etc.)

On Jan 31, 2018 11:36 AM, "rebelxt" <notifications@github.com> wrote:

Linux Mint Mate 64bit 18.3 currently up to date
flatpak 0.10.0-alexlarsson1~xenial

When attempting to install any flatpak app, this happens:

$ flatpak install -vv flathub org.libreoffice.LibreOffice
XA: Opening system flatpak installation at path /var/lib/flatpak
Required runtime for org.libreoffice.LibreOffice/x86_64/stable
(org.gnome.Platform/x86_64/3.24) is not installed, searching...
Found in remote flathub, do you want to install it? [y/n]: y
XA: Transaction: install/update flathub:runtime/org.gnome.
Platform/x86_64/3.24[$old]
XA: No installations directory in /etc/flatpak/installations.d. Skipping
XA: Transaction: install/update flathub:runtime/org.
freedesktop.Platform.ffmpeg/x86_64/1.6[$old]
XA: Transaction: install/update flathub:runtime/org.gnome.
Platform.Locale/x86_64/3.24[/en]
XA: Transaction: install flathub:app/org.libreoffice.
LibreOffice/x86_64/stable[*]
XA: Updating remote metadata for flathub
Installing: org.gnome.Platform/x86_64/3.24 from flathub
[#### ] Downloading: 24.3 MB/200.4 MB (1.1 MB/s)
Usage:
flatpak install [OPTION...] COMMAND
*... more usage info*
error: While pulling runtime/org.gnome.Platform/x86_64/3.24 from remote
flathub: Writing object 2e70a2c3e87d711e89998b75581037
c040793037a483b3319961e1165a27e097.file: fsetxattr(user.ostreemeta):
Operation not supported

I tried installing 4 different apps, each failed with the same error. Is
there any other information I can get to help figure this out?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/flatpak/flatpak/issues/1370>, or mute the thread

**Comment by rebelxt** [comment]
ext4

**Comment by lmintmate** [comment]
I also have the same OS as you, but don't have this problem. The apps I installed so far (including LibreOffice) I installed them either from the software center, or (when it came to installing a Gtk theme) with flatpak install flathub e.t.c, but without that -vv command parameter. Why did you use that one? Maybe that's the one causing the problem. For the record, I also think I have ext4 (that's probably the default in Linux Mint too).

**Comment by rebelxt** [comment]
'flatpak --help' says: "-v, --verbose          Print debug information during command processing, -vv for more detail"

**Comment by lmintmate** [comment]
Ah, I see. When I needed a manual, I used `man flatpak` instead however, so I didn't think there would be a `flatpak --help` too -and, interestingly enough, the `man flatpak` command doesn't mention the -vv parameter as well. I guess this inconsistency in the documentation can be confusing (but is another issue, and it might have been fixed in later releases of flatpak too). Given that, maybe the -vv parameter didn't have anything to do with your problem. Still though, since I entered the issue this way, I wonder if you tried to install LibreOffice a) from the Software Center (as I, for example, didn't muck in the command line, until I wanted to install a flatpak Gtk theme, and had installed LibreOffice already before that) b) from the commandline but without the -vv parameter. Other than that, I don't know what else could have happened there, except for something pertaining to your particular model of computer.

**Comment by rebelxt** [comment]
'flatpak' and 'flatpak -v' give the same results as 'flatpak -vv'. As for the Mint Software Center, that's where I started, and tried the flatpak command only when that failed.
[https://github.com/linuxmint/mintinstall/issues/169](url)

My computer is home-built with an Intel i5-3550 CPU. I have been wondering if it's hardware related myself. Booting a flash drive with Mint Cinnamon 18.3 live gives the same error. However, with Mint Mate installed in VirtualBox, flatpak runs without error.

Any suggestions as to what to look at would be appreciated.

**Comment by lmintmate** [comment]
Well, I use a laptop myself (so nothing home-made other than my installing Linux Mint on its original FreeDOS), so I don't know too much about self-made desktop setups. The clues this thread gives however would suggest something with the hard drive, given that the collaborator @mwleeds asked you about the filesystem you use, and the error message itself says `error:` [...] `Writing object` [...] `Operation not supported`. Perhaps VirtualBox is writing to a different part of the hard-drive (or an emulated hard-drive file - don't recall how file management in VMs works right now), and that's why it works, while the real deal doesn't.

**Comment by rebelxt** [comment]
I finally broke down and did a clean install of Linux Mint Mate 64bit. Both mintinstall and flatpak are working there. My problem installation was also a clean install, so apparently something I installed or modified caused the problem. If I ever figure out what that was, and it seems relevant, I'll come back here, but for now I will close this.

**Comment by RoyiAvital** [comment]
How could one update the FlatPak application from 0.10.0 to the latest on Linux Mint 18.3?

**Comment by herirudini** [comment]
Hey, i was have the same issue, error while pulling... And after for 4 month i just found the solution. 1. Purge flatpak, reboot, 2 Install flatpak, list the repository using $flatpak remotes and then i see there's no repository yet. And then i copy paste the code i get from flatpak documentation website 
$ flatpak remote-add --if-not-exist flathub https://flathub.org/repo/flathub.flatpakrepo.
Try $ remotes again and i see there is flathub repo on the list.
Then i do $ mintinstall, then it tells me the mintinstall is doing update and stuff about flatpak, and i try to install some flatpak app and now its working.
