### ISSUE TITLE
P2P installs can fail when ostree-metadata is pulled from a different remote

### ISSUE THREAD

**Issue by mwleeds** [flatpak/flatpak#1425]
Apparently there's nothing in the OstreeRepoFinderAvahi code to prevent a computer from treating itself as a server and pulling from itself. The unfortunate consequence of this is a failed install. This is because the two `flatpak_dir_pull` calls in `flatpak_dir_install` for the ref and `ostree-metadata` are separate. So one might pull from the remote server and the other from the local host. This means the summary file in the child repo is the one from the localhost, which of course doesn't have the ref you're trying to pull and the system helper pull errors out. I'm not sure yet what the solution is. I don't think this is a regression from my recent commits but I'm not 100% sure. Here's a log from running `flatpak install eos-apps com.endlessm.wiki_art.en`: [flatpak-install-fail.log](https://github.com/flatpak/flatpak/files/1730013/flatpak-install-fail.log)

(cc: @pwithnall)

**Comment by mwleeds** [comment]
I suppose there might be some legitimate use cases for pulling from yourself so the solution is probably to merge the two `flatpak_dir_pull` calls so they use one `ostree_repo_find_remotes_async` call.

**Comment by mwleeds** [comment]
Actually even then it might fail. I'll have to check if there's a way to tell `ostree_repo_pull_from_remotes_async` to pull the refs from a single remote. Alternatively we could just move the `ostree-metadata` pull to before the ref pull so the `summary` in the child repo gets overwritten.

**Comment by mwleeds** [comment]
@cgwalters any opinion on adding an option to `find_remotes_async` maybe called `one-remote` to pull all the refs from the same remote?

**Comment by pwithnall** [comment]
> any opinion on adding an option to find_remotes_async maybe called one-remote to pull all the refs from the same remote?

That’s working against the point of the `OstreeRepoFinder`. One of the points is that you can end up pulling refs from different remotes, depending on what’s available, what’s fastest to get, and what’s the most up to date.

I don’t think there are any regular use cases for pulling from yourself. I think the fix here is:
 * Work out why the repo finder is deciding to pull from ourselves, given that it should not be managing to find more up-to-date refs on localhost than already exist on localhost.
 * Change `OstreeRepoFinderAvahi` to explicitly not pull from `localhost`/`127.0.0.1`/`::1/128` unless a `allow-localhost` property is set on it (defaulting to `FALSE`).
 * Merge the two `flatpak_dir_pull()` calls too, since that makes everything more atomic.

**Comment by mwleeds** [comment]
@pwithnall preventing localhost pulls wouldn't solve this issue (and by the way it doesn't show up as localhost, just the local IP address). If computer A on the network provides `app/com.endlessm.wiki_art.en/x86_64/eos3` and computer B provides `ostree-metadata`, the `summary` in the child repo will be from computer B which might not have the app ref, so the pull from the child repo into the system repo will fail.

**Comment by mwleeds** [comment]
Maybe ostree could pull the ostree-metadata for mirror pulls the same way it pulls the summary file. I'd have to look into it more to know if that's a good idea though.

**Comment by pwithnall** [comment]
> @pwithnall preventing localhost pulls wouldn't solve this issue

Why not? If you can’t pull `ostree-metadata` and you can’t pull any app refs from localhost, then you have to either get them from another computer on the network, or fail to get them (i.e. correctly report an error).

> (and by the way it doesn't show up as localhost, just the local IP address)

`localhost`, the output of `gethostname()`, `127.0.0.0/8` and `::1/128` are all easy enough to check for.

**Comment by mwleeds** [comment]
@pwithnall the problem arises if the app ref and `ostree-metadata` come from different computers on the network, and the one providing `ostree-metadata` doesn't have the app ref in its `summary`. Is there some guarantee against that happening? In other words, is every repo guaranteed to serve `ostree-metadata` and are the avahi results sorted deterministically? Even so, there'd still be a race condition.

**Comment by pwithnall** [comment]
I suspect the `ostree-metadata` stuff here is a red herring, since the `ostree-metadata` should only contain repository metadata which isn’t specific to the branches in the repository (since peers cannot regenerate `ostree-metadata` to represent the set of branches they contain — they can only regenerate the unsigned `summary`).

If I’m understanding correctly, the issue here is that a P2P pull could grab branches from various peers and pull them into the local system helper repository. Any `summary` file from one of the peers would not be appropriate to put in the system helper repository, since its list of branches will only be relevant to that peer, not to the mixture of branches pulled into the system helper repository.

So the solution seems to be to locally regenerate the `summary` file in the system helper repository after pulling from all the peers, if using collection IDs. If not using collection IDs (and using signed `summary` files), this *should not* be done, and a `summary` file from the remote you’ve pulled from must be used instead. Unless we could eliminate the use of the `summary` file in the system helper repository entirely? But I suspect quite a lot depends on that, so it wouldn’t be possible.

**Comment by mwleeds** [comment]
Good idea, I didn't think about avoiding using `summary` in the local pull. I have a WIP branch for that which seems to be working so far: https://github.com/mwleeds/flatpak/tree/avoid-local-summary-use
