### ISSUE TITLE
flatpak and Monodevelop don't get along for Interop (libcrypto.so.10)/ DllNotFoundException if project is run

### ISSUE THREAD

**Issue by jpfreyen** [flatpak/flatpak#1485]
Don't know if this is purely a Monodevelop bug or flatpak bug, but probably a little of both, so I'm filing bugs in both.

Here is the Xamarin Monodevelop (flatpak) bug:

https://bugzilla.xamarin.com/show_bug.cgi?id=46998

First of all, /lib/libcrypto.so.10 doesn't exist in flatpak runtime.  It should exist.

SQLite.Interop.so, which depends and loads libcrypto.so.10, works just fine on the command-line mono (5.4.1), ie my distro environment.  When I try and run it under Monodevelop-flatpak-runtime  (in the debugger), I get the message:

Mono: DllImport error loading library 'libSQLite.Interop.so': '/lib/libcrypto.so.10: version `libcrypto.so.10' not found 

I get this error even though I have manually added a symbolic link to the flatpak runtime at:

/var/lib/flatpak/runtime/org.freedesktop.Sdk/x86_64/1.4/active/files/lib

$ ls -l libcrypto.so.10 
lrwxrwxrwx. 1 root root 18 Mar 14 13:02 libcrypto.so.10 -> libcrypto.so.1.0.0

At the very least, Monodevelop in the flatpak distribution should be flexible enough to work when a symbolic link needs to be added to the flatpak runtime to get things to work like in this situation I have...this is the power of Linux after all.

**Comment by alexlarsson** [comment]
libcrypto.so.10 is an older version that is not ABI compatible with libcrypto.so.1.0.0. You can't just make one one point to the other, all you get from that is crashes.

The flatpak runtimes don't ship compat version of old ssl version, because doing so is a poor idea from a security perspective (these are not generally supported). If mono requires some old version of openssl it has to bundle a copy of it.
