### ISSUE TITLE
Using different language for application is magic

### ISSUE THREAD

**Issue by barthalion** [flatpak/flatpak#1504]
This is repeatedly coming back to us on our IRC channel. It will be easier on an example.

First, my locale settings:
```
LANG=en_DK.UTF-8
LC_CTYPE="en_DK.UTF-8"
LC_NUMERIC="en_DK.UTF-8"
LC_TIME="en_DK.UTF-8"
LC_COLLATE="en_DK.UTF-8"
LC_MONETARY="en_DK.UTF-8"
LC_MESSAGES="en_DK.UTF-8"
LC_PAPER="en_DK.UTF-8"
LC_NAME="en_DK.UTF-8"
LC_ADDRESS="en_DK.UTF-8"
LC_TELEPHONE="en_DK.UTF-8"
LC_MEASUREMENT="en_DK.UTF-8"
LC_IDENTIFICATION="en_DK.UTF-8"
```

Available locales:
```
C
en_DK.utf8
pl_PL.utf8
POSIX
```

I installed Corebird from Flathub with `--user` and I want to have it run in Polish. I understand that I need to pull missing language files first:

```
flatpak --user update --subpath= org.baedert.corebird
flatpak --user update --subpath= org.baedert.corebird.Locale
```

(Can I limit this to `/en` and `/pl` somehow?) In theory I should be able to set `LC_ALL` now to `pl_PL.utf8` and call it a day. However Corebird starts in English, while in the terminal I see a message:

```
$ flatpak run --env=LC_ALL=pl_PL.UTF-8 org.baedert.corebird
(corebird:3): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
```

I have similar results with GNOME Recipes. What am I doing wrong?

Related issues:
https://github.com/flathub/org.baedert.corebird/issues/5
https://github.com/flatpak/flatpak/issues/596

**Comment by barthalion** [comment]
This also brings question how can I permanently change the language for given application without playing with metadata files or modifying exported desktop file.

**Comment by ramcq** [comment]
I think this error originates from the system's runtime's .Locales extension, rather than the subpaths used in the app's Locale extension.

If you don't set it, it defaults to the union of every local user's configured language, according to AccountsService: https://github.com/flatpak/flatpak/commit/62760761b

At a manual level, I think this will do what you wish:
```flatpak --user update --subpath=/en --subpath=/pl org.baedert.corebird.Locale
flatpak update subpath=/en --subpath=/pl org.gnome.Platform.Locale```

(--user or --system as appropriate)

But this should also work a bit more "normally":
``flatpak config --user --set languages en,pl
flatpak config --system --set languages en,pl``

However, I'm intrigued to know two things:
1. Is there a better way to reflect that your user has >1 language you might use, depending on the app. Obviously from inspecting your LANG/etc environment, flatpak --user would reasonably conclude that en was sufficient.
2. Is there another place on the system that would make sense to check for what system locales are available, which we should be adding to the list from AccountsService? Where does your C / en_DK.utf8 / pl_PL.utf8 / POSIX list come from?

**Comment by barthalion** [comment]
Whoa, it works running update on locale extension of platform. (And for the record, `flatpak override --env=LC_ALL=xx_XX.utf8` can be used for permanent change.) Setting languages doesn't seem to change anything though, newly installed applications still need `update --subpath=/lang`.

The list is produced with `locale -a` command. I'm not sure how various distributions handle it; in Arch the person who does the installation uncomments locales that are later generated with `locale-gen` in `/etc/locale.conf`. These locales are later possible to set by user in their desktop environment. Does Fedora generate all possible locales by default?

**Comment by barthalion** [comment]
Nope, it works fine also after `flatpak config --user --set languages en,pl`. Clearly a PEBKAC…

**Comment by albfan** [comment]
@ramcq seems the separator is semicolon

    $ flatpak config --user --set languages "es;ko"

Now I can see all the apps in spanish and korean

    LC_ALL=ko_KR.UTF-8 flatpak run <whatever>
    flatpak run --env=LC_ALL=ko_KR.UTF-8  <whatever>

**Comment by ramcq** [comment]
Oops! :)

**Comment by matthiasclasen** [comment]
I've now documented the syntax for the languages config in the flatpak-config man page

**Comment by hanariyada** [comment]
> @ramcq seems the separator is semicolon
> 
> ```
> $ flatpak config --user --set languages "es;ko"
> ```
> 
> Now I can see all the apps in spanish and korean
> 
> ```
> LC_ALL=ko_KR.UTF-8 flatpak run <whatever>
> flatpak run --env=LC_ALL=ko_KR.UTF-8  <whatever>
> ```

This doesn't work. Did you try https://flathub.org/apps/com.microsoft.Edge https://flathub.org/apps/org.chromium.Chromium?

```
flatpak run --env=LC_ALL=zh_CN.UTF-8 org.chromium.Chromium
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (zh_CN.UTF-8)

(process:2): Gtk-WARNING **: 10:20:14.432: Locale not supported by C library.
	Using the fallback 'C' locale.
```
