### ISSUE TITLE
URLs do not seem to open

### ISSUE THREAD

**Issue by MichaelAquilina** [flatpak/flatpak#1508]
I've noticed since switching to wayland that URLs do not seem to open in a browser when using flatpak applications. The current behavior I have to stick to is Right Click -> `Copy Link` -> Paste in browser url bar.

UPDATE: Just tried switching back to Xorg and the issue seems to persist.

I am running OpenSUSE Tumbleweed with Gnome 3.28

```
$ uname -a
Linux linux-vl27 4.15.9-1-default #1 SMP PREEMPT Sun Mar 11 22:31:16 UTC 2018 (2c1b8ee) x86_64 x86_64 x86_64 GNU/Linux
```

Let me know if any other specs would help you!

**Comment by TingPing** [comment]
The application has to use the correct portals which is *usually* automatic. What applications are you having problems with?

**Comment by MichaelAquilina** [comment]
Slack and Spotify both dont seem to work

**Comment by TingPing** [comment]
Spotify works fine here (If I click Upgrade Your Account).

It sounds like maybe you don't have `xdg-desktop-portal-gtk` installed?

**Comment by MichaelAquilina** [comment]
You were right that it was not installed. Just installed it now - but I still seem to have the same issue. I even tried restarting Slack just in case. Are there any logs I can check to help out with this?

**Comment by TingPing** [comment]
If you run `flatpak run --log-session-bus com.spotify.Client` you should see something like this when you open a URL:
```
C39: -> org.freedesktop.DBus call org.freedesktop.DBus.GetNameOwner at /org/freedesktop/DBus
B30: <- org.freedesktop.DBus return from C39
C40: -> :1.129 call org.freedesktop.DBus.Properties.GetAll at /org/freedesktop/portal/desktop
B2308: <- :1.129 return from C40
C41: -> :1.129 call org.freedesktop.portal.OpenURI.OpenURI at /org/freedesktop/portal/desktop
B2310: <- :1.129 return from C41
B2313: <- :1.129 signal org.freedesktop.portal.Request.Response at /org/freedesktop/portal/desktop/request/1_2626/t
```

**Comment by MichaelAquilina** [comment]
```
C12: -> org.freedesktop.portal.Desktop call org.freedesktop.portal.OpenURI.OpenURI at /org/freedesktop/portal/desktop
B189: <- :1.87 return error org.freedesktop.DBus.Error.UnknownMethod from C12
```
Got this from trying to open a link on Slack

**Comment by MichaelAquilina** [comment]
Restarting the entire machine seems to have solved this! I'm guessing the DBus daemon needed to restart.

**Comment by MichaelAquilina** [comment]
Sorry to re-open this issue but it seems like I am experiencing this problem again on the wayland desktop "sway". Here is what running spotify with the command previously specified shows:

```
[0506/182501.273260:ERROR:gl_surface_presentation_helper.cc(237)] GetVSyncParametersIfAvailable() failed!
[0506/182501.286998:ERROR:gl_surface_presentation_helper.cc(237)] GetVSyncParametersIfAvailable() failed!
[0506/182503.103852:ERROR:input_method_base.cc(146)] Not implemented reached in virtual ui::InputMethodKeyboardController *ui::InputMethodBase::GetInputMethodKeyboardController()Using InputMethodKeyboardControllerStub
C26: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C27: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C28: -> org.freedesktop.DBus call org.freedesktop.DBus.AddMatch at /org/freedesktop/DBus
C29: -> org.freedesktop.DBus call org.freedesktop.DBus.StartServiceByName at /org/freedesktop/DBus
B27: <- org.freedesktop.DBus return from C26
B28: <- org.freedesktop.DBus return from C27
B29: <- org.freedesktop.DBus return from C28
B30: <- org.freedesktop.DBus return from C29
C30: -> org.freedesktop.DBus call org.freedesktop.DBus.GetNameOwner at /org/freedesktop/DBus
B31: <- org.freedesktop.DBus return from C30
C31: -> :1.14 call org.freedesktop.DBus.Properties.GetAll at /org/freedesktop/portal/desktop
B105: <- :1.14 return from C31
C32: -> :1.14 call org.freedesktop.portal.OpenURI.OpenURI at /org/freedesktop/portal/desktop
B107: <- :1.14 return from C32
B110: <- :1.14 signal org.freedesktop.portal.Request.Response at /org/freedesktop/portal/desktop/request/1_32/t
```

Needless to say that I have installed `xdg-desktop-portal` and restarted my machine just in case.

**Comment by joemccall86** [comment]
I've noticed a consistency: if my first session is an X session (i3wm) links will work just fine in the slack flatpak. If I start with a Wayland session (sway) links do not work. If I subsequently start another X session without restarting links do not work. I hope this helps!

**Comment by Adonai** [comment]
I'm having the same problem. If you need any logs/info I'd be lad to provide.

**Comment by jccr** [comment]
Experiencing the same issue..

This other issue might be related:
https://github.com/flatpak/xdg-desktop-portal/issues/285

**Comment by gtors** [comment]
Have same problem with sway 1.2 and flatpak 1.5.0

**Comment by reestr** [comment]
I also have this problem with sway 1.4 and flatpak 1.6.3

**Comment by cmollekopf** [comment]
From also running into this under sway:
I have noticed that "systemctl --user show-environment" lacks variables such as DISPLAY, and it seems by first starting a gnome session (and perhaps also starting a flatpak in that session) that environment is getting updated. After that opening links works also from under sway (via the xdg-desktop-portal).

I'm not sure what exactly updates the systemd environment in the gnome session and what is supposed to handle that under sway.

**Comment by mavaa** [comment]
I can't use the Slack app at all on my machine, since the sign in button does nothing. Running `flatpak run --log-session-bus com.slack.Slack` logs the following when clicking the button:

`
C1: -> org.freedesktop.DBus call org.freedesktop.DBus.Hello at /org/freedesktop/DBus
C2: -> org.freedesktop.DBus fake AddMatch for org.kde.StatusNotifierWatcher
C3: -> org.freedesktop.DBus fake GetNameOwner for org.kde.StatusNotifierWatcher
C4: -> org.freedesktop.DBus fake AddMatch for com.canonical.AppMenu.Registrar
C5: -> org.freedesktop.DBus fake GetNameOwner for com.canonical.AppMenu.Registrar
C6: -> org.freedesktop.DBus fake AddMatch for org.freedesktop.Notifications
C7: -> org.freedesktop.DBus fake GetNameOwner for org.freedesktop.Notifications
C8: -> org.freedesktop.DBus fake wildcarded AddMatch for com.slack.Slack
C9: -> org.freedesktop.DBus fake wildcarded AddMatch for org.mpris.MediaPlayer2.com.slack.Slack
C10: -> org.freedesktop.DBus fake wildcarded AddMatch for org.freedesktop.portal
C11: -> org.freedesktop.DBus fake ListNames
B1: <- org.freedesktop.DBus return from C1
B2: <- org.freedesktop.DBus signal org.freedesktop.DBus.NameAcquired at /org/freedesktop/DBus
B3: <- org.freedesktop.DBus return from C2
*SKIPPED*
B4: <- org.freedesktop.DBus return error org.freedesktop.DBus.Error.NameHasNoOwner from C3
*SKIPPED*
B5: <- org.freedesktop.DBus return from C4
*SKIPPED*
B6: <- org.freedesktop.DBus return error org.freedesktop.DBus.Error.NameHasNoOwner from C5
*SKIPPED*
B7: <- org.freedesktop.DBus return from C6
*SKIPPED*
B8: <- org.freedesktop.DBus return error org.freedesktop.DBus.Error.NameHasNoOwner from C7
*SKIPPED*
B9: <- org.freedesktop.DBus return from C8
*SKIPPED*
B10: <- org.freedesktop.DBus return from C9
*SKIPPED*
B11: <- org.freedesktop.DBus return from C10
*SKIPPED*
B12: <- org.freedesktop.DBus return from C11
C12: -> org.freedesktop.DBus fake GetNameOwner for org.freedesktop.DBus
C13: -> org.freedesktop.DBus fake GetNameOwner for org.freedesktop.portal.Desktop
C14: -> org.freedesktop.DBus fake GetNameOwner for org.freedesktop.portal.Documents
*SKIPPED*
B13: <- org.freedesktop.DBus return from C12
*SKIPPED*
B14: <- org.freedesktop.DBus return from C13
*SKIPPED*
B15: <- org.freedesktop.DBus return from C14
*SKIPPED*
C15: -> org.freedesktop.portal.Desktop call org.freedesktop.portal.OpenURI.OpenURI at /org/freedesktop/portal/desktop
B186: <- :1.795 return from C15
`
I'm running a minimal Arch install with Lightdm & BSPWM as DM/WM, and qutebrowser as my main browser (Also have Firefox installed), so it might be that I'm missing a package/library somewhere. Installing Slack from AUR works perfectly. xdg-desktop-portal and xdg-desktop-portal-gtk are already installed.

**Comment by returntrip** [comment]
Worth trying this to sort this issue: https://github.com/flatpak/xdg-desktop-portal/issues/285#issuecomment-665109459

**Comment by dofinn** [comment]
Same on 
```
sway --version; flatpak --version
sway version v1.5
Flatpak 1.6.5
```

**Comment by saboya** [comment]
Trying to open a link gives me this:

```
20: -> org.freedesktop.portal.Desktop call org.freedesktop.portal.OpenURI.OpenURI at /org/freedesktop/portal/desktop
B281: <- :1.73 return error org.freedesktop.DBus.Error.AccessDenied from C20
```

**Comment by pvanderlinden** [comment]
This issue started recently (~ a week now). Links don't open anymore. I don't use firefox, so that is not the issue.
The packages xdg-desktop-portal and xdg-desktop-portal-gtk were already installed. The only thing I see in the logs when opening a link is:

```
C16: -> org.freedesktop.portal.Desktop call org.freedesktop.portal.OpenURI.OpenURI at /org/freedesktop/portal/desktop
B62: <- org.freedesktop.DBus signal org.freedesktop.DBus.NameOwnerChanged at /org/freedesktop/DBus
B63: <- org.freedesktop.DBus signal org.freedesktop.DBus.NameOwnerChanged at /org/freedesktop/DBus
...
```
The "NameOwnerChanged" message keeps repeating, but that also happens if I don't open a link. For the rest nothing happens. I have set a default browser (chrome)

**Comment by refi64** [comment]
Does `xdg-open` work from the local terminal? Also, what does `journalctl --user -u xdg-desktop-portal` say after you try opening a link...

**Comment by saboya** [comment]
`xdg-open` works from the local terminal. `journalctl --user -u xdg-desktop-portal` doesn't show anything:

```
$ journalctl --user -u xdg-desktop-portal
-- Logs begin at Thu 2021-02-11 13:43:57 -03, end at Fri 2021-02-12 00:38:45 -03. --
Feb 11 14:53:21 saboya-desktop systemd[3552]: Starting Portal service...
Feb 11 14:53:21 saboya-desktop systemd[3552]: Started Portal service.
```

**Comment by duartec3000** [comment]
I have the same problem using GNOME3 (Xorg) since 2 weeks ago any URL I click in a Flatpak applications does not open the native browser, does nothing in for example Flatpak Discord and hangs the application for 2 seconds in Flatpak Telegram.

**My System:**
OS: Arch Linux x86_64 
Kernel: 5.10.16-zen1-1-zen 
Packages: 1258 (pacman), 17 (flatpak) 
Shell: zsh 5.8 
Resolution: 1920x1080 
DE: GNOME 3.38.3 
WM: Mutter 
WM Theme: Adwaita 
Theme: Adwaita-dark [GTK2/3] 
Icons: Adwaita [GTK2/3] 
Terminal: gnome-terminal 
CPU: AMD Ryzen 5 2600X (12) @ 3.600GHz 
GPU: AMD ATI Radeon RX Vega 56/64 
Memory: 1941MiB / 16019MiB

**Troubleshooting:**
1. Installed both `xdg-desktop-portal `and `xdg-desktop-portal-gtk ` from official repository > reboot > testing: KO
2. Changed to Wayland from Xorg > testing: KO
3. Removed Firefox as default browser from GNOME Settings > reboot > re-added Firefox as default browser > reboot > testing: KO

**Requested information:**
`xdg-open https://www.youtube.com` > opens new Firefox tab: OK

After clicking a few links >run `journalctl --user -u xdg-desktop-portal` > results:
```
Feb 23 00:34:50 abox systemd[3893]: Starting Portal service...
Feb 23 00:36:20 abox systemd[3893]: xdg-desktop-portal.service: start operation timed out. Terminating.
Feb 23 00:36:20 abox systemd[3893]: xdg-desktop-portal.service: Failed with result 'timeout'.
Feb 23 00:36:20 abox systemd[3893]: Failed to start Portal service.
Feb 23 00:38:03 abox systemd[5906]: Starting Portal service...
Feb 23 00:39:33 abox systemd[5906]: xdg-desktop-portal.service: start operation timed out. Terminating.
Feb 23 00:39:33 abox systemd[5906]: xdg-desktop-portal.service: Failed with result 'timeout'.
Feb 23 00:39:33 abox systemd[5906]: Failed to start Portal service.
Feb 23 00:56:19 abox systemd[5906]: Starting Portal service...
Feb 23 00:57:49 abox systemd[5906]: xdg-desktop-portal.service: start operation timed out. Terminating.
Feb 23 00:57:49 abox systemd[5906]: xdg-desktop-portal.service: Failed with result 'timeout'.
Feb 23 00:57:49 abox systemd[5906]: Failed to start Portal service.
Feb 23 01:01:41 abox systemd[5906]: Starting Portal service...
```

Please let me know if you need more information I love Flatpaks and will do anything to help you iron this Bug.

**Comment by sorat0mo** [comment]
Hi, I am necroing this issue to describe what I encountered and how I fixed _my issue_.

I am currently using openSUSE Tumbleweed, on KDE.

So I installed the Librewolf flatpak(io.gitlab.librewolf-community) and set it to handle https/http url scheme, as well as setting it as the default browser for xdg-open. But flatpak apps still do not open links in the browser, i.e., nothing happens.

I tried enabling dbus for the app, no luck. Then I discovered this: https://librewolf.net/docs/faq/#cant-open-links-with-librewolf-when-using-wayland

Note, I am not using Wayland, but nevertheless, copying the flatpak version of .desktop file to `~/.local/share/applications` instantly fixed this for me. I hope this will help someone should they encounter the same problem as mine.

**Comment by alxlg** [comment]
@sorat0mo thank you very much, yours was the right solution to make the app Logseq handle the logseq:// protocol.
Here there are the two lines needed in the com.logseq.Logseq.desktop file if anyone need them:

```
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=run.sh --file-forwarding com.logseq.Logseq @@u %u @@
MimeType=x-scheme-handler/logseq;
```

**Comment by jinnko** [comment]
On Arch with wayland/sway It seems that xdg-desktop-portal-wlr is not sufficient as there is no intention to support OpenURI as indicated by this comment: https://github.com/emersion/xdg-desktop-portal-wlr/issues/42#issuecomment-667150324

With that understanding I installed xdg-desktop-portal-gtk and after a reboot it worked (didn't work immediately and I was unable to start xdg-desktop-portal-gtk manually and didn't investigate why).

**Comment by ikcikoR** [comment]
Same here, can't log into Unity3D because com.unity.UnityHub flatpak isn't opening the browser, getting:
```Failed to call portal: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface ?org.freedesktop.portal.OpenURI? on object at path /org/freedesktop/portal/desktop```
on Gentoo Linux with bspwm and pipewire because I saw someone mention that. Got `xdg-desktop-portal` 1.15.0 and flatpak 1.14.1 installed

**Comment by Thiago-Assis-T** [comment]
hey, having the same issues described above, in gentoo and in hyprland. would gladly provide more details and logs if asked, but I want to know if there is a timeframe to tackle this problem, it doesn't seem to be a security risk or anything of sorts, but it is quite anoying

if there isn't a plan, ill install slack from the gentoo repos (really rather use the flatpak since it is one of the few proprietary softwares I use along with zoom...) but if there isn't a plan to fix, ill use the official repo one, it is quite troboulsome to open meetings in zoom, since the links are broken.

if this comment felt in anyway rude or demanding, note it was not my intention, english just isn't my first or second language, it's my third and I know how foss can be hard, time comsuming and costly. anyway, if there is an atack plan to this matter, do let us know

**Comment by smcv** [comment]
The [original report](https://github.com/flatpak/flatpak/issues/1508#issue-307260289) from @MichaelAquilina was solved 5 years ago [by installing xdg-desktop-portal-gtk and then rebooting](https://github.com/flatpak/flatpak/issues/1508#issuecomment-375247104).

**Comment by smcv** [comment]
[A second report](https://github.com/flatpak/flatpak/issues/1508#issuecomment-489703025) from @MichaelAquilina seems to be unresolved. @MichaelAquilina, if you are still experiencing that problem, please check https://github.com/flatpak/flatpak/issues/1508#issuecomment-1702714679; and if that doesn't provide you with a solution, please open a separate issue with as much detail as you can provide.

**Comment by smcv** [comment]
@joemccall86:
> I've noticed a consistency: if my first session is an X session (i3wm) links will work just fine in the slack flatpak. If I start with a Wayland session (sway) links do not work. If I subsequently start another X session without restarting links do not work. I hope this helps!

This sounds like a problem with the environment variables needed to be able to launch a GUI app not getting put in the D-Bus/systemd activation environment by Sway, probably similar to https://github.com/flatpak/xdg-desktop-portal/issues/285.

@cmollekopf appears to have had the same thing. The same is probably true for other Sway users at around the same time.

**Comment by smcv** [comment]
@sorat0mo:
> Note, I am not using Wayland, but nevertheless, copying the flatpak version of .desktop file to `~/.local/share/applications` instantly fixed this for me.

At a guess, this probably means that the `XDG_DATA_DIRS` that Flatpak tries to set up are not present in your `systemctl --user show-environment` - similar to the issue with Sway, but different environment variables.

**Comment by smcv** [comment]
I'm closing this as not really actionable, because it has accumulated 5 years' worth of different reasons why opening links might not work, most of which are outside Flatpak's control.

If you are tempted to reopen this issue, or if you are experiencing a similar problem, please do not reopen this issue. Instead, please collect the information described in https://github.com/flatpak/flatpak/issues/1508#issuecomment-1702714679 and then open a **separate** issue, with as much information as possible, and as specific a title as possible.

The more specific and informative an issue report is, the more likely it is that someone can solve it.

> I want to know if there is a timeframe to tackle this problem

This is a community project whose maintainers have too many other responsibilities, so there is no specific timeframe to resolve anything. You can help problems to be solved more quickly by providing information (or solutions of course).

You can also help problems to be solved more quickly by trying to avoid several separate problems being discussed in the same issue report, which just makes everyone more confused and slower.

**Comment by ironhak** [comment]
Sorry to necropost. I've tried everything but the only thing that seems to have fixed was to execute at login `/usr/libexec/xdg-desktop-portal --replace` with my WM (i3), hence appending to config:
```
exec --no-startup-id /usr/libexec/xdg-desktop-portal --replace
```
Only in this way flatpak apps were able to open links. Can anyone give feedback on this?

**Comment by deviantsemicolon** [comment]
> Sorry to necropost. I've tried everything but the only thing that seems to have fixed was to execute at login `/usr/libexec/xdg-desktop-portal --replace` with my WM (i3), hence appending to config:
> 
> ```
> exec --no-startup-id /usr/libexec/xdg-desktop-portal --replace
> ```
> 
> Only in this way flatpak apps were able to open links. Can anyone give feedback on this?

This also worked for me. Thank you :)
