### ISSUE TITLE
Python3 round() behaviour in Flatpak

### ISSUE THREAD

**Issue by gnumdk** [flatpak/flatpak#1528]
From python3 on Fedora 28/ArchLinux:
```
>>> round(0.199999999999999999999999999999999999999999999999, 2)
0.2
```

From python3 in flatpak:
```
>>> round(0.199999999999999999999999999999999999999999999999, 2)
0.20000000000000001
```

Why this behaviour?

_Return number rounded to ndigits precision after the decimal point._

**Comment by mwleeds** [comment]
Check what version of python is in each? Maybe it just needs an update? Also specify what you mean by "in flatpak". Do you mean in `org.gnome.Platform`?

**Comment by barthalion** [comment]
I think it's dependent on python3 version. Python 3.6 from unstable freedesktop runtime returns `0.2`. (Either way, not a flatpak issue…)

**Comment by barthalion** [comment]
Although I can't reproduce it with local 3.5.2 build. @alexlarsson any ideas?

**Comment by gnumdk** [comment]
Yes I mean org.gnome.Platform.

**Comment by skewty** [comment]
Computers, when it comes to floating point values, usually don't store / hold the value you think they are.  They often just store approximations.
-----------------------------------------------------------------------
[Source: Python Docs](https://docs.python.org/3.7/tutorial/floatingpoint.html)

In the same way, no matter how many base 2 digits you’re willing to use, the decimal value 0.1 cannot be represented exactly as a base 2 fraction. In base 2, 1/10 is the infinitely repeating fraction

```
0.0001100110011001100110011001100110011001100110011...
```

Stop at any finite number of bits, and you get an approximation. On most machines today, floats are approximated using a binary fraction with the numerator using the first 53 bits starting with the most significant bit and with the denominator as a power of two. In the case of 1/10, the binary fraction is 3602879701896397 / 2 ** 55 which is close to but not exactly equal to the true value of 1/10.

Many users are not aware of the approximation because of the way values are displayed. Python only prints a decimal approximation to the true decimal value of the binary approximation stored by the machine. On most machines, if Python were to print the true decimal value of the binary approximation stored for 0.1, it would have to display

```
>>> 0.1
0.1000000000000000055511151231257827021181583404541015625
```

**Comment by mwleeds** [comment]
It seems clear that this isn't a flatpak issue.
