### ISSUE TITLE
Flatpak-ed GIMP runs as superuser?

### ISSUE THREAD

**Issue by Jehan** [flatpak/flatpak#1557]
## Linux distribution and version
Ubuntu 16.04
## Description of the problem
A user on Ubuntu reported us that Ubuntu is announcing that GIMP as flatpak is running as superuser. Since there is nothing special in our manifest (https://github.com/flathub/org.gimp.GIMP/) about such a thing, nor a need, I am assuming that the problem is either in flatpak and/or how Ubuntu detects that a process is owned by the superuser (probably through how the sandbox works).

Mailing list discussion: https://mail.gnome.org/archives/gimp-user-list/2018-April/msg00002.html
Also apparently not GIMP only but any flatpak, it would seem: https://github.com/mate-desktop/marco/issues/301

In any case, this is a bit of a trust issue if people believes GIMP runs as root.

**Comment by alexlarsson** [comment]
This is probably due to the flatpak:ed app running in a different pid namespace and mate being confused about this. I don't think there is much we can do, we're not *actually* running as root, nor are we reporting that from flatpak anywhere, its just a detection issue in mate.

**Comment by burianvlastimil** [comment]
Linux distribution and version: Linux Mint 19 Cinnamon 64-bit (based on Ubuntu 18.04)

Flatpak version: 1.0.1

Description of the problem:
The following does not produce any error message, thus confusing me:
```
$ /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=gimp-2.10 --file-forwarding org.gimp.GIMP
```

If I repeated the same command with:
```
$ sudo !!
```
The GIMP ran just fine, until reboot that is. Now GiMP won't run at all!

Ever since the Flatpak introduction, there are problems, ... could you maybe provide me with SIMPLE steps of debugging this Flatpak issue?

**Comment by mwleeds** [comment]
@burianvlastimil that sounds like a separate issue. Please open a new issue and include the steps you took to install the GIMP flatpak (e.g. was it `flatpak install flathub org.gimp.GIMP` or `sudo flatpak install flathub org.gimp.GIMP` or did you use a GUI).
