### ISSUE TITLE
p2p summary/metadata offline issues

### ISSUE THREAD

**Issue by alexlarsson** [flatpak/flatpak#1583]
I have some issue with the p2p offline support that i found when doing #1575 .

When doing an update or install, during the setup phase flatpak-transaction.c it needs to download the remote metadata for the ref to know the dependencies.  
For this the current code calls: flatpak_dir_fetch_ref_cache() -> flatpak_dir_lookup_repo_metadata() -> flatpak_dir_fetch_remote_repo_metadata() -> flatpak_dir_lookup_ref_from_summary() -> fetch_remote_summary_file(), which downloads the summary directly from the master uri. This is less convoluted after #1575, but the issue is there still.

If we are offline, this will fail because we can't get that summary. In order to allow an offline update the transaction code then ignores this failure:
```
      else
        {
          g_print (_("Warning: Can't find dependencies: %s\n"), local_error->message);
          g_clear_error (&local_error);
        }
```

Which makes the operation succeed, but without the metadata there is no guarantee that this results in a working system. Maybe the update depends on a new runtime which is not installed?

Similarily, the later call to flatpak_dir_find_remote_related() for things like locales will fail for similar reasons, but is also made optional:
```
      g_printerr (_("Warning: Problem looking for related refs: %s\n"), local_error->message);
```

This means you will not get translation updates when you are offline.

I'm also worried a bit about how the metadata branch is handled when doing system-helper deploys. We seem to pull the OSTREE_REPO_METADATA_REF into the child repo, but I don't really see it being used anywhere? (It is however, pulled and deployed to the system repo in flatpak_dir_fetch_remote_repo_metadata() which only works when online.)

I'm also worried a bit about the permissions handling in the offline install case. The general idea is that we use the metadata keyfile data to show at install time the permissions that the app requires. If you then install from some other peer might you not get a different version with different permissions?

**Comment by alexlarsson** [comment]
Ping @pwithnall @mwleeds

**Comment by mwleeds** [comment]
This is almost exactly the issue I fixed [here](https://github.com/endlessm/flatpak/pull/79) (except that is focused on install rather than update, but I think similar logic applies). My plan is to upstream some other Endless patches first before upstreaming that; otherwise there will be merge conflicts.

**Comment by pwithnall** [comment]
> When doing an update or install, during the setup phase flatpak-transaction.c it needs to download the remote metadata for the ref to know the dependencies.

Yeah, as Matthew says, the solution here is to make sure that flatpak uses `ostree-metadata` when offline to get related refs. I think `flatpak_dir_get_remote_state_optional()` shouldn’t be used here: if `ostree-metadata` doesn’t exist, a P2P update or install should fail.

Similarly for translations.

> I'm also worried a bit about how the metadata branch is handled when doing system-helper deploys. We seem to pull the OSTREE_REPO_METADATA_REF into the child repo, but I don't really see it being used anywhere? (It is however, pulled and deployed to the system repo in flatpak_dir_fetch_remote_repo_metadata() which only works when online.)

I’m out of the loop with that code, but what you describe does sound like a bug. I’d expect `ostree-metadata` to be pulled into the child repo so that it can be queried offline. Pulling and deploying it from the child to the system repo should only be necessary so we have a copy of it around for serving to other P2P peers in future, I think; by the time we’re copying things to the system repo, all the queries against `ostree-metadata` should be complete.

> I'm also worried a bit about the permissions handling in the offline install case. The general idea is that we use the metadata keyfile data to show at install time the permissions that the app requires. If you then install from some other peer might you not get a different version with different permissions?

What keyfile is this? Is it stored in the `summary`/`ostree-metadata`, but affects each app? If the permissions for an app are stored anywhere other than in the commit for that app (either in the commit content, or in the commit metadata), then there could be mismatches between the permissions and the installed app, yes.

**Comment by alexlarsson** [comment]
> Yeah, as Matthew says, the solution here is to make sure that flatpak uses ostree-metadata when offline to get related refs. I think flatpak_dir_get_remote_state_optional() shouldn’t be used here: if ostree-metadata doesn’t exist, a P2P update or install should fail.

flatpak_dir_get_remote_state_optional() just means "get what you can", and then you need to call ensure_xxx() if you require some specific thing. But, right not the code always relies on the online summary, as described above. Clearly this needs to be fixed before it can be made non-optional during e.g. an update.

> I’m out of the loop with that code, but what you describe does sound like a bug. I’d expect ostree-metadata to be pulled into the child repo so that it can be queried offline. Pulling and deploying it from the child to the system repo should only be necessary so we have a copy of it around for serving to other P2P peers in future, I think; by the time we’re copying things to the system repo, all the queries against ostree-metadata should be complete.

The remote state is pulled into the system repo during _flatpak_dir_fetch_remote_state_metadata_branch(), whic does a child repo pull and then a system-helper deploy of it. We then also pull it from the real update, but ignore the result of that.
Basically, this code seems a bit half-done.

> What keyfile is this? Is it stored in the summary/ostree-metadata, but affects each app? If the permissions for an app are stored anywhere other than in the commit for that app (either in the commit content, or in the commit metadata), then there could be mismatches between the permissions and the installed app, yes.

The way it works in the non-p2p case is we put the "metadata" file from the app in the commit xa.metadata field. During deploy we verify that the deployed file is identical to the data in the commit. To make the metadata accessible for dependency resolving and displaying permissions in gnome-software we also copy this data from the commit into the summary/ostree-metadata in build-update-repo.

I though we also verified that the summary metadata matched the commit data after a pull, but I can't seem to find the code that does this...

**Comment by mwleeds** [comment]
It looks like `flatpak_transaction_update_metadata` isn't P2P friendly either, so when doing an offline install you get `Error updating remote metadata for 'eos-apps': Error resolving “origin.ostree.endlessm.com”: Name or service not known`

Since `flatpak_dir_update_remote_configuration_for_state` uses the metadata already it should be simple to fix that.

**Comment by alexlarsson** [comment]
This is fixed by https://github.com/flatpak/flatpak/pull/1796
