### ISSUE TITLE
Temporary repos aren't always cleaned up

### ISSUE THREAD

**Issue by mwleeds** [flatpak/flatpak#1609]
## Linux distribution and version
Fedora 27
## Flatpak version
0.11.3
## Description of the problem
If an install or update operation is interrupted or fails, the temporary repos in /var/tmp/flatpak-cache-XXXXXX/ aren't necessarily cleaned up. This is separate from #1263 because I'm talking about the repo itself not the lock file.
## Steps to reproduce
1. Run "flatpak install ..." to start an install
2. Once the install has gotten far enough to create a repo in /var/tmp/flatpak-cache-XXXXXX/, disconnect from the Internet to make the install fail.
3. Notice that the repo is never cleaned up.

If the operation fails because the flatpak process is killed, I suppose there's not much we can do. But if there's an error we should be able to clean up.

**Comment by alexlarsson** [comment]
Well, its kinda meant to work like that. This is how a partially downloaded result are picked up again when we restart the operation if you had some sort of transient failure. We should *eventually* remove it though, but I think that will happen on the next successful operation, no?

**Comment by ramcq** [comment]
I think the recovery path from the full disk case should be more aggressive (like, drop all of the caches) because it's about disaster recovery and leaving the system usable again. Maybe we could remove all of the /other/ caches and on the first out of disk error, and if we have only one cache and we're still out of disk, then we have to remove it and throw the whole cache away?

Note that this out of disk fallback shouldn't be "plan A" - plan A should be avoiding getting into this state in the first place, because we're wasting either user disk space or bandwidth or both. But see https://github.com/ostreedev/ostree/issues/1557 for that.
