### ISSUE TITLE
Software versions not the latest ... FEATURE :  offline installation option in flatpak ?

### ISSUE THREAD

**Issue by aiamuzz** [flatpak/flatpak#1649]
## Linux distribution and version
Deepin OS 15.5

## Flatpak version
0.11.3.p1-4

## Description of the problem
Updates are not latest ...

## Steps to reproduce
some versions of apps ...

**flatpak** - version is as above  ... latest 0.11.7 (4 versions behind)
**qbittorrent** - flatpak installation is currently 4.0.3 (2 versions behind with the latest one being 4.1)
**pycharm** - currently 2017.3 (latest 2018.1.2)

## Any Possibility of ...

Does flatpak have an option of offline installations ?
Where one could download the regular download file(package) and then have it installed as a flatpak ?

It would be a great idea only if the current design/architecture of flatpak has room for such an option ... **Does it ?**

**Comment by TingPing** [comment]
> Software versions not the latest

Sure that happens, those just need updating.

> flatpak - version is as above ... latest 0.11.7 (4 versions behind)

That one is a discussion to have with your distro.

> Does flatpak have an option of offline installations ?

Kind of, bundles can be made but they don't exist for Flathub for example because they are just very inefficient. You have to make a bundle manually.

**Comment by aiamuzz** [comment]
thanks ...

software versions not the latest ...
**need updating** ... by us the users ?
or by the flatpak package managers for those particular apps ?

hmmm ... the 'bundles' concept sounds complex ... i was more so hoping it to be as easy as using the normal software downloads for linux and something akin to importing/installing into the flatpak environment.

**Comment by TingPing** [comment]
>  or by the flatpak package managers for those particular apps ?

Them.

**Comment by aiamuzz** [comment]
oh ... so it will be quite a while until flatpak users start getting the first updates of their apps ... may be when  the number of flatpak users grow things may change ...

**Comment by TingPing** [comment]
> oh ... so it will be quite a while until flatpak users start getting the first updates of their apps ... may be when the number of flatpak users grow things may change ...

What? Just ask them to update. It might happen in 5 minutes.

**Comment by aiamuzz** [comment]
oh ... its a simple process ...let me try ...

**Comment by mwleeds** [comment]
> Does flatpak have an option of offline installations ?

As @TingPing said, one option is to use flatpak bundles. Basically use a command like `flatpak build-bundle /var/lib/flatpak/repo gedit.flatpak org.gnome.gedit` to create the bundle and `flatpak install gedit.flatpak` to install it when offline. By default the app installed from a bundle won't ever be updated but look at the  `--repo-url` and `--runtime-repo-url` options for `build-bundle` for a way around that.

There's also more complete P2P install/update support in the works that allows you to install or update flatpaks from USB drives or peers on a local network such that they are then identical to an online install with respect to updates, etc. But you probably don't want to use it yet since it would require compiling flatpak yourself (for now) and it's still experimental.

**Comment by mwleeds** [comment]
It seems like this issue is about two separate things. Maybe make two issues next time? Anyway I think all the questions have been answered.
