### ISSUE TITLE
GPG verification for fetched sources/binaries

### ISSUE THREAD

**Issue by Esokrates** [flatpak/flatpak#1675]
Coming from https://github.com/flathub/org.signal.Signal/issues/27 it would imho be essential to gpg verify fetched sources/binaries to ensure their integrity.

Ideally I imagine the gpg key file to be stored along the json files and something like "verify-commands" that prepares the fetched files (e.g. debian package) for gpg verification.

Imho doing gpg verification fits well with the mission of flatpak (users trust the flathub store, so you better make sure to verify your origins otherwise I consider this to be irresponsible). The situation now is equal to simply downloading a binary without verifying the source which (despite the sandbox) leads to a false sense of security.

**Comment by Esokrates** [comment]
Regarding "maintainer can verify": of course they can, but imho there should be a policy that forces them to  actually do that (though that's out of scope for this issue) and it should be transparent to users which gpg key the verified against.

Checksum and filesize is absolutely not enough e.g. the hosting server gets pwned and you do not notice because you didn't verify that the package is actually signed with the key you trust.

Thus the gpg key should imho be stored along the json files.

**Comment by TingPing** [comment]
To make this a bit more simple, and backwards compatible, this could be all done at `flatpak-builder` time. It downloads and verifies the key but only the hash is kept in the package.

**Comment by Esokrates** [comment]
@TingPing I don't see how this would help build a web of trust. Imho gpg key should not be downloaded at build time, because it would only shift the problem to the download of the key. Ideally there should be a one time download of the key by the maintainer that is kept and all future downloads are verified against this key. If the key is revoked, the maintainer verifies the new key against the old one and replaces the key.

**Comment by TingPing** [comment]
What I meant doesn't necessarily conflict with that, the key could be kept in git for example.

**Comment by muelli** [comment]
> Coming from flathub/org.signal.Signal#27 it would imho be essential to gpg verify fetched sources/binaries to ensure their integrity.

what attack are you attempting to thwart with that defense?

**Comment by Esokrates** [comment]
@muelli Ensuring integrity of upstream. For the latter suppose some binary download page was hijacked and a new "release" binary was uploaded, how would you notice without verifying the gpg signature? It is a lot stronger measure to make sure new files are from the same authors and not just trust the webpage you see when you follow a link.

Especially today with governments investing very much money to try to prevent privacy there is a high interest if they could spread fake builds of Signal for example, therefore I find it vital to make sure the builds are really from Open Whisper Systems.

**Comment by muelli** [comment]
> how would you notice without verifying the gpg signature

with the hash in the manifest.

**Comment by Esokrates** [comment]
@muelli You did not understand my scenario correctly. Suppose the upstream site is hijacked and a new release is uploaded and the flatpak maintainer goes to the site, adds the new hash etc. in the manifest, then flatpak would simply spread the malware. So we must check upstream's integrity. Just because a new release is listed on their site, does not imply everything is fine and just copying the new Hash to the manifest could be fatal. The problem I described is not about a MITM attack between flatpak and upstream, but to verify upstream's integrity. 

Thats like trusting an email, just because it comes from an email address you trust, completely ignoring that cryptographic signing does way more more than just ensuring that the message is correctly downloaded from the address, I want also be sure it is authored by the sender I trust.

Judging by your Github profile I assume you understand the concept of web of trust. How would there be any strong cryptographic verification between Flathub and upstream if no cryptography is involved in between? 
Now you could argue that's a Faltpak maintainer's job to verify everything manually, but imho that's too weak. The link to the locally saved gpg key should be in the hash in order to rule out human error. The key should simple be stored the first time a faltpak package gets created and be trusted ultimately in order to ensure integrity of every future upstream release.

**Comment by Esokrates** [comment]
@muelli English is not my first language, so I guess "verify authenticity" instead of "verify integrity" would have been the better description.

**Comment by muelli** [comment]
> You did not understand my scenario correctly

probably. Now with your description I think the attack you are trying to prevent is understood.  Thanks for that description.



> How would there be *any strong cryptographic verification* between Flathub and upstream if *no cryptography* is involved in between?

heh, that sentence is tautological.



> Now you could argue that's a Faltpak maintainer's job to verify everything manually

yeah, that's the argument currently used. And yeah, that's not exactly watertight. But there is a publicly auditible log of what the maintainer of the package does, so attacks can probably be detected retrospectively, at least.

>  but imho that's too weak

fair enough.
Would doing the verification as part of the build steps by using `gpgv` or so with the key and the tarball in question thwart your attack? You could easily have that command in the manifest and flatpak-builder will bail if it fails.

> in order to rule out human error

hihi. I bet you'd find more people arguing that mixing gnupg into anything makes the likelihood of human error go through the roof.  But I get your point. Mind you though, currently the builds are stateless, that is, a build knows nothing about previous builds. In particular, it does not know whether the given OpenPGP key has validated the previous version of the package to build. I mention that because I haven't really understood what your actual proposal is now, because [here](https://github.com/flatpak/flatpak/issues/1675#issuecomment-389424760) you seem intend that state is being kept across builds implicitly by the system. (I am referring to your statement "that is kept and all future downloads are verified against this key"). And I need some more convincing in order to like that idea, because it comes with a great deal of complex questions to keep previous state. However, there is, as I've mentioned, the public git repository of the flatpak manifest to have an audit trail of what happened to a package.

**Comment by Esokrates** [comment]
@muelli I don't see a problem with the builds being stateless, gpgv as part of the build step is indeed something I would have in mind. What I was pointing out is, that the gpg key is not received every time the build happens, but the gpg key is stored along the manifest.

So submitting a new flatpak package would look like providing the json/xml files along with the gpg key of upstream. Maintainers job is to constantly update the manifest pointing to the new tarballs / tarball signature files and the build process then verifies the authenticity of the tarballs by verifying the signature with the stored key.

This would improve the situation, as with submitting a new package to flathub, reviewers can agree on the gpg key submitted along the json files and thus ultimately agree that specified upstream is authentic.

After some time a gpg key could be updated / revoked. Maintainers job is then to replace the gpg key and verify the new one against the old one. 

So there is no more reliance on the maintainer to gpg verify every new release. Even more secure would be if the the maintainer needs to request permission to change the gpg key he initially submitted, however I do not know about your review policy.

**Comment by Esokrates** [comment]
@muelli But not a single flatpak package I reviewed does that. Could there be some kind of policy introduced? Could you provide an example?

How would this be this be done optimally? A hacky way would be to make it part of "build-commands", but wouldn't introducing something like "verify-commands" where gpgv and preparing the received files before the build-commands be better?

For e.g. in case of Signal the verification process would involve downloading "Release" and "Release.gpg" (which is the signature, not the gpg key!) as well as the "Packages" file from the apt repository. Then "Release" would have to be verified against the gpg key the maintainer has uploaded. After that one has to check if the sha256sum of the "Packages" file is the one specified in "Release".  In the end there needs to be checked if the sha256sum of the received deb file is the one specified in "Packages".
Since I assume there are no apt/dpkg utils available in the build environment all of that text file parsing has to be done manually, so in order to keep the manifest clean I would suggest to outsource that logic into something like "verify-commands" where the preparation is done to receive the additional files, verify them against the gpg key and check the received deb file is the authentic one.

**Comment by muelli** [comment]
>But not a single flatpak package I reviewed does that. 

I'm not surprised. Is there even a single package that offers a signature for either the source or a binary? Let alone for the full dependency chain.

Hint: Signal does not provide a signed binary as far as I could find out. That is, the Debian package itself (note: Not the source code) does not carry a signature. I've checked https://updates.signal.org/desktop/apt/pool/main/s/signal-desktop/signal-desktop_1.10.1_amd64.deb and there is no signature in the archive as signed deb packages do.

> Could there be some kind of policy introduced?

Because I think that nobody is actually using signed packages, I think that introducing a policy is way too much to ask for (but I am not the one making any decisions anyway).  Unless I am judging the situation wrongly and there is actually a significantly sizeable fraction of packages that do offer signed source code.
For those who do, there is already a mechanism that you can use. `gpgv` is not making things exactly easy here in that it does not simply accept an openpgp key, a detached signature, and a file. But it's doable.






> A hacky way would be to make it part of "build-commands", but wouldn't introducing something like "verify-commands" where gpgv and preparing the received files for verification take place be better?

Yeah, maybe hacky. But it does the job for the maintainers who want to do it without annoying anybody else.  So I'd say that it's adequate compromise.

Note that I believe that the Signal people want to defend against a slightly different attack than what you've described. As far as I understand their motivations for wanting to be the only source of binaries, they want to defend against compromised builds that get in users hands without them noticing. This could probably be achieved by the package being reproducible. Then the flatpak build bots would yield the same binaries and the OWS build bots and OWS could somehow distribute that signature to its users.

**Comment by muelli** [comment]
> Of course the deb package is not signed itself

That wasn't obvious to me given that it's possible to sign deb packages.

> however in KDE land it is (as you can see all the tarballs have signtures):

that's great to hear.
Your attack is not thwarted by the defence you propose, though.  The attacker would need to inject a single small C file into any dependency, not just your target app. But making it more expensive for an attacker is a good thing, still. But only if the cost of defending is actually less than the expected expense of the attacker.

> The annoy argument is quite obscure to me, it is in everybody's interest to make sure maintainers actually do everything possible for the user's security

The good news is that they can do it already now. You, as the flathub app maintainer, can check in the OpenPGP key of your packages' source and verify that the downloaded sources are indeed signed with the key you've provided.

Adding a mandatory mechanism for verifying a Debian package listing that all flathub apps have to use does not sound like a reasonable thing to me.

`flatpak-builder` could facilitate verifying the signature by offering not only `sha256`, but also `signing-key` and `signature-file` or so.  Maybe that time is better invested in making flatpak-builder verify git tags, though.

**Comment by alexlarsson** [comment]
I agree that its important that flatpak packagers are careful with the sources they refer to, making sure they are actually from the real upstream. But, I don't really think there is currently an widespread in-use system that does this, and I don't think it is the place of flatpak to invent it. This affects all distros, and a solution needs buy-in from "everyone", so should be done as a separate project.

**Comment by Erick555** [comment]
> I don't really think there is currently an widespread in-use system that does this, and I don't think it is the place of flatpak to invent it

@alexlarsson Arch Linux does it. I don't now if this is enough "widespread in-use system" for you. There is nothing to invent - gpg is widely used for decades and in fact, it's used by flatpak as well but not for this part of supply chain. If flatpak-builder can use checksums then it can handle gpg keys too.

> This affects all distros, and a solution needs buy-in from "everyone", so should be done as a separate project.

Every distro has its own build infrastructure and packaging workflow. There is no everyone solution for fetching sources and I don't think anyone is currently looking for it. In flatpak sources verification is integral part of build process, done by flatpak-builder. I don't know why it should be moved to some third party tool. I understand that maybe you don't have time or resources to working on it but claiming this issue is on someone other than flatpak is IMHO dishonest.

**Comment by tugit** [comment]
@alexlarsson I disagree with closing this bug report. Yes, various upstream projects, like Gnome for example should support such an infrastructure by signing their releases appropriately, so that is in your words the buy-in from "everyone". 
Various distributions have each their own way of ensuring that, I don't think there will ever be away that everyone does it the same way.

**Comment by Erick555** [comment]
I just found there is already opened issue about this by @alexlarsson himself which is quite weird: https://github.com/flatpak/flatpak/issues/16
