### ISSUE TITLE
Disable sandbox for app

### ISSUE THREAD

**Issue by DelicatePanda** [flatpak/flatpak#1699]
Atom packages require access to external binaries (for eg., linter-php requires access to the PHP executable) and I can't find a way to add an exemption for this or better yet disable sandbox for a particular app.

**Comment by alexlarsson** [comment]
If you give flatpak access to the org.freedesktop.Flatpak.Development then you can use flatpak-spawn --host to run a command on the host. Its not really possible to run a binary from the host inside the sandbox though, because it depends on the libraries on the host, which may not be compatible with the ones in the sandbox.

**Comment by DelicatePanda** [comment]
Can't I disable sandbox (preferably for only one package?

**Comment by TingPing** [comment]
No, the sandbox isn't optional. You can only poke holes in it.

**Comment by DumboJetEngine** [comment]
For all it's worth, I would like a way to run an app without a sandbox too.
I want to run VS Code and have access to system SDKs.
I've turned to flatpaks to avoid getting a "library version hell" in my system from installing from unofficial sources.

I don't understand why the sandbox is required.
If the each flatpak is updated regularly (perhaps automatically), and supply chain attacks are prevented, then there shouldn't be any known and unpatched vulnerabilities left (compared to the latest software version), right? Since no library compatibility testing is required, shouldn't it be easy to automate the flatpak package generation and publishing?

A question:
If I install VS Code, PowerShell and .NET 5 as flatpaks, will VS Code be able to see those other flatpaks and use them as SDKs?

P.S.:
I see now that there is no flatpak for .NET libraries, nor PowerShell, and I am pulling my hair out...
I have read somewhere that Flatpaks target GUI apps mainly.
Is this the reason those SDKs are missing?
Maybe this should be reconsidered a bit?
Because I feel that there are many restrictions in place, that don't serve a solid purpose.
But perhaps it is just my impression. Donno.

**Comment by TingPing** [comment]
@DumboJetEngine This is a very old, closed issue, with a clear answer.

So I'll just repeat: The sandbox isn't optional, it can't be optional.

For VSCode I'd probably recommend using this extension https://code.visualstudio.com/docs/remote/ssh to execute on the host.

**Comment by spikespaz** [comment]
How dumb.

**Comment by christianparpart** [comment]
@TingPing I'm building a terminal emulator, which -naturally- needs system access. I was considering using flatpak as way of distribution and it seems like system packages are by default left out? Maybe I am misunderstanding something here. So, from a terminal emulator point of view, it's rarely the case where only specific UNIX sockets or path parts should be whitelisted, but people want actual system access (by default). So I was looking for an option to build a flatpak package that has actual host access.

**Comment by TingPing** [comment]
@christianparpart You can escape the sandbox (different than disabling it). There are some apps doing that for a terminal.

- https://github.com/gnunn1/tilix/blob/5008e73a278a97871ca3628ee782fbad445917e7/source/gx/tilix/terminal/terminal.d#L2963
- https://gitlab.gnome.org/chergert/flatterm/-/blob/master/fp-vte-util.c

**Comment by llothar** [comment]
I think enforcing the sandbox is a terrible decision, let me explain.

There are two important use cases: 

1) Application packaging and deployment
2) Security 

Flatpak at the beginning was, as far as i remember, just about (1), because this was the biggest pain point for the desktop. 

And then the security people came in and ruined it. Just listen to Linus Torvald and his attitude against this security fanatics who want to break the kernel regularly. Security leads always to fascism. And thats what we see when we make everything mandatory. Why should flathub be a walled garden like Apple? Apple and Google are doing this primarily for business purposes. If your money comes from everyone installing and paying as many apps as possible they need high safety.  

Sandboxes are good for tiny little apps from the mobile world. Linux Desktop is nowhere in the mobile world ints in the business and geek domain. But business applications (especially all developer apps) need a lot of interaction. And its the unix mantra to have multiple apps that do one thing good and you pipe data through them. You need plugins and calls to the outside world. 

As long as we have still no solution to (1) you guys, with all the good intensions you have, you are the reason why we still waiting for the year of the Linux desktops, and its not coming. Meanwhile MacOS and Windows are laughing. 

MacOS just needs notarisation. Aka someone looked at your program and it didn't crash immediately. 

Windows just last month released the latest Win Application SdK 1.1. And in it Microsoft removed the last bits that were remains from their enforced sandboxing area. Now good old file copy installation works again with Win UI3.  UWP and Windows 8 run against the same wall that flatpak is running against today. But they already realized after a few years  that this sandboxing was the death for business apps and as a result the windows store was as boring as all unix stores right now.  

Just put a big fat warning sign for non sandboxed apps and give people the freedom to live fast and furious.  Most people will choose this over masks and potential danger of less then 2% of getting infected (uups wrong topic, but same argument).

Flatpak is technically a good solution for (1). Dont force me to go Canonical way and only provide snaps with classic confiment.

**Comment by TingPing** [comment]
Please stop bumping 4 year old issues.

Flatpak is a sandbox, its designed around a sandbox, and only time travelers can change this.

**Comment by llothar** [comment]
I don't want to remove the sandbox.

I asking to be able to remove the most restricting security restrictions from the sandbox. 
I thought i made it clear that this are two total independent things.

And the current progress to finally (a handful of years after i asked for it) extend it to provide native messaging web extensions is a sign that everything is possible if you poke the team long enough.

**Comment by kuiperzone** [comment]
> I think enforcing the sandbox is a terrible decision, let me explain.
> 
> There are two important use cases:
> 
> 1. Application packaging and deployment
> 2. Security
> 
> Flatpak at the beginning was, as far as i remember, just about (1), because this was the biggest pain point for the desktop.
> 
> And then the security people came in and ruined it. Just listen to Linus Torvald and his attitude against this security fanatics who want to break the kernel regularly. Security leads always to fascism. And thats what we see when we make everything mandatory. Why should flathub be a walled garden like Apple? Apple and Google are doing this primarily for business purposes. If your money comes from everyone installing and paying as many apps as possible they need high safety.
> 
> Sandboxes are good for tiny little apps from the mobile world. Linux Desktop is nowhere in the mobile world ints in the business and geek domain. But business applications (especially all developer apps) need a lot of interaction. And its the unix mantra to have multiple apps that do one thing good and you pipe data through them. You need plugins and calls to the outside world.
> 
> As long as we have still no solution to (1) you guys, with all the good intensions you have, you are the reason why we still waiting for the year of the Linux desktops, and its not coming. Meanwhile MacOS and Windows are laughing.
> 
> MacOS just needs notarisation. Aka someone looked at your program and it didn't crash immediately.
> 
> Windows just last month released the latest Win Application SdK 1.1. And in it Microsoft removed the last bits that were remains from their enforced sandboxing area. Now good old file copy installation works again with Win UI3. UWP and Windows 8 run against the same wall that flatpak is running against today. But they already realized after a few years that this sandboxing was the death for business apps and as a result the windows store was as boring as all unix stores right now.
> 
> Just put a big fat warning sign for non sandboxed apps and give people the freedom to live fast and furious. Most people will choose this over masks and potential danger of less then 2% of getting infected (uups wrong topic, but same argument).
> 
> Flatpak is technically a good solution for (1). Dont force me to go Canonical way and only provide snaps with classic confiment.


I have to say I completely agree.

Just spent a week learning how to build a Flatpak and feel I have just wasted my time. Impossible to build a real world app in this damn sandbox.

As a user of Flatpak apps, I always have issues with those apps being able to see my drives. A normal user should not have to spend their time with Flatseal and learning about D-bus permissions. This is madness!

**Comment by kuiperzone** [comment]
I utterly fail to understand the rational of sandboxing and associated permissions. Almost all apps will override the restrictions and users will just wave them through. For apps that don't override sufficiently, users need to fight with the sandbox themselves -- hence the reason for the existence of Flatseal.

Flatpak sandboxing merely thwarts good developers while, not only do nothing to protect regular users, but actually frustrates them!.

See also:
Flatpak - a security nightmare
https://flatkill.org/

Here below, for example, is a screenshot of the crippled save dialog from Pinta. Yes I fix it with Flatseal, but the point is that as a user I should have to!

![image](https://user-images.githubusercontent.com/17156238/216490515-9fcf3e8b-4c05-4092-a927-f0708bc8818b.png)

Having just written an experimental deployment utility to support Flatpak, I find myself in the bizarre position of recommending users don't use it. Instead I feel I will need to look in the future to: AppImage, Snap, RPM, deb etc.

**Comment by TingPing** [comment]
I'm locking this thread because there is nothing to discuss here. Bumping a 5 yo closed issue isn't productive. 

Flatpak is, fundamentally, a sandbox. It cannot be simply disabled.

The way filesystem access is abstracted through portals can be improved but that clearly isn't the discussion here.
