### ISSUE TITLE
Allow sandbox exemption of just --device=video for accessing V4L2 devices

### ISSUE THREAD

**Issue by alexander255** [flatpak/flatpak#1715]
## Linux distribution and version

Debian unstable

## Flatpak version

Flatpak 0.11.7

## Description of the problem

I'm trying to port an application to Flatpak that has a feature where allows you to scan a QR code with a payment address. For this the application needs some kind of camera access. Since there doesn't seem anything like a video/camera portal available this requires raw access to the V4L2 video device nodes. Currently the only way of doing this seems to be the `--device=all` sandbox exemption flag (which fortunately does exist), ideally however this could be limited to just V4L2 video devices.

A hyptothetical `--device=video` flag would then grant access to:

  * V4L2 raw device nodes (RegExp: `/dev/video[0-9]+`)
  * V4L2 device symlinks (Wildcard: `/dev/v4l/by-*/*`)
  * Maybe also: V4L2 SysFS information (`/dev/class/video4linux`)

**Comment by TingPing** [comment]
The solution for this moving forward will be using Pipewire so I don't think it makes sense to make convenience permissions for the unsandboxed support.

**Comment by alexander255** [comment]
@TingPing: Is there an ETA for Pipewire as default in all major distros (including LTS)? Do you know of a QR-recognition library that supports video capturing using PipeWire? Until then I'd think there's still “a market” for such a permission.

**Comment by alexlarsson** [comment]
This kind of device is tricky, because video devices are very dynamic (i,e. usb plugging) and the device nodes have to be set up at sandbox setup time. So, i don't think this is doable. Also --device=all is not *that* problematic as a temporary solution until we get pipewire everywhere, because most device nodes are not readable as non-root. Also, the rest of sandboxing is not really safe anyway until everything moves to wayland, etc.

So, for sandboxing we target the long-term, which is pipewire, and for "works right now" we're fine with --device=all.

**Comment by alexander255** [comment]
@alexlarsson: Thanks for expressing a clear analysis and opinion on this subject! We'll just keep using `--device=all` for the forseeable future then and see if/when a replacement becomes feasable.
