### ISSUE TITLE
The apps take a long time to start.

### ISSUE THREAD

**Issue by alexb3d** [flatpak/flatpak#1768]

**Comment by alexlarsson** [comment]
Typically when this happens it is because flatpak needs to regenerate the fontconfig font caches, and it should only happen once (per app). Does the slowness persist when launching the same app multiple times?

Did you recently update fontconfig on the host, or something like that?

**Comment by aiamuzz** [comment]
> it should only happen once (per app)

the regeneration of fontconfig font caches that you are referring to ... does this happen only once after the first install/update ? or it happens the first time after a system is freshly booted up ?

I too find the flatpak apps start off a little slow compared to the non-flatpak ones ...

**Comment by alexb3d** [comment]
Whenever I open a Flatpak app. It does not matter how many times I open it.

I do not know what fontconfig is.

**Comment by ahayzen** [comment]
@alexlarsson while making the Ubuntu package for SRU, I am also seeing this on a fresh VM. Furthermore I also see the issue of this happening every time an app is launched (eg not just first launch).

Usually when there is something which blocks for 25 seconds on Ubuntu, we say blame a dbus issue (as that is what the timeout is set at IIRC).

Let me know if there is any debug information I can acquire.

**Comment by rugk** [comment]
Also happens with UberWriter for me, but not for other flatpaks. It is persistent during application restarts.

**Comment by alexlarsson** [comment]
Hmm, I think I need some help debugging this then, because both blender and uberwriter starts essentially instantly for me. I mean, it might take half a second or something before the window is fully shown, but certainly not 25 seconds.

When this happens can you `flatpak run -v org.the.app` and post the output here, including *where* in the output the pause happens.

**Comment by ahayzen** [comment]
@alexlarsson this is starting org.gnome.Recipes

```
$ flatpak run -v org.gnome.Recipes
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening user flatpak installation at path /home/andrew/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/andrew/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak

===== Pause here for 25 seconds =====

F: Allowing wayland access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/andrew/.config/pulse/client.conf': Error opening file /home/andrew/.config/pulse/client.conf: No such file or directory
F: Running 'bwrap --args 21 /usr/lib/flatpak/flatpak-dbus-proxy --args=23'
F: Running 'bwrap --args 20 gnome-recipes'
```

**Comment by alexb3d** [comment]
Hello, it is already functioning normally. Thank you very much.

**Comment by alexbrrsclnt** [comment]
This is starting to happen to me since 2 days ago, in two different PCs, a desktop at home and a laptop at work.

It doesn't happen with all the apps, for example, LibreOffice and Xonotic start very fast, but VLC and KeepassXC take a lot. This last one, in both home and work PCs, it is an app that I use a lot every day, and it really surprised me when started to take so long to show me the password prompt.

How can I provide some feedback or util information?

**Comment by alexb3d** [comment]
I had a similar problem with some applications after an update. I deleted the configuration folders and they worked fine.  `~/.var/app/`

**Comment by LinuxOnTheDesktop** [comment]
For the program 'fwupd`, deleting the configutation directory (as per the post by alexb3d above) did _not_ fix the problem for me.

**Comment by somas95** [comment]
This seems to be the case again. Apostrophe takes 30 seconds to start, and deleting ~/.local/share/flatpak/db or ~/.var/app doesn't solve the issue either
