### ISSUE TITLE
please create a flatpak driver for nvidia-390-67

### ISSUE THREAD

**Issue by michellemark** [flatpak/flatpak#1769]

**Comment by RogueScholar** [comment]
Driver Release Page: http://www.nvidia.com/download/driverResults.aspx/134859/en-us

Direct Download Link: http://us.download.nvidia.com/XFree86/Linux-x86_64/390.67/NVIDIA-Linux-x86_64-390.67.run

**Comment by michellemark** [comment]
I have the driver installed... the problem comes when I try to run nuvola for my amazon cloud player.  That is what needs this now that my system has automatically updated to this new version.  The documentation says if it isn't in the list to request it here, and this newest update I just installed a few days ago is not in the list https://github.com/tiliado/nuvolaruntime/wiki/Graphics-Drivers

**Comment by RogueScholar** [comment]
@michellemark My bad, I really should have included some context with my earlier post. I opened issues here for the last couple minor driver updates from NVIDIA and included the direct links to the official release with them as I did above. Both times the illustrious @TingPing had builds underway in under a half hour, with the results hitting the flathub repo scant minutes afterward...talk about feeling like royalty! My earlier reply here was simply another attempt at trying to keep the time-cost of setting up the new Buildbot builder at a minimum for whoever was kind enough to do so.

I too am a Nuvola user and once again am in @TingPing 's debt for making the magic happen on this task yesterday afternoon. (In all fairness I wish @fenryxo had a similar Buildbot setup since it's his ecosystem that necessitates the effort and we could nag him about them; I dislike having to lean on @TingPing every time) My apologies for the ambiguity that prompted you to elaborate on your request unnecessarily.

**Comment by fenryxo** [comment]
> In all fairness I wish @fenryxo had a similar Buildbot setup since it's his ecosystem that necessitates the effort and we could nag him about them

I don't understand how it would help if I set up a build bot for the driver. I mean I could build the driver extension and upload it to Nuvola's repository, but @TingPing would be still building the same extension for Flathub to be used by all other flatpaks.

**Comment by alexlarsson** [comment]
Closing this as the driver should be in flathub now
