### ISSUE TITLE
GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name :1.567 was not provided by any .service files

### ISSUE THREAD

**Issue by mwleeds** [flatpak/flatpak#1845]
## Linux distribution and version
Fedora 28
## Flatpak version
0.99.2 (built from git master)
## Description of the problem
It took me two tries just now to install an app. Here's what happened the first time:
```
$ flatpak install eos-apps com.endlessm.wiki_art.en
1 metadata, 0 content objects fetched; 569 B transferred in 1 seconds           
Required runtime for com.endlessm.wiki_art.en/x86_64/eos3 (runtime/com.endlessm.apps.Platform/x86_64/3) found in remote eos-sdk
Do you want to install it? [y/n]: y
Installing in system:
com.endlessm.apps.Platform/x86_64/3                     eos-sdk  07046fc5a683
org.freedesktop.Platform.Icontheme.EndlessOS/x86_64/1.0 eos-sdk  a73d8e9d75d5
com.endlessm.apps.Platform.Locale/x86_64/3              eos-sdk  7b8861e41a47
com.endlessm.wiki_art.en/x86_64/eos3                    eos-apps 59b85f128df8
  permissions: ipc, network, pulseaudio, x11, dri
  dbus access: org.gnome.OnlineAccounts, org.gnome.Software
  system dbus access: com.endlessm.Metrics
Is this ok [y/n]: y
Installing: com.endlessm.apps.Platform/x86_64/3 from eos-sdk
[####################] 2218 metadata, 16209 content objects fetched; 179662 KiB transferred in 1413 seconds
Warning: Failed to install com.endlessm.apps.Platform/x86_64/3: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name :1.567 was not provided by any .service files
Installing: org.freedesktop.Platform.Icontheme.EndlessOS/x86_64/1.0 from eos-sdk
[####################] 28 metadata, 140 content objects fetched; 111 KiB transferred in 4 seconds
error: Failed to install org.freedesktop.Platform.Icontheme.EndlessOS/x86_64/1.0: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name :1.567 was not provided by any .service files
```
## Steps to reproduce
1. Have a slow Internet connection
2. Try to install something.

**Comment by mcatanzaro** [comment]
> Have a slow Internet connection

That is not required to reproduced. I have a 200 Mbps connection and I just hit this with flatpak 0.99.2.

**Comment by alexlarsson** [comment]
When this happens, does the flatpak-system-helper exit or die/crash or something?

**Comment by GongT** [comment]
Fedora 28 & 0.99.2 from dnf

```
Required runtime for com.github.wwmm.pulseeffects/x86_64/stable (runtime/org.gnome.Platform/x86_64/3.28) found in remote flathub
Installing in system:
org.gnome.Platform/x86_64/3.28                    flathub e676fe7f9420
org.freedesktop.Platform.ffmpeg/x86_64/1.6        flathub d757f762489e
org.gnome.Platform.Locale/x86_64/3.28             flathub 0296024b5e1d
com.github.wwmm.pulseeffects/x86_64/stable        flathub ea4a15b3eaf9
  permissions: ipc, pulseaudio, wayland, x11
  file access: xdg-run/dconf, ~/.config/dconf:ro
  dbus access: ca.desrt.dconf
com.github.wwmm.pulseeffects.Locale/x86_64/stable flathub 7c6f7edcb09a
Installing: org.gnome.Platform/x86_64/3.28 from flathub
[####################] 10 delta parts, 80 loose fetched; 261229 KiB transferred 
Warning: Failed to install org.gnome.Platform/x86_64/3.28: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name :1.176 was not provided by any .service files
Installing: org.freedesktop.Platform.ffmpeg/x86_64/1.6 from flathub
[####################] 1 metadata, 0 content objects fetched; 569 B transferred in 4 seconds
error: Failed to install org.freedesktop.Platform.ffmpeg/x86_64/1.6: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name :1.176 was not provided by any .service files
```

**Comment by dsboger** [comment]
In my case, updating com.google.AndroidStudio seems to be causing this same issue. Whenever I try updating it, that "ServiceUnknown" problem occurs, and every update queued after AndroidStudio also fails with the same message. Leaving AndroidStudio out and updating everything else worked.

**Comment by smcv** [comment]
This is the Flatpak system helper service crashing. I get this while smoke-testing a backport of Flatpak 0.99.2 to Debian 9 'stretch'.

```
Jul 06 17:54:16 d9gnome dbus[411]: [system] Successfully activated service 'org.freedesktop.Flatpak.SystemHelper'
Jul 06 17:54:16 d9gnome systemd[1]: Started flatpak system helper.
Jul 06 17:54:16 d9gnome kernel: pool[2703]: segfault at 8 ip 000055e6f445e813 sp 00007fa0e8dee560 error 4 in flatpak
-system-helper[55e6f4447000+81000]
Jul 06 17:54:16 d9gnome systemd[1]: flatpak-system-helper.service: Main process exited, code=killed, status=11/SEGV
Jul 06 17:54:16 d9gnome systemd[1]: flatpak-system-helper.service: Unit entered failed state.
```

I'll try to get a backtrace.

**Comment by smcv** [comment]
Looks like #1854?

```
                Stack trace of thread 4231:
                #0  0x00005569ac20f813 handle_deploy_appstream (flatpak-system-helper)
                #1  0x00007fd535965038 ffi_call_unix64 (libffi.so.6)
                #2  0x00007fd535964a9a ffi_call (libffi.so.6)
                #3  0x00007fd53b96e7ae g_cclosure_marshal_generic (libgobject-2.0.so.0)
                #4  0x00007fd53b96df75 g_closure_invoke (libgobject-2.0.so.0)
                #5  0x00007fd53b97ff82 n/a (libgobject-2.0.so.0)
                #6  0x00007fd53b987d41 g_signal_emitv (libgobject-2.0.so.0)
                #7  0x00005569ac253499 _flatpak_system_helper_skeleton_handle_method_call (flatpak-system-helper)
```

**Comment by smcv** [comment]
No, looking at this in gdb, I'm in the `/* empty path == local pull */` case in `handle_deploy_appstream()`, specifically this statement:

```
              g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_FAILED,
                                                     "Error pulling from repo: %s", second_error->message);
```

and `second_error` is NULL, because the second `flatpak_dir_pull()` call passed a NULL `GError **` instead of the `&second_error` that was presumably intended.

**Comment by smcv** [comment]
I haven't been able to reproduce this since applying #1867.

**Comment by alexlarsson** [comment]
I think what happens is that flatpak-system-helper idle times out 10 minutes after the last operation, and we keep a single dbus proxy object around for the lifetime of the FlatpakDir. If we create the SystemHelper early on we resolve the name and keep the unique id, and then it dies we will get this error, because the proxy only resolves the name once.

**Comment by strongholdmedia** [comment]
> In my case, updating com.google.AndroidStudio seems to be causing this same issue. Whenever I try updating it, that "ServiceUnknown" problem occurs, and every update queued after AndroidStudio also fails with the same message. Leaving AndroidStudio out and updating everything else worked.

This.
Since some update (I am on Debian 10, but same happens on Debian 9), with Android Studio installed, I receive this error every now and then, including with flatpak.
But for me, _it only seems to cause problems when I have an Android device connected_.
(Autostarting the emulator may also count as one, for whoever configured it to always run.)

**Comment by smcv** [comment]
@strongholdmedia: Please open a separate bug report with details and steps to reproduce the problem. The high-level symptom you see being the same does not mean that the root cause is the same. If it turns out to be the same root cause then it's easy to close a separate bug as a duplicate, but if the root cause is different and two causes get mixed up on the same bug number, it's really confusing for everyone and will make it slower and more difficult to solve the bug.

**Comment by strongholdmedia** [comment]
I absolutely didn't want to file a bug report whatsoever.
I just suggested that anyone who can actually reproduce this issue try with any Android devices, including any possible emulators, disconnected, so that it may help them to narrow down any set of causes.

_I also have the personal opinion that the primary issue is _not_ with Flatpak, and if you indeed want to make the update "bulletproof" should any lower level script fail (that I suppose the case is currently), then you may try to rename the issue as such. But this is only a suggestion._

(I find it sad to see that more and more people are in this continuous-integration-flow-metrics-BS-obsessed mindset recently instead of actually being focused on rectifying issues, like in my opinion collaboration should.)

**Comment by Gameransari** [comment]
The solution is here... :)
https://youtu.be/34iXHWuhsss

**Comment by Gameransari** [comment]
This is the Solution
https://youtu.be/34iXHWuhsss
