### ISSUE TITLE
flatpak_transaction_progress_get_status() isn't very good

### ISSUE THREAD

**Issue by hughsie** [flatpak/flatpak#1858]
At the moment `flatpak_transaction_progress_get_status()` returns an allocated string:

    Downloading metadata: 0/(estimating) 0 bytes:0
    Downloading: 21.3 kB/372.0 kB:13

The "estimating" hueristic is broken out as `flatpak_transaction_progress_get_is_estimating()` which is useful, but it would be much more helpful if `_get_status()` returned a enum of `FLATPAK_TRANSACTION_STATUS_DOWNLOADING` or `FLATPAK_TRANSACTION_STATUS_DOWNLOADING_METADATA` and a new method (perhaps called `flatpak_transaction_progress_get_text()` returned the ostree-provided low-level info suitable for a command line.

At the moment I'm scraping the string, which isn't awesome, and I don't know if the string from `_get_status()` is ever going to be translated for a non-en locale. Thanks.

**Comment by alexlarsson** [comment]
Well, its fundamentally very hard to do progress reporting with ostree pull due to the fact that it doesn't know all that will be downloaded until the end. We do our best to try to get something easy out, but its very hard. The current progress estimation took several rounds of iteration to get something that sort of worked.

However, the progress is at least a GObject now, so we can extend it.

**Comment by matthiasclasen** [comment]
closing this for now. if you need other bits of information, please open new issues for them
