### ISSUE TITLE
Full homedir access and custom xdg-user-dir setup conflict

### ISSUE THREAD

**Issue by alexlarsson** [flatpak/flatpak#19]
This was originally:
https://bugs.freedesktop.org/show_bug.cgi?id=91163

If you explicitly allow xdg-documents, then it will load the real user-dirs.dir and create a new one inside ~/.var/app/$appid/config based on that. But if you allow access to the entire homedir it does not do this. I guess we need to do this for all configured xdg dirs if the whole homedir is visible.

**Comment by mariospr** [comment]
I came across this issue today while investigating a problem we had with an app, which "refused" to know  what the different `XDG_*_DIR` user directories were except `XDG_DESKTOP_DIR` (and this one only because it was being [artificially added by GLib](https://git.gnome.org/browse/glib/tree/glib/gutils.c#n1761)), even despite of granting either `home` or `host` access to the app.

After quite some investigation I found that the problem I was seeing was caused by https://github.com/flatpak/flatpak/commit/f1df5cb1 and easily fixable by simply cherry picking https://github.com/flatpak/flatpak/commit/81f48024, but I thought I'd comment here because I read the whole fdo bug and it feels to me like the problem originally reported by Dan there might not be an issue anymore (since user-dirs.dirs gets bind mounted when home access is granted, which seems to match Dan's suggestion in https://bugs.freedesktop.org/show_bug.cgi?id=91163#c5.

@alexlarsson Could you confirm if I'm missing anything and whether this issue is solved now? Thanks!

**Comment by alexlarsson** [comment]
Yes, this seems fixed by 0040312b07fc62fb0ff1ed2568968b0f25fe1de1 (but then regressed, and later was re-fixed in https://github.com/flatpak/flatpak/commit/81f48024
