### ISSUE TITLE
Unable to uninstall app when remote cannot be found

### ISSUE THREAD

**Issue by bastianilso** [flatpak/flatpak#1982]
## Linux distribution and version
Arch Linux

## Flatpak version
v0.99.3

## Description of the problem
I was using `flatpak list` to list all apps I have and found quite a few I dont actually use. One of them is `org.gnome.Calendar/x86_64/master` which I installed a long time ago (only available for user). So I ran `flatpak uninstall org.gnome.Calendar/x86_64/master`, expecting it to uninstall the app. Instead Flatpak responded with `error: Remote "gnome-builder-builds" not found` and `org.gnome.Calendar/x86_64/master` is still installed.

It is unclear for me how to proceed or why Flatpak errors out if it cannot find the remote. Is this a bug? Or could we perhaps improve the error handling here to give more clear instructions?

**Comment by bastianilso** [comment]
Update: it also seems like I cannot run `flatpak update` due to this remote being missing.

**Comment by mwleeds** [comment]
Not that this is a good solution, but I wonder if using `uninstall --force-remove` would work

**Comment by alexlarsson** [comment]
Add some remote called "gnome-builder-builds" and try again?
These days we refuse to remove remotes that have an app from it installed, so you should not be able to get this again.

**Comment by Alexander-Wilms** [comment]
This can still happen if one removed the remote with `--force`. Adding a fake remote to `/var/lib/flatpak/config` allows removing the installed app.

**Comment by mwleeds** [comment]
I have a WIP branch for this here: https://github.com/mwleeds/flatpak/tree/uninstall-with-missing-remote

But the current issue is that related refs such as locale extensions are not uninstalled when the remote has been deleted (with `--force`). This is because in `flatpak_dir_remove_remote()` we remove all the refs associated with the remote without actually deleting them. So you end up with e.g. `org.kde.okular.Locale` still showing up in `flatpak list -a` but not being uninstalled by `flatpak uninstall org.kde.okular` because `flatpak_dir_find_local_related_for_metadata()` ignores refs that can't be resolved to commits. So it seems we need that function to add refs which are deployed but not resolvable. Though I wonder what other issues could pop up when something is deployed but has had its ref deleted. Maybe `flatpak_dir_remove_remote()` shouldn't do that.

Also still need to write a unit test.
