### ISSUE TITLE
Feature request ... efficient and easy command line installation ...

### ISSUE THREAD

**Issue by aiamuzz** [flatpak/flatpak#2005]
Hi,

I love the way we can now install things from the command line with `flatpak install flathub org.octave.Octave` compared to the earlier downloading of the `.flatpakref` and then running the `flatpak install file.name.flatpakref` command.

I also love that this works ... hitting `tab` to see the package possibilities.

```
flatpak install flathub org.
Display all 318 possibilities? (y or n)

```

the hitting of tab to complete/view the possible packages available for installation is absolutely in line with the linux way of installing packages from the command line, which we all know is very efficient and easy ... and its great flatpak has followed suit ...

... however ...

**its still not efficient and easy for the simple fact, that its hard for anybody to use the tab to complete the package name bcos of the way flatpak package names are constituted by design, which is the reverse domain format of package names ...**

I was hoping if an **alias name** could be used instead of the **reverse.domain.package.name**

**What if the package name `com.visualstudio.code` had an alias `visualstudio`**

its difficult for anybody to remember the former package name given its complexity ... the latter however would be a breeze to install ... and given that you have already implemented the 'tab' package auto complete option, things are all the more easy.

**Eg.:**
Say i would like to install visual studio code ...
`flatpak install flathub visual` (hit 'tab')

and the name would complete to `visualstudio` with the command looking like ...

`flatpak install flathub visualstudio `

and when we hit enter and the alias is configured in such a way that it runs the command `flatpak install flathub com.visualstudio.code` completing the package installation.

**am i making sense ? ... could this be accommodated ?**

**Comment by mwleeds** [comment]
The point of the reverse DNS names is that they're globally unique, so how would you make sure these aliases are globally unique, or even unique for a given repository?

Another way to go about this would be to have flatpak suggest similarly named flatpaks when the one you specify doesn't exist. This idea was proposed [here](https://github.com/flatpak/flatpak/wiki/CLI-experimental-design) and discussed at the Flatpak BoF at GUADEC this year. There seemed to be a bit of resistance to making the CLI user friendly but I think if the patch existed it would be considered.

Anyway, since we already have https://github.com/flatpak/flatpak/issues/1258 which has been around for longer, I'll close this issue in favor of that one.
