### ISSUE TITLE
ubuntu cosmic 18.10 support missing?

### ISSUE THREAD

**Issue by fastrizwaan** [flatpak/flatpak#2075]
apt update

Err:6 http://ppa.launchpad.net/alexlarsson/flatpak/ubuntu cosmic Release       
  404  Not Found [IP: 91.189.95.83 80]

**Comment by ahayzen** [comment]
The PPA will need to be enabled for cosmic. However cosmic already has the latest version of flatpak (1.0.1) and as it has the 1.0.X series, it'll probably be recommended not to use the PPA but the version from the archives.

https://launchpad.net/ubuntu/+source/flatpak/

**Comment by alexlarsson** [comment]
Yeah. I recommend using the cosmic packages for this. When we diverge from 1.0.x (i.e. start unstable development) I might add cosmic to the PPA tho).

**Comment by pizzadude** [comment]
@alexlarsson can you add cosmic to the ppa, pretty please? : )

**Comment by alessanderbotti** [comment]
The current version of `Flatpak` in universe is `1.0.4-1`, while your PPA for Bionic has version `1.0.6-flatpak1~bionic`, and the most recent version is `1.1.0`.

**Comment by iuridiniz** [comment]
Is safe to use packages from bionic on cosmic? (there's no cosmic packages in ppa)

**Comment by jebeld17** [comment]
I'm having the same problem.

**Comment by Eonfge** [comment]
This is not really a technical problem, but a usability problem. With 18.04 LTS, many got on the boat with Ubuntu and Flatpak. Now that 18.10 has come around, their current version of flatpak stops working (mismatch in libraries) and the traditional updater doesn't work because there is no 18.10 package on the PPA. This will hurt less experienced users the most, aggravated because they are also the primary audience of Flatpak.

My proposal would be, to provide an up-to-date Cosmic package on the PPA.

# how to triage
*This will fix your flatpak installation*
- For a graphical experience, Synaptic Package Manager is advised (_sudo apt install synaptic_)
- Remove the PPA from your repository list (Synaptic -> Settings -> Repositories -> Other Software )
- Remove the packages _flatpak_, _libflatpak0_, _gnome-software-plugin-flatpak_
- Reinstall _flatpak_ and _gnome-software-plugin-flatpak_ (If you pay close attention, you can see the version number change)
