### ISSUE TITLE
Add "--filesystem=media" permission

### ISSUE THREAD

**Issue by Erick555** [flatpak/flatpak#2185]
## Description of the problem
Acces to files from removable media such as usb drive, cdrom, sd card, etc. is a common usecase for users. Until every app migrate to portals (and wayland :smile: and rust :grinning:) sometime in upcoming decades the common solution in flathub is to use `--filesystem=host` permission which creates an enormous hole in flatpak sandbox (I don't think users expect that sandboxed app will have access to all their secrets on host system). Currently there are about [hundred apps which do this on flathub ](https://github.com/search?p=10&q=org%3Aflathub+%22filesystem%3Dhost%22&type=Code), among them video players, photo editors, music players, bittorent clients, etc. I think it's safe to assume that most of them do this because of removable media access.

I propose new filesystem permission `--filesystem=media` (or whatever name) to grant access to `/media`, `/run/media` and `/var/run/media` (whichever exist). Those dirs are the place where modern distros mount removable devices these days. It's probable that someone will use `/mnt` or somewhere else for mounting but the common place should fit for 90% usecases thus solve this issue for general public.

[removable-media](https://docs.snapcraft.io/reference/interfaces) already exist as connectable interface in snap and does what I proposed above.

**Comment by alexlarsson** [comment]
Would you expect apps to request access to media, but not the users home-directory? Because, fundamentally, access to $HOME is a very wide hole. You can write whatever to ~/.profile and have it run outside the sandbox. I don't think people realize how easy it is to turn individual permissions into full host access (nor do i expect them too), so rather than trying to create a multitude of permissions that "seem safe" (but are probably not) we should work on making apps actually sandboxed (portals, etc), and just leave the non-sandboxed apps clearly so.

**Comment by Erick555** [comment]
> Would you expect apps to request access to media, but not the users home-directory?

There is `--filesystem=xdg-xxx` for handling `$HOME` access without dotfiles. I know that `--filesystem=home` is still widely (ab)used but it's up to conscience of app maintainers. Something like `--filesystem=nodotfiles` would perhaps help to solve this problem.

> I don't think people realize how easy it is to turn individual permissions into full host access

Yeah, but is giving them full host access from the start the right answer? Mandatory sandbox is one of Flatpak design decisions and concession to tear down that sandbox so easily works against that.

> rather than trying to create a multitude of permissions that "seem safe" (but are probably not) we should work on making apps actually sandboxed (portals, etc), and just leave the non-sandboxed apps clearly so.

Realistically, transition to portals will take a long time. Meanwhile apps remain less sandboxed than they could be with a little effort. Recently Flatpak hit 1.0 but overall app sandboxing looks more like 0.1. Even brand new apps are using `host` permission in flathub, not saying about legacy ones. I don't think this is something Flatpak can ignore and just wait for all developers to fix their apps.

**Comment by matthiasclasen** [comment]
You have a point that we need to start putting pressure on sandboxing in flathub reviews.

**Comment by alexlarsson** [comment]
`--filesystem=nodotfiles` can't really work, because sandbox setup is a static set of bind-mounts that happens on startup. We can't do arbitrary things at a later point. 

To be more exact, we could iterate over $HOME at startup and make covering bind-mounts for any non-dot-files. But any later created dot-file would still be accessible to the app, and there is no way we can forbid the app from creating a new dot-file.

**Comment by alexlarsson** [comment]
I don't think --filesystem=media is entirely unrealistic to add. However, my main concern is that it will not really do what people want it in a lot of cases. I mean, it works for the "plug in usb drive" thing, *only* that case. I can see people using this so they can plug in a usb disk with videos or some other data, but I can also see that usecase not working in many cases because the user has a static mountpoint for the data drive.

I wonder if we could solve this by having some fstab metadata, like the `x-gvfs-show`, `x-gvfs-name=My%20Movies` or `x-systemd.*`. Say x-flatpak=media.

**Comment by TingPing** [comment]
It is just a workaround to the real problem, ability to dynamically add a directory to a sandbox.

**Comment by Marko10-000** [comment]
A question, how does nautilus and dolphin create the list of mounted devices on the left side of the window? My nfs mounts are shown there too. When the list is easy accessible (I'm not talking about all mounts that the command `mount` shows), then customer mounting points aren't any problem.

**Comment by alexlarsson** [comment]
The snap removable media interface https://docs.snapcraft.io/t/the-removable-media-interface/7910 is very simple, and the flatpak version of it is: `--filesystem=/run/media --filesystem=/media`.

**Comment by TingPing** [comment]
@Marko10-000 That probably goes through GVFS.

**Comment by matthiasclasen** [comment]
Sounds like we're not going to do this
