### ISSUE TITLE
No repository packages for Ubuntu 18.10

### ISSUE THREAD

**Issue by Eate** [flatpak/flatpak#2349]
- Ubuntu 18.10 64-bit
- Release 1.0.6 (although this does not matter)

There are no official repository packages for Ubuntu 18.10 "cosmic".
Reproduce by installing Flatpak on Ubuntu 18.10 and updating your repositories by running `sudo apt update`.

Temporary fix: Open a terminal and run `sudo nano /etc/apt/sources.list.d/alexlarsson-ubuntu-flatpak-cosmic.list ` or open it with your text editor of choice. Change `cosmic` on both lines to `bionic`. Save and exit. This will point the repository to the 18.04 bionic packages.

**Comment by ahayzen** [comment]
This was also discussed here https://github.com/flatpak/flatpak/issues/2075

**Comment by galgalesh** [comment]
@alexlarsson Please note that the [official instructions for installing flatpak on Ubuntu](https://flatpak.org/setup/Ubuntu/) point you to the ppa. As a result, the official instructions have been broken for a while on the latest Ubuntu release. Users might interpret this as Flatpak not being a serious and stable project.

**Comment by ahayzen** [comment]
I've been trying to keep the Ubuntu repos up to date with the latest stable releases (i'm currently working on submitting 1.0.6 to bionic and cosmic). The only current advantages the PPA then has over the repos are that it has a newer xdg-desktop-portal and it is built for xenial (16.04). xdg-desktop-portal is currently under security review to go into main for xenial and bionic (and is already in cosmic) and then will hopefully be kept up to date by the desktop/snappy team.

I sort of think we need to consider the purpose of the PPA, as with Ubuntu 18.04 onwards there aren't many advantages. Maybe the PPA could track the unstable releases (eg 1.1.X) and the stable ones could be found in the repos. Maybe we are almost at the point where the install instructions should be recommending to use the version from the archive rather than PPA (for Ubuntu 18.04 onwards), but this is ultimately a decision for Alex.

I'm happy to help out where I can, but I personally think effort is better spent on the ubuntu repos themselves rather than PPAs.

**Comment by galgalesh** [comment]
@ahayzen 

So if I understand you correctly, Flatpak is in the normal Ubuntu repos and is maintained by you? In that case, it might be best to update [the official docs](https://flatpak.org/setup/Ubuntu/) to point to this package instead of the ppa.

**Comment by refi64** [comment]
18.10 has been EOL for quite some time now.
