### ISSUE TITLE
Flatkill.org

### ISSUE THREAD

**Issue by iamantu93** [flatpak/flatpak#2374]
According to flatkill.org
Flatpak is। a security nightmare. It's impossible to package kde apps as flatpak

**Comment by kirbyfan64** [comment]
https://www.reddit.com/r/linux/comments/9n50ba/lets_see_why_flatpak_and_sandboxing_are_awesome/

"According to domain-any-idiot-can-buy.xyz" isn't a very reliable source (I guess to be fair, neither is Reddit).

**Comment by aiamuzz** [comment]
I am no techie to understand the nuts and bolts of security and vulnerability ... but i would much rather see videos posted on flatkill.org demonstrating the attacks on the system gained through flatpak apps ... its only fair to provide proof rather than speak in hypothetical terms and in tech-speak ... that way at least the person(flatkill.org or @iamantu93 ) warning against the vulnerability will build credibility ... if they provide proofs on video ... until then its just he said she said !!!

I would prefer the team didn't close this thread ... let it lay open ... if the guy from flatkill.org or @iamantu93  can post proofs ... let them do it ...

**Comment by matthiasclasen** [comment]
Sorry, but no

**Comment by rokejulianlockhart** [comment]
@iamantu93, http://flatkill.org never purports that packaging such software is impossible. It merely evaluates the current state of packaged software, and is correct that KDE's on its kdeapps repository are indeed not yet ready to be provided to end-users.

However, note that the kdeapps repository is for unevaluated (versions of) software, and consequently does not demonstrate accurately the current state of packaged stable KDE software (although this isn't *significantly* superior).
