### ISSUE TITLE
flatpak-spawn fails in valid directories

### ISSUE THREAD

**Issue by TingPing** [flatpak/flatpak#2418]
## Flatpak version

1.0.6

## Description of the problem

Even though the sandbox will have access to a directory it can fail to execute sometimes.

## Steps to reproduce

```sh
flatpak run --command=sh org.foo.Bar
flatpak-spawn ls /var/data # The new sandbox totally has this directory
...
cd /var/data
flatpak-spawn ls /var/data
Failed to call flatpak portal: GDBus.Error:org.freedesktop.DBus.Error.Failed: Failed to start command: Failed to change to directory “/var/data” (No such file or directory)
```

**Comment by matthiasclasen** [comment]
any chance to get debug spew from the session helper when this happens ? that might be helpful

**Comment by matthiasclasen** [comment]
Could not reproduce this here

**Comment by matthiasclasen** [comment]
curious that the same happens with /var/data and /var/config, but not /var/cache or /var/tmp. How are these different ?

**Comment by matthiasclasen** [comment]
Turns out the issue here is rather simple. flatpak-spawn passes the its cwd as cwd arguemtn into the Spawn call, and the flatpak portal mistakenly uses that cwd argument as cwd when calling g_spawn_async to launch flatpak. This does not work since the cwd that flatpak-spawn sees is inside the sandbox, and flatpak is launched outside, where /var/data does not exist.

**Comment by matthiasclasen** [comment]
I think the cleanest way to fix this might be to add a --cwd option to flatpak run. The alternative is to 
always use --command=sh and then pass "cd $cwd; $argv"
