### ISSUE TITLE
Why is --die-with-parent needed ?

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/flatpak#2516]
In my testing, Using Ctrl-C to kill the flatpak run process in the terminal takes the entire sandbox with it. What am I missing?

**Comment by alexlarsson** [comment]
That happens because ctrl-c in the terminal kills the entire foreground group. This doesn't happen if the parent (typically flatpak-builder) dies from some other reason (e.g. sigkill). Also, it doesn't happen if the app creates its own process group.

Basically, we saw leftover processes from flatpak-builder when the parent build exited in the gnome flatpak buildsystem, so we added this so we can ensure that a force-exited flatpak-builder completely goes away.
