### ISSUE TITLE
Can't use flatpak-system-helper on non-systemd

### ISSUE THREAD

**Issue by Cogitri** [flatpak/flatpak#2645]
## Linux distribution and version
Void Linux

## Flatpak version

1.2.0

## Description of the problem

It seems like since 1.2.0 Flatpak searches for `flatpak-system-helper.service` to activate the system-helper, which doesn't work on distros which don't use systemd

## Steps to reproduce

Install flatpak >=1.2.0 on a non systemd distro and try to install something without specifying `--user` and without sudo (or friends), E.g.:

```
flatpak install --from https://gitlab.gnome.org/GNOME/gnome-apps-nightly/raw/master/gnome-builder.flatpakref
```

This outputs the following: 
```
The application org.gnome.Builder depends on runtimes from:
  https://sdk.gnome.org/nightly/repo/
Configure this as new remote 'gnome-nightly' [Y/n]: Y
error: Unit flatpak-system-helper.service not found.
```

**Comment by smcv** [comment]
Flatpak communicates with the system helper via D-Bus: it's normal D-Bus activation with no explicit systemd dependency.

The D-Bus service file `org.freedesktop.Flatpak.SystemHelper.service` configures a matching `SystemdService`, but that should only get used when dbus-daemon was run with the `--systemd-activation` option, which should only be done by systemd.

Is Void Linux a distro that optionally/conditionally boots using systemd (like Debian and Gentoo), or does it never use systemd (like Devuan and Slackware)?

Does Void Linux run `dbus-daemon --system` with the `--systemd-activation` option? If it is not using systemd to boot, then it should not do that. In Debian, the `dbus.service` systemd unit runs `dbus-daemon --system --systemd-activation`, but the LSB init script used when booting with sysvinit runs `dbus-daemon --system --fork`, so we do the right thing in both cases.

**Comment by smcv** [comment]
```
error: Unit flatpak-system-helper.service not found.
```

That [looks like a message from systemd](https://codesearch.debian.net/search?q=Unit+%25s+not+found%5C.), which is surprising if Void Linux doesn't use systemd...

Does Void Linux have some sort of emulation or shim that pretends to be systemd, like the systemd-shim package that was historically available in Debian?

Flatpak's only explicit D-Bus interaction with systemd is to call `StartTransientUnit()` on the `systemd --user` instance to put each sandboxed app in a scope (cgroup), but that's optional functionality - if it fails, most likely because you aren't using systemd, then Flatpak just ignores the error.

Please try running Flatpak with `flatpak --verbose` to see more debug information.

**Comment by Cogitri** [comment]
> Is Void Linux a distro that optionally/conditionally boots using systemd (like Debian and Gentoo), or does it never use systemd (like Devuan and Slackware)?

Ah, sorry, I didn't know that flatpak/dbus detected that during runtime. I tested this on a Void system, which unofficially has systemd installed, so this is a non problem sorry!

**Comment by smcv** [comment]
> I tested this on a Void system, which unofficially has systemd installed

OK, so the problem is likely to be: official Void packages don't install systemd service files for packages like Flatpak, even if they do install D-Bus service files that reference those systemd service files.

I would recommend choosing a distribution that supports your preferred init system, or choosing an init system that is supported by your preferred distribution, depending which one is more important to you. The purpose of a distribution is to provide an integrated system that is configured to work well together; rearchitecting arbitrary parts of a distribution is unlikely to end well, unless you do the transition completely (for instance modifying and rebuilding packages like Flatpak to include the systemd service files).
