### ISSUE TITLE
Should Flatpak always mount a tmpfs on extension directories?

### ISSUE THREAD

**Issue by kirbyfan64** [flatpak/flatpak#2675]
## Linux distribution and version

Fedora Silverblue 29.

## Flatpak version

1.2.0 and master.

## Description of the problem

For all subdirectory extensions, Flatpak [mounts a tmpfs on the parent directory](https://github.com/flatpak/flatpak/blob/1.2.0/common/flatpak-utils.c#L4257). Why does this always occur? In my case, there's a proprietary applicatioon that *only* supports a few set directories for extensions, and one of them already has some other directories inside. By mounting a tmpfs, the entire directory is now empty fromt eh other folders inside.

**Comment by smcv** [comment]
> Why does this always occur?

The parent directory (in your case part of the app on `/app`, or it could be part of a runtime on `/usr`) is mounted read-only. Flatpak needs to make the extension directory read/write, so that it can create the subdirectories for individual extensions; otherwise it would not be able to add the extensions. It mounts a tmpfs because that gives it a new read/write directory.

If Flatpak mounted the app or runtime read/write instead of adding a tmpfs, then creating the subdirectories for the extensions would permanently modify the original app or runtime. Flatpak apps and runtimes are content-addressed OSTree trees (their commit IDs are a hash of their content, a bit like git), and unlike git, OSTree does not ignore empty directories (because they can be functionally significant); so Flatpak would eventually detect the change as corruption.

**Comment by alexlarsson** [comment]
Yeah, technically this is required.

**Comment by kirbyfan64** [comment]
Out of curiosity, could it mount the tmpfs on an overlayfs, or would that be too much?
