### ISSUE TITLE
Use a system call whitelist

### ISSUE THREAD

**Issue by DemiMarie** [flatpak/flatpak#2684]
We should use a system call whitelist, rather than a blacklist.  The default whitelist used by Docker would be a good choice.

Most of the syscalls we don’t block (but Docker does) are not major weaknesses, since they are already denied to unprivileged users.

**Comment by matthiasclasen** [comment]
Why should we ?

**Comment by DemiMarie** [comment]
Security.  New system calls should not be allowed without consideration.

For example, Flatpak currently allows all ioctls.  Virtually all ioctls should not be available to sandboxed apps, and there are so many that a blacklist is not feasible.

**Comment by clopez** [comment]
This is the doc about docker syscall blacklist: https://docs.docker.com/engine/security/seccomp/

**Comment by alexlarsson** [comment]
It is not realistic to have a whitelist and run abitrary desktop application code and expect it to work. For instance, you would have to list every ioctl that every OpenGL driver in the world uses, and even then you would break when a new version introduces a new one, or there is a new gpu driver.

Docker has a much easier time because it typically just runs some network facing daemon, and additionally it expects sysadmin-level work to disable or modify the permissions of individual containers when needed, we can't require that.

**Comment by clopez** [comment]
> It is not realistic to have a whitelist and run abitrary desktop application code and expect it to work.

Note that docker doesn't have a whitelist but a blacklist.
And I don't think its unrealistic to expect a desktop application to work with a blacklist.
