### ISSUE TITLE
Accessing Host Trusted Certificates

### ISSUE THREAD

**Issue by LorbusChris** [flatpak/flatpak#2721]
## Linux distribution and version
Fedora Silverblue 29
## Flatpak version
v1.2.3
## Description of the problem
Flatpaks apps do not pick up PEM certificates placed in `/etc/pki/ca-trust/source/anchors/` on the host.
## Steps to reproduce
- Place custom trusted cert in `/etc/pki/ca-trust/source/anchors/`
- Install Riot.im or Firefox Nightly flatpak
- In Riot.im: Try to log in to a Matrix server that uses that cert -> not possible
- In Firefox Nightly: Navigate to an URL that uses that cert -> 'Warning: Potential Security Risk Ahead' page is shown

**Comment by LorbusChris** [comment]
Confirmed not to work on Fedora 29 standard as well.

**Comment by TingPing** [comment]
Riot probably uses OpenSSL which doesn't respect PKI anyway AFIAK.

**Comment by LorbusChris** [comment]
Right, that could be, as I only reproduced it with Riot this time. Firefox Nightlies aren't up to date at the moment, so I didn't test that.

Any idea how this could be made compatible with OpenSSL?

**Comment by TingPing** [comment]
Hmm, it looks like Fedora builds openssl with `--openssldir=/etc/pki/tls` while freedesktop-sdk has the default `/etc/ssl`. So that is probably relevant.

**Comment by matthiasclasen** [comment]
@amigadave is this something you could look into for our fedora flatpak builds ?

**Comment by mcatanzaro** [comment]
I think Firefox should be fixed nowadays, since https://gitlab.com/freedesktop-sdk/freedesktop-sdk/commit/a11bd7c94e163b34e4ac209361c47f914997932f, which is in 18.08. Can you confirm?

Then Riot.im is an Electron app, right? So you would need to add p11-kit support to Chromium (CrNet) if you expect it to be able to access host certificates. I don't think it uses OpenSSL.

Accessing host certificates requires use of the p11-kit server running on the host OS, so if your TLS library doesn't support using p11-kit as its trust store, this is simply not expected to work. So you should report a bug to Chrome (good luck with that) for Riot.im, not here.

It's true that OpenSSL is not expected to work either, though I think neither of your example apps use OpenSSL. Eventually, OpenSSL will be improved to support p11-kit. Once that happens, we will need to change freedesktop-sdk to build OpenSSL with p11-kit configured as its default trust, like we already do for GnuTLS. freedesktop-sdk also has NSS patched to use p11-kit, like Fedora does, so NSS should work too. (I think OpenSSL is the last remaining significant holdout that doesn't support using p11-kit as its trust store; eventually it will get fixed.)

So, expected to work:

 * Anything using GnuTLS, including anything that uses GLib sockets
 * Anything using NSS
 * freedesktop-sdk only: libcurl (configured to use GnuTLS), and anything using libcurl

Not expected to work and not our problem:

 * Chrome/Electron stuff
 * Anything using OpenSSL
 * Fedora runtime only: libcurl (configured to use OpenSSL), and anything using libcurl

**Comment by mcatanzaro** [comment]
> * Chrome/Electron stuff

Note: this will be using CrNet, and beneath that, BoringSSL, bundled in the Chromium source code under third_party/.

**Comment by mcatanzaro** [comment]
OK one last tip. If you want a workaround, then instead of Riot.im you can use Revolt, which just uses WebKitGTK instead of Electron. That means you get GLib sockets -> glib-networking -> GnuTLS -> p11-kit which should have access to the host certificates.

**Comment by AdrianVovk** [comment]
There seem to be mechanisms to generate CA bundles for openssl & java & everything else in p11-kit: `trust extract --format=openssl-bundle --filter=ca-anchors --overwrite /tmp/openssl-bundle.pem`

As a distributor, the fd.o sdk can override /usr/libexec/p11-kit/trust-extact-compat, and then just run `trust extract-compat`. p11-kit runs this automatically whenever `trust anchor` is run, but I'm not sure how it handles the daemon/client relationship used by Flatpak.

**Comment by mcatanzaro** [comment]
Not sure I understand. How could that help?

**Comment by AdrianVovk** [comment]
@mcatanzaro All the SDKs have to do is run `trust extract [...]` at some point and then OpenSSL will use the system's CA certs, right? Or am I missing something

**Comment by mcatanzaro** [comment]
Yes, that would work, but it would conflict with the certificates provided by the runtime itself. The runtime would have to stop shipping its own certificates. I'm not sure whether that would be desirable or not. There would be... implications. :)

Proper fix is to finish and land https://github.com/openssl/openssl/pull/8200.

**Comment by AdrianVovk** [comment]
@mcatanzaro That's fair

**Comment by dustymabe** [comment]
I think I hit this today. Trying to use firefox in a flatpak on f31 silverblue and I have system wide certs added to my host (to access websites hosted by my employer). These certs don't make it into the flatpak AFAICT.

**Comment by mcatanzaro** [comment]
No, as stated above, Firefox uses NSS which uses p11-kit for the trust store therefore should work fine. After making sure you have p11-kit-server running on your host, file a new bug against the Firefox flatpak packaging if it is no longer working.

**Comment by mcatanzaro** [comment]
BTW this bug should be closed since there is nothing to be changed in flatpak here. Everything should be using host certificates nowadays except (a) Chrome/BoringSSL ecosystem, which requires a Chrome bug report, (b) stuff using OpenSSL, https://github.com/openssl/openssl/pull/8200, and (c) minor/unconventional TLS libraries we shouldn't worry about.

**Comment by dustymabe** [comment]
> After making sure you have p11-kit-server running on your host, file a new bug against the Firefox flatpak packaging if it is no longer working.

https://bugzilla.redhat.com/show_bug.cgi?id=1766340

**Comment by TingPing** [comment]
@mcatanzaro I don't think flatpak does anything to expose any of this actually.

**Comment by mcatanzaro** [comment]
> I don't think flatpak does anything to expose any of this actually.

But p11-kit does, in the flatpak container it connects to p11-kit-server on the host. You should be the expert on this by now, not me. :)

**Comment by aviwad** [comment]
Problem remains in Fedora silverblue 31

**Comment by dustymabe** [comment]
I still have to follow the directions in https://bugzilla.redhat.com/show_bug.cgi?id=1766340#c3 every time I re-setup my system. Not sure what needs to be done to fix this, but it would be nice.

**Comment by mcatanzaro** [comment]
This bug really needs to be closed.

> BTW this bug should be closed since there is nothing to be changed in flatpak here.

Please report bugs to the affected applications that don't use p11-kit. Don't comment here. Nothing is wrong with flatpak.

The issue with Fedora's Firefox build is reported against Fedora because it is a bug in Fedora's Firefox flatpak packaging. If you have the same issue with Flathub's Firefox, please report it to Flathub. Don't comment here. Flatpak is setting everything up properly, but it can't *force* applications to use the host certificates and it's not flatpak's fault if they don't.

**Comment by Erick555** [comment]
> If you have the same issue with Flathub's Firefox, please report it to Flathub

No such thing yet 😄

**Comment by mcatanzaro** [comment]
So everybody's just using Fedora's build? We already know that's a Fedora bug. (Well, ideally it would be fixed *upstream* instead of requiring every distro to patch Firefox to use p11-kit, but in practice this is how all distros package Firefox and only Fedora's flatpak build gets it wrong.)

**Comment by TingPing** [comment]
I don't believe this bug should be closed. Even if p11-kit works many applications do not use p11-kit for certificates and it is entirely possible for Flatpak to expose host certificates. Maybe we don't want to do that but it hasn't really been explored here.

**Comment by dyskette** [comment]
Is this the issue I hit?

I'm using Steam Flatpak on Fedora 32 and trying to play Dirt Rally 2 game, however it needs a certificate from codemasters (a .pem file). I added it using the [fedora documentation](https://docs.fedoraproject.org/en-US/quick-docs/using-shared-system-certificates/), but it doesn't seem to have any effect within the game, as it still doesn't let me play online.

Certificate: https://www.upload.ee/files/9626680/codemasters.pem.html

**Comment by mcatanzaro** [comment]
Dirt Rally 2 is probably not using p11-kit, so I would not expect it to be able to access host certificates.

**Comment by jokeyrhyme** [comment]
Howdie,

I'm encountering this issue again (both Discord and Steam flathub flatpaks are having TLS/connectivity issues), and I'm not 100% sure how to deal with this myself, and I apologise if this isn't the best place to report this (please let me know, if so)

```
$ flatpak list --user
Steam                          com.valvesoftware.Steam                     1.0.0.62  stable flathub
Freedesktop Platform           org.freedesktop.Platform                    19.08.10  19.08  flathub
i386                           org.freedesktop.Platform.Compat.i386                  19.08  flathub
default                        org.freedesktop.Platform.GL.default                   19.08  flathub
default                        org.freedesktop.Platform.GL32.default                 19.08  flathub
openh264                       org.freedesktop.Platform.openh264                     2.0    flathub
```

```
$ pacman -Ss p11-kit
core/libp11-kit 0.23.20-5 [installed]
    Loads and enumerates PKCS#11 modules (library)
core/p11-kit 0.23.20-5 [installed]
    Loads and enumerates PKCS#11 modules
multilib/lib32-p11-kit 0.23.20-4 [installed]
    Loads and enumerates PKCS#11 modules (32-bit library)
```

```
$ pacman -Ss gnutls
core/gnutls 3.6.13-2 [installed]
    A library which provides a secure layer over a reliable transport layer
multilib/lib32-gnutls 3.6.13-2 [installed]
    A library which provides a secure layer over a reliable transport layer (32-bit)
...
```

Weirdly enough, the Firefox flatpak is working perfectly now, but virtually everything else I've installed is having connectivity issues

Seems like this comes up every couple of months (I assume when all the copies of p11-kit happen to line up properly), then goes away again (when a runtime is distribution is updated out of lock-step with the rest)

**Comment by damianatorrpm** [comment]
+1 for finding a solution for non-conform applications like Dirt Rally

**Comment by jokeyrhyme** [comment]
I've reported this to the Freedesktop Platform runtime folks here: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1050

**Comment by zicklag** [comment]
I'm having the same issue in #3746 but with the `flatpak-builder` flatpak because `curl` won't use `pk11-kit`, it looks instead at `/etc/ssl/certs/ca-certificates.crt` for its certificate, but there isn't any way for me to share that file with the flatpak because `/etc` is blacklisted for the `--filesystem` options.

It seems like a way to somehow mount that file into the flatpak, is required, but the path on the host and the path in the container might be different per app and application unfortunately. 😕

**Comment by mcatanzaro** [comment]
What's required is fixing Debian to build its SSL libraries to use the p11-kit trust store by default. Your problem is specific to legacy distros that have their own hand-rolled ca-certificate infrastructure and have not switched to p11-kit. I've no doubt that many other functions are broken without p11-kit (e.g. the `trust` command cannot work). This is just a symptom of a much larger problem.

Anyway, /etc/ssl/certs/ca-certificates.crt is a nonstandard Debian-specific location. See https://www.happyassassin.net/posts/2015/01/12/a-note-about-ssltls-trusted-certificate-stores-and-platforms/

**Comment by zicklag** [comment]
So then that would not be *my* problem, though, that would be a problem with the base runtime used by the `flatpak-builder` Flatpak, because that is where `curl` is incorrectly configured.

**Comment by zicklag** [comment]
> Well if you want the host trust store to really work correctly, then it's certainly a host problem too. But yes, for simple functionality, then as long as p11-kit-server is running on the host, that should suffice as long as libcurl in the runtime actually uses it.

Yes. In my case I'm pretty sure that my host *is* correctly configured as I can see my custom certificate when I rust `trust list`. Is than an effective way to check whether that is working?

---

> That causes me to worry that libcurl is not designed to do the right thing. I don't plan to investigate further, but ideally libcurl would just use GnuTLS's default trust store instead of a legacy path that's passed at configure time.

That's a good find. It looks like my next step is to look into building the freedesktop SDK myself and see if I can get CURL to use p11-kit.

**Comment by mcatanzaro** [comment]
> Yes. In my case I'm pretty sure that my host is correctly configured as I can see my custom certificate when I rust trust list. Is than an effective way to check whether that is working?

*Sort of.* Thing is, if GnuTLS or OpenSSL doesn't default to the p11-kit store (which is still the case in Debian), your "trusted" certificate is not really going to be trusted. But it should *definitely* be enough to expose the certificate to flatpak applications. I think you are correct to guess that libcurl in the runtime is the problem.

**Comment by nanonyme** [comment]
How this is supposed to work is flatpak drops a configuration fragment under /etc which makes p11kit under flatpak use host trust store. curl is already linked against p11kit. Looks like the chain is libcurl->nss->p11kit.

**Comment by nanonyme** [comment]
Iirc GnuTLS has supported certs from host through p11kit from like 1.6 (not taking bugs into account). nss grew support in 19.08 by @valentindavid . I don't know which curl uses here.

**Comment by nanonyme** [comment]
Unsure if OpenSSL route support p11kit, probably not.

**Comment by mcatanzaro** [comment]
> Iirc GnuTLS has supported certs from host through p11kit from like 1.6 (not taking bugs into account). nss grew support in 19.08 by @valentindavid . I don't know which curl uses here.

curl uses GnuTLS and GnuTLS uses p11-kit, certainly, but my concern is that curl is compiled with --with-ca-bundle= which tells libcurl to use a certificate bundle on disk rather than GnuTLS's default trust store (the p11-kit trust). I'm not sure if libcurl can be told to do the right thing; I haven't investigated. There _should_ be some option to use the default trust store rather than a certificate bundle. I would expect it to be the default behavior, but the warning comment in the bst element indicates otherwise. Moreover, I see curl in Fedora is compiled to use the certificate bundle, so that causes me to suspect it's not going to work.

It's possible for curl to use p11-kit for PKCS#11 without using it for its trust store.

> Unsure if OpenSSL route support p11kit, probably not.

It *ought* to work... the history here is that OpenSSL upstream refused to play ball, so p11-kit developed an OpenSSL engine.

**Comment by nanonyme** [comment]
Right, we don't have libp11 in the runtime though.

**Comment by nanonyme** [comment]
@valentindavid said there may be legal implications to TLS backend so we probably need to keep the OpenSSL one as well.

**Comment by Yuri6037** [comment]
I've hit this as well: I require features that do not exist in p11-kit so I have to rely on loading the bundle. However the bundle is incorrect in the flatpak container as I can see many more CA certificates on my host Ubuntu system than in the flatpak container.

This really needs to be fixed. Also not even considering .NET Core apps, Java apps and possibly many other frameworks...

The flatpak container should just use the certificate bundle from the host system so that all applications are consistent on a given system...

**Comment by nanonyme** [comment]
It's not really as simple as "just using certificate bundle". Certificate ecosystem has been a true mess for a long time and without glue like p11-kit bringing things together it's not really possible to have something that works same way in all distros.

**Comment by zicklag** [comment]
Yeah, it is a surprisingly difficult problem because tons programs have been using their own way of getting the certificate bundle since forever. Python programs get it from a `certify` python package, some C programs like `curl` on different distros might be compiled to literally look in a specific directory. Everything has its own idea of where to get the certs and p11-kit is one of the few developing standards to start pushing everybody to use a standardized way of getting the cert, if I understand correctly.

**Comment by nanonyme** [comment]
I was trying to get https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/3798 done which might help some (probably not really backportable material since it's quite invasive) but it hit some static analysis tools with the project and I ran out of time figuring out how to fix them.

**Comment by thegarlynch** [comment]
/usr/local/share/ca_certificates is ignored though, even though /etc/ssl/certs is trusted

**Comment by nanonyme** [comment]
FWIW freedesktop-sdk 21.08 is going to carry libp11 to make OpenSSL hopefully play ball with p11kit. First beta is going to be done real soon.

**Comment by j1mc** [comment]
It looks like the freedesktop-sdk 21.08 and 21.08.1 were tagged [within the last week](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/tags).

Can anyone verify if the issue is resolved or if it still persists?

**Comment by nanonyme** [comment]
Okay, so the thing is, OpenSSL clearly can access host certs as can GnuTLS. But curl appears to use both in a way that results in embedded CA certs being used. I don't understand why.

**Comment by nanonyme** [comment]
You can observe this by that

`curl -L https://mesa.freedesktop.org/archive/glu/glu-9.0.2.tar.xz` fails

`CURL_SSL_BACKEND=gnutls curl -L https://mesa.freedesktop.org/archive/glu/glu-9.0.2.tar.xz` fails


`gnutls-cli --ca-verification mesa.freedesktop.org` succeeds

`openssl s_client -connect mesa.freedesktop.org:443` succeeds

So remaining problem is clearly making curl not do something stupid. Crypto libraries work fine, curl does not.

**Comment by nanonyme** [comment]
@mcatanzaro looks like "causes me to worry that libcurl is not designed to do the right thing" was entirely correct.

**Comment by mcatanzaro** [comment]
> looks like "causes me to worry that libcurl is not designed to do the right thing" was entirely correct.

To be clear: we **must** get rid of `--with-ca-bundle` from curl.bst if we want curl to have any chance at using host certificates (and we almost surely do want that). That does exactly what it says: it forces curl to use certs from the bundle installed in the runtime, rather than the host.

That said, I see [this warning](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/commit/a33b3be76d29e1215dfb657b33770df90af1682f) in the buildstream element:

```
# Curl must be configured --with-ca-bundle in order to find the
# correct certificate bundle at runtime, which is later generated
# by update-ca-certificates. Other applications such as git, rely
# on curl knowing the default location of the certs.
```

which indicates that libcurl defaults to using no certs at all? That doesn't sound right. If that's still true, it would be a curl bug IMO: it should default to using the system trust, not no trust at all.

> How this is supposed to work is flatpak drops a configuration fragment under /etc which makes p11kit under flatpak use host trust store. curl is already linked against p11kit. Curl is a bit weird since it builds against both nss and GnuTLS and builds a dependency on p11kit on both directions.
> Looks like for possibly historic reasons curl also links against OpenSSL and has OpenSSL backend which will not result in a working p11kit host cert usage if that ends up being used.

For avoidance of doubt: curl lets you choose the TLS backend at build time. Normally you would pick just one.  Don't expect any consistency between distros here. Fedora used to use NSS (I think) but nowadays uses OpenSSL. I see freedesktop-sdk uses both NSS and GnuTLS, and I'm not sure why. My suggestion would be to drop the NSS support and see if anything breaks: my guess is probably not. Debian builds all three and lets applications pick which one they want; only one of them gets used by default, but I don't remember which.

> FWIW freedesktop-sdk 21.08 is going to carry libp11 to make OpenSSL hopefully play ball with p11kit. First beta is going to be done real soon.

If you've got OpenSSL hooked up to p11-kit, then that's cool. p11-kit is the primary reason to prefer GnuTLS vs. OpenSSL.

P.S. It seems I've requested this bug be closed multiple times in prior comments, since its scope is too broad and it's obviously not a flatpak issue. The flatpak issue tracker would be more useful if misplaced issues were closed more aggressively.

**Comment by nanonyme** [comment]
Well, it defaults to trying to figure out where platform-specific CA bundle is. I'm currently trying to build curl with `--without-ca-bundle` to disable its bundle logic completely. Note that currently OpenSSL, GnuTLS and NSS should be using p11kit correctly. So backend shouldn't matter as long as curl doesn't try to tell crypto library to use the runtime CA bundle.

**Comment by nanonyme** [comment]
I would also note that currently curl does *the wrong thing* even with GnuTLS backend.

**Comment by mcatanzaro** [comment]
> So backend shouldn't matter as long as curl doesn't try to tell crypto library to use the runtime CA bundle.

I believe so, yes. Certainly that is correct for GnuTLS.

**Comment by shmu26** [comment]
Just wanted to mention that I am having this certificate issue with the Zoom flatpak app. 
It is not honoring the certificate store of my system.
Ubuntu 22.04.

**Comment by nanonyme** [comment]
For the record, --with-ca-fallback in combination with -without-ca-bundle was the right solution. Not all apps will ever work correctly if they have eg bundled curl.

**Comment by shmu26** [comment]
> For the record, --with-ca-fallback in combination with -without-ca-bundle was the right solution. Not all apps will ever work correctly if they have eg bundled curl.

As a home user without a technical background, is there anything I can do about this, on my side? I don't understand the terms you mentioned.

**Comment by nanonyme** [comment]
I mean, fix has been done. Runtime and flatpak work correctly. Remaining bugs are on app sid.

**Comment by smcv** [comment]
> As a home user without a technical background, is there anything I can do about this, on my side?

Not really, other than reporting it as a bug to the apps that are affected if nobody else has already done so.

(The maintainers of the Flathub package for Zoom probably cannot fix it, because Zoom is proprietary software, but at least having a bug report would record that limitation.)

> It seems I've requested this bug be closed multiple times in prior comments, since its scope is too broad and it's obviously not a flatpak issue

Closing this as not Flatpak's bug.

What is now meant to happen is that apps (or the SSL/TLS libraries used by apps) should use p11-kit as their trust store. If they do that, then they will automatically pick up a socket forwarded by Flatpak from the host system, and trust whatever certificates the host trusts. If they do not do that, then that's a bug (or at least a limitation) in that app or the SSL/TLS library that it uses, and not a bug in Flatpak itself.

**Comment by merlinz01** [comment]
For folks landing here trying to figure out how to get a Go or NodeJS program inside Flatpak to trust a custom root certificate, try this workaround:

- Place the certificate file somewhere under your home folder, e.g. `/home/yourusername/.local/share/root-ca.pem`.
- Run `flatpak override --user --env=SSL_CERT_FILE=/home/yourusername/.local/share/root-ca.pem <flatpak-app-id>`.
- Run `flatpak override --user --env=NODE_EXTRA_CA_CERTS=/home/yourusername/.local/share/root-ca.pem <flatpak-app-id>`.
