### ISSUE TITLE
No decent way for flatpaked IDE's to acess compilers and runtimes stored on /usr/bin (and elsewhere on root)

### ISSUE THREAD

**Issue by retiform** [flatpak/flatpak#2742]
## Description of the problem
If one installs a text editor/IDE like VSCode, one might wish to be able to run language compilers or runtimes from within the application. If these languages and runtimes are installed to root, like most package managers will do, then one can not access them. The obvious workaround is to install langs to 
/home/username but that has the following downsides:
* You generally can not easily install binaries to a /home/ directory from a pacakge manager

* If you have already installed the language, you will probably want to overwrite the $languagename.home variable for convenience (with the /home installition's path), meaning other programs will now default to the home based installation of the language, not the one installed by the package manager

* Pretty much all of this is done manually, wasting time.

## Steps to reproduce
Install VS Code. Try to use a language not bundled in flatpak, but installed via pacakge manager.

This is a known issue, but there appears to be no issue on github, so I decided to create one.

See other complaints about this: 

https://discussion.fedoraproject.org/t/developing-applications-using-flatpak-packaged-editors-ides/269

https://dev.to/satimewallin/go--mess-with-flatpakvscode-ja6

## A bunch of questions/issues raised on the mailing list about this (mostly unresolved):

https://lists.freedesktop.org/archives/flatpak/2018-June/001128.html

https://lists.freedesktop.org/archives/flatpak/2018-March/000972.html

https://lists.freedesktop.org/archives/flatpak/2018-July/001159.html

https://lists.freedesktop.org/archives/flatpak/2017-March/000635.html

## Current resolutions that seem to somewhat exist:

* Just install stuff to home

* have a really well integrated IDE with flatpak (like GNOME studio)

* build your own flatpak dev enviroment like piviti did https://developer.pitivi.org/HACKING.html

* have flathub or others distribute an extension for the language you need (GCC, OpenJDK, fortran, Rust, Mono, and .NET core work for this). However, it should be noted these are not listed under flathub's search function or in KDE's Discover (I did not test GNOME Software), so it is likely most users are unaware of when their language is supported.

**Comment by kirbyfan64** [comment]
Add the permission `--talk-name=org.freedesktop.Flatpak` and run `flatpak-spawn --host some-host-command`. 

Similar bugs have been filed many times for this, the general consensus is that it's just a side effect of Flatpak using a custom rootfs and can't be easily worked around.

**Comment by DNSCrypt-Lists** [comment]
> Add the permission `--talk-name=org.freedesktop.Flatpak` and run `flatpak-spawn --host some-host-command`.
> 
> Similar bugs have been filed many times for this, the general consensus is that it's just a side effect of Flatpak using a custom rootfs and can't be easily worked around.

Or, @retiform, use a partitioning scheme that separates usr directories from root, not merely separating your home partition from root.

- [x] Something like this, though depending on what distro you use they may have to be given space to grow a bit more as you use your system:
`/dev/sda`, depending on the space involved in your setup, use a full 100 GiB for root (I've mine located @ /dev/sda3, and if need be, a 1 GiB fat32 partition for esp boot on `/dev/sda1`. That's my setup on sda minus a bios_grub @ `/dev/sda2` created just in case it's ever needed.
- - `/dev/sdb`  holds my usr, home, var, tmp, var/logs, etc... all in oversized partitions (except my logs; when I've time I'll unmount sdb and grow that particular partition). usr/bin can be housed in it's own partition as well, as you wish to do. If you have a 2nd platter, that can be turned into essentially anything you want. WebDAV, a local DNSCrypt server, or even a directory for a low-privileged generic user account for you to perform operations, store sensitive data, run a git server, or open up the DNSCrypt server to the outside world using, e.g., @OpenNic's decentralized infrastructure that ICANN has no control over.
While I realize using the aforementioned partitioning scheme would require you to do a bit of work in ordr not to lose your current installation, it will make future problems easier to fix.
- - Peace

**Comment by AdrianVovk** [comment]
Uhh what @DNSCrypt-Lists? What does *any* of this have to do with Flatpak?

**Comment by TingPing** [comment]
Duplicate of #2732

See https://github.com/flatpak/flatpak/issues/2732#issuecomment-468748747

**Comment by DNSCrypt-Lists** [comment]
@AdrianVovk It’s a temporary fix for @retiform ‘s issue. By removing his /usr/bin/ directory from his root, he can use Flatpak as usual until Flatpak commits a fix. @TingPing I was not off topic, I was offering a user of your product a workaround he may wish to implement until a fix is offered. Now, @AdrianVovk was indeed off topic and moreover quite rude and dismissive just to be rude and dismissive. I understand Flatpak is a young entity in the Linux ecosphere, though that in no May excuses the horrid experience I’ve had here in under 24 hours. Organizations like Debian and RedHat have existed literally since many within your organization had yet been born for two main reasons: being open to a worldwide community while still maintaining a professional attitude toward said community, and the products they create, maintain, distribute, etc., are solid and have been since their beginnings. I do wish you well, but while I found Flatpak convenient and novel, it’s not a new idea nor is it a necessity in any way for, at least, my use. It’s just as simple to install the actual software and run what one chooses to in sandboxes. And not one response to the post from a Debian contributor advising you of the security advisory allowing exploits of Flatpaks - it affects a not just Debian & it’s derivatives but also Red Hat Enterprise Linux, whose codebase comes from Fedora. That’s a huge population of Linux users. She was kind enough to notify you, yet it’s nearly a month now and no one in your organization will even acknowledge her post. Your product won’t last unless your team changes its attitude toward its user base and slows down Flatpak’s market growth because of the negative impact it’s had on Flatpak.

**Comment by AdrianVovk** [comment]
@ghost I don't think you understand how flatpak works. Or filesystems for that matter. 

So what you are trying to say is that by repartitioning (aka literally wiping everything unless you are a demigod who can perform this kind of surgery on a running system) is a way to fix a problem that exists within the flatpak runtime environment, which is **completely** independent of the host. And WebDAV is involved somehow in this? What does that have to do with Flatpak? 

I get that you're trying to help, but don't give people solutions that'll destroy their systems when the actual solution is a one-line change in their manifest.

> And not one response to the post from a Debian contributor advising you of the security advisory allowing exploits of Flatpaks

Reread the issue, please. This is not a security issue. This is a question that is asking how to **leave** the sandbox and use programs on the host.

Also, TingPing never said that you are off topic. They closed the issue because it is a duplicate. You were never mentioned.

Finally, I have nothing to do with the Flatpak project. I'm just some random dude off the internet. Don't take my perceived "rudeness" out on the devs here that are doing great work.

**Comment by andrew-ma** [comment]
For VSCodium:  https://github.com/flathub/com.vscodium.codium/blob/master/README.md#host-shell
