### ISSUE TITLE
'flatpak install --from' doesn't use a runtime remote in another installation

### ISSUE THREAD

**Issue by mcatanzaro** [flatpak/flatpak#2758]
## Linux distribution and version

Fedora 30

## Flatpak version

flatpak-1.2.3-2.fc30

## Description of the problem

`flatpak install --from` fails to install the remote specified by `RuntimeRepo=` in the flatpakref.

## Steps to reproduce

Download [epiphany-tech-preview.flatpakref](https://webkitgtk.org/epiphany-tech-preview) and try to install it:

```
$ flatpak install --user --from ~/Downloads/epiphany-tech-preview.flatpakref
error: The application org.gnome.Epiphany/x86_64/master requires the runtime org.gnome.Platform/x86_64/master which was not found
```

It should have found and installed the remote because there is a pointer to it in the flatpakref:

```
RuntimeRepo=https://sdk.gnome.org/gnome-nightly.flatpakrepo
```

**Comment by mcatanzaro** [comment]
It works for me now after deleting a bunch of remotes, probably after `sudo flatpak remote-delete gnome-nightly`. I don't think that should have been required.

**Comment by matthiasclasen** [comment]
You should never use sudo with flatpak, unless you want to install an app for the root user.

That being said, if you can still reproduce this, it would be useful to know the state of the user and system installation when it happens (what remotes and refs are installed, mainly)

**Comment by mcatanzaro** [comment]
> You should never use sudo with flatpak, unless you want to install an app for the root user.

That was for deleting a system remote, though, not a user remote.

**Comment by matthiasclasen** [comment]
still; don't use sudo

**Comment by mwleeds** [comment]
I can reproduce this when I have the `gnome-nightly` remote in the system installation (but without `org.gnome.Platform//master` installed) and try to install the epiphany flatpakref in the user installation.

**Comment by mwleeds** [comment]
The fix is a bit complicated because currently a FlatpakTransaction only operates on one installation. So we can't just add an operation to the transaction to install the runtime in the system installation for a user transaction. We could either:

- teach FlatpakTransaction how to work on more than one installation, which is probably a lot of added complexity
- add the `gnome-nightly` remote in the user installation and install the runtime there
- create two transactions in the case where the runtime remote is in another installation and the runtime is not installed, which would mean consumers of the FlatpakTransaction API would need to do extra work

I'm inclined to go with the second option. It means you might end up with a remote duplicated across multiple installations but I suppose if you don't want that to happen don't use `--user`.
