### ISSUE TITLE
Fix remotes.d/ handling

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/flatpak#2800]
We support dropping remote configs into /etc/flatpak/remotes.d/ by telling ostree to look there. Sadly, it is not suitable for actual pre-configuration, since the remotes dropped there become effectively readonly, which is not what we want.

We need a place to drop remote snipplets that then get imported and become regular remotes, so users can enable and disable them afterwards.

**Comment by kalev** [comment]
Also, while at this, it might be a good idea to have an /usr version of remotes.d for distros, so that we can have /usr (distro config) and /etc (user overrides) split.

**Comment by mwleeds** [comment]
It sounds like there are three options:

1. have Flatpak import remotes from `remotes.d` or
2. make Flatpak able to modify remotes in `remotes.d` directories or
3. make `remotes.d` remotes immutable by the user

Endless has had issues before trying to dynamically add flatpak remotes for users and we want to switch to using the more declarative style of `remotes.d`. There's also the use case of modifying existing remotes as opposed to adding new ones. In theory for that we have things like `xa.redirect-url` and `ostree.deploy-collection-id` but it might be nice to be able to do it by changing the `remotes.d` config being shipped rather than indirectly by setting a metadata key. That raises two more questions:

- If the remote is imported from `remotes.d` into `repo/config` and then later the `remotes.d` one is modified by the distribution, does it get imported again and overwrite the existing one?
- If the remote is not imported but the user is allowed to modify it, how do you resolve conflicts between user modifications and distro modifications?

**Comment by matthiasclasen** [comment]
I think ideally, $INST/repo/config would have a $INST/repo/config.d/ cousin, so we could just drop things there. And yes, then it is up to distro packaging tools to manage merges. Can be as primitive as .rpmnew or more elaborate, like ostrees 3-way-merge of /etc

**Comment by matthiasclasen** [comment]
I think this is basically duplicate of https://github.com/flatpak/flatpak/issues/2508
