### ISSUE TITLE
Identifying objects after scanned as threat

### ISSUE THREAD

**Issue by Yuji-Shimohira-Calvo** [flatpak/flatpak#2838]
## Linux distribution and version
CentOS 7

## Flatpak version
Flatpak 1.0.2

## Description of the problem
I know ClamAV can sometimes be annoying with false positives, but since a Google search did not yield anything meaningful I decided to post this here.

Apparently, ClamAV finds a security threat in:

`~/.local/share/flatpak/repo/objects/34/32b76db9f3df9ffb126a55624df56417c367c47d95e3f619585af51e448144.file`

Is there an easy way to identify to which app the file under "objects/34" belongs?

**Edit**: just realised, does that object not belong to Flathub?

## Steps to reproduce
`clamscan -ir /home`

**Comment by miabbott** [comment]
I don't know if this is the easiest way, but I was able to map an object in the repo to a file with a script like this:

```bash
$ cat test.sh 
#!/usr/bin/env bash

repo=/home/miabbott/.local/share/flatpak/repo
csum=f2b43d6731b860578313efa2e3c4af38fbe92025b4df287cebb7dd8aa9bb2b

for r in $(ostree --repo=$repo refs); do
  ostree --repo=$repo ls -R -C $(ostree --repo=$repo rev-parse $r) | grep $csum
done
```

The `repo` points to my Flatpak repo and the `csum` is the leading part of the `.file` name that I chose at random.

Since the Flatpak repo has multiple refs, you have to enumerate the refs with `ostree refs`.  Then you need the commit from each ref, which is provided with `ostree rev-parse`.  Finally you can list all the files in a commit with `ostree ls -R -C`.  This recursively lists all the files in the commit and prints the checksum associated with the file.

When I run the script, I get something like this:

```
$ ./test.sh 
-00755 0 0 109152 34f2b43d6731b860578313efa2e3c4af38fbe92025b4df287cebb7dd8aa9bb2b /files/lib64/gstreamer-1.0/libgstdtls.so
-00755 0 0 109152 34f2b43d6731b860578313efa2e3c4af38fbe92025b4df287cebb7dd8aa9bb2b /files/lib64/gstreamer-1.0/libgstdtls.so
```

So I can guess that the `.file` I chose at random belongs to the `gstreamer` package.

YMMV.

**Comment by Yuji-Shimohira-Calvo** [comment]
Thanks, @miabbott, that worked like a charm!
