### ISSUE TITLE
/etc/profile.d/flatpak.sh should be disabled/removed after "apt remove flatpak"

### ISSUE THREAD

**Issue by wheelcomplex** [flatpak/flatpak#2840]
## Linux distribution and version
Ubuntu 18.04 
## Flatpak version
1.3.1-flatpak1~bionic
## Description of the problem
after "apt remove flatpak", /etc/profile.d/flatpak.sh still in place and case "command not found" errors when user login (invoke by /etc/profile).
## Steps to reproduce
apt remove flatpak and re-login

## Workaround
apt purge flatpak

**Comment by matthiasclasen** [comment]
Sounds like an issue with the ubuntu packaging

**Comment by ahayzen** [comment]
From the apt-get manpage https://manpages.debian.org/stretch/apt/apt-get.8.en.html

```
       remove
           remove is identical to install except that packages are removed instead of installed. Note that removing a package leaves its configuration files on the system. If a plus sign is appended to the
           package name (with no intervening space), the identified package will be installed instead of removed.

       purge
           purge is identical to remove except that packages are removed and purged (any configuration files are deleted too).
```

If `/etc/profile.d/flatpak.sh` is a "configuration" file then this would be expected behaviour from the manpages I think ? Or maybe this isn't a "configuration" file ?

Also note if a change did need to occur, please change the Debian packaging as Ubuntu just imports that (I also checked the same behaviour happens with PPA vs archive versions of flatpak)

**Comment by alexlarsson** [comment]
@smcv does the debian package have this fixed?

**Comment by smcv** [comment]
It is normal that configuration files aren't deleted when a package is removed, only when it is purged.

The canonical way to fix this sort of thing is for the configuration file to have a guard that makes it not do anything if the package it came from is no longer installed:

```
if command -v flatpak > /dev/null; then
    # ... the current contents of flatpak.sh ...
fi
```

(You can't use `exit` in script fragments that are sourced, like `profile.d/*` and `Xsession.d/*`.)

**Comment by smcv** [comment]
We get `flatpak.sh` from upstream code, so it would be best to fix this upstream (and backport it as a patch in the packaging if necessary). I'll send a PR.

**Comment by matthiasclasen** [comment]
I think the bug here is that /etc/profile.d/ content is considered a 'config' file ?

**Comment by smcv** [comment]
/etc is the directory for system-wide configuration files, so ... yes, it is considered to be a configuration file.

If you consider that file to be intended to be completely immutable, I could move it into /usr/share in the Debian packaging, and put a symlink in /etc/profile.d instead of a regular file.

There is currently no /usr/share/profile.d (at least, not in Debian).

**Comment by matthiasclasen** [comment]
I think it should be packaged in a way that makes it not a config file - it is required for proper functioning of flatpak, there's nothing to configure in there...

**Comment by mourad81dz** [comment]
in instalation of Centreon /
how i can delete  this directory  file   :   /etc/profile.d/centreon.sh file.  
thank You .
