### ISSUE TITLE
config option for letting 2+ flatpak containers share the same environment

### ISSUE THREAD

**Issue by kupiqu** [flatpak/flatpak#2846]
## Linux distribution and version

KDE neon 18.04

## Flatpak version

1.3.1

## Description of the problem

One of the backends of Cantor is Octave. I installed Octave and Cantor via flatpak packages. To make Octave visible to Cantor I needed to do (so Octave's executable in exports is visible to Cantor):

`sudo flatpak override --filesystem=/var org.kde.cantor`

However, executing any Octave instruction in Cantor makes Cantor go crazy, presumably waiting for Octave's response that is never reached, with a 100% CPU issue.

I assume I'm missing sth or doing it wrong, so I wonder, is there a way to allow interaction/communication between two flatpak packages?

**Comment by kupiqu** [comment]
> However, executing any Octave instruction in Cantor makes Cantor go crazy, presumably waiting for Octave's response that is never reached, with a 100% CPU issue.

Please note that this doesn't happen if Cantor is installed as a regular application instead of via a flatpak container (while keeping the Octave side the same, i.e., installed via flatpak).

**Comment by kupiqu** [comment]
I guess what I'm requesting is a config option for letting 2+ flatpak packages share the same environment.

**Comment by alexlarsson** [comment]
You can't in general just "share" two environments. Each of the two apps have their own runtimes which they rely on the ABI of and the runtime used can be different (right now, or on the next update or whenever).

What you want is to trigger the running of the other app as a flatpak. This can be done with open OpenURI/OpenFile portal. But maybe you want to do this more automatically (i.e. not a UI operation)?

What you *can* do is use the org.freedesktop.Flatpak.Development.HostCommand() dbus call (easiest by using the flatpak-spawn tool) which lets you do something like `flatpak-spawn --host flatpak run org.kde.cantor`, and even lets you pass file descriptors and whatnot. You do have to grant the app access org org.freedesktop.Flatpak on the bus though, which is quite a wide operation.

Alternatively, if you're in more control of both apps you can expose the callee as an (auto-starting) dbus service, and then launch it from the caller via a dbus call. Then you can just open up access to that particular name. Such a setup will also work if the called app is host-installed but the callee is flatpaked (or vice versa).

**Comment by kupiqu** [comment]
Thank you very much for the explanation. I am very interested in trying to apply this option you mentioned:

> Alternatively, if you're in more control of both apps you can expose the callee as an (auto-starting) dbus service, and then launch it from the caller via a dbus call. Then you can just open up access to that particular name. Such a setup will also work if the called app is host-installed but the callee is flatpaked (or vice versa).

However, I don't know how to do it. Is this explained or is there an example somewhere I could emulate?

**Comment by alexlarsson** [comment]
> However, I don't know how to do it. Is this explained or is there an example somewhere I could emulate?

I'm not sure there is a specific example of this for flatpak, but it is really quite generic. 

First of all you want to make octave (or a helper for it) have a mode where it starts up, grabs a well-known name on the session bus and starts to listen for requests. Then you want to register this name with the bus so that it is auto-started when someone talks to it but it is not running.

I found this kde doc explaining autostarting: 
https://techbase.kde.org/Development/Tutorials/D-Bus/Autostart_Services

Then all cantor has to do is call the right dbus method on the well known octave name and it will be auto-started as needed and fed the dbus message.

There are some specifics to the flatpak situation though:

Flatpak filters what dbus names you're allowed to own by default to the application id. So, given a flatpak application id like say 'org.kde.Octave', this can only own the name 'org.kde.Octave', or names with this as a prefix like 'org.kde.Octave.worker'. Similarly, only such names gets their .service file exported, and without that exported the dbus on the host can't start the service.

And then, even when the above works, cantor is not allowed to call it. You must tell flatpak about this by specifying a finish-arg like `--talk-name=org.kde.Octave.worker` or `--talk-name=org.kde.Octave.*`

**Comment by alexlarsson** [comment]
Note that when flatpak exports a .service file it will rewrite the Exec= line to automatically start the thing via flatpak, similar to how it works for desktop files.

**Comment by kupiqu** [comment]
Will check it out, thank you!
