### ISSUE TITLE
In an SSH session, flatpak install asked me fourteen times for authentication

### ISSUE THREAD

**Issue by cmurf** [flatpak/flatpak#3001]
## Linux distribution and version

Fedora Rawhide

## Flatpak version

flatpak-1.4.2-1.fc31.x86_64

## Description of the problem

When installing a flatpak without using sudo, I was asked for authentication fourteen times. Seems rather excessive which is why I usually use sudo. But I've read elsewhere a few times people saying 'yeah you really shouldn't need to use sudo' which clearly is very true but would I rather type in my password fourteen times? Or once for sudo and then not be asked by flatpak for authentication for every little thing it wants to do?

## Steps to reproduce

$ flatpak install 

For example, I just did this on a rawhide test system:

```
[chris@fmac Downloads]$ ls -l
total 4
-rw-rw-r--. 1 chris chris 4018 Jun 23 20:09 com.slack.Slack.flatpakref
[chris@fmac Downloads]$ flatpak remotes
Name   Options
fedora system,oci
[chris@fmac Downloads]$ flatpak list
[chris@fmac Downloads]$ flatpak install -vv com.slack.Slack.flatpakref
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/chris/.local/share/flatpak
The remote 'flathub', referred to by 'com.slack.Slack' at location https://dl.flathub.org/repo contains additional applications.
Should the remote be kept for future installations? [Y/n]: n
F: Loading https://dl.flathub.org/repo/flathub.flatpakrepo using libsoup
F: Received 4040 bytes
The application com.slack.Slack depends on runtimes from:
  https://dl.flathub.org/repo/
Configure this as new remote 'flathub' [Y/n]: y
F: Calling system helper: ConfigureRemote
==== AUTHENTICATING FOR org.freedesktop.Flatpak.configure-remote ====
Authentication is required to configure software repositories
Authenticating as: chris
Password: 
==== AUTHENTICATION COMPLETE ====
F: Calling system helper: ConfigureRemote
==== AUTHENTICATING FOR org.freedesktop.Flatpak.configure-remote ====
Authentication is required to configure software repositories
Authenticating as: chris
Password: 
==== AUTHENTICATION COMPLETE ====
F: Fetching summary file for remote ‘slack-origin’
F: Transaction: install slack-origin:app/com.slack.Slack/x86_64/stable[*]
F: marking op install:app/com.slack.Slack/x86_64/stable resolved to 5eb3cfc6d38e11671e0f1ee0640f696c4ae198339e90c3cae3b075e054a0d0fd
F: Calling system helper: GenerateOciSummary
==== AUTHENTICATING FOR org.freedesktop.Flatpak.metadata-update ====
Authentication is required to update metadata
Authenticating as: chris
Password: 
==== AUTHENTICATION COMPLETE ====
F: Failed to download optional summary
F: Fetching summary file for remote ‘flathub’
Required runtime for com.slack.Slack/x86_64/stable (runtime/org.freedesktop.Platform/x86_64/18.08) found in remote flathub
Do you want to install it? [Y/n]: y
F: Transaction: install/update flathub:runtime/org.freedesktop.Platform/x86_64/18.08[$old]
F: marking op install/update:runtime/org.freedesktop.Platform/x86_64/18.08 resolved to 5a03802b4550ae60170112dd33f5a5958c34d28e64bb4f21674a642ac01e2e6f
F: Transaction: install/update flathub:runtime/org.freedesktop.Platform.Locale/x86_64/18.08[/en]
F: Transaction: install/update flathub:runtime/org.freedesktop.Platform.VAAPI.Intel/x86_64/18.08[$old]
F: Transaction: install/update flathub:runtime/org.freedesktop.Platform.html5-codecs/x86_64/18.08[$old]
F: marking op install/update:runtime/org.freedesktop.Platform.html5-codecs/x86_64/18.08 resolved to dfca6ff90bc40f1895340fb83d2e5b4bfbf2ea55e1bb264240af7aa58309268a
F: marking op install/update:runtime/org.freedesktop.Platform.VAAPI.Intel/x86_64/18.08 resolved to 2c9e1aa9097f0d1f7e063b448c4b2af746929208a28da16b5c34bf369daa33b1
F: marking op install/update:runtime/org.freedesktop.Platform.Locale/x86_64/18.08 resolved to 2b4e517a4a1af0ead50854e8653165d91883e71ef170f6f1ec9c8b893454d968

com.slack.Slack permissions:
    ipc	network	pulseaudio	x11	devices	file access [1]	dbus access [2]

    [1] xdg-documents:ro, xdg-download, xdg-music:ro, xdg-pictures:ro, xdg-run/dconf, xdg-videos:ro, ~/.config/dconf:ro
    [2] ca.desrt.dconf, org.freedesktop.Notifications, org.kde.StatusNotifierWatcher


 1.	   	org.freedesktop.Platform	x86_64	18.08	flathub	< 290.3 MB
 2.	   	org.freedesktop.Platform.Locale	x86_64	18.08	flathub	< 315.9 MB (partial)
 3.	   	org.freedesktop.Platform.VAAPI.Intel	x86_64	18.08	flathub	< 1.8 MB
 4.	   	org.freedesktop.Platform.html5-codecs	x86_64	18.08	flathub	< 2.9 MB
 5.	   	com.slack.Slack	x86_64	stable	slack-origin	< 63.9 MB

Proceed with these changes to the Default system installation? [Y/n]: y
Installing 1/5…                                                                                                                            F: Calling system helper: GetRevokefsFd
F: Calling system helper: GetRevokefsFd
==== AUTHENTICATING FOR org.freedesktop.Flatpak.modify-repo ====
Authentication is required to modify a system repository
Authenticating as: chris
Password: 
==== AUTHENTICATION COMPLETE ====
F: flatpak_dir_pull: Using commit 5a03802b4550ae60170112dd33f5a5958c34d28e64bb4f21674a642ac01e2e6f for pull of ref runtime/org.freedesktop.Platform/x86_64/18.08 from remote flathub
Installing 1/5… ████████████████████ 100%  4.1 MB/s  00:00F: Calling system helper: Deploy
==== AUTHENTICATING FOR org.freedesktop.Flatpak.app-install ====
Authentication is required to install software
Authenticating as: chris
Password: 
==== AUTHENTICATION COMPLETE ====
Installing 2/5…                                                                                                                            F: Calling system helper: GetRevokefsFd
F: Calling system helper: GetRevokefsFd
==== AUTHENTICATING FOR org.freedesktop.Flatpak.modify-repo ====
Authentication is required to modify a system repository
Authenticating as: chris
Password: 
==== AUTHENTICATION COMPLETE ====
F: flatpak_dir_pull: Using commit 2b4e517a4a1af0ead50854e8653165d91883e71ef170f6f1ec9c8b893454d968 for pull of ref runtime/org.freedesktop.Platform.Locale/x86_64/18.08 from remote flathub
Installing 2/5… ████████████████████ 100%  2.5 kB/s  00:00F: Calling system helper: Deploy
==== AUTHENTICATING FOR org.freedesktop.Flatpak.app-install ====
Authentication is required to install software
Authenticating as: chris
Password: 
==== AUTHENTICATION COMPLETE ====
Installing 3/5…                                                                                                                            F: Calling system helper: GetRevokefsFd
F: Calling system helper: GetRevokefsFd
==== AUTHENTICATING FOR org.freedesktop.Flatpak.modify-repo ====
Authentication is required to modify a system repository
Authenticating as: chris
Password: 
==== AUTHENTICATION COMPLETE ====
F: flatpak_dir_pull: Using commit 2c9e1aa9097f0d1f7e063b448c4b2af746929208a28da16b5c34bf369daa33b1 for pull of ref runtime/org.freedesktop.Platform.VAAPI.Intel/x86_64/18.08 from remote flathub
Installing 3/5… ████████████████████ 100%  202.9 kB/s  00:00F: Calling system helper: Deploy
==== AUTHENTICATING FOR org.freedesktop.Flatpak.app-install ====
Authentication is required to install software
Authenticating as: chris
Password: 
==== AUTHENTICATION COMPLETE ====
Installing 4/5…                                                                                                                            F: Calling system helper: GetRevokefsFd
F: Calling system helper: GetRevokefsFd
==== AUTHENTICATING FOR org.freedesktop.Flatpak.modify-repo ====
Authentication is required to modify a system repository
Authenticating as: chris
Password: 
==== AUTHENTICATION COMPLETE ====
F: flatpak_dir_pull: Using commit dfca6ff90bc40f1895340fb83d2e5b4bfbf2ea55e1bb264240af7aa58309268a for pull of ref runtime/org.freedesktop.Platform.html5-codecs/x86_64/18.08 from remote flathub
Installing 4/5… ████████████████████ 100%  279.6 kB/s  00:00F: Calling system helper: Deploy
==== AUTHENTICATING FOR org.freedesktop.Flatpak.app-install ====
Authentication is required to install software
Authenticating as: chris
Password: 
==== AUTHENTICATION COMPLETE ====
Installing 5/5…                                                                                                                            F: Calling system helper: GetRevokefsFd
F: Calling system helper: GetRevokefsFd
==== AUTHENTICATING FOR org.freedesktop.Flatpak.modify-repo ====
Authentication is required to modify a system repository
Authenticating as: chris
Password: 
==== AUTHENTICATION COMPLETE ====
F: flatpak_dir_pull: Using commit 5eb3cfc6d38e11671e0f1ee0640f696c4ae198339e90c3cae3b075e054a0d0fd for pull of ref app/com.slack.Slack/x86_64/stable from remote slack-origin
Installing 5/5… █▍                     7%  125.2 kB/s  01:59F: Loading https://downloads.slack-edge.com/linux_releases/slack-desktop-3.4.2-amd64.deb using libsoup
Installing 5/5… ████████████████████ 100%  3.4 MB/s  00:00F: Received 62724122 bytes
Installing 5/5… ████████████████████ 100%  2.5 MB/s  00:00F: Calling system helper: Deploy
==== AUTHENTICATING FOR org.freedesktop.Flatpak.app-install ====
Authentication is required to install software
Authenticating as: chris
Password: 
==== AUTHENTICATION COMPLETE ====
F: Calling system helper: RunTriggers
==== AUTHENTICATING FOR org.freedesktop.Flatpak.modify-repo ====
Authentication is required to modify a system repository
Authenticating as: chris
Password: 
==== AUTHENTICATION COMPLETE ====
Installation complete.                                                                                                                       
[chris@fmac Downloads]$ rpm -qa | grep flatpak
flatpak-libs-1.4.2-1.fc31.x86_64
flatpak-1.4.2-1.fc31.x86_64
flatpak-session-helper-1.4.2-1.fc31.x86_64
flatpak-selinux-1.4.2-1.fc31.x86_64
[chris@fmac Downloads]$ 
```

**Comment by mwleeds** [comment]
Interesting that you are prompted for your password by the text-based polkit agent rather than the graphical one. You have a graphical desktop environment running right?

**Comment by cmurf** [comment]
>You have a graphical desktop environment running right?
Correct. It's GNOME.

**Comment by cmurf** [comment]
OK this only happens when I do the install on a remote (ssh) system. If I do the install in GNOME Terminal on the target system, I get a single GUI popup asking for authentication, no additional authentication requests happen.

**Comment by mwleeds** [comment]
> OK this only happens when I do the install on a remote (ssh) system. If I do the install in GNOME Terminal on the target system, I get a single GUI popup asking for authentication, no additional authentication requests happen.

Flatpak's `FlatpakPolkitAgentTextListener` is copied from `polkit` so we may have to change it there to make it remember credentials if possible.

**Comment by matthiasclasen** [comment]
I think this is just a matter of policy.

Our actions have the typical defaults:

```
      <allow_any>auth_admin</allow_any>
      <allow_inactive>auth_admin</allow_inactive>
      <allow_active>auth_admin_keep</allow_active>
```

And on top of that, we have a rule that says:

```
        subject.active == true && subject.local == true &&
        subject.isInGroup("wheel")) {
            return polkit.Result.YES;
```

When running via ssh, you are missing out on both subject.local and auth_active, so polkit ends up asking every time.

Install a local rule if operating via ssh is important to you...

**Comment by brittyazel** [comment]
I'm on Ubuntu 18.04 and I was hitting an issue with ssh and VNC sessions both not being able to use flatpak without being bombarded with password requests. My "solution" was to append /var/lib/polkit-1/localauthority/10-vendor.d/org.freedesktop.Flatpak.pkla with:
ResultAny=yes

This allows non-local sessions to follow the rule set

**Comment by dbarnett** [comment]
Could someone clarify the resolution on this issue? It sounds like it's "working as intended" according to flatpak devs that a standard flatpak install behaves this way over SSH, and can be bypassed by users "installing a local rule". Is there a pointer to instructions for that?

FWIW, I'm having similar problems running it in a regular terminal on a Pixelbook which may not be "WAI". Should that be a new issue independent of SSH behavior? Any idea why that case wouldn't match the rules here?

**Comment by rayfoss** [comment]
I've had this issue on all my Chromebooks with Crostini. They use Wayland via LXC. I suspect Windows WSL2 has the same issue... we have a graphical environment, but it's not exactly Gnome 3.

It's really painful when timeouts happen on long downloads such as `app/com.visualstudio.code.oss`... I had to restart that 1GB install 3 times due too slowish connection and polkit timing out while I grabbed a byte

**Comment by nicekiwi** [comment]
I'm getting this issue in Kubuntu 21.10 in Discover the update flat fails, on CLI (not over ssh) I get the same issue as the OP, asking for sudo password heaps.

**Comment by sirus20x6** [comment]
i just experienced this on a server that I VNCed into. I lost count at the number of times I had to authenticate just to install deluge, but it was more than excessive.

**Comment by zenbooster** [comment]
To install obsidian with flatpak via xrdp over ssh, I had to suffer specifically ...

**Comment by digitalextremist** [comment]
So bad. `ssh` between two `Linux Mint` machines of differing versions. I almost respected `flatpak` at the level of `apt` and `snap` despite its apparent gotchas and need for special treatment... but not after being unable to comfortably install applications via `ssh` with a radically long password. Having to re-enter that is insane. Cannot be asked to suffer through that while also maintaining self-respect. Same page with @callegar here. This is an actual black mark on the entire idea of `flatpak`

**Comment by brittyazel** [comment]
> So bad. `ssh` between two `Linux Mint` machines of differing versions. I almost respected `flatpak` at the level of `apt` and `snap` despite its apparent gotchas and need for special treatment... but not after being unable to comfortably install applications via `ssh` with a radically long password. Having to re-enter that is insane. Cannot be asked to suffer through that while also maintaining self-respect. Same page with @callegar here. This is an actual black mark on the entire idea of `flatpak`

Yeah it's a bit weird that the polkit policy is so specific and restrictive, but it's easily fixable:

The issue is with the `subject.local==true` clause on line 7 in `/usr/share/polkit-1/rules.d/org.freedesktop.Flatpak.rules`:

```
polkit.addRule(function(action, subject) {
    if ((action.id == "org.freedesktop.Flatpak.app-install" ||
         action.id == "org.freedesktop.Flatpak.runtime-install"||
         action.id == "org.freedesktop.Flatpak.app-uninstall" ||
         action.id == "org.freedesktop.Flatpak.runtime-uninstall" ||
         action.id == "org.freedesktop.Flatpak.modify-repo") &&
        subject.active == true **&& subject.local == true** &&
        subject.isInGroup("@privileged_group@")) {
            return polkit.Result.YES;
    }

    return polkit.Result.NOT_HANDLED;
});
```

To fix it, you just create an override rule in `/etc/polkit-1/rules.d/` to remove the `subject.local==true` clause, e.g. `/etc/polkit-1/rules.d/Flatpak-ssh-override.rule`:

```
polkit.addRule(function(action, subject) {
    if ((action.id == "org.freedesktop.Flatpak.app-install" ||
         action.id == "org.freedesktop.Flatpak.runtime-install"||
         action.id == "org.freedesktop.Flatpak.app-uninstall" ||
         action.id == "org.freedesktop.Flatpak.runtime-uninstall" ||
         action.id == "org.freedesktop.Flatpak.modify-repo") &&
        subject.active == true &&
        subject.isInGroup("@privileged_group@")) {
            return polkit.Result.YES;
    }

    return polkit.Result.NOT_HANDLED;
});
```

That's all I had to do and it's never been an issue since. Is it annoying to 'have' to do this? Sure. But at least the fix is trivially easy.

**Comment by GenocideStomper** [comment]
This whole discussion makes it sound like SSH is some fringe use case that nobody uses on _Linux_. A fix should be included in the package installation or with polkit.

Unless of course the flatpak devs encourage never updating via SSH, and therefore perhaps never at all.

Closing this issue as completed is also incredibly flippant of the issue.

**Comment by brittyazel** [comment]
Sure, there's definitely a case to be made that removing the `subject.local == true` condition should be the default, and I'd be inclined to agree with you. That being said, I haven't heard the rationale for why they decided to enable this specific condition in the first place, so it's hard to form a full opinion until getting the complete story.

However, the problem many people are taking with this discussion isn't so much technical, rather it's policy, and right now many people here disagree with the default policy, **which is totally fair**. People have been disagreeing about defaults since the creation of computers, and everyone has a different, and valid, line that they draw between security and convenience. I understand why they chose to close _this_ issue, as the purview of this issue was not to have a security discussion about the default policies, rather it was to work around _this_ specific usability issue in a technical context. Toward that end, this issue achieved its desired outcome in that it resulted in a direct, official solution to create a local override for the rule in question.

With all that being said, I think it would be entirely reasonable for someone to open a separate issue scoped around having a security conversation about this particular condition in this rule. That way we can hear from the developers and others knowledgeable in this area why it was decided to restrict the rule to `subject.local == true`, and whether the rationale still stands today. It's quite possible they can and would reconsider their decision if given real use cases where this policy is overly cumbersome, assuming the security implications are not overwhelming.

**Comment by callegar** [comment]
@brittyazel thanks for your comments and explanations.

From the discussion, I am getting the impression that the low hanging fruit to work on is documentation.

If the override file you provide above becomes a part of the documentation, then life will be easier for many users and not just because they will be able to activate the override themselves. In fact, it will also be easier for many Linux distributions to play their downstream role by deciding if they want the override by default or not.

Providing some documentation will also indirectly prompt those who picked the `subject.local == true` behavior to re-evaluate it and in case it was there for a reason to express it explicitly in the documentation, that will also be good for everybody.

Given that this bug is closed, what is the preferred course of action now? To try to have it reopened or to have a "documentation enhancement request" issue opened? Wrt the latter, I am afraid that as any enhancement request it might not end up getting sufficient attention.

**Comment by brittyazel** [comment]
@callegar afaik, and future attention on this should be in new issues, i.e. a ticket to request documentation clarity and/or a ticket to reconsider this security policy. Developers like to work within singular, purposeful issues in order to keep discussion on track and centered around a singular topic. In general, once a discussion veers away from the original ticket in question, it's best to open a new ticket directly targeting that new discussion point.

**Comment by TiZ-HugLife** [comment]
Confirming [the documented fix](https://github.com/flatpak/flatpak/issues/3001#issuecomment-2098981907) works on SteamOS, in case it's helpful for anyone who stumbles upon this. For anyone attempting to implement it, I do want to point out: make sure you change that `@privileged_group@` snippet to whatever the name of your sudoers group is. It is indeed `wheel` on SteamOS. That tripped me up because I didn't notice it the first time.

**Comment by erdnuesse** [comment]
removing `subject.local == true &&` didn't work for me. 
Using an arch based distro (endeavour), alas wheel is the corrrect group, however changing the file didn't change a thing as I got heaps of password prompts.

**Comment by brittyazel** [comment]
Did you log out and back in? I dunno what to tell you because I'm also on Arch and it works great for me.

**Comment by erdnuesse** [comment]
I logged out of the ssh session first and back in. After it remained, I started a new tmux in the ssh session. 
Still remained, so I rebooted the whole system, just to make sure polkit, ssh, and all shell sessions restarted. 
Issue remained after reboot. 
What I am unclear about is, I ended up with just the one file without subject local, because I suspected having two configs may have caused using the old preferred over the new one. But even then it didn't work and I was really confused as to why. 

However, I have another section had in my config that I even commented out to have it look like in the example. 
Secondly, I'm not sure which polkit I was using lately as I had issues with brave browser startup delays with my polkit of choice, so I need to recheck which one the current one was.

**Comment by ChonkaLoo** [comment]
> removing `subject.local == true &&` didn't work for me. Using an arch based distro (endeavour), alas wheel is the corrrect group, however changing the file didn't change a thing as I got heaps of password prompts.

Check it's named ` /etc/polkit-1/rules.d/Flatpak-ssh-override.rules` and not .rule worked for me after that easy change.

**Comment by YanceyChiew** [comment]
It is not a big deal to need to verify the password when logging in remotely, or, at least we can manually overwrite the polkit rules.

But if you run `flatpak update` when logging in remotely, it will ask for the password multiple times for each entry that needs to be upgraded, which is simply torture. People tend not to manually interrupt this torture when going through it, out of concern for potential data corruption.

I can't think of any reason to need to constantly re-verify the password, I think this is a problem that needs to be fixed, rather than only having polkit automatically pass the authentication as a workaround.

**Comment by awused** [comment]
Flatpak should ask for permissions once at the beginning. This bug seems to have been considered WAI because flatpak asks for permission over SSH, but that's not the bug. The bug is that it asks for permission dozens of times for routine operations.

It can also leave the system in an inconsistent state if I, say, uninstall something and then don't give permission to update the system repository (whatever that means).

**Comment by rgadsdon** [comment]
The fix mentioned here does not work on Fedora 41 flatpak..   Still getting prompted multiple times, once for each item on the update list..

**Comment by lukaszsobala** [comment]
>Yeah, it is a bit annoying that by default the polkit rule is so restrictive, but it's trivially easy to fix as @matthiasclasen described.

I am sorry but this is not "trivial" at all for normal users - who are not supposed to know how polkit works in the back end (I certainly have no clue).

The fix mentioned did not work. I installed flatpak on Ubuntu (24.10) and in that directory there were no rules. So I created 2 rules: the original and the override. This did not change anything. Ubuntu doesn't seem to have the "wheel" group so I changed it to sudo. But again, as a normal user I am not supposed to even think about dealing with this, I should just run `flatpak update` and it should just work. And yes, I did reboot the system after creating these rules. 

What is worse is that the authentication it asks for (a few times per 1 package) is still broken, because sometimes it says "authentication complete" and sometimes "authentication failure", despite writing the same password. This is tedious and should be seriously looked at. I don't have physical access to the machine, I only update it from time to time through network. Is this such a rare use case really?

**Comment by brittyazel** [comment]
> This may be a little late to the party, but I can confirm this is also an issue over xRDP. I've tried with Mint, Ubuntu, and Rocky. I can also confirm that [@brittyazel](https://github.com/brittyazel)'s fix of creating an override file works. My question is, why not just edit the /usr/share/polkit-1/rules.d/org.freedesktop.Flatpak.rules file, instead of creating an override file? What is the order of file processing and what benefit does creating an override file give?

It is bad form to edit the files in /usr/ directly as those files are provided by the upstream package/distribution and any edits to these files will either be overwritten on an update or, by editing this file, you may inadvertently lock yourself from ever getting an updated version of the file, depending on the behavior of the package manager. Basically, it's dangerous to edit the files in /usr/share/ and you shouldn't do it, even though you can.

Generally speaking, configurations and rules defined in /etc/ will take precedence over the default rules found in /usr/. So if you need to modify a config or a rule found in /usr/, the best way to do so is to create the override file in /etc/, and this is true for many, many software packages, i.e. systemd, polkit, openssh, pipewire, etc. That being said, there is nuance to how different configuration are done for each software package, but overall the theme of /usr/ being off-limits and /etc/ being writable holds true.

**Comment by bnosie** [comment]
> Generally speaking, configurations and rules defined in /etc/ will take precedence over the default rules found in /usr/. So if you need to modify a config or a rule found in /usr/, the best way to do so is to create the override file in /etc/. This is true for many, many software packages, i.e. systemd, polkit, openssh, pipewire, etc. That being said, there is nuance to how different configurations are handled for each software package, but overall the theme of /usr/ being off-limits and /etc/ being writable holds true.

Thanks for the explanation, makes good sense.

**Comment by fontypete** [comment]
How TF can we expect people to adopt Linux when we present them with things like this? Do you think I can say to my son "Here's Linux, it's great. But every time you update something whose developers decided to use Flatpack rather than a nice simple .deb you're going to be asked to give your password 50 times"? No wonder he's using a Mac.

Flatpack seems to be another GRUB: We had something that worked well in 99.9% of cases and needed a bicycle permit to use it. Now we have something mega complicated that you need F37 pilot's training for, to satisfy the 0.1% of cases and so some FOSS developers can get orgasms thinking how brilliant they are. Who cares whether you run the command from ssh,a terminal or a GUI. 

There should be absolutely no reason for any system to request a password more than once IN ANY CIRCUMSTANCES for any adjoined collection of operations. Flatpack upgrade is "an adjoined collection of operations" in this case. 

When you can show that Flatpack is more useful than Snap (which is scaping the bottom of the cesspit) you'll have at least done that. For the moment, Flatpack is a class one pain in the butt.

**Comment by callegar** [comment]
As mentioned before, the biggest issue here is *actively training users to type in passwords with little or no attention*. Should one be able to craft things so that among those 10 password requests or immediately after them a password is asked for something totally unrelated and hazardous, the disaster is easy to foresee.

Yet, there is now know and relatively easy recipe to locally modify the setup and prevent the issue.

**Comment by lukaszsobala** [comment]
It is even worse - to maintain my sanity I just copy the password to the clipboard and paste it instead of typing the same thing over and over. I do not know why the workaround did not work for me, I will retry it and if it still does not, I don't think this is closed. To be honest, I wouldn't consider it closed until there is an easy way for the user to fix this, instead of manually modifying obscure config files. Flatpaks are meant to be "easy", don't they?
EDIT: can confirm, the override works, it was my pasting mistake.

**Comment by ghost** [comment]
Yep.  2025:  Issue still remains.

Flatpak should, _by default_, _not_ ask for the password over and over.  It's fine to ask once.  But when you're typing your password over and over for each component it starts to become a problem.  The user should not have to manually provide overrides.  I get that security is a thing, but asking a bunch times for a password during one installation process just because it has multiple components isn't a good default.  Worse, the solution presented here is now in the hidden posts that users won't see when searching until they go through the whole thread manually.

yay in Arch is able to keep a sudo loop going in the background (though this too isn't on by default and it should be IMO) so it won't keep asking for passwords.  That allows it to use elevated permissions when required and de-elevated when not.  This seems like a really simple solution that should be effective?  If you're concerned about users walking away during long operations, it could have a timeout or something.

I don't know what's different about the setup I'm seeing this on.  I installed Debian Bookworm 12.10 on a server system, but I'm pretty sure I didn't see this when I had Bookworm installed on my primary system (currently using Trixie with no issue.)  Only difference I know of with it is I didn't install all the desktop environments, instead focusing on XFCE.  It's not just SSH/RDP though.  I got it when sitting right at that system. 

EDIT:  This also creates an extra problem in that if you ever type the password wrong (and if you're asked 50 times you will at least once) it fails the entire component rather than retries.

Definitely shouldn't be marked closed.

**Comment by callegar** [comment]
Funny enough, on an ssh session, flatpak asks for the password *twice* even right after having declared "Looking for updates… Nothing to do." Asking permission to do nothing is already interesting. Asking again to be 100% sure of being allowed to do nothing is even more. Question is what flatpak would do if permission to do nothing is negated ;-)

**Comment by zeroepoch** [comment]
> The fix mentioned here does not work on Fedora 41 Flatpak.. Still getting prompted multiple times, once for each item on the update list.. ==== AUTHENTICATING FOR org.freedesktop.Flatpak.modify-repo ==== Authentication is required to modify a system repository Authenticating as: RG (rgadsdon)
> 
> * As this discussion is marked 'Closed' I will raise this as a new issue..

For Fedora take a look at this other open issue, https://github.com/flatpak/flatpak/issues/4267#issuecomment-1244583804

Essentially it's a different action that is being triggered causing the prompts (`org.freedesktop.Flatpak.metadata-update`). I thought the rule I added wasn't working until I noticed the action didn't match any of those mentioned above in this issue.

**Comment by honduken** [comment]
Just happened to me, connection over RDP, asked for password 10 times to install 1 app. So basically what I'm reading here is if I were to log in normally (through x session or whatever the default is) this wouldn't be an issue but because im logging in through XRDP it's going to ask me constantly.

**Comment by lukaszsobala** [comment]
The workaround still works. However, as @callegar said, after it is done updating everything, it actually STILL asks for the password (for me it was once) when there is nothing to do. And as far as I can observe, the operation is successful no matter if you give the password or not. So this is definitely still **not solved**, this is a bug. This behavior makes no sense.

**Comment by matozoid** [comment]
Here's a better described workaround: https://forum.nomachine.com/topic/weird-issue-with-flatpak-mint-21-3-virtual-framebuffer

**Comment by Kurizek27** [comment]
i just found out you can just log in as root (in the remote location) and it wont ask you for your password a million times

**Comment by k4cus** [comment]
Agree problem from 2025 still in 2026 !! how you want people to switch to linux if it sucks like that?
