### ISSUE TITLE
Missing Ubuntu 19.04 (disco) builds on PPA

### ISSUE THREAD

**Issue by riyad** [flatpak/flatpak#3011]
## Linux distribution and version

Ubuntu 19.04 (disco)

## Description of the problem

@alexlarsson's Ubuntu PPA is missing 19.04 (disco) builds.
see https://launchpad.net/~alexlarsson/+archive/ubuntu/flatpak

I hope it's not too troublesome to activate builds for disco.
I've recognized that builds for new Ubuntu releases were delayed (since at least 18.04). Is there a way to have Launchpad activate builds for new (Ubuntu) releases automatically or does it always need manual intervention?

**Comment by mwleeds** [comment]
Looks like [Disco has Flatpak 1.2.4](https://packages.ubuntu.com/disco/flatpak) so you're right that would be nice to have the latest version in the PPA.

**Comment by riyad** [comment]
Yes, Ubuntu includes Flatpak in since a few releases. But it would be nice to have more recent builds for disco also ... especially when they're already being built for 7 other Ubuntu releases. :wink:

**Comment by leinardi** [comment]
I came here to report the same issue. It would be really nice to have Disco packages.

**Comment by FakeShemp** [comment]
`Warning: org.freedesktop.Platform.openh264 needs a later flatpak version`
Ubuntu's build is now so old that some 19.08 packages won't even install. It would be really nice if disco was added to the PPA.

**Comment by mwleeds** [comment]
@ahayzen might be the person to ask

**Comment by Eonfge** [comment]
> `Warning: org.freedesktop.Platform.openh264 needs a later flatpak version`
> Ubuntu's build is now so old that some 19.08 packages won't even install. It would be really nice if disco was added to the PPA.

Can confirm. With the new release of OpenH264, it cannot be updated on Ubuntu 19.04

**Comment by ahayzen** [comment]
@mwleeds I've only been trying to do SRUs into the archive, for the PPA Alex needs to tick the box on the PPA to enable disco and then upload a build.

**Comment by petersaints** [comment]
> > `Warning: org.freedesktop.Platform.openh264 needs a later flatpak version`
> > Ubuntu's build is now so old that some 19.08 packages won't even install. It would be really nice if disco was added to the PPA.
> 
> Can confirm. With the new release of OpenH264, it cannot be updated on Ubuntu 19.04

I can also confirm this. When the issue was opened it was not a pressing matter, but if packages are now requiring 1.4.2 it's important to get it to Ubuntu, ideally through SRU as @ahayzen said. However, it would be nice if @alexlarsson could enable and release it on the PPA as a quick fix for anyone affected.

**Comment by petersaints** [comment]
I could have tried to fix this all by myself by building packages from source. However, as POTENTIALLY DANGEROUS and VERY BAD work around I installed the following packages from the PPA that were built for the previous release (Ubuntu 18.10 Cosmic Cuttlefish):
- https://launchpad.net/~alexlarsson/+archive/ubuntu/flatpak/+files/libostree-1-1_2019.1-flatpak2~cosmic_amd64.deb
- https://launchpad.net/~alexlarsson/+archive/ubuntu/flatpak/+files/flatpak_1.4.2-flatpak1~cosmic_amd64.deb

Everything SEEMS to have worked fine! We may do the same AT YOUR OWN RISK!

Offtopic/Rant: The general lack of updates for Ubuntu fixed releases is the kind of thing that sometimes just makes me want to jump ship to Fedora. I used it for a bit in the past and they are not as conservative about updates. Or I could go for a rolling release like Manjaro, which I tried before in the past but my install got borked from an update 3 days after a clean install and that was the ONLY reason I immediately dropped it because I felt it was probably too unreliable as my daily driver.

**Comment by ahayzen** [comment]
@petersaints FYI Ubuntu has the latest microrelease of whichever stable version happened to be in the archive at the time of release (so 18.04 has 1.0.8, 19.04 has 1.2.4, 19.10 will have 1.4.2 right now). 

Jumping major versions is tricky and it tends to introduce new dependencies (which aren't allowed in a SRU).  So the main way to include a future stable series to an old Ubuntu release is to use backports. However, packages in backports aren't automatically installed (the user has to opt in for each package) and I'm not sure if all downstreams enable the backports repository, so I don't think it's worth the effort to push flatpak (and all it's depends like ostree, and any new packages like xdg-dbus-proxy) to backports.

For this specific issue, there might be a 1.2.5 that includes support for the OpenH264 extension, if that happens soon I will likely look at SRU'ing that into Ubuntu 19.04 (which ends support in January 2020).

**Comment by petersaints** [comment]
@ahayzen Yes, I'm mostly aware of how Ubuntu releases work. However, there are some packages which have been granted an exception to the rule (e.g., Firefox) and perhaps flatpak should be one of them since the inability to have the latest flatpak version may stop users from installing certain flatpak packages, which kinda defeats the purpose of a universal cross-distro package manager.

**Comment by ahayzen** [comment]
Yes, such an exception would be nice, but I believe we would have to get it approved by the release team and/or technical board, would likely require more QA, and would potentially require a lot of work if there are multiple new depends :-)

But so far since 1.0, the OpenH264 issue is the first one that is user facing to users on old versions of flatpak (everything else has been compatible/working), and you don't lose much functionality with this issue.

This is the list of some of the special cases at the moment in Ubuntu https://wiki.ubuntu.com/StableReleaseUpdates#Documentation_for_Special_Cases

**Comment by petersaints** [comment]
> 
> But so far since 1.0, the OpenH264 issue is the first one that is user facing to users on old versions of flatpak (everything else has been compatible/working), and you don't lose much functionality with this issue.
> 
Sure. It's not critical issue but, since it is prone to happen again in the future, perhaps it's a good idea to have a plan on how to deal with it.

**Comment by Eonfge** [comment]
We can all rest in peace, it's available:
https://launchpad.net/~alexlarsson/+archive/ubuntu/flatpak

**Comment by FakeShemp** [comment]
Yay! Thank you, team :)

**Comment by riyad** [comment]
Thanks to all invloved. :+1:
Can we still get a mechanism set up that would allow for a more timely update of the configuration in launchpad? I mean the next Ubuntu release (eoan) is just weeks away. :wink:
