### ISSUE TITLE
Difficultly distributing libflatpak without pulling in OSTree

### ISSUE THREAD

**Issue by robert-ancell** [flatpak/flatpak#3091]
In Ubuntu packages are divided into a "main" category which is commercially supported and a larger "universe" category which is available but not supported. All the flatpak packages currently live in "universe" as they're not used in our default images.

Core parts of GNOME are likely to link against libflatpak to integrate features. We're looking at bringing [libflatpak into main](https://launchpad.net/bugs/1812456) (the daemon would remain in Universe). This would be otherwise fine except libflatpak links against libostree. Since libostree is OSTree AFAICT this is too much for us to formally support.

I'm looking for insight and ideas of how we can resolve this. Is libflatpak only using a small subset of OSTree? Are there any runtime detections that could occur, or could there be a smaller OSTree library that Flatpak uses that is more supportable? Perhaps this is more of an OSTree question?

**Comment by mwleeds** [comment]
Flatpak uses libostree very heavily and there are few parts of libostree that are unused by flatpak (with a few exceptions like `ostree-bootloader.h`, `ostree-sysroot.h`, and `ostree-kernel-args.h`). But it might be possible to split your ostree package so that the ostree command line tools and ostree boot support are not in the same package as libostree. Debian already has `ostree` separate from `libostree`, and they have an experimental `ostree-boot` [package](https://packages.debian.org/experimental/ostree-boot) (since it doesn't have unit tests).

**Comment by cgwalters** [comment]
I'd also be OK adding a `--disable-sysroot` support to libostree upstream, which turns some of those APIs into runtime errors.  Or possibly even strips out the symbols.  It'd be like the recent [PR to make GPG optional](https://github.com/ostreedev/ostree/pull/1889) but more invasive of course.

**Comment by cgwalters** [comment]
That said, I think mwleed's suggestion is simpler - if you move the systemd units into a separate package as Debian has done, then it rather cripples the "sysroot" parts of libostree anyways.

**Comment by robert-ancell** [comment]
We're using the Debian package unmodified in Ubuntu, so we can distribute without the systemd units.

We don't want to disable anything at compile time, because ideally the functionality should all be available in Ubuntu, just not on the default images.

Thanks for the feedback, the desktop team is sprinting next week and hopefully we can get some sort of plan solved then!

Feel free to close this issue if you don't think there's anything that can be done on the Flatpak side to help with this.

**Comment by cgwalters** [comment]
> We don't want to disable anything at compile time, because ideally the functionality should all be available in Ubuntu, just not on the default images.

OK; splitting out the systemd units I think is by far the easiest.  Splitting up the shared library would be far, far harder - they're together in the first place because there are some [complicated dependencies](https://github.com/ostreedev/ostree/pull/1566/commits/47655d730727970c3bd04107d103fc5f9581d641) between them.

But, whatever we can do libostree side to help, don't hesitate to ping!

**Comment by smcv** [comment]
> OK; splitting out the systemd units I think is by far the easiest

Until recently, they weren't shipped in Debian/Ubuntu at all, so it would have been hard to distribute them. They are now (currently only in Debian experimental, but about to be in unstable) shipped in the separate `ostree-boot` binary package (subpackage, in RPM jargon). 

The ostree(1) CLI tool is in the `ostree` binary package, which is required by flatpak-builder and by flatpak's installed-tests, but is not required by flatpak itself.

**Comment by mwleeds** [comment]
Looks like [they decided not to bring libflatpak into main](https://bugs.launchpad.net/ubuntu/+source/flatpak/+bug/1812456/comments/6). And since there doesn't seem to be any action needed on the flatpak side, closing this.
