### ISSUE TITLE
flatpak package not found on buster-backports for debian jessie

### ISSUE THREAD

**Issue by jrsanchezalcala** [flatpak/flatpak#3098]
## Linux distribution and version
Debian Jessie

## Flatpak version
Last version

## Description of the problem
flatpak package is not in 
deb http://deb.debian.org/debian buster-backports main
just as you said for install in debian jessie 

## Steps to reproduce
add "deb http://deb.debian.org/debian buster-backports main" in /etc/apt/sources.list
do "apt-get update"
do "apt-cache search flatpak"

**Comment by aiamuzz** [comment]
> Set in sources.list
> deb http://ftp.es.debian.org/debian/ stretch-backports main
> 
> `apt-get update`
> 
> Now i could find flatpak but when install there are so many depencies to install and the install do not end
> 
> `apt-get install flatpak`

If i am not wrong you should mention the backport repo name in your install commant with the `-t` flag ...

so say if you are installing from a repo other than the default one your command ...

`sudo apt-get install flatpak`

will become ... `sudo apt-get -t specific-repo-you-want install flatpak` ... as in your case the specific-repo-you-want to use is `stretch-backports` ... or for that matter `jessie-backports` as @mwleeds ... has specified ... your install command will become 

```
sudo apt-get -t jessie-backports install flatpak
sudo apt-get -t stretch-backports install flatpak
```

**Comment by carlo-strata** [comment]
> Flatpak is not in buster-backports according to https://packages.debian.org/search?keywords=flatpak

But 1.2.4 is too old because after a classic update command:
`flatpak update`

I get:
`Note that the directory`
`/root/.local/share/flatpak/exports/share`

`is not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.`

`Looking for updates…`

`        ID                                           Arch              Branch           Remote            Download`
 `1.     org.freedesktop.Platform.openh264            x86_64            19.08            flathub           < 593,4 kB`

`Proceed with these changes to the Default system installation? [Y/n]: Y`
`Warning: org.freedesktop.Platform.openh264 needs a later flatpak version`
`Installation complete.`

**needs a later flatpak version** ==> I guess 1.4.2 at least!

Some debian policy have to flex, to bend in front of this needs. At least at "*-backports" repositories!!! Otherwise security fall down brutally.

Have not?

I think this issue had not to be closed at all! Please reopen!

Have a nice eventing,
Carlo
