### ISSUE TITLE
Uncomplete download when update

### ISSUE THREAD

**Issue by olmouneu** [flatpak/flatpak#3102]
## Linux distribution and version
Linux 4.19.0-5-amd64
Debian Buster 10.1
## Flatpak version
Flatpak 1.2.4
## Description of the problem
When I execute Flatpak update command, the download of new updates never reach
![flatpak_strange](https://user-images.githubusercontent.com/48359058/64878731-7b8dd380-d654-11e9-9e1b-704d5c7f2bc3.png)
 the update size. However, the update work well.

**Comment by mwleeds** [comment]
This is because when Flatpak discovers that it already has some of the needed files (because they're shared by something that's already installed) it doesn't download them. So the actual downloaded amount ends up being less than the full amount that would be downloaded if you didn't have any of the relevant files locally.
