### ISSUE TITLE
Can't grant access to a filesystem directory that doesn't exist yet

### ISSUE THREAD

**Issue by hufman** [flatpak/flatpak#316]
I am working on building a Flatpak that contains a game, and this game wants to put save files in a subdirectory of the user's home directory: For example, ~/.gamename/savegame1

If I add `--filesystem=~/.gamename` to the flatpak-build-finish command, or the equivalent to flatpak-run or the metadata, the file is successfully created and persisted *if ~/.gamename already exists*. If the directory does not already exist, the game happily creates a temporary sandbox directory that disappears when the Flatpak exits, and any save games are lost. The game doesn't need access to the rest of the user's home directory, so it seems wrong to set `--filesystem=home`.

Is there any advice about how to work around this? Somehow pre-create the directories before entering the sandbox?

**Comment by alexlarsson** [comment]
Hmm, tricky. In *general* we don't want to always create the target directory, because we want to allow optional dirs, but the actual bind-mount of the directory can only happen at sandbox launch time. 

Anyway, for your particular case I think the easiest solution is to us "--persist=.gamename" instead.
This will create a ~/.gamename in the sandbox which actually stores the data in ~/.var/app/$appid/.gamename.

**Comment by hufman** [comment]
I was hoping there is a way to have the persisted directory more visible to the user, and hopefully to use existing save games if they have previously manually installed the app. However, I think it should be easy enough to document a way for my users to import existing games.
Thank you!

**Comment by aburgm** [comment]
I encountered the same issue building a flatpak for a (different) game as well. I'm imagining a use-case where people would install the game from their distribution and try out a flatpak every now and then when they need a build from master. I guess my options are:

 * Use `--filesystem=~/.gamename`, in which case the flatpak game files will not be persistent if the directory does not exist already.
 * Use `--persist=.gamename`, in which case the flatpak won't see host game files.
 * Use `--filesystem=~/.gamename` and `--persist=.gamename` in which case flatpak will see host game files if available, otherwise persist them in its own directory. Not bad, but also not ideal in case someone uses a flatpak for a while and then switches to a host version (suddenly all the flatpak game files are no longer available).

There is already a read-only mode that one can specify for the filesystem option (`--filesystem=home` vs. `--filesystem=home:ro`). Would it be possible and/or desirable to add another mode that ensures the directory is created on the host file system before running the flatpak, to get the best of both worlds?
