### ISSUE TITLE
Development DBus interface requires zero byte terminated byte arrays

### ISSUE THREAD

**Issue by muelli** [flatpak/flatpak#319]
It seems to be  a weird thing to require arrays (which presumingly carry their length) and trailing null bytes.
This caused some pain when implementing a DBus client in Python, because it's quite unnatural to append null bytes.  See https://github.com/LEW21/pydbus/issues/25.

Btw, the DBus API doesn't seem to versioned. If that's not intentional, it might be a good idea to take it up.

**Comment by smcv** [comment]
> It seems to be a weird thing to require arrays (which presumingly carry their length) and trailing null bytes

This is the "bytestring" convention that GVariant encourages for use cases where a byte-array represents a string with no embedded `'\0'` but no other constraints (and in particular no guarantee of being UTF-8). If you do this, C clients can get a valid C `const char *` by looking into the payload of the D-Bus message or the GVariant, with no copying; if you don't, they have to use `g_strndup()` or similar, because there is no guarantee that the next byte after the end of the byte-array will be `'\0'`

Unfortunately, lots of data structures in Unix, including filenames and environment variable names and values, are `'\0'`-terminated bytestrings in any or no character set. I assume this is why Flatpak is doing this.

The D-Bus core protocol has adopted this convention for the `LinuxSecurityLabel` value in the hash table returned by `GetConnectionCredentials()`, although the older `GetConnectionSELinuxContext()` method doesn't do it.

**Comment by LEW21** [comment]
Ah, so those strings are sent as "ay", and not as "s"? Then I guess in Python that should be mapped to the "bytes" object, \0 should be automatically appended, and TypeErrors should be thrown when trying to send a "str" object as a bytestring instead of converting it quietly.

Probably it's time to patch pygi's Glib.Variant.

However...

Do you check if the received strings contain trailing '\0', or is it possible to do a nice buffer overflow here?

**Comment by LEW21** [comment]
Looks like [g_variant_get_bytestring()](https://developer.gnome.org/glib/stable/glib-GVariant.html#g-variant-get-bytestring) has added some duct tape to keep us safe here...

"If the array does not end with a nul terminator character, the empty string is returned. For this reason, you can always trust that a non-NULL nul-terminated string will be returned by this function.

If the array contains a nul terminator character somewhere other than the last byte then the returned string is the string, up to the first such nul character.

g_variant_get_fixed_array() should be used instead if the array contains arbitrary data that could not be nul-terminated or could contain nul bytes."

Looks a bit problematic, as if I (the author of the bindings) will decide to always append \0 to bytestrings, then people that want to receive bytestrings containing \0s inside them will be forced to assume that the last byte is trash, and they need to read only len(str)-1 elements.

**Comment by smcv** [comment]
> Ah, so those strings are sent as "ay", and not as "s"? Then I guess in Python that should be mapped to the "bytes" object, \0 should be automatically appended, and TypeErrors should be thrown when trying to send a "str" object as a bytestring instead of converting it quietly.

You can't safely strip or append `\0` in a generic D-Bus binding, because a generic D-Bus binding can't know whether a particular `ay` is a bytestring or an opaque blob of data. I've commented on 
https://github.com/LEW21/pydbus/issues/27 to say so.

I agree with the idea of forcing API users to be explicit about how they want their `str` turned into a byte-array, for example `s.encode('utf-8') + b'\0'` for the bytestring convention.

**Comment by alexlarsson** [comment]
Closing this as its not really a flatpak issue per se, more like a binding issue.
