### ISSUE TITLE
libflatpak creates duplicate mirror and remote refs

### ISSUE THREAD

**Issue by mwleeds** [flatpak/flatpak#3215]
## Linux distribution and version
Endless OS 3.8.0~191104-230107 (development)
## Flatpak version
1.5.0
## Ostree version
2019.3
## Description of the problem
`flatpak_installation_install_full()` creates entries in both `refs/remotes/` and `refs/mirrors/` for the app being installed. One known consequence of this is that upon uninstall, only the remote ref is deleted (and the deploy ref) but not the mirror ref, so the disk space is not reclaimed during the prune.

The current thinking by @ramcq and I is that this happens because Flatpak uses OSTREE_REPO_PULL_FLAGS_MIRROR for some pulls and not others, but it needs further investigation. My theory is this may have been introduced by https://github.com/flatpak/flatpak/pull/2705/

## Steps to reproduce
Ensure you have a flathub remote configured in your user installation and it has a collection ID:
```
$ flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
$ flatpak --user remote-modify --collection-id=org.flathub.Stable flathub
```
Run this python script:
```
#!/usr/bin/env python3

from gi import require_version
require_version('Flatpak', '1.0')
from gi.repository import Flatpak

inst = Flatpak.Installation.new_user()
inst.install_full(flags=Flatpak.InstallFlags.NONE, remote_name="flathub", kind=Flatpak.RefKind.APP, name="org.gnome.Chess", arch="x86_64",branch="stable",subpaths=None)
```

Note the duplicate refs:
```
$ cat ~/.local/share/flatpak/repo/refs/remotes/flathub/app/org.gnome.Chess/x86_64/stable 
a4aca2424f05df85b862ea2dfb853aca9e9bda974e6a80ab9fde9b63885405d2
$ cat ~/.local/share/flatpak/repo/refs/mirrors/org.flathub.Stable/app/org.gnome.Chess/x86_64/stable 
a4aca2424f05df85b862ea2dfb853aca9e9bda974e6a80ab9fde9b63885405d2
```
Uninstall and note the leftover mirror ref:
```
$ flatpak --user uninstall org.gnome.Chess


        ID                      Branch
 1. [-] org.gnome.Chess         stable

Uninstall complete.

$ cat ~/.local/share/flatpak/repo/refs/remotes/flathub/app/org.gnome.Chess/x86_64/stable 
cat: /sysroot/home/mwleeds/.local/share/flatpak/repo/refs/remotes/flathub/app/org.gnome.Chess/x86_64/stable: No such file or directory
$ cat ~/.local/share/flatpak/repo/refs/mirrors/org.flathub.Stable/app/org.gnome.Chess/x86_64/stable 
a4aca2424f05df85b862ea2dfb853aca9e9bda974e6a80ab9fde9b63885405d2
```

This is not reproducible when the CLI `flatpak install ...` is used.

**Comment by ramcq** [comment]
I think there is also a separate, related bug that needs to be considered in the case two refs exist already - for instance as the after-effects of upgrading a system that already has this bug. OSTree has separate APIs for looking for either remote or mirror refs, but Flatpak searches through both of them for matching collection refs, if there is a duplicate it will only normally find one of the duplicated pair, and presumably when this bug is fixed, will write to one of them - hopefully the same one. But we should probably remove the duplicated/shadowed one if we detect this situation, otherwise we will only prevent this bug for new users, but not recover the disk space for already affected users.

**Comment by ramcq** [comment]
Flatpak calls versions of ostree_repo_pull functions 6 times during the flatpak_installation_install_full operation. MIRROR is not used other than in combination with COMMIT_ONLY, so no mirrors/ ref is written. However, inspecting the refs after each operation suggests that a normal ostree pull with no MIRROR flag is creating /both/ remotes/ and mirrors/ refs.

**Comment by ramcq** [comment]
It looks like the call to repo_pull in flatpak_dir_setup_extra_data adds the non-collection ref to the transaction as a side-effect of being called without the MIRROR flag. This is also happening to ostree-metadata, because _flatpak_dir_fetch_remote_state_metadata_branch sets FLATPAK_PULL_FLAGS_DOWNLOAD_EXTRA_DATA when doing the metadata pull.

**Comment by ramcq** [comment]
Strawman fix at https://github.com/flatpak/flatpak/pull/3220 to go "all mirror". Maybe we need a separate ticket for what to do when we /do/ have the cloned/replicated refs.

**Comment by mwleeds** [comment]
This was fixed by https://github.com/flatpak/flatpak/commit/13366524d82af14ad35fa4618ccf202ece1adacc
