### ISSUE TITLE
Requirements for WebKit flatpak-spawn sandbox

### ISSUE THREAD

**Issue by TingPing** [flatpak/flatpak#3241]
WebKitGTK added support for a `flatpak-spawn` backed sandbox but it was removed because it didn't expose enough options for us. This is just a list of some changes we would like:

- `--sandbox` is all or nothing

  In the end we just used `--no-network` which is a good start but we would like that to be expanded so for example we can selectively disable DBus access and remove all host filesystem access but keep Wayland access.

  Something as simple as `--no-filesystem` and `--no-dbus` might do; We currently pass through pulseaudio, wayland, and dri so ideally not a single other permission is exposed in the end. Maybe the reverse approach of `--sandbox --socket=wayland` makes more sense.

- `--sandbox-expose` is too limiting

  We expose API allowing applications to mount any path in the sandbox and requiring all files be in a specific directory is not useful for us.

  I realize this is tricky but we need the ability to mount any path in the current sandbox (including inside `/tmp` for example) into the newly made sandbox.

**Comment by alexlarsson** [comment]
@TingPing So, the approach I was thinking was to start with --sandbox and then add in stuff you want, like files or sockets, etc. The reason for this is that its tricky to reason about what happens if you take "whatever flatpak switches the caller had" and want to add some "remove this or that permission". Its much easier to start from a known setup and punch holes in that.

So, I would prefer if you used --sandbox, and then we'd add flags for: wayland, x11, dri, pulseaudio, session-bus (with default/no filter rules), as well as allow paths to be mounted from the original sandbox (probably passed by O_PATH fds, not by pathname to ensure you have access to them). Would that work for you?

**Comment by TingPing** [comment]
> So, I would prefer if you used --sandbox, and then we'd add flags for: wayland, x11, dri, pulseaudio, session-bus (with default/no filter rules), 

Perfect.

> allow paths to be mounted from the original sandbox (probably passed by O_PATH fds, not by pathname to ensure you have access to them)

That sounds like it will complicate things a bit (blocking IO) but should cover what we need.

**Comment by alexlarsson** [comment]
For the dbus access, do you want access to the main app? i.e. if the spawning app is org.foo.bar, should the sandbox be able to own and talk to org.foo.bar.*-

**Comment by alexlarsson** [comment]
Also, what about a11y?

**Comment by TingPing** [comment]
For DBus we only want access to `org.freedesktop.portal.Desktop` and the normal `a11y` bus.
