### ISSUE TITLE
Manage /run/host/share centrally

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/flatpak#3245]
It seems, we leave it up to individual runtimes to add that location to XDG_DATA_DIRS. As a consequence, the fedora runtime is missing it. Just as we handle font setup inside flatpak, we could handle this centrally, instead of letting each runtime fend for itself.

Once we do that, we should also consider adding ~/.local/share as well, to pick up HOME-installed icon themes alongside system-installed ones.

**Comment by alexlarsson** [comment]
I don't think we should generally be in the business of setting env vars, because doing so might conflict with the wishes of the runtime, like where it wants to put its fonts, or in the case of fontconfig configuration it depends on what version of fontconfig is in the runtime, etc. 

The particular case of /run/host is a *bit* different because its actually set up by flatpak itself and not the flatpak, but I think the boat sailed for this anyway, for a runtime to work with old flatpak releases it has to set XDG_DATA_DIRS anyway, so imho changing it at this point is not very useful.
