### ISSUE TITLE
"error: Invalid group" when primary group is "10001"

### ISSUE THREAD

**Issue by Djiock** [flatpak/flatpak#3416]
## Linux distribution and version
Debian 10.3 "Buster"
## Flatpak version
1.2.5
## Description of the problem
The apps are installing and are visible in my Gnome applications list but nothing happens when I click on it.
Trying in terminal gives : "error: Invalid group: 10001". Same with 2 differents app.
This group is the primary of every user we have in my company and comes from our LDAP. Don't see why it should be invalid, we never had any issue with the use of this group.
## Steps to reproduce
Install an app, user having primary group "10001", launch with "flatpak run"

**Comment by alexlarsson** [comment]
Can you paste the output of "flatpak run -v -v .,..", that might help show where the warning comes from.

**Comment by Djiock** [comment]
Hi ! Thank you for your answer ! Here goes :

```
flatpak run -v io.atom.Atom
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/julien.negros/.local/share/flatpak
F: Opening user flatpak installation at path /home/julien.negros/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/julien.negros/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
error: Invalid group: 10001
```

I assumed the "-v" two times was a typo since only one gives the same output.

**Comment by smcv** [comment]
What does

```
getent group 10001 || echo $?
```

say? (You can censor the list of users in the group, I mostly want to know whether it succeeds, and if not, what error messages you get.)

**Comment by Djiock** [comment]
This command returns
`2`
:confused:

**Comment by smcv** [comment]
Right, thanks, that's the information I was looking for.

So: the issue here is that your primary group ID does not exist in the system group database - it's just an opaque number, with no name or other group information associated with it. This is not a great idea for the same reasons that we have login names and DNS names, rather than just uids and IP addresses.

Unix systems let you do this, because many aspects of group semantics on Unix systems are bizarre, but it would probably be a good idea to fix that. If nothing else, it would let `ls` show your files as owned by `djiock:yourcompany` rather than `djiock:10001`.

However, there doesn't seem to be any real reason why Flatpak *needs* to copy the name of your primary group into the container: if your primary group is nameless outside the container, clearly that's working well enough for you that you haven't had a problem with it so far, so it might as well be nameless inside the container as well. I think I can see where to patch that, and I'll send a pull request soon.

**Comment by makzef** [comment]
Hi, how to fix this thing?  
Have similar problem, flatpak installed but not start, in terminal got `error: Invalid group: 10000`

**Comment by Djiock** [comment]
Well I didn't answer since @alexlarsson closed this issue but he was right : my group didn't exists and that was the problem. I changed my primary group as one that does exist and that was it.
