### ISSUE TITLE
fallback-wayland

### ISSUE THREAD

**Issue by jurf** [flatpak/flatpak#3467]
There are now Wayland-only setups in the wild (see flathub/org.musescore.MuseScore#52). Qt apps currently have an opposite situation to GTK apps – X11 still preferred (due to some rough edges of the Wayland backend), but Wayland now usable as a backup option. A `--socket=fallback-wayland` would be useful in these scenarios, until the transition to Wayland becomes complete.

**Comment by alexlarsson** [comment]
The reason for fallback-x11 is that if you grant x11 access you're basically neutering sandboxing. So, if you use fallback-x11 you can be "secure" on wayland system while still working on X11.

However, this would not be the case in the prefer-x11 case, so rather than adding more permissions to maintain forever this should be easily handled in the app itself.

**Comment by jurf** [comment]
I guess it could be easily handled in the app, but I am somehow missing a straightforward way to do this from a Flatpak maintainer point of view.

**Comment by TingPing** [comment]
Its really a discussion for Qt.
