### ISSUE TITLE
Cannot install apps. -  Error: Failed to read commit

### ISSUE THREAD

**Issue by arun54321** [flatpak/flatpak#3479]
## Cannot install apps

```
flatpak install com.discordapp.Discord                                                                                       [11:41:14]
Looking for matches…
Remotes found with refs similar to ‘com.discordapp.Discord’:

   1) ‘flathub’ (system)
   2) ‘flathub’ (user)

Which do you want to use (0 to abort)? [0-2]: 2
Required runtime for com.discordapp.Discord/x86_64/stable (runtime/org.freedesktop.Platform/x86_64/19.08) found in remote flathub
Do you want to install it? [Y/n]: 

com.discordapp.Discord permissions:
    ipc            network       pulseaudio      x11      devices      file access [1]      dbus access [2]
    tags [3]

    [1] xdg-download, xdg-pictures:ro, xdg-videos:ro
    [2] org.freedesktop.Notifications, org.freedesktop.portal.Fcitx, org.kde.StatusNotifierWatcher
    [3] proprietary


        ID                                Branch          Op          Remote           Download
 1. [✗] org.freedesktop.Platform          19.08           i           flathub             1.0 kB / 238.2 MB
 2. [ ] com.discordapp.Discord            stable          i           flathub          < 69.8 MB

Error: Failed to read commit 3df64a7c249c10d57f920728e03f6e749491f5ab9ecc2d5e8ecdb0fc0a5d92c1: No such metadata object 459a811e4a019a5e022aeb213cef43c5d54c811c10c34c5a8c5cac5ec78bffca.dirtree
error: Failed to install org.freedesktop.Platform: Failed to read commit 3df64a7c249c10d57f920728e03f6e749491f5ab9ecc2d5e8ecdb0fc0a5d92c1: No such metadata object 459a811e4a019a5e022aeb213cef43c5d54c811c10c34c5a8c5cac5ec78bffca.dirtree
```

**Comment by arun54321** [comment]
Running `sudo flatpak repair` doesn't fix it.

**Comment by javashin** [comment]
hi same problem here in gentoo

**Comment by arun54321** [comment]
Temporary fix - run `flatpak repair --user `

It looks like it can't resume interrupted downloads.

**Comment by DanielVenturini** [comment]
Thanks, @javashin. It works.

**Comment by LargePrime** [comment]
@arun54321
thanks fixed me too

**Comment by winkdong** [comment]
@arun54321 Thanks, bro! `flatpak repair --user` Fixed my issue on Clear Linux while installing Scribus Flatpak

**Comment by Memorytaco** [comment]
`flatpak repair --user` should work.

**Comment by TheJackiMonster** [comment]
I had a similar issue with org.freedesktop.Sdk.Extension.texlive:
```
Error: Failed to read commit c7958d966cfa8b80a42877d1d6124831d7807f93c89461a2a586956aa28d438a: No such metadata object 8bdaa943b957f3cf14d19301c59c7eec076e57389e0fbb3ef5d30082e47a178f.dirtree
error: Failed to install org.freedesktop.Sdk.Extension.texlive: Failed to read commit c7958d966cfa8b80a42877d1d6124831d7807f93c89461a2a586956aa28d438a: No such metadata object 8bdaa943b957f3cf14d19301c59c7eec076e57389e0fbb3ef5d30082e47a178f.dirtree
```

`flatpak repair --user` fixed it but I assume it would be much better if that could trigger automatically by a failing installation like this or if it will at least be provided as option as potential fix in the dialog.

**Comment by mwleeds** [comment]
I did some digging and figured out a few things but haven't quite found the bug:

- on the code path where libostree decides to fetch static delta parts, it fetches the `.commit` and `.commitmeta` objects into a staging dir in `~/.local/share/flatpak/repo/tmp/staging-...`
- if the download of one of the static delta parts is interrupted, and we hit the error code path where the transaction is aborted, the staging dir will still have those two objects (and possibly others)
- the next time the installation is attempted, `ostree_repo_pull_with_options` will complete with a success return value, and the `.commit` and `.commitmeta` objects will be copied to the main repo from the staging dir, and the `refs/remotes/app/...` file will point to the commit, despite the pull not actually being successful
- in `flatpak_dir_deploy()`, we call `ostree_repo_read_commit()` and discover that the commit is not actually complete, that's where the `Failed to read commit ...` error message comes from.
- it's possible to "reset" back to the state where the install will try again rather than fail every time by deleting the remote ref file and the commit and commitmeta objects from the local repo
- so it seems like there's a bug in libostree where it considers a commit object in its staging dir complete and pulls it into the main local repo even if it's not

**Comment by mwleeds** [comment]
Haven't tested it yet but I think the patch will be just adding a `ostree_repo_mark_commit_partial()` call in `process_one_static_delta()` to match the one we have in `meta_fetch_on_complete()`

**Comment by caio-vinicius** [comment]
flatpak repair
flatpak reapir --user
sudo flatpak repair
sudo flatpak reapir --user

Did not work. I had to rm -rf /var/lib/flatpak and now it's working.

**Comment by LargePrime** [comment]
flatpak reapir --user is spelling error, no?
