### ISSUE TITLE
Need udev example script to replace auto-finding sideload repos

### ISSUE THREAD

**Issue by alexlarsson** [flatpak/flatpak#3490]
The previous p2p support probed all mounts for usb drives with sideload repos for each time you called it. We don't do that anymore, instead we have a global option for these repos.

It would be good to ship at least an example udev-using script to update the config as usb sticks are inserted.

**Comment by alexlarsson** [comment]
To make this easier we should probably switch from the xa.sideload-repos option to a sideload.d directory of symlinks, ideally one that persists in /etc/ and one for dynamic stuff in /run/

**Comment by mwleeds** [comment]
> To make this easier we should probably switch from the xa.sideload-repos option to a sideload.d directory of symlinks, ideally one that persists in /etc/ and one for dynamic stuff in /run/

Just a note for posterity that the way this was implemented is to support the `sideload-repos` subdirectory of the installation directory (e.g. `/var/lib/flatpak/sideload-repos` for the system installation) as well as `/run/flatpak/sideload-repos` which is cleared on reboot and overridable with the `FLATPAK_RUN_DIR` environment variable.

**Comment by mwleeds** [comment]
I don't think it's possible to do this cleanly with a udev rule, since there is no way to easily access the mount point (only the device like `/dev/sdb`). Udisks is responsible for mounting hot-plugged USB devices, so perhaps there's some way to get the information from there and do it as a system service.

**Comment by mwleeds** [comment]
WIP for this using systemd is here: https://github.com/mwleeds/flatpak/tree/auto-add-sideloads

One complication is to be compatible with `flatpak create-usb`, we have to check the paths `.ostree/repo`, `ostree/repo`, and all the directories under `.ostree/repos.d/` under each sideload-repo directory. Alternatively we could do that checking in flatpak rather than the shell script, so the script can just link to the root directory of the USB.

**Comment by mwleeds** [comment]
Another way to implement this would be a small daemon that uses GVolumeMonitor and keeps `/run/flatpak/sideload-repos` up to date, but I like the systemd way better. It does have the disadvantage that since different distributions mount hot-plugged drives at different locations, that path (`/run/media/` or `/media/` usually) will have to be specified at compile time.
