### ISSUE TITLE
Suddenly none of installed flatpaks can be found in the "remote flathub"

### ISSUE THREAD

**Issue by dln949** [flatpak/flatpak#3656]
Ubuntu 18.04.2
gnome shell 3.28.4
flatpak 1.7.2

Yesterday, I was able to run the command   flatpak update  with no problem, everything worked normally, no error messages, etc.  

Today, when I run   flatpak update   , I get an error message for each flatpak app I have installed.  I show only one here as an example:  

F: Warning: Treating remote fetch error as non-fatal since app/org.audacityteam.Audacity/x86_64/stable is already installed: No such ref 'app/org.audacityteam.Audacity/x86_64/stable' in remote flathub

I don't know what this cryptic message is trying to tell me, nor what I should do.  

In case it matters, the output of   flatpak remotes   is this:  

Name               Options
flathub              system
gnome              system
almond-origin   system,no-enumerate

**Comment by barthalion** [comment]
Does it still happen? It was CDN misconfiguration; it's fixed since few hours now though.

**Comment by dln949** [comment]
Thanks, you are correct, I was attempting this earlier today.  Now when I try it, it works.  

Incidentally:  What is "CDN"?  Is that some kind of flatpak thing?  I don't see that when I look in any of the flatpak documentation.  And - Who are the people responsible for configuring it?

**Comment by axelsimon** [comment]
@dln949 Just so you have the answer, a CDN is a Content Distribution Network, it's a way of using servers spread around the world to deliver bits to people, and usually works by having one common name like "flatpak.cdncompany.com" but actually resolving to different servers depending on where you make the request from. It will resolve to a server close to you, so that it comes faster and costs less, in the end, to move the bits around.

It's essentially a way of keeping many copies of stuff (_aka_ a cache) close to users, but keeping things simple by always requesting the stuff from the same name.

It's not at all a Flatpak-specific thing, if you look at the source of many, many web pages, you'll see they call stuff from a CDN. For instance, github.com calls things from githubassets.com, many site use Amazon Web Services' Cloudfront, etc..
