### ISSUE TITLE
[Ubuntu bionic PPA] Please update bubblewrap

### ISSUE THREAD

**Issue by philn** [flatpak/flatpak#3707]
I know this is not the right bug-tracker for this issue, but I couldn't find where to report issues for the Ubuntu PPA. My apologies :)

Would it be possible to update bwrap through your PPA? In bionic flatpak calls bwrap with the `--ro-bind-try` option (`--ro-bind-try /proc/self/ns/user /run/.userns`), but it's not available in bwrap 0.2.1.

**Comment by philn** [comment]
This is happening because I have a custom bwrap "wrapper" set via the `$FLATPAK_BWRAP` env var. That wrapper calls `bwrap`, but if i make it call `/usr/libexec/flatpak-bwrap` instead, it works.

**Comment by alexlarsson** [comment]
I don't understand the problem. Flatpak in the ppa is built to use the flatpak-specific bwrap which is new enough to work. If you want to use the (undocumented, used-for-tests) option FLATPAK_BWRAP to point it at a know old version, then it obviously will not work, but why would you want to do that?

I have no interest in updating the system-wide bwrap packege in the ppa, because the is just going to increase the chances of the ppa accidentally affecting something else. The choice to bundle a flatpak-specific bwrap was very much intentional.
