### ISSUE TITLE
Implement gamepad permission so it doesn't need device=all

### ISSUE THREAD

**Issue by monterrr** [flatpak/flatpak#3725]
## Linux distribution and version
Fedora 32

## Flatpak version
flatpak-1.6.4

## Description of the problem
Flatpak should have a permission for gamepad controllers.

## Steps to reproduce
Don't use device=all and an usb gamepad won't work.

**Comment by alexlarsson** [comment]
This is not technically possible (due to details of the dynamic nature of joystick device nodes), but also not how we generally want to move forward with sandboxing. We want static permissions to not be used unless absolutely necessary, and instead use portals for granting device access interactively as needed.

For gamepads, i think the current plan in wayland is to route joypad events via wayland so that e.g. the window focus can limit what apps get events. @hadess would know the details better here though.

**Comment by hadess** [comment]
The wayland protocols was implemented in mutter/gnome-shell by @garnacho (I can't find the branch anymore, did it get merged?). I was planning on writing the GTK side of it, but never did...
