### ISSUE TITLE
.flatpak and .flatpakref file endings look odd

### ISSUE THREAD

**Issue by allanday** [flatpak/flatpak#375]
Most file endings are three letters and I think that's what people are used to. .flatpak and .flatpakref therefore look a bit strange and out of place. I can imagine that a lot users will find them odd and possibly confusing.

**Comment by allanday** [comment]
The other thing that bothers me about the current file endings is how they expose implementation details to the user. First they expose the concept of "flatpak" - users often won't know what flatpak is; you certainly can't expect them to know what it is. Then "ref" is exposed which is a bit technical and non-obvious.

If you want to avoid that there's probably two options:

 1. Meaningful file endings, like .app and .repo.
 2. Completely obscure file endings. For example: no one knows what .exe literally means, but it doesn't matter.

**Comment by alexlarsson** [comment]
".app" and ".repo" are very broad though, and will probably conflict with exsting use.
We could use 3-letter short forms maybe: .fpa .fpr

**Comment by ebassi** [comment]
Some TLA acronym proposals:

 * `.fab` — flatpak app bundle (i.e. `.flatpak`)
 * `.far` — flatpak app ref (i.e. `.flatpakref`)
 * `.fpr` — flatpak repo (i.e. `.flatpakrepo`)

I'm purposefully avoiding `.fap` for flatpak app repo, because this is not 4chan.

**Comment by alexander255** [comment]
@allanday 

 1. I agree, but, as was mentioned, these are already taken
 2. `.exe` isn't "obscure" at all: It means *executable* (=thing that can be run), no less and definitely no more

@ebassi: I know, I'm just complaining now, but none of these endings convey much meaning and they are kind of hard to tell apart. (To me as random person who happened to stumble upon this issue, at least.)

I therefor propose this instead:

 * `.pak` –– Flatpak app bundle
 * `.pak-ref` –– Flatpak app reference
 * `.pak-repo` –– Flatpak repository

All of these are reasonably short and, unlike previous proposals, at least convey the basic idea of *this is some kind of package*. Now, I know that `.pak` has been used by various games to denote exactly that, but since there never has been anything even remotely similar to a standard for what these files actually contain (hand-crafted data structures, zip files, file system images, …) I'd think it might well be worth it.

This is just Joe Random (who really happens to like FlatPak in general) dumping his opinion on you :wink:. Feel free to disagree/ignore/…

**Comment by allanday** [comment]
> .exe isn't "obscure" at all: It means executable (=thing that can be run), no less and definitely no more

Most people aren't familiar with the word "executable".

There's been some discussion about this issue on the xdg-app mailing list, starting here: https://lists.freedesktop.org/archives/xdg-app/2016-November/000470.html

What I've taken from that discussion:

 * We don't need to limit ourselves to three letters - that's somewhat artificial
 * Single words work well
 * Ideally any words used should be recognisable to users

My latest tentative suggestion was to use .app (.flatpak) .install (.flatpakref) and .repo/.repository
(.flatpakrepo).

**Comment by ebassi** [comment]
Just for the record: my suggestions for TLAs do not imply endorsement. I agree with @allanday that words, instead of acronyms/abbreviations, make for a better extension.

**Comment by alexlarsson** [comment]
So, I've been considering this and following the discussion. I like that the names are full and unique names, and while I agree that especially .flatpakref is a bit of a leak of the internals, its not really worth to break all the exsting code and deployed repos for this change, which imho should not really be visible to most users in normal use.

So, I'll keep the current extensions.
