### ISSUE TITLE
creating flatpak's for Raspbian?

### ISSUE THREAD

**Issue by The-Alchemist** [flatpak/flatpak#382]
I'm interested in using flatpak's for my Raspberry Pi / Raspbian projects.

Because it's a fairly limited embedded device, I'm not that interested in the sandbox portion of it and could easily do without it.  Which should make supporting Raspbian easier, should it not?

Is this even worth pursuing, or do you guys think I'm barking up the wrong tree and should just stick to distributing .deb's?

**Comment by alexlarsson** [comment]
I don't see what the problem would be, its just an arm build, no? We already have working arm builds of flatpak...

**Comment by directhex** [comment]
@alexlarsson which ARM target? Raspbian has an unusual target of ARMv6 hard float (because the Pi 1 has a v6-only CPU), whereas most distributions target ARMv7 for hard float

**Comment by alexlarsson** [comment]
Yeah, the gnome/freedesktop runtimes are built for armv7, so you couldn't use those builds. So, you'd need a custom built runtime, but that shouldn't need any changes to flatpak itself.

**Comment by directhex** [comment]
Miiiiiiiiiiiiiiiiiiiiiiiiight be worth defining a specific arch name for the Raspbian armv6hf variant? I've had plenty of bug reports over the years against mono-project.com armhf Debian packages throwing SIGILL on Pi, because Raspbian overloads the meaning of Debian's "armhf" architecture rather than define their own

**Comment by refi64** [comment]
The runtimes don't even support armv7 anymore, so I don't think this is relevant.
