### ISSUE TITLE
[Question] Way to sandbox X11 using Flatpak?

### ISSUE THREAD

**Issue by TheEvilSkeleton** [flatpak/flatpak#3833]
Hello, I'm wondering if there is a workaround to sandbox X11 when using Flatpak. I really love Flatpak thanks to the easy sandboxing solution, but not being able to sandbox X11 at all is a very big issue when it comes to privacy.

**Comment by mat8913** [comment]
If you feel like tinkering, xpra has Wayland support now when run with `GDK_BACKEND=wayland`. ie It can act as an x11 server and a Wayland client. My idea is to run the flatpak with `--nosocket=x11 --socket=wayland`, run xpra inside of the sandbox and connect the application to xpra's x11 server.

**Comment by TheEvilSkeleton** [comment]
> run xpra inside of the sandbox and connect the application to xpra's x11 server.

What do you mean by that?

**Comment by mat8913** [comment]
So if you start xpra with `xpra start :11; GDK_BACKEND=wayland xpra attach :11`, then you run the application with `DISPLAY=:11 /path/to/app`. If you do both of these inside the flatpak sandbox, then the sandboxed application wont have access to your outside x11 server.

**Comment by TheEvilSkeleton** [comment]
Can you give me an example? Sorry, it's in my first time hearing about Xpra

**Comment by mat8913** [comment]
In that case, it might be easier to start with something that's known to work: running xpra normally outside the flatpak sandbox. You need two terminal windows. In the first one run `xpra start :11; GDK_BACKEND=wayland xpra attach :11`, and in the second one run `DISPLAY=:11 flatpak run io.freetubeapp.FreeTube`.

The benefit of doing this is that the application connects to Xpra instead of your real x11 server. Xpra translates the x11 commands into Wayland and forwards them to your Wayland compositor. The application wont have access to your clipboard or be able to take screenshots for example.
 
Some notes about this:

- You need a fairly recent version of Xpra installed for this to work
- I just used io.freetubeapp.FreeTube as an example, use any app you like
- The `:11` is also just an example. Change it to whatever number you like (but not `:0` or `:1` since those are probably already taken by your real x11 server). If you want to run multiple applications at the same time, use a different number for each application
- At the end, run `xpra stop :11` to shut down Xpra

**Comment by TheEvilSkeleton** [comment]
I understand now. Thank you so much for the detailed explanation.
