### ISSUE TITLE
Support for initializing a repo on build-import-bundle

### ISSUE THREAD

**Issue by directhex** [flatpak/flatpak#384]
I have physically distinct builders from my download server. My canonical build output is bundles (as these are easily shared in CI, uploaded to storage, etc).

Right now, you can't use `flatpak build-import-bundle` without a valid repository already in place:

```
error: Opening objects/ directory: openat: No such file or directory
```

There's no obvious way to create an empty repository, without doing an initial build/export on my download server. `ostree init` isn't the right answer, as it causes the following on bundle import:

```
error: Executing delta part 0: opcode open-splice-and-close: opcode open-splice-and-close: Operation not permitted
```

**Comment by alexlarsson** [comment]
The EPERM is because a regular ostree "bare" mode repository stores the file attributes "as themselves" on the file, and the commit contains a file owned by root, so it tries to create a file owned by root => EPERM.

You need to create a repo of "bare-user" (simiular to bare, but writable as a user) or "archive-z2" (gzip:ed files, used for http repos) with `ostree init --mode XXX`.

**Comment by alexlarsson** [comment]
Closing this as @directhex got this working, but we should have better docs for this.
