### ISSUE TITLE
Libgl error with amdgpu

### ISSUE THREAD

**Issue by Starcommander** [flatpak/flatpak#3875]
## Linux distribution and version
Debian GNU/Linux bullseye/sid
## Flatpak version
Flatpak 1.8.2
## Description of the problem
I am using the AMD Radeon 5500 XT graphics card.
On the host system I played a lot of games (alien-isolation,half-life,...) without problems.

There was no driver-installation necessary, just to copy the firmware to /lib/firmware/amdgpu/ on hostsystem.
_Source: git://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git
Doc: https://www.phoronix.com/scan.php?page=news_item&px=Ubuntu-19.10-Radeon-RX-5700_

However, starting a flatpak app that needs GL results into the error message:
```
ppp@ppp-desktop:~/workspace/flatpak$ flatpak run --filesystem=/lib/firmware/amdgpu/ org.supertuxproject.SuperTux
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: MESA-LOADER: failed to open amdgpu (search paths /usr/lib/x86_64-linux-gnu/GL/default/lib/dri)
libGL error: failed to load driver: amdgpu
[WARNING] /run/build/supertux/src/supertux/sector.cpp:227 [levels/misc/menu.stl] Tried spawning Tux in solid matter. Compensating.
```
## Steps to reproduce
Install the same graphics card, install flatpak, install supertux via flatpak, start supertux.

**Comment by nanonyme** [comment]
Any idea which version of Mesa your GPU is supposed to require?

**Comment by Starcommander** [comment]
The output of **glxinfo -B** shows an information about mesa.
Maybe **20.1.7**?
Hope this can help.

**Full output:**

> name of display: :0
> display: :0  screen: 0
> direct rendering: Yes
> Extended renderer info (GLX_MESA_query_renderer):
> .    Vendor: X.Org (0x1002)
> .    Device: Radeon RX 5500 XT (NAVI14, DRM 3.38.0, 5.8.0-1-amd64, LLVM 10.0.1) (0x7340)
> .    Version: 20.1.7
> .    Accelerated: yes
> .    Video memory: 4096MB
> .    Unified memory: no
> .    Preferred profile: core (0x1)
> .    Max core profile version: 4.6
> .    Max compat profile version: 4.6
> .    Max GLES1 profile version: 1.1
> .    Max GLES[23] profile version: 3.2
> Memory info (GL_ATI_meminfo):
> .    VBO free memory - total: 3778 MB, largest block: 3778 MB
> .    VBO free aux. memory - total: 3746 MB, largest block: 3746 MB
> .    Texture free memory - total: 3778 MB, largest block: 3778 MB
> .    Texture free aux. memory - total: 3746 MB, largest block: 3746 MB
> .    Renderbuffer free memory - total: 3778 MB, largest block: 3778 MB
> .    Renderbuffer free aux. memory - total: 3746 MB, largest block: 3746 MB
> Memory info (GL_NVX_gpu_memory_info):
> .    Dedicated video memory: 4096 MB
> .    Total available memory: 8176 MB
> .    Currently available dedicated video memory: 3778 MB
> OpenGL vendor string: X.Org
> OpenGL renderer string: Radeon RX 5500 XT (NAVI14, DRM 3.38.0, 5.8.0-1-amd64, LLVM 10.0.1)
> OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.1.7
> OpenGL core profile shading language version string: 4.60
> OpenGL core profile context flags: (none)
> OpenGL core profile profile mask: core profile
> 
> OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.1.7
> OpenGL shading language version string: 4.60
> OpenGL context flags: (none)
> OpenGL profile mask: compatibility profile
> 
> OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.1.7
> OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

**Comment by LeonXuAMD** [comment]
Hi, @Starcommander 
Any result of this issue?
Per my understanding, Flatpak didn't integrate amdgpu driver support into its package, instead it 
support mesa and nvidia's, like
org.freedesktop.Platform.GL.default, org.freedesktop.Platform.GL.nvidia
May be it is because amd didn't support libglvnd in its GL driver.
i installed a amdgpu-pro driver on the host and wanna to run "flatpak run org.videolan.VLC"
also got the problem.

**Comment by megawattz** [comment]
[This may or may not be relevant,

I was getting this error

``root@dockerbox:/app# blender
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: MESA-LOADER: failed to open amdgpu: /usr/lib/dri/amdgpu_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: amdgpu
libGL error: failed to open /dev/dri/card0: No such file or directory
libGL error: failed to load driver: radeonsi
Saved session recovery to '/tmp/quit.blend'

Blender ran OK on my host (had a different error, which is why I was trying it in a docker container). 

I mounted my host /dev/dri directory into my docker container

` docker run --rm -it -e DISPLAY --network host -v/tmp/.X11-unix:/tmp/.X11-unix -v/dev/dri:/dev/dri blender bash`

And the problem disappeared.

**Comment by Starcommander** [comment]
@megawattz Yes, this was relevant, thanks.
I can run it now using the Flatpak-option: --device=dri
Alternatively i can enable dri using flatseal
I remember, that these options did not help in the past.

**Comment by GammaGames** [comment]
I had this problem on elementary os 8, had to enable GPU acceleration in the app permissions
