### ISSUE TITLE
GTK3 Breeze dark theme doesn't work with Flatpak in KDE Plasma

### ISSUE THREAD

**Issue by tgharib** [flatpak/flatpak#3883]
## Linux distribution and version

Fedora silverblue 33

## Flatpak version

Flatpak 1.8.2

## Description of the problem

As per this [reddit thread](https://old.reddit.com/r/kde/comments/h8sqmg/kde_519_breezedark_missing_gtk3_arch/), KDE Plasma simply uses the vanilla Breeze GTK3 theme and that same theme adjusts to use dark colors when the relevant color setting in System Settings is configured. If I do `flatpak install org.gtk.Gtk3theme.Breeze`, evince uses light colors, which means flatpak doesn't understand that I set my colors to dark. If I do `flatpak install org.gtk.Gtk3theme.Breeze-Dark`, evince still uses light colors because flatpak prefers to use `org.gtk.Gtk3theme.Breeze` since I am technically using the vanilla Breeze theme in KDE Plasma.

The only way to fix this issue by creating the following file `/var/home/owner/.var/app/org.gnome.Evince/config/gtk-3.0/settings.ini` (copied and modified from `~/.config/gtk-3.0/settings.ini`):

```
[Settings]
gtk-application-prefer-dark-theme=true
gtk-button-images=true
gtk-cursor-theme-name=breeze_cursors
gtk-decoration-layout=icon:minimize,maximize,close
gtk-enable-animations=true
gtk-font-name=Sans Serif,  10
gtk-icon-theme-name=breeze-dark
gtk-menu-images=true
gtk-modules=colorreload-gtk-module
gtk-primary-button-warps-slider=false
gtk-theme-name=Breeze-Dark
gtk-toolbar-style=3
```

so that flatpak prefers to use the `Breeze-Dark` theme over `Breeze`.

## Steps to reproduce

1. Use the Breeze Dark Theme in a KDE Plasma desktop.
2. Install a GTK3 flatpak application (e.g. evince).
3. Install either Breeze GTK3 theme or Breeze-Dark GTK3 theme in flatpak or install both of them.
4. No matter what, the GTK3 application will still be light.

**Comment by tgharib** [comment]
It would be nice to able to explicitly set the qt/gtk2/gtk3 themes globally in flatpak so that I don't have to troubleshoot the theme selector. Also, that would also improve the situation in cases where I am using an esoteric theme on my base system that I can't a corresponding flatpak theme for.

**Comment by tgharib** [comment]
I decided to install fedora silverblue from scratch and I couldn't apply the Breeze dark theme. It turns out that evince must be installed from the flathub repos rather than the fedora flatpak repos.

Also, this time around, instead of copying `settings.ini`, I did `flatpak override --system --filesystem=xdg-config/gtk-3.0:ro` and simply modified `~/.config/gtk-3.0/settings.ini` so that it has this line: `gtk-theme-name=Breeze-Dark`.

**Comment by wsdfhjxc** [comment]
Flatpak-packaged applications use Flatpak-packaged GTK themes. By default, the applications are unaware of your regular themes (their content, more precisely) and CSS overrides applied to them (or globally). This behavior can be changed, by allowing per-application (or global) access to  directories containing your regular themes and general GTK-related directories.

The issue here is that, while Breeze Dark is being enabled as a Plasma color scheme, Plasma doesn't update the XSettings GTK theme configuration to point to the Breeze Dark theme. After all, this is correct, because it's not the GTK theme that has changed, it's just the Plasma color scheme, and Flatpak still sees that the regular variant of the Breeze theme should be loaded. So, it's not exactly an issue with Flatpak itself, because resorting to Flatpak-packaged GTK themes is the intended way of handling theming for Flatpak-packaged applications. Flatpak itself just needs to know the name of the GTK theme that should be used.

To address the issue in a Flatpak-intended way, you need to explicitly configure the GTK theme in Plasma's System Settings - Application Style - Configure GNOME/GTK Application Style - select the Breeze Dark theme. Then, the XSettings will be updated so that the GTK theme configuration points to the Breeze Dark theme. To address the issue in a non-preferred, although more compatible way, allow access to the GTK-related directories, so Flatpak can pick up the CSS overrides applied by Plasma to the regular GTK Breeze theme variant (see #3901 for more details). You've chosen a similar approach, but that manual file editing shouldn't be required, as long as the `~/.config/gtk-3.0` directory is accessible (Plasma puts its CSS overrides there).

**Comment by tgharib** [comment]
>To address the issue in a Flatpak-intended way, you need to explicitly configure the GTK theme in Plasma's System Settings - Application Style - Configure GNOME/GTK Application Style - select the Breeze Dark theme.

Okay, done and problem solved.

![image](https://user-images.githubusercontent.com/6457015/97052800-a6cd3c80-154f-11eb-8fdd-95fc86407a15.png)

I could've swore the option for "Breeze Dark" was not an option 3 weeks ago. I'm pretty sure an update changed something. I even had the `breeze-gtk` package (which AFAIK, is the only breeze gtk package available) installed in fedora.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
I am using http://kinoite.fedoraproject.org, which is the counterpart of http://silverblue.fedoraproject.org because instead of containing only the desktop environment of GNOME, it is containing only the desktop environment of KDE Plasma. However, currently, it is without all of the modules that are required for usage of systemsettings5. Consequently, are any terminal alternatives of http://github.com/flatpak/flatpak/issues/3883#issuecomment-715583932 available?
