### ISSUE TITLE
/var/lib/flatpak/repo/objects Folder is taking up almost 12 GBs of space

### ISSUE THREAD

**Issue by egeoz** [flatpak/flatpak#3894]
## Linux distribution and version
Ubuntu 20.10
## Flatpak version
1.8.2
## Description of the problem
After installing about 50ish flatpaks(10.1 GB is taken by runtimes, 7 GB is taken by the apps and 11.8 GB is taken by repo/objects), my remaining disk space was quickly gobbled up by repo/objects folder. If I understand correctly, this folder is unrelated to the runtime and application packages and I could not find much about reducing the size of this folder. So far I have tried;
- sudo flatpak uninstall --unused 
- sudo flatpak repair

## Steps to reproduce
1- Install some Flatpaks.
2- Use Flatpaks for more than an arbitrary time.

[List of installed Flatpaks](https://github.com/flatpak/flatpak/files/5351014/flatpak_list.txt)

**Comment by refi64** [comment]
The runtime and app folders only contain hardlinks to the objects folder,
thus they use no extra space. Given that, it seems like the other numbers
may have been exaggerated a bit due to the hardlink use (the other folders
combined shouldn't use significantly more space than the repo afaik). How
are you measuring?

**Comment by mwleeds** [comment]
This doesn't seem like a bug. If that folder is 12 GB, you have 12 GB of flatpaks installed. The disk space usage can be difficult to measure with some tools because of the hardlinks into that objects folder.
