### ISSUE TITLE
PULSE_SERVER=tcp:... not supported

### ISSUE THREAD

**Issue by alzeih** [flatpak/flatpak#3908]
## Linux distribution and version

Arch Linux rolling

## Flatpak version

Flatpak 1.8.1 
(latest packaged for Arch Linux as of writing)

## Description of the problem

A specific PULSE_SERVER environment variable cannot be set when running a Flatpak.

My PULSE_SERVER environment variable is set on the host as `tcp:X.X.X.X:XXXXX` and also needs to be set to `tcp:X.X.X.X:XXXXX` in the Flatpak, but when I try to run Spotify through Flatpak, sound does not work, and Spotify outputs the error:

`ALSA lib ../../pulse/pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused`

I think it should be possible to set a value for PULSE_SERVER.

## Steps to reproduce

Have Spotify installed:
```
$ flatpak list --user
Name                           Application ID                                Version             Branch
Spotify                        com.spotify.Client                            1.1.42.622          stable
Freedesktop Platform           org.freedesktop.Platform                      19.08.12            19.08
Freedesktop Platform           org.freedesktop.Platform                      20.08.0             20.08
default                        org.freedesktop.Platform.GL.default                               19.08
default                        org.freedesktop.Platform.GL.default                               20.08
openh264                       org.freedesktop.Platform.openh264             2.1.0               2.0
```

Running Spotify in three different ways:

`$ flatpak run --user com.spotify.Client`

`$ flatpak run --user --env=PULSE_SERVER=$PULSE_SERVER com.spotify.Client`

`$  flatpak override --user --env=PULSE_SERVER=$PULSE_SERVER com.spotify.Client`
`$ flatpak override --user --show com.spotify.Client`
`[Environment]`
`PULSE_SERVER=tcp:X.X.X.X:XXXXX`
`$ flatpak run --user com.spotify.Client`

Checking if the PULSE_SERVER environment variable is being set in the above three configurations by using env, e.g.:

`$ flatpak run --user --command=sh com.spotify.Client -c 'env'`

shows much output but no PULSE_SERVER.

The PULSE_SERVER value is a working pulseaudio server, as the following workaround has sound:

`flatpak run --user --env=PULSE_SERVER_FOO=$PULSE_SERVER --command=sh com.spotify.Client -c 'PULSE_SERVER=$PULSE_SERVER_FOO spotify'`

PULSE_SERVER_FOO gets passed through fine, but PULSE_SERVER does not, so I use PULSE_SERVER_FOO instead and then set PULSE_SERVER from that in the Flatpak. However, this seems like a workaround and I think it would be better if the value I set using `flatpak --env` or `flatpak override` was passed through.

A simpler workaround that also works using double quotes is:

`$ flatpak run --user --command=sh com.spotify.Client -c "PULSE_SERVER=$PULSE_SERVER spotify"`

**Comment by nuno-silva** [comment]
I'm experiencing the same issue using
- Flatpak 1.10.0
- com.spotify.Client  1.1.55.498.gf9a83c60

Though in my case it does not show any error, just ignores the env variable.

Thanks for the workaround @alzeih :)

**Comment by egrath** [comment]
It seems that bwrap is stripping some environment variables, even when they are set using a override or specified directly using the <code>--env</code> parameter when running the Flatpak. I had a similar issue with the DISPLAY variable, thanks for pointing out the workaround.

**Comment by smcv** [comment]
This is not bwrap removing environment variables, this is Flatpak rewriting the `PULSE_SERVER` variable specifically. It needs to do this because the `PULSE_SERVER` is typically an `AF_UNIX` socket path, which is a filesystem path, and the filesystem namespace outside the sandbox is not the same as the filesystem namespace inside the sandbox: so any socket that we want the app to be able to access must be made available specifically, and that will often change its path, so we have to change the environment variable to match up with the path inside the sandbox.

It seems that in both the initial issue report and the more recent comments, everyone might have forgotten to highlight the key piece of information making their systems unusual: that you are using a `tcp:` server address to redirect the app's audio to a remote PulseAudio server (in a way that is probably not secure on untrusted networks, but I'll assume you know that and have ensured that everything on your local LAN, including any games consoles, smart fridges, etc., is trusted).

You'll see that `flatpak_run_parse_pulse_server()` says:

```
      /* TODO: Support TCP connections? */
```

and has no further implementation.

The PulseAudio support in that function and `flatpak_run_add_pulseaudio_args()` currently assumes that every PulseAudio server is an `AF_UNIX` socket, so some structural adjustment would be needed to implement support for detecting `tcp:` addresses and passing those through to the app unaltered.

Obviously, this would also only work for apps with `--share=network`, such as Spotify, because if an app cannot access the network then it will definitely be unable to access TCP sockets.

> I had a similar issue with the DISPLAY variable

Similarly, remote X11 (`DISPLAY=othermachine:0`) is not currently supported by `flatpak_run_add_x11_args()`: if the `DISPLAY` is not of the form `:123` then it is specifically unset.
