### ISSUE TITLE
Installed software via flatpak cannot recognize mounted partition

### ISSUE THREAD

**Issue by 3I2vv4n** [flatpak/flatpak#3981]
# Linux distribution and version
Fedora 33 workstation edition (64bit) Gnome 3.38.1

## Flatpak version
Flatpak 1.8.3 

## Description of the problem
Hi, I have been using flatpak recently to install software not available via the DNF method (such as Zotero or Syncthing-gtk, for instance). All software install via flatpak is working correctly. However, there is a detail that is to be very striking. 

I have my hard disk partitioned, to make it brief: partitions for windows, partitions for fedora, one partition for storing my data (documents, photo, etc.). I have been aware that software installed via flatpak cannot access the data partition (/mnt/Data). I can bypass this problem on some software, such as Syncthing-gtlk: I copy the path and past it in the corresponding line instead of using the 'browse' option. However, this bypassing does not work for all, as in Zotero: the software cannot reach my bibliography located in the Data partition. 

Do you know if it is due to some flatpak options?

## Steps to reproduce
none?

**Comment by X-m7** [comment]
The difference is due to the permissions set when building the flatpaks; [syncthing](https://github.com/flathub/me.kozec.syncthingtk/blob/master/me.kozec.syncthingtk.yaml) is set to have access to most of the host filesystem, while [Zotero](https://github.com/flathub/org.zotero.Zotero/blob/master/org.zotero.Zotero.json) only has access to your home folder, along with wherever your Documents, Downloads and Desktop folders point to.

To check the permissions of a flatpak, you can use the command `flatpak info --show-permissions name.of.app`, and to change them you can use `flatpak override`. Say for example you want to give Zotero permission to access your `/mnt/Data` folder, for that you can use `flatpak override --filesystem=/mnt/Data org.zotero.Zotero`. Alternatively, you can just use [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal) instead.

**Comment by 3I2vv4n** [comment]
This is great, it worked perfectly. Thank you very much. Cheers

**Comment by hfiguiere** [comment]
question resolved it seems.
