### ISSUE TITLE
Tilde~ not converted into $HOME

### ISSUE THREAD

**Issue by aleixpol** [flatpak/flatpak#401]
```
$ flatpak remote-add kdelocal `pwd`/repo --gpg-import=~/kdeflatpak.gpg
error: The file ~/kdeflatpak.gpg specified for --gpg-import was not found: Error opening file /home/apol/tmp/flatpak-kde-runtime/~/kdeflatpak.gpg: No such file or directory
```

**Comment by alexlarsson** [comment]
Hmm, tildes are typically expanded by the shell, so apps don't even see them. I guess this is not actually true unless the tilde is the first element in an argument though:

```
$ echo ~/foo --bar=~/foo
/home/alex/foo --bar=~/foo
```

I somewhat dislike doing magic parsing of ~ in the app, because that means we can never handle files that actually have tildes in them (no way to escape the magic). Maybe that is not a huge deal for the particular case of gpg key files though...

**Comment by TingPing** [comment]
I had the same problem myself: #197

**Comment by matthiasclasen** [comment]
I would say this is not  bug, just the way unix commandlines work
