### ISSUE TITLE
Regression: Cython installation fails on runtime 3.38 (works on 3.36)

### ISSUE THREAD

**Issue by leinardi** [flatpak/flatpak#4020]
## Linux distribution and version
```
Distro: Ubuntu 20.10 (Groovy Gorilla) 
Kernel: 5.8.0-31-generic x86_64
```
  
## Flatpak version
```
$ flatpak --version
Flatpak 1.8.2
```

## Description of the problem
After switching form  runtime-version 3.36 to 3.38, the Cython dependency installation fails with the following error:
```
========================================================================
Building module python3-Cython in /home/leinardi/Workspace/gitlab/gkraken/.flatpak-builder/build/python3-Cython-4
========================================================================
Running: pip3 install --exists-action=i --no-index --find-links="file://${PWD}" --prefix=${FLATPAK_DEST} Cython==0.29.20
Looking in links: file:///run/build/python3-Cython
Processing ./Cython-0.29.20.tar.gz
Building wheels for collected packages: Cython
  Building wheel for Cython (setup.py) ... done
  Created wheel for Cython: filename=Cython-0.29.20-cp38-cp38-linux_x86_64.whl size=5543197 sha256=55e5c3745e51127c5cb5f4267bbc761ae7c00c5a89c19a3a0fb9653aba0c4baa
  Stored in directory: /home/leinardi/.cache/pip/wheels/b7/10/09/e19a2982a363ac4ed9516f7f55e1dc66bb3d76e4453b46b521
Successfully built Cython
Installing collected packages: Cython
  Attempting uninstall: Cython
    Found existing installation: Cython 0.29.21
    Uninstalling Cython-0.29.21:
ERROR: Could not install packages due to an EnvironmentError: [Errno 30] Read-only file system: '/usr/bin/cygdb'

```
## Steps to reproduce

1. Clone https://gitlab.com/leinardi/gkraken:
```
git clone --recurse-submodules -j4 https://gitlab.com/leinardi/gkraken.git
cd gkraken
git checkout cython
```
2. Change the runtime to 3.38 in `./flatpak/com.leinardi.gkraken.json`
3. Run `./build.sh --flatpak-local --flatpak-install --flatpak-bundle`

**Comment by eszlari** [comment]
Try using `setup.py` like openshot:

https://github.com/flathub/org.openshot.OpenShot/blob/3ddf17543d44d95a2c88a01d3142ee386d8f92eb/org.openshot.OpenShot.yaml#L149

(the KDE 5.15 runtime, like the GNOME 3.38 runtime, is based on the freedesktop 20.08 runtime)

**Comment by leinardi** [comment]
Thanks, can't test right now but I'll test in a week or so...

**Comment by cxrvh** [comment]
I don't think this is a regression. The Freedesktop Sdk 20.08 just has changed & now [includes Cython](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/14be3ba67834c1e848b7fa2266c4473a04cba145/NEWS#L171) (currently [0.29.21](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/master/elements/components/cython.bst)). Since your version differs from the provided one, pip3 tries to delete it & fails, an application can't modify the contents of a runtime/sdk.

The build works if you use the provided Cython (by removing it or updating to the same version) or if you add ```--ignore-installed``` (I don't know python so I can't say which version will be used, but this builds Cython into /app). Using the provided one should be the preferred solution if possible.

**Comment by leinardi** [comment]
> The build works if you use the provided Cython (by removing it or updating to the same version)

Hi, I can confirm that removing the dependency completely seems to fix the issue.

Thanks
