### ISSUE TITLE
Flatpak integrity/security robustness

### ISSUE THREAD

**Issue by HulaHoop0** [flatpak/flatpak#4031]
Hi. I am a privacy and security distro maintainer and was wondering if Flatpak accounts for attacks such as stale metadata and other techniques noted here:

https://theupdateframework.io/security/

While the TUF goes beyond widely used app delivery frameworks like apt, I am only interested in how it compares with the ground covered by apt and nothing more.

Please point me to a design document if this is already noted somewhere. TIA

**Comment by alexlarsson** [comment]
Its partially protected against such things. If a user installs or updates a specific app-id the code verifies that:
 * The new app is gpg signed by a trusted key
 * Checksum verifying that all files are untampered with
 * The new app has that app id
 * The new app has a later timestamp on update

Which solves most of the issues. However, there is currently not protection against "Indefinite freeze attacks". I.e. if an attacker can man-in-the-middle the network for a client, he can force a user to not see updates. Of course, most repos like flathub use https, so man-in-the-middleing isn't trivial.

**Comment by tinywrkb** [comment]
The title of this issue is very general while the question in the content is very specific for the delivery and deployment.  
I would like to ask about another aspect regarding the security of this solution.  
In a secure boot fashion, every code is being measured before it being executed to make sure it wasn't changed locally post-deployment.  
Has this been thought about?

**Comment by adrelanos** [comment]
To defend against an `indefinite freeze attack`, flatpak would need to implement something similar to Debian's `valid-until` field. References:

* https://blog.ganneff.de/2008/09/valid-until-field-in-release-f.html
* https://wiki.debian.org/DebianRepository/Format#Date.2C_Valid-Until

> The title of this issue is very general while the question in the content is very specific for the delivery and deployment.
> I would like to ask about another aspect regarding the security of this solution.
> In a secure boot fashion, every code is being measured before it being executed to make sure it wasn't changed locally post-deployment.
> Has this been thought about?

Flatpak is not a Linux distribution. It's called `verified boot`. Some references here:
https://www.whonix.org/wiki/Verified_Boot
If there was a Linux desktop distribution implementing verified boot, they might need some cooperation / API from flatpak.
Either way, I guess it might be best to create a separate ticket for this but I am not a flatpak maintainer to make this call.

**Comment by M-i-k-o-t-o** [comment]
> Its partially protected against such things. If a user installs or updates a specific app-id the code verifies that:
> 
>     * The new app is gpg signed by a trusted key
> 
>     * Checksum verifying that all files are untampered with
> 
>     * The new app has that app id

Please correct me if I misunderstood something but it seems like right now when you are specifying a git dependency you can either specify a specific commit (in which case you run into the danger of depending on old and vulnerable libraries) or specify no commit, in which case someone who has taken control of the domain/account of the person managing the repository could push malicious changes. This could be solved by adding a "signed-by:" field for modules with source-type 'git'.

Also, can you please confirm whether the manifest files themselves are signed?

Apologies for reviving this old issue and for my ignorance, I hope that you don't mind.

**Comment by smcv** [comment]
I suspect that an issue titled "Flatpak integrity/security robustness" is not particularly useful to leave open: to be useful and not just cluttering the issue tracker, issues need to be actionable (there needs to be something that could be done to close the issue). There are lots of things that could be thought of as being something to do with integrity, security or robustness, and if we discussed them all on this issue, it would quickly become unmanageable.

If there is a specific, identifiable thing that is wrong, then *that* makes sense as an issue: for example, "indefinite freeze attacks are not detected" would be an actionable issue report. (I say "detected" rather than "prevented" because an attacker with sufficient control over the network path between client and server is always going to be able to prevent upgrades, by breaking the connection to the server so that the client never receives new data; the best that could be done with an equivalent of valid-until would be to tell the user that they are probably no longer up to date.)

If there is something that Flatpak could do differently to help verified boot somehow, then that would make sense as a *separate* feature request. However, verified boot as practically implemented (e.g. UEFI secure-boot) only measures the bootloader and kernel, and Flatpak is not either of those things, so Flatpak is outside the scope of verified boot. A feature request for this would have to be a lot more specific about what the desired functionality is and why it is needed.

Checking signatures on dependencies is already a separate issue.

**Comment by tinywrkb** [comment]
There's an initial fs-verity support in ostree, and btrfs gained fs-verity support recently, so probably fs-verity would be the best choice for runtime code authentication.

For me, as a user who know very little about measured boot, the most obvious problem with Flatpak is that in the local Flatpak installation there's no separation between stateful configs and stateful data.  

If I want to wipe the system to a clean state but keep installed applications, or if the user wants to make system changes that the security policy requires wiping the TPM (e.g. switching to a different ostree system branch, or like in Chromium OS switching to dev mode), then in these cases the stateful system volume (`/var`) which is encrypted with a key kept with the TPM, will be wiped, as its encryption key is not available.  
But this shouldn't force to also wiping the Flatpak system installation.  
In other words, `/var` is not the correct place for the Flatpak system installation. The Flatpak installation configs (e.g. overrides) should be kept in `/var`, but the apps themselves and everything else that can be shipped signed shouldn't.  

The second obvious problem is `/app/extra`, this would be impossible to authenticate unless the app maintainer can promise that its content is predictable, which is not always the case (e.g. Wine prefix).  
`/app/extra` is added to the Flatpak installation, and this means that ostree should make it possible to mark opted-out files from fs-verity.

**Comment by aidanharris** [comment]
Is there a way to perform integrity checks of an installed flatpak after installation?

I'm asking not from a security perspective but for detecting bitrot/corruption (runtime validation would solve this though).

I ran into an issue recently where an installed flatpak somehow became corrupt. I suspect this happened by accident due to my filesystem running out of space and I fixed it by uninstalling and re-installing the flatpak.

Being able to run a hypothetical command like [code]flatpak verify[/code] to check that the installed contents of a flatpak match would be nice.

**Comment by smcv** [comment]
> Being able to run a hypothetical command like flatpak verify to check that the installed contents of a flatpak match would be nice.

I think that's outside the scope of this issue, but it would make sense as a separate feature request. Unlike this issue, that feature request has a finite scope, and we can easily look at it and say "this is finished" or "this hasn't been done yet".

Flatpak has considerably more feature requests and bug reports than maintainers, so the requested feature is unlikely to happen any time soon unless someone (perhaps you?) looks into implementing it - but it still seems like a useful feature request to open.

> I'm asking not from a security perspective but for detecting bitrot/corruption

I think this reinforces my feeling that this issue is not useful to keep open, because it's not really actionable (there is no specific thing anyone can do that will make it "finished"), and will attract comments and feature requests that are not really part of the issue as originally reported.
