### ISSUE TITLE
Flatpak app from Flathub test repo is always displayed as having updates available 

### ISSUE THREAD

**Issue by Huluti** [flatpak/flatpak#4062]
## Linux distribution and version
Fedora 33
## Flatpak version
Flatpak 1.8.4

## Description of the problem

Flatpak continue to show updates for apps that are already updated. It seems to affect "test" repos.

The initial issue was created in the GNOME Software repo. Here's the original issue:
https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1084

A maintainer of GNOME Software think that the problem comes from Flatpak directly:
https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1084#note_999152

I'm creating this issue to continue investigating this rather annoying problem.

Thank's in advance!

**Comment by larathbone** [comment]
Could you try updating to flatpak 1.10.2?

I was experiencing some similar issues while working on a simple GTK flatpak installer I've been writing called GFI. Some spurious updates were appearing when I was calling flatpak_installation_list_installed_refs_for_update() in 1.8.x, but since upgrading, this issue seems to have gone away. I did read in the NEWS file that several improvements were made to the update APIs over the last major release cycle.

**Comment by Huluti** [comment]
Can't reproduce it in fact these times. Thank's!
