### ISSUE TITLE
Runtime installed in the home directory is always used.

### ISSUE THREAD

**Issue by Latesil** [flatpak/flatpak#4067]
## Linux distribution and version
Fedora 33, GNOME 3.38.2

## Flatpak version
Flatpak 1.8.4

## Description of the problem
I have a program installed in `system` and it has a runtime dependency `org.gnome.Platform//3.38` which installed both in system and in user directories. Every time I launch that program it uses runtime from homedir, even when I launch it with `--system`. I don't know if it's an error.

## Steps to reproduce
1. Install program in `system`
2. Install another program with `--user` (after that you should have two identical runtimes in system and in user homedir)
3. Launch program from step 1, which installed in system.

**Comment by tim77** [comment]
Did you mount `home` partition with `noexec`?

**Comment by Latesil** [comment]
Yes, I did and that's why I discovered this behavior.

**Comment by smcv** [comment]
If you have your home directory mounted `noexec`, then you can't install any Flatpak apps or runtimes into your home directory (well, you can, but they won't work). Uninstall the non-working runtime from your home directory and the system-wide runtime will be used again.

I think this is expected behaviour: you asked the OS to make everything in your home directory be not executable, so things in your home directory aren't executable.

I think it's also expected behaviour that runtimes installed in your home directory are used in preference to system-wide-installed runtimes of the same name: your personal choices (which in this case might include "install a modified/beta/older/newer version of the same runtime") intentionally override choices made on a system-wide basis for everyone.
