### ISSUE TITLE
App specific locales?

### ISSUE THREAD

**Issue by qoheniac** [flatpak/flatpak#4124]
Is there a way to use different locales for different applications?

**Comment by tinywrkb** [comment]
See `locale.1`, `flatpak-config.1`, and `flatpak-override.1` man pages.

* Set languages in Flatpak installation repo so locales will be fetched. Due to a [bug](https://github.com/flatpak/flatpak/issues/3712) you need to set it separately for the user and system installation repos.
```
$ flatpak config  --system --set languages 'en;he'
$ flatpak config  --user --set languages 'en;he'
```
* Update to fetch missing locales
```
$ flatpak update
```
* Override locale environment vars per app. They should already be set for your user account by the desktop environment or other means. You can also use Flatseal for the override.
```
$ flatpak override --user --env=LC_MESSAGES=he_IL.UTF-8 --env=LANG=he_IL.UTF-8 org.gnome.gedit
```

**Comment by qoheniac** [comment]
I somehow did not find the `flatpak-override` man pages. `flatpak override --env` is exactly what I was looking for. Thank you very much!
