### ISSUE TITLE
Is it not possible to reduce the size of Flatpak packages?

### ISSUE THREAD

**Issue by xzj8b3** [flatpak/flatpak#4177]
## Fedora 33 x 64 

But don't they use somewhat excessive package sizes? We do not have all SSD from some Terabyte, me as an example on Notebook I have SSD from 240

Then also the timing of the update are longer and if you are on the move is not entirely practical!!!

**Comment by mwleeds** [comment]
There are some important trade-offs involved; see this blog post: https://blogs.gnome.org/alexl/2017/10/02/on-application-sizes-and-bloat-in-flatpak/

Closing this issue since it's not a specific bug or feature request. If there are specific suggestions on how to reduce the size of Flatpaks that would be worth having an issue open about.
