### ISSUE TITLE
Request: make Application Id case insensitive

### ISSUE THREAD

**Issue by protoboolean** [flatpak/flatpak#4217]
I would suggest considering making Application Id case-insensitive, for the same reason [hostnames](https://serverfault.com/a/261344/126842) are.

Firefox has already shown that this can be a source of confusion and "noise" for the end-user: which one of the following do I pick?
Perhaps it could also be exploited to publish seemingly official packages (i.e. a malicious `org.Mozilla.Firefox`, or `org.mozilla.FireFox`).

Two applications should have names that are distinct beyond the casing of the letters used also because it makes communicating about them easier.

```
Name           Description                   Application ID          Version     Branch Remotes
Firefox        Mozilla Firefox Web Browser   org.mozilla.firefox     87.0        stable flathub
Firefox        Web Browser                   org.mozilla.Firefox     87.0        stable fedora
```

**Comment by hughsie** [comment]
Not a fan of this; I think it's a really slippery slope to difficult to find bugs.

**Comment by smcv** [comment]
I think this ship has already sailed. Flatpak app IDs are based on the AppStream specification, the Desktop Entry specification, and D-Bus, which all compare strings case-sensitively; and now Flatpak does too. In all of these, being case-insensitive would be an incompatible change.

With hindsight, perhaps some or all of those specifications, or Flatpak, should have specified that upper case was not allowed in IDs (UIs wanting to be helpful could automatically fold IDs input by the user into lower-case)... but they didn't, and we're stuck with that now.

Ideally, upstream developers would choose a canonical case combination for their app ID in the AppStream metadata that they publish, and packagers would all follow that. However, some apps (notably Firefox and Steam) don't or historically didn't have that, resulting in packagers having to make one up, and not always making the same choice. Fedora chose an ID for Firefox that differs only by case, but Flathub and Ubuntu chose IDs for Steam that have different text (`com.valvesoftware.Steam` and `com.steampowered.steam` respectively, both using domains that are owned by Valve and used for Steam). Comparing case-insensitively is never going to solve Steam's situation.

> Firefox has already shown that this can be a source of confusion and "noise" for the end-user: which one of the following do I pick?

This is not really any better or worse than having both Fedora and Flathub offering `org.gnome.Recipes` or `org.mozilla.firefox`, with no case distinction between them at all...

> Perhaps it could also be exploited to publish seemingly official packages

Each app publisher controls what they publish. By adding Flathub and Fedora as remotes, you have to trust Flathub when they say that their `org.mozilla.firefox` is really from Mozilla, and when they say that their `org.gnome.Recipes` is really from GNOME. Equally, you have to trust Fedora when they say that their `org.mozilla.Firefox` is really from Mozilla, and when they say that their `org.gnome.Recipes` is really from GNOME.

If you don't trust an app publisher to control their namespace correctly and non-maliciously, you can add their remote with `--no-enumerate` to avoid letting it provide apps when you did not specifically choose that remote. This is what happens when you add an app using a `.flatpakref` file.
