### ISSUE TITLE
Host update breaks flatpak app

### ISSUE THREAD

**Issue by keleset** [flatpak/flatpak#4237]
## Linux distribution and version
Alpine Edge
## Flatpak version
1.10.1 -> 1.10.2
## Description of the problem
Somehow upgrading kernel from 5.4.19 to 5.4.30, flatpak from 1.10.1 to 1.10.2 (and some other packages) causes total wreck in every Chromium/Elecron based flatpak app.
## Steps to reproduce
I upgraded the OS (pure host update, flatpak apps and runtimes got no changes during upgrade) and now Chromium and couple of other Electron-based apps have some issues with GPU/DRI and fail to start. Here is the stderr of Chromium started after:
https://pastebin.com/YqbY6gRq

Electron apps do not provide the same verbosity and just have `Modifiers specified, but DRI is too old` repeated in loop.

I understand that might be not flatpak's fault, but AFAIK, there are quite a short list of OS components on host side that can cause such problems. One of the first things I've checked was my wayland compositor, but it was not upgraded and all other flatpak and host-side apps seem to work. I'm not sure where to look for solution now and would really appreciate any help.

**Comment by smcv** [comment]
> upgrading kernel from 5.4.19 to 5.4.30

The kernel affects a lot, so I would suggest looking there first. In particular, if the kernel-side driver for whatever GPU you are using (which GPU?) was affected by this upgrade, that might have introduced a regression.

If you can temporarily boot into the older kernel and try Flatpak again, that would be a useful way to find out whether this triggered the problem. Some distributions like Debian and Ubuntu deliberately keep a previous kernel available so that this step is possible, but I don't know whether Alpine does the same.

> and some other packages

Please check whether your OS has an equivalent of Debian's `/var/log/apt` and `/var/log/dpkg.log*` where you can find out *which* other packages were upgraded.

**Comment by keleset** [comment]
@smcv Thanks for the answer. I've got two AMD GPUs - dedicated one and integrated one. This is snapshot-based setup so I just rolled back (everything works and that's how I write here) and tried to upgrade everything except kernel/firmware and the issue still persists. Update was pretty huge so thats the log from my most recent try: https://pastebin.com/j8RNLZiM
What should I try to exclude from the upgrade process next?

**Comment by refi64** [comment]
Try excluding the Mesa-related packages, they have the closest relationship to GL/GBM-related operations, which is what the Chromium logs seem to be hinting towards. It's...a bit odd that they would affect Flatpaks, since that's the userspace component of the graphics drivers (and the Flatpak runtimes ship their own copy), but I'd imagine they could affect your compositor which still affects Flatpak?

**Comment by keleset** [comment]
@refi64 thanks, that was mesa indeed... I guess I should wait till next time my compositor gets an update and mesa 21 gets more maturity.
