### ISSUE TITLE
snap2flat (convert a snap-pkg  to a flatpak)  feature req. 

### ISSUE THREAD

**Issue by necrose99** [flatpak/flatpak#4262]
convert a snap-pkg  to a flatpak , else convert other alike formats to flatpack etc.... 
a convert to flatpak format tool would be quite nice to have.... 
 feature requested. Utilities to do semi-"automagic" conversion of snaps/appimage or alike  etc to flatpak

`# download a snap , snap2flat -c xfce-ninja-wallpapers.snap     xfce-ninja-wallpapers.flatpak | outputting package successful.` 

( snap requires systemd , since flatpak is native openrc/systemd  gentoo , I'd like to avoid any hassles with needed a systemd instance , or being forced to ram systemd on every install.  for hardened systems , the openrc is of use.)

**Comment by mwleeds** [comment]
If such a tool existed (and I don't know how technically hard it would be to create) it would give users on Flatpak-only distributions (e.g. Fedora Silverblue, Endless OS) access to applications they wouldn't otherwise have.

More interesting perhaps than one-off conversions would be converting Snap manifests into Flatpak manifests that could be added to Flathub and maintained long-term.

Fedora has some similar tooling that converts rpms to Flatpaks, but I don't believe it produces ideal output without human intervention.

**Comment by necrose99** [comment]
for gentoo its trivial to convert system  packages 


but for easy one offs a tool would be nice further iteration might automatically convert swaths of packages..  and or fetch update convert and done

**Comment by barthalion** [comment]
Because snap is essentially squashfs, Flathub already ships some snaps via extra-data: https://github.com/flathub/com.nordpass.NordPass/blob/e93574f94b4387917fb8d5b0fb725660b2b01817/com.nordpass.NordPass.yaml

**Comment by barthalion** [comment]
Similiarly about AppImage. As long as something is extractable, there's no reason why it can't be used for flatpak.

**Comment by refi64** [comment]
From my (admittedly limited) snap knowledge, I don't think this could reasonably be fully automatic, you'd need at least some tweaking of the generated output. That being said, as mentioned above, you can already build Flatpaks by hand using snap packages.

I don't believe there are any plans to have this part of Flatpak core in the near future, and this could easily exist as a separate tool, so I'm going to close this.

**Comment by izissise** [comment]
I made a tool to do that https://github.com/izissise/snap2flatpak
I didn't test a lot of apps though
