### ISSUE TITLE
file's mtime not preserved

### ISSUE THREAD

**Issue by abique** [flatpak/flatpak#4293]
## Linux distribution and version
Archlinux

## Flatpak version
flatpak 1.11.1-1

## Description of the problem
The file mtime is not preserved.

## Steps to reproduce
```
flatpak install com.bitwig.BitwigStudio
flatpak enter com.bitwig.BitwigStudio /bin/sh
ls -l /app/Library/modules/Spectrum.bwmodule
```

**Comment by abique** [comment]
On IRC, I've been told that this is on purpose and this is for making reproduce-able builds.

**Comment by abique** [comment]
Actually that can be bad for java apps: https://docs.oracle.com/javase/7/docs/api/java/io/File.html#lastModified()

**Comment by abique** [comment]
It did not change in java 16: https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/io/File.html

**Comment by abique** [comment]
Apparently it does not happen with Flatpak 1.10.2, could it be a client thing only? If so it would have nothing to do with reproduce-able builds given that it just has to extract the pack, not to build it.

**Comment by smcv** [comment]
> The file mtime is not preserved

Why this is a problem? What wrong behaviour is it causing in an app?

The goal here should be to fix the wrong behaviour, whatever that is - the mtime is an implementation detail.

It is intentional that Flatpak doesn't preserve mtime. This is done to maximize reuse of identical files between builds: if a different mtime needs to be preserved, then the file isn't identical, and so the old and new versions can't be hard links to each other (if a file has multiple hard links they all share one inode, therefore they all share one mtime), which would mean apps and runtimes take up more space.

In particular, the GNOME and KDE runtimes are both derived from the freedesktop.org runtime. For each file in the freedesktop.org runtime, we want the corresponding file in the GNOME runtime and the corresponding file in the KDE runtime to be literally identical, so that if you have those three runtimes installed, you don't have to download and store each file of the freedesktop.org runtime as three separate files that differ only by their mtime.

Upgrading apps, or installing stable and beta versions of the same app, also benefits from this deduplication.

> install with a mtime of "now" or "release time from appstream" or "package build date"

None of these would allow identical files to be deduplicated between similar runtimes, or between similar versions of an app, or in other situations where you'd want the files to only be stored once.

> Actually that can be bad for java apps: https://docs.oracle.com/javase/7/docs/api/java/io/File.html#lastModified()

This isn't specific to Java, any reasonable programming language runtime will have an equivalent of that (on Linux, they're all eventually wrappers for `stat(2)` or similar).

**Comment by abique** [comment]
We had long discussion on IRC about it.
I'll summarize my opinion:
- when we build BitwigStudio, we build it from an archive that contains mtime and ctime
- the end-user is not interested in implementation details of deduplication
- to the end-user a time of 1970 for its files looks like a problem/bug
- the modified time and creation time are useful/valuable information
- flatpak is loosing information in order to perform an optimization

**Comment by alexlarsson** [comment]
I understand that people can be confused about this, but it is just how ostree/flatpak works. Any choice in design has pros and cons, and this decision has already been made.
