### ISSUE TITLE
Allow applications to make use of `modify_ldt` syscall

### ISSUE THREAD

**Issue by alaviss** [flatpak/flatpak#4297]
## Linux distribution and version
Gentoo

## Flatpak version
Flatpak 1.10.0

## Description of the problem
Some variants of Wine requires this syscall, see: https://github.com/flathub/net.lutris.Lutris/issues/85

**Comment by xM8WVqaG** [comment]
As [documented in source](https://github.com/flatpak/flatpak/blob/6f86a8ff423a2e7a8e1db70c69612f3fa49ae9d4/common/flatpak-run.c#L2859-L2886), this `seccomp` rule and it's associated comment is copied verbatim from an upstream project.

For some more context on _a_ source of this rule:

> [CVE-2015-3290](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-3290), [5157](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-5157): Bugs in the kernel's non-maskable interrupt handling allowed privilege escalation. Can't be exploited on Sandstorm because the `modify_ldt()` system call is blocked using seccomp.

-- [sandstorm-io/sandstorm/docs/using/security-non-events.md](https://github.com/sandstorm-io/sandstorm/blob/267bc267d35436b3e50472b58938a6a4609f1ea5/docs/using/security-non-events.md#linux-kernel)

Although the linked CVEs have been patched, the comment suggests LDTs have posed issues before these CVEs.

Unfortunately `modify_ldt()` isn't just used in unusual patched versions of wine (`wine-lol` from the OP). This rule also blocks running other older 16-bit software under Flatpak via unpatched wine. It would be convenient if it were possible to opt-in to enabling this system call for this usecase.

**Comment by mortenfc** [comment]
I guess the security argument comes from making it a bit harder to pack viruses?
In my humble opinion that's not worth the cost. People shouldn't download random flatpaks.

**Comment by M-Reimer** [comment]
Actually it's kind of sad to see this issue hanging around for so long. Flatpak is really cool stuff which could really help simplifying software deployment for Linux. And now we are on a point where other tools with similar goals, like Lutris, are trying to get their way into flathub.  Maybe that League of Legends case is just an "edge case" but there are classics on Lutris that may require 16 bit support in the Wine version behind it.

Currently modify_ldt is blocked by flatpak because of being "a historic source of interesting information leaks". Are the issues behind that still in existence? Also the quoted CVE above is fixed since years, right? I totally agree that allowing only a minimum of permissions is a good idea. Most people won't need 16 bit anymore. Almost all software developed in the last few decades is at least 32 bit. But for the people that want to ship an application that needs this support, there should be a (default turned off) checkbox to enable "16 bit support". If you really think this is necessary you could add a warning next to this checkbox and maybe place it to some "advanced settings" place.

**Comment by andrewathalye** [comment]
Seconding M-Reimer, I believe it would be very useful to see a flatpak configuration option that allows modify_ldt (disabled by default, of course).

**Comment by GloriousEggroll** [comment]
> As [documented in source](https://github.com/flatpak/flatpak/blob/6f86a8ff423a2e7a8e1db70c69612f3fa49ae9d4/common/flatpak-run.c#L2859-L2886), this `seccomp` rule and it's associated comment is copied verbatim from an upstream project.
> 
> For some more context on _a_ source of this rule:
> 
> > [CVE-2015-3290](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-3290), [5157](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-5157): Bugs in the kernel's non-maskable interrupt handling allowed privilege escalation. Can't be exploited on Sandstorm because the `modify_ldt()` system call is blocked using seccomp.
> 
> -- [sandstorm-io/sandstorm/docs/using/security-non-events.md](https://github.com/sandstorm-io/sandstorm/blob/267bc267d35436b3e50472b58938a6a4609f1ea5/docs/using/security-non-events.md#linux-kernel)
> 
> Although the linked CVEs have been patched, the comment suggests LDTs have posed issues before these CVEs.
> 
> Unfortunately `modify_ldt()` isn't just used in unusual patched versions of wine (`wine-lol` from the OP). This rule also blocks running other older 16-bit software under Flatpak via unpatched wine. It would be convenient if it were possible to opt-in to enabling this system call for this usecase.

I feel the CVEs involved should be handled(patched) by the software that the CVE reports exposes them, and if as you say these have already been patched, it's not the place of flatpak to block LDTs. 

Let's look at the classic log4j as an example. If the CVE is exposed in the log4j binary, is it flatpak's responsibility to block it? No, I don't think so. It should be patched within log4j like it was. 

If flatpak's goal is to act as a cross distro library agnostic translation layer I don't think things like this should be blocked, it's not flatpak's responsibility to mitigate and/or patch other party's software.

**Comment by smcv** [comment]
> If flatpak's goal is to act as a cross distro library agnostic translation layer I don't think things like this should be blocked

One way to look at this is:

Some software authors just want to be able to use Flatpak as a cross-distro runtime environment, and are uninterested in being sandboxed: "I trust myself, I trust my codebase, and everyone else should too".

However, even for those authors, it is to their advantage for Flatpak to be something that users, sysadmins and distros consider to be safe and trustworthy, and having a useful level of sandboxing and security hardening is something that contributes to that. If users/sysadmins/distros don't trust Flatpak to be a safe thing to use, then they won't install or use it, which immediately makes it a less useful cross-distro runtime environment, because it can no longer reach those users/sysadmins/distros.

I'm not saying that this *specific* piece of security hardening is necessarily pulling its weight - maybe it is, maybe it isn't, I don't have enough context to say one way or another. However, the way we should make this decision is more like "which is bigger, the risk or the benefit?" rather than trying to set up a false dichotomy where each piece of security hardening is either essential or useless.

**Comment by smcv** [comment]
> "modify_ldt is a historic source of interesting information leaks" is fear mongering. If there -is- some kind of information leak it should be properly exposed and patched within the software exposing it, not hidden away, especially not hidden away by another software that is unrelated to it

I don't have enough historical context to know what specific information leak this is talking about. Can someone help?

(My best guess would be that it lets one process get information about the memory layout of another process, which is helpful to attackers who want to turn vulnerabilities in things like image decoders from a crash into an arbitrary code execution by crafting the contents of memory to include valid pointer values.)

There seem to have been attempts in the past to patch `modify_ldt()`-related attacks "properly", in the kernel, by disabling the syscall entirely, either on 64-bit kernels or everywhere ([example](https://lore.kernel.org/lkml/5357F82D.8020307@zytor.com/t/), [example](https://lkml.org/lkml/2015/7/23/243)). While you're right to say that this would be perhaps a "more correct" place to put the hardening, that's not going to help the affected versions of Wine.

**Comment by Erick555** [comment]
I think having separate `--allow` option is too much of slice and dice for such obscure feature and including it in `--allow=multiarch` may make more sense. This way `multiarch` won't only mean 32bit support but both 32bit &16bit support which is still consistent with its name.

`multiarch` is in ~99% for wine & friends anyway so for apps this would be transparent change.

**Comment by mortenfc** [comment]
As a general rule, if blocking something for security would prevent *any* kind of super obscure software from being able to run, then that rule should be made configurable.
Perhaps you can introduce multiple security levels that the user is prompted with before installing a flatpak.
Like, is the app very secure, medium, or no restrictions. And is the user "sure it wants to install an app of this security level? Blabla there is low risk of it messing up your Linux machine" (which people don't really care that much about since most people that install obscure software on their linux machine are already tinkering around for fun anyway)

I dislike the idea of generally banning things because of a fear of the unknown. It's lazy, narrow-minded and restricting.

**Comment by xM8WVqaG** [comment]
FWIW, one thing I failed to make clear in my [previous comment](https://github.com/flatpak/flatpak/issues/4297#issuecomment-1165066763) is the `modify_ldt` restriction was (apparently) copied verbatim _from a web framework_ which genuinely had no reason to be running any code using this interface. So the comment `16-bit code is unnecessary in the sandbox` made complete sense in it's original context of a web sandbox but is more arbitrary in Flatpak.

For a primer on local descriptor table (LDT)'s functionality, there is [this Wikipedia article](https://en.wikipedia.org/wiki/Global_Descriptor_Table) and [the `modify_ldt` man page](https://man7.org/linux/man-pages/man2/modify_ldt.2.html) both of which are pretty approachable for a 101 but neither discuss malicious usage.

Of the currently proposed `--allow` flags to hide this behind: `--allow=16bit` and `--allow=multiarch` are more accurate than `--allow=wine` and `--allow=emulation`. If the concern is unnecessarily exposing this syscall - it's more likely somebody would innocently toggle on `wine` or `emulation` (because that's the software they're running) when they don't need `modify_ldt`.

**Comment by smcv** [comment]
>  Perhaps you can introduce multiple security levels that the user is prompted with before installing a flatpak.

We already have those, they're the various permissions flags (including `--allow`, which I think is probably the most appropriate one here).

> including it in --allow=multiarch may make more sense

That hadn't occurred to me as an option, because the `multiarch` flag is really about something completely different (it's really about the ability to call "compat" syscalls, like when you run native Linux i386 binaries on an x86_64 kernel)... but it's a surprisingly good fit, because the most likely reason you'd want to be able to call "compat" syscalls is that you're running legacy proprietary software, and the sorts of situations where you want to do that have a lot of overlap with the sorts of situations where you want to be able to run Windows binaries under Wine (in practice mostly games).

Please could you put a merge request together for that if it's something you want to pursue?

**Comment by alexlarsson** [comment]
I think going the multiarch route makes a lot of sense. They really are quite similar, both in what they are used for and in the "security risk", and we don't want a ton of static permissions.
