### ISSUE TITLE
Controllers are enumerated backwards in a sandbox

### ISSUE THREAD

**Issue by HugLifeTiZ** [flatpak/flatpak#4329]
## Linux distribution and version
Xubuntu 20.04

## Flatpak version
1.11.2

## Description of the problem
It seems that controller enumeration in sandbox environments is consistently reverse of enumeration outside of a sandbox. That is to say, if you have four controllers, what SDL2 would consider controller 1 outside of the sandbox is considered controller 4 inside of a sandbox, and vice versa and so on.

Some examples of real-world applications and games affected by this include GZDoom, RPCS3, and the most problematic case: Steam. If you have Xbox controllers connected, you can "Identify" them in the controller configuration dialog and it will send a rumble. (It doesn't give you this option for dualshock 4s, not sure why.) You can use that to verify incorrect controller ordering.

This is particularly problematic for Steam because some games ignore controller input coming from any controller other than what it thinks to be "player 1". This *may* be an SDL2 issue rather than a Flatpak or Bubblewrap issue, but I wanted to start here because sandbox/no sandbox is the condition under which I have identified the problem to occur.

## Steps to reproduce
Connect two or more controllers to your computer. Install sdl2-jstest and the flatpak version, io.gitlab.sdl_jstest.sdl2_jstest. Run `sdl2-jstest -t 0`. Press some buttons on the first controller you connected, and see that input is shown. Now, run `flatpak run io.gitlab.sdl_jstest.sdl2_jstest -t 0`. Press some buttons on the first controller again. Nothing appears. Press some buttons on the **last** controller you connected. Input is shown. Now, do `flatpak run io.gitlab.sdl_jstest.sdl2_jstest -t $n` where n is the number of controllers minus one. Press buttons on the first controller, and see that input is shown there.

**Comment by HugLifeTiZ** [comment]
After a cursory newbie-eyed check of SDL's code on github, I didn't see it doing anything that looked particularly wrong in the fallback detection function that is used at the start when inside a sandbox, but I did discover the SDL_JOYSTICK_DEVICE environment variable; by enumerating controllers manually and setting that variable before entering a sandbox, controllers that are present before entering a sandbox are enumerated in the correct order.

**Comment by smcv** [comment]
> This may be an SDL2 issue

I'm fairly sure it is. The difference between sandbox and non-sandbox is that outside a sandbox it enumerates controllers by asking libudev, but inside a sandbox it has to enumerate controllers by reading /dev and /sys directly, because the IPC protocol between udevd and libudev is not container-friendly (it is not guaranteed to be stable between versions, and cannot do change-notification for hotplugging in an unprivileged user namespace).

readdir() order is arbitrary, so I think to discover the controllers in a defined order, instead of adding each device as soon as it discovers it in readdir() order as it currently does, SDL would have to do the readdir() into a temporary data structure (most likely a dynamically-allocated resizable array), sort them (by device node name or something), and then iterate though the sorted data structure adding each device.

You can run games with environment variable `SDL_JOYSTICK_DISABLE_UDEV=1` to force SDL to use the fallback code path even when it is not in a Flatpak or pressure-vessel sandbox.

Proton's Wine has similar logic for enumerating controllers in a container, which might need similar changes.

Flatpak cannot solve this: it is outside Flatpak's scope. flatpak/xdg-desktop-portal#536 is the closest there can be to a Flatpak solution for this.

**Comment by HugLifeTiZ** [comment]
> You can run games with environment variable `SDL_JOYSTICK_DISABLE_UDEV=1` to force SDL to use the fallback code path even when it is not in a Flatpak or pressure-vessel sandbox.

Thanks for that! I tried using that to run sdl2-jstest and found that it was enumerating controllers in the correct order, but I realized Xubuntu 20.04's packaged version of SDL2 is 2.0.10. So I installed 2.0.14 from source and recompiled sdl2-jstest. After that, with the environment variable, it exhibited the same incorrect behavior as in the sandbox.

So yeah, definitely not a Flatpak problem. My apologies! And my thanks to you once again for explaining things well as you always do.

And conveniently, it looks like SDL already has an [issue open](https://github.com/libsdl-org/SDL/issues/4430) for this, so I'm just gonna close this one and discuss it over there. Thanks!
