### ISSUE TITLE
[Feature request] Drag-n-drop as way to grant access to file

### ISSUE THREAD

**Issue by liferooter** [flatpak/flatpak#4337]
## Description of the feature
Drag-n-drop is commonly used by applications to load, send or open file. But Flatpak-ed apps usually can't use drag-n-drop for these tasks because they're sanboxed and has no access to most files. There is a way to open file and get access to it from app (yes, I'm speaking about one of desktop portals). But sometimes drag-n-drop is more convient and handy way to load, send or open file (e.g. to send file via Telegram). I suggest to grant file acces to the application when file is dropped in its window.

**Comment by soredake** [comment]
Yes, it's very annoying not being able to use dnd out of the box in telegram flatpak :(

**Comment by vchernin** [comment]
There's two ways of addressing this issue. Workarounding in a Flatpak by Flatpak basis or making more use of the file-chooser portal which fixes it for every app.

If an app has permissions to access a directory it can do this just fine, but that means the app is unilateral access to that directory.

The xdg desktop file-transfer portal lets apps communicate and use the portal, so drag and drop can work without granting file system permissions. Unfortunately, this isn't yet implemented in most UI toolkits. It's in GTK4 so apps like Clapper will work, but since the GNOME file manager isn't yet on GTK4 it doesn't work (https://github.com/Rafostar/clapper/issues/75). See [this bug](https://gitlab.gnome.org/GNOME/gtk/-/issues/3094) for GTK3 file-transfer portal support. 

Telegram is QT based so you need the file-transfer portal to be implemented there.

[Original file-transfer portal implementation](https://github.com/flatpak/xdg-desktop-portal/issues/99).

**Comment by liferooter** [comment]
@vchernin cool, so I close the issue
