### ISSUE TITLE
error: Can't load uri https://flathub.org/repo/flathub.flatpakrepo: TLS support is not available

### ISSUE THREAD

**Issue by serpro69** [flatpak/flatpak#4347]
## Linux distribution and version

5.8.0-63-generic #71~20.04.1-Ubuntu

## Flatpak version

Flatpak 1.6.5

## Description of the problem

Running: `flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo -v` and getting the below error:

```
F: Opening system flatpak installation at path /var/lib/flatpak
F: Loading https://flathub.org/repo/flathub.flatpakrepo using libsoup
F: flatpak_http_should_retry_request: error: 462:0 TLS support is not available, n_retries_remaining: 5
error: Can't load uri https://flathub.org/repo/flathub.flatpakrepo: TLS support is not available
```

## Steps to reproduce

Not sure what else to include here. Was working fine until recently.

**Comment by serpro69** [comment]
possibly a duplicate of https://github.com/flatpak/flatpak/issues/1207

**Comment by mtovmassian** [comment]
For documentation purpose I add my comment here since #1207 is no more editable.

The problem persists in 2026 with Ubuntu *22.04* and Alacritty *0.16.1* (either with snap or cargo installation) while it works with Gnome Terminal. As explained [here](https://github.com/flatpak/flatpak/issues/1207#issuecomment-1132724817) exporting GIO_MODULE_DIR `export GIO_MODULE_DIR=/usr/lib/x86_64-linux-gnu/gio/modules/` fixes the issue.
