### ISSUE TITLE
package installed or not 

### ISSUE THREAD

**Issue by morozoff** [flatpak/flatpak#4358]
## Linux distribution and version
Linux localhost.localdomain 5.13.6-200.fc34.x86_64 #1 SMP Wed Jul 28 15:31:21 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
## Flatpak version
Flatpak 1.10.2
## Description of the problem
list of pacages
![image](https://user-images.githubusercontent.com/88345298/127910777-f1c8d23c-5c7d-4eb5-bcc4-43c82c340d13.png)
but Flatpak offers to update a package that is not in the list 
![image](https://user-images.githubusercontent.com/88345298/127910839-90b67907-9e8e-456b-abdf-f260e98a1332.png)
and the update fails 
![image](https://user-images.githubusercontent.com/88345298/127910918-765698b9-5ea5-469a-b379-687beff197f1.png)

**Comment by AsciiWolf** [comment]
Try running: `flatpak repair`

**Comment by morozoff** [comment]
dont work
![image](https://user-images.githubusercontent.com/88345298/128055561-44470750-bab3-44a4-a769-85eb253e2eb3.png)

**Comment by mwleeds** [comment]
It is expected behavior that `flatpak update` will sometimes offer to install a package you don't have, for example when an update to an app adds a new app extension or an update to a runtime adds a new runtime extension.

The "error deploying" message in your last screenshot is not expected behavior, but there's not enough information here to debug it so it's not worth leaving this issue open for that.
