### ISSUE TITLE
contradiction between Freedesktop icon naming specification and Flatpak icon naming

### ISSUE THREAD

**Issue by Be-ing** [flatpak/flatpak#4368]
The [Freedesktop icon naming specification](https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html#guidelines) says:

> An application must either use a generic application icon name provided by this specification, or install an icon named the same as the executable for running the application.

This contradicts the [Flatpak documentation](https://docs.flatpak.org/en/latest/conventions.html#application-icons):

> Applications are expected to provide an application icon, which is used for their application launcher. These icons should be provided in accordance with the [Freedesktop icon specification](https://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html) [links to icon *theme* specification, *not* icon naming specification].
> Icons should be named with the application’s ID, be in either PNG or SVG format, and must be placed in the standard location:
> /app/share/icons/hicolor/$size/apps/
> For example, the path to the 128✕128px version of GNOME Dictionary’s icon is:
> /app/share/icons/hicolor/128x128/apps/org.gnome.Dictionary.png

flatpak-builder requires reverse DNS for icon file names:

```
Finishing app
Exporting share/applications/org.mixxx.Mixxx.desktop
Exporting share/icons/hicolor/scalable/apps/org.mixxx.Mixxx.svg
Not exporting share/icons/hicolor/32x32/apps/mixxx.png, non-allowed export filename
Exporting share/icons/hicolor/32x32/apps/org.mixxx.Mixxx.png
Exporting share/icons/hicolor/64x64/apps/org.mixxx.Mixxx.png
Exporting share/icons/hicolor/128x128/apps/org.mixxx.Mixxx.png
Exporting share/icons/hicolor/256x256/apps/org.mixxx.Mixxx.png
Exporting share/icons/hicolor/512x512/apps/org.mixxx.Mixxx.png
```

Further context:
https://github.com/mixxxdj/mixxx/pull/4204
https://github.com/flathub/org.mixxx.Mixxx/pull/35
https://github.com/flathub/flathub/issues/2463

**Comment by nanonyme** [comment]
I'm not sure there is contradiction. The executable in case of flatpak is the application, right? So rename-icon is required in order to comply with freedesktop spec in both cases.

**Comment by Holzhaus** [comment]
There are basically 3 ways to interpret the spec w.r.t. flatpak:

1. The executable inside the flatpack package is named `foo`, so the icon should be named `foo.svg`
2. You run the flatpak app using `flatpak run org.foo.Foo`. The executable name is `flatpak`, so the icon should be named `flatpak.svg`
3. You run the flatpak app using `flatpak run org.foo.Foo`. The flatpak package name is `org.foo.Foo`, which is technically not the executable name, but the logical choice when not looking at the flatpak package *contents*.

Option 2 follows the spec to the letter, but obviously doesn't make sense and would lead to a naming conflict as soon as you have 2 flatpak apps installed.
Option 1 could lead to naming conflicts when two flatpak apps have the same executable name inside the package, especially when the default executable name is something generic such as `app`.

Option 3 guarantees that the icon name is unique (because the flatpak ID is unique) so I understand the decision to use that.

**Comment by hfiguiere** [comment]
It's not a contradiction. It's perfectly in line with the original spec. The application name in that case IS the `id` in the manifest.

**Comment by Be-ing** [comment]
The [Freedesktop icon naming specification](https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html#guidelines) does not say "application name", "id", "Flatpak manifest id", "reverse DNS", or anything hinting that "org.foo.Foo" would be a valid icon name, unless the executable is literally "org.foo.Foo". If "org.foo.Foo" is indeed intended to be the name of the icon file *in the case of Flatpak*, then either the Freedesktop icon naming specification should specify that explicitly, or the Flatpak documentation should clarify that the Flatpak id is required regardless of what the Freedesktop icon naming specification says.

**Comment by hfiguiere** [comment]
The flatpak documentation is pretty clear.
