### ISSUE TITLE
Making downloaded files accessible to the host

### ISSUE THREAD

**Issue by sw-dbrown** [flatpak/flatpak#4392]
## Linux distribution and version
Debian 11

## Flatpak version
Flatpak 1.10.2

## Description of the problem

I need to use the Teams application (com.microsoft.Teams) at work for conferences. The application by default downloads files to `~/Downloads`. It does not appear to be possible to change the download location.

For security reasons, I have revoked access to xdg-download for the application. This causes the Teams application to create a `~/Downloads` directory inside the flatpak filesystem context and place downloaded files there. Without resorting to the CLI, I therefore do not have access to the downloaded files.

I would like to accomplish the following:
- Mount a directory inside the application's flatpak filesystem context (e.g. Host side: `~/flatpak_rw`, Flatpak side: `~/flatpak_rw`)
- Redirect `~/Downloads` to `~/flatpak_rw` inside the flatpak context
- Access the downloaded files from the host via `~/flatpak_rw`

How can I accomplish this?

#### Set `XDG_DOWNLOAD_DIR` environment variable

I tried overriding the `XDG_DOWNLOAD_DIR` environment variable, hoping that Teams would honor it:

```
[Context]
filesystems=!xdg-download;~/flatpak_rw;

[Environment]
XDG_DOWNLOAD_DIR=~/flatpak_rw
```

This does, however, not work. The file is still downloaded to `~/Downloads`. When I check via `flatpak enter` the environment variable does not appear to be set: 

```
user@debian:~$ flatpak enter 1980817159  /bin/bash
bash-5.1$ env
PWD=/home/user
PULSE_CLIENTCONFIG=/run/user/1000/pulse/config
DISPLAY=:99.0
SHLVL=1
XDG_RUNTIME_DIR=/run/user/1000
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
PULSE_SERVER=unix:/run/user/1000/pulse/native
_=/usr/bin/env
```

I'm therefore not sure, whether the variable is actually propagated to the Teams application.

## Other options

I guess it would also be possible to modify the runtime to symlink `~/Downloads` to `~/flatpak_rw`. I assume changes to the runtime are not desireable, therefore I did not try this yet.

Any help and pointers would be greatly appreciated!

**Comment by refi64** [comment]
Did you try `--persist=Downloads`?

**Comment by lestephane** [comment]
> Did you try `--persist=Downloads`? That would create it under `.var/app/the.app.Id/Downloads` on the host side but `~/Downloads` on the Flatpak side.

Yes that works for me.

So to summarize (and correct me if I'm wrong)
- `--filesystem=xdg-download` makes the standard download directory from the host available to the flatpak
- `--persist=Downloads` makes the files written to the download directory in the flatpak context 'visible' to the host.

What confuses me the most is that, in my case, I added `--filesystem=xdg-download` without `:ro` so I assumed I was giving write access to that host directory as well.

I did not at first use `--persist=Downloads` (because I did not understand how this flag works). 

So in the flatpak I could see the existing downloads, and new downloads were being written somewhere I could not see on the host. Confusion and doubt ensued.

In the end all I needed was `--persist`.

So the suggestion works, but the way these flag work (especially in combination) is not intuitive.

**Comment by hfiguiere** [comment]
Let me get this straight:

> For security reasons, I have revoked access to xdg-download for the application. This causes the Teams application to create a ~/Downloads directory inside the flatpak filesystem context and place downloaded files there. Without resorting to the CLI, I therefore do not have access to the downloaded files.

So you disable a feature that is necessary and then complain it doesn't work.


It think the rest has been answered.
