### ISSUE TITLE
[Feature Request] Add a device=usb option

### ISSUE THREAD

**Issue by rmader** [flatpak/flatpak#4405]
Which exposes `/dev/bus/usb`

### Rationale
There is a diverse group of devices such as security devices (Yubikeys), gaming controllers etc. that a big group of applications want to use, notably browsers and even [games](https://github.com/flathub/net.supertuxkart.SuperTuxKart/blob/master/net.supertuxkart.SuperTuxKart.json#L17). Many of these applications thus currently use `device=all`.
There is an attempt to create a xdg-portal[1], however it appears to be far from ready and, crucially, many applications are unlikely to pick it up in the near feature, especially proprietary ones.
Thus having a way to allow access to usb devices without `device=all` could have a relatively easy benefit for sandboxing efforts, even if not as optimal as a portal solution.

1: https://github.com/flatpak/xdg-desktop-portal/pull/559

Related:
https://github.com/flatpak/flatpak/pull/4083
https://bugzilla.mozilla.org/show_bug.cgi?id=1729344

**Comment by alexlarsson** [comment]
I'm not fundamentally against exposing usb as a device class, if we can make it work. But it seems tricky, although honestly I don't really know it well enough to tell.

The general problem with device access is that we only can grant access during the sandbox setup, as that is the only place we have permissions to mount stuff in the sandbox. This means that unless the devices are all in a subtree like `/dev/dri` which we can bind-mount into the sandbox, we can never handle dynamic devices.

/dev/bus/usb is such a subtree, so exposing that would work. However, usb seem to have other kinds of device nodes too. For example, i have `/dev/usb/hiddev0` and `/dev/usbmon*`. Furthemore, I am not sure how well actual software can handle usb device access without for directores like `/dev/char`, `/dev/block`,  `/dev/input` and `/dev/snd` , which lets you access usb devices via a different device types, thus using the type specific kernel-level drivers.

For example, i have various usb devices like sound, input and v4l, and enumerating /sys/bus/usb like this:
```
for DEV in $(find -H /sys/bus/usb/devices/* -name dev);  do \
  NODE=$(cat $DEV); \
  echo "| ${DEV:21} | ${NODE} | $(readlink -f /dev/char/${NODE}) |"; \
done
```

Results in this:

| sysfs file | devno | device node |
| -- | -- | -- |
| 1-10/1-10:1.2/media0/dev | 237:0 | /dev/media0 |
| 1-10/1-10:1.2/video4linux/video1/dev | 81:1 | /dev/video1 |
| 1-10/1-10:1.2/video4linux/video0/dev | 81:0 | /dev/video0 |
| 1-10/1-10:1.2/input/input16/event13/dev | 13:77 | /dev/input/event13 |
| 1-10/1-10:1.0/sound/card3/pcmC3D0c/dev | 116:20 | /dev/snd/pcmC3D0c |
| 1-10/1-10:1.0/sound/card3/controlC3/dev | 116:21 | /dev/snd/controlC3 |
| 1-10/dev | 189:4 | /dev/bus/usb/001/005 |
| 1-10:1.0/sound/card3/pcmC3D0c/dev | 116:20 | /dev/snd/pcmC3D0c |
| 1-10:1.0/sound/card3/controlC3/dev | 116:21 | /dev/snd/controlC3 |
| 1-10:1.2/media0/dev | 237:0 | /dev/media0 |
| 1-10:1.2/video4linux/video1/dev | 81:1 | /dev/video1 |
| 1-10:1.2/video4linux/video0/dev | 81:0 | /dev/video0 |
| 1-10:1.2/input/input16/event13/dev | 13:77 | /dev/input/event13 |
| 1-5/1-5:1.3/0003:1038:1612.0004/input/input9/mouse0/dev | 13:32 | /dev/input/mouse0 |
| 1-5/1-5:1.3/0003:1038:1612.0004/input/input9/event6/dev | 13:70 | /dev/input/event6 |
| 1-5/1-5:1.3/0003:1038:1612.0004/input/input8/event5/dev | 13:69 | /dev/input/event5 |
| 1-5/1-5:1.3/0003:1038:1612.0004/hidraw/hidraw3/dev | 240:3 | /dev/hidraw3 |
| 1-5/dev | 189:1 | /dev/bus/usb/001/002 |
| 1-5/1-5:1.1/usbmisc/hiddev0/dev | 180:96 | /dev/usb/hiddev0 |
| 1-5/1-5:1.1/0003:1038:1612.0002/hidraw/hidraw1/dev | 240:1 | /dev/hidraw1 |
| 1-5/1-5:1.2/0003:1038:1612.0003/input/input7/event4/dev | 13:68 | /dev/input/event4 |
| 1-5/1-5:1.2/0003:1038:1612.0003/hidraw/hidraw2/dev | 240:2 | /dev/hidraw2 |
| 1-5/1-5:1.0/0003:1038:1612.0001/input/input6/event3/dev | 13:67 | /dev/input/event3 |
| 1-5/1-5:1.0/0003:1038:1612.0001/hidraw/hidraw0/dev | 240:0 | /dev/hidraw0 |
| 1-5:1.0/0003:1038:1612.0001/input/input6/event3/dev | 13:67 | /dev/input/event3 |
| 1-5:1.0/0003:1038:1612.0001/hidraw/hidraw0/dev | 240:0 | /dev/hidraw0 |
| 1-5:1.1/usbmisc/hiddev0/dev | 180:96 | /dev/usb/hiddev0 |
| 1-5:1.1/0003:1038:1612.0002/hidraw/hidraw1/dev | 240:1 | /dev/hidraw1 |
| 1-5:1.2/0003:1038:1612.0003/input/input7/event4/dev | 13:68 | /dev/input/event4 |
| 1-5:1.2/0003:1038:1612.0003/hidraw/hidraw2/dev | 240:2 | /dev/hidraw2 |
| 1-5:1.3/0003:1038:1612.0004/input/input9/mouse0/dev | 13:32 | /dev/input/mouse0 |
| 1-5:1.3/0003:1038:1612.0004/input/input9/event6/dev | 13:70 | /dev/input/event6 |
| 1-5:1.3/0003:1038:1612.0004/input/input8/event5/dev | 13:69 | /dev/input/event5 |
| 1-5:1.3/0003:1038:1612.0004/hidraw/hidraw3/dev | 240:3 | /dev/hidraw3 |
| 1-6/1-6:1.0/sound/card0/controlC0/dev | 116:19 | /dev/snd/controlC0 |
| 1-6/1-6:1.0/sound/card0/pcmC0D0c/dev | 116:18 | /dev/snd/pcmC0D0c |
| 1-6/1-6:1.0/sound/card0/pcmC0D0p/dev | 116:17 | /dev/snd/pcmC0D0p |
| 1-6/dev | 189:2 | /dev/bus/usb/001/003 |
| 1-6:1.0/sound/card0/controlC0/dev | 116:19 | /dev/snd/controlC0 |
| 1-6:1.0/sound/card0/pcmC0D0c/dev | 116:18 | /dev/snd/pcmC0D0c |
| 1-6:1.0/sound/card0/pcmC0D0p/dev | 116:17 | /dev/snd/pcmC0D0p |
| 1-9/dev | 189:10 | /dev/bus/usb/001/011 |
| 3-2/3-2:1.1/0003:1532:005C.0006/input/input12/event9/dev | 13:73 | /dev/input/event9 |
| 3-2/3-2:1.1/0003:1532:005C.0006/input/input11/event8/dev | 13:72 | /dev/input/event8 |
| 3-2/3-2:1.1/0003:1532:005C.0006/hidraw/hidraw5/dev | 240:5 | /dev/hidraw5 |
| 3-2/dev | 189:257 | /dev/bus/usb/003/002 |
| 3-2/3-2:1.2/0003:1532:005C.0007/input/input13/event10/dev | 13:74 | /dev/input/event10 |
| 3-2/3-2:1.2/0003:1532:005C.0007/hidraw/hidraw6/dev | 240:6 | /dev/hidraw6 |
| 3-2/3-2:1.0/0003:1532:005C.0005/input/input10/event7/dev | 13:71 | /dev/input/event7 |
| 3-2/3-2:1.0/0003:1532:005C.0005/input/input10/mouse1/dev | 13:33 | /dev/input/mouse1 |
| 3-2/3-2:1.0/0003:1532:005C.0005/hidraw/hidraw4/dev | 240:4 | /dev/hidraw4 |
| 3-2:1.0/0003:1532:005C.0005/input/input10/event7/dev | 13:71 | /dev/input/event7 |
| 3-2:1.0/0003:1532:005C.0005/input/input10/mouse1/dev | 13:33 | /dev/input/mouse1 |
| 3-2:1.0/0003:1532:005C.0005/hidraw/hidraw4/dev | 240:4 | /dev/hidraw4 |
| 3-2:1.1/0003:1532:005C.0006/input/input12/event9/dev | 13:73 | /dev/input/event9 |
| 3-2:1.1/0003:1532:005C.0006/input/input11/event8/dev | 13:72 | /dev/input/event8 |
| 3-2:1.1/0003:1532:005C.0006/hidraw/hidraw5/dev | 240:5 | /dev/hidraw5 |
| 3-2:1.2/0003:1532:005C.0007/input/input13/event10/dev | 13:74 | /dev/input/event10 |
| 3-2:1.2/0003:1532:005C.0007/hidraw/hidraw6/dev | 240:6 | /dev/hidraw6 |
| usb1/1-9/dev | 189:10 | /dev/bus/usb/001/011 |
| usb1/1-5/1-5:1.3/0003:1038:1612.0004/input/input9/mouse0/dev | 13:32 | /dev/input/mouse0 |
| usb1/1-5/1-5:1.3/0003:1038:1612.0004/input/input9/event6/dev | 13:70 | /dev/input/event6 |
| usb1/1-5/1-5:1.3/0003:1038:1612.0004/input/input8/event5/dev | 13:69 | /dev/input/event5 |
| usb1/1-5/1-5:1.3/0003:1038:1612.0004/hidraw/hidraw3/dev | 240:3 | /dev/hidraw3 |
| usb1/1-5/dev | 189:1 | /dev/bus/usb/001/002 |
| usb1/1-5/1-5:1.1/usbmisc/hiddev0/dev | 180:96 | /dev/usb/hiddev0 |
| usb1/1-5/1-5:1.1/0003:1038:1612.0002/hidraw/hidraw1/dev | 240:1 | /dev/hidraw1 |
| usb1/1-5/1-5:1.2/0003:1038:1612.0003/input/input7/event4/dev | 13:68 | /dev/input/event4 |
| usb1/1-5/1-5:1.2/0003:1038:1612.0003/hidraw/hidraw2/dev | 240:2 | /dev/hidraw2 |
| usb1/1-5/1-5:1.0/0003:1038:1612.0001/input/input6/event3/dev | 13:67 | /dev/input/event3 |
| usb1/1-5/1-5:1.0/0003:1038:1612.0001/hidraw/hidraw0/dev | 240:0 | /dev/hidraw0 |
| usb1/1-10/1-10:1.2/media0/dev | 237:0 | /dev/media0 |
| usb1/1-10/1-10:1.2/video4linux/video1/dev | 81:1 | /dev/video1 |
| usb1/1-10/1-10:1.2/video4linux/video0/dev | 81:0 | /dev/video0 |
| usb1/1-10/1-10:1.2/input/input16/event13/dev | 13:77 | /dev/input/event13 |
| usb1/1-10/1-10:1.0/sound/card3/pcmC3D0c/dev | 116:20 | /dev/snd/pcmC3D0c |
| usb1/1-10/1-10:1.0/sound/card3/controlC3/dev | 116:21 | /dev/snd/controlC3 |
| usb1/1-10/dev | 189:4 | /dev/bus/usb/001/005 |
| usb1/dev | 189:0 | /dev/bus/usb/001/001 |
| usb1/1-6/1-6:1.0/sound/card0/controlC0/dev | 116:19 | /dev/snd/controlC0 |
| usb1/1-6/1-6:1.0/sound/card0/pcmC0D0c/dev | 116:18 | /dev/snd/pcmC0D0c |
| usb1/1-6/1-6:1.0/sound/card0/pcmC0D0p/dev | 116:17 | /dev/snd/pcmC0D0p |
| usb1/1-6/dev | 189:2 | /dev/bus/usb/001/003 |
| usb2/dev | 189:128 | /dev/bus/usb/002/001 |
| usb3/3-2/3-2:1.1/0003:1532:005C.0006/input/input12/event9/dev | 13:73 | /dev/input/event9 |
| usb3/3-2/3-2:1.1/0003:1532:005C.0006/input/input11/event8/dev | 13:72 | /dev/input/event8 |
| usb3/3-2/3-2:1.1/0003:1532:005C.0006/hidraw/hidraw5/dev | 240:5 | /dev/hidraw5 |
| usb3/3-2/dev | 189:257 | /dev/bus/usb/003/002 |
| usb3/3-2/3-2:1.2/0003:1532:005C.0007/input/input13/event10/dev | 13:74 | /dev/input/event10 |
| usb3/3-2/3-2:1.2/0003:1532:005C.0007/hidraw/hidraw6/dev | 240:6 | /dev/hidraw6 |
| usb3/3-2/3-2:1.0/0003:1532:005C.0005/input/input10/event7/dev | 13:71 | /dev/input/event7 |
| usb3/3-2/3-2:1.0/0003:1532:005C.0005/input/input10/mouse1/dev | 13:33 | /dev/input/mouse1 |
| usb3/3-2/3-2:1.0/0003:1532:005C.0005/hidraw/hidraw4/dev | 240:4 | /dev/hidraw4 |
| usb3/dev | 189:256 | /dev/bus/usb/003/001 |
| usb4/dev | 189:384 | /dev/bus/usb/004/001 |

Yes, each usb device has a `/dev/bus/usb` device linked to it, but very few only have that, and its unclear to me how useful having only those available to the app is. However, I am willing to be educated by someone who knows the details of USB better.

**Comment by smcv** [comment]
Taking a concrete example that I know about: games and game-adjacent libraries accessing game controllers generally want `/dev/input/event*` (ordinary users get access to game controllers via this interface by default, but not e.g. keyboards or mice) or `/dev/hidraw*` (ordinary users *do not* get access to any of these by default, but projects like Steam install udev rules to allow this lower-level "raw HID" access to specific game controllers).

Games and game-adjacent libraries generally *don't* use raw USB access to `/dev/bus/usb`, because that would require them to reinvent too many wheels that are generally agreed to be the kernel's job.

If we want a semi-big hammer to give games with simple requirements access to game controllers without always opening up *all* of `/dev`, then I think a `--device=input` that means `/dev/input/*` would be better for this than `--device=usb`. That would also let them talk to Bluetooth controllers, such as PS3/PS4/PS5 gamepads and Wii/Switch controllers, which is probably desirable. I know that doesn't solve access to e.g. Yubikeys, but I think those are really a separate feature request anyway.

Games and game-adjacent libraries with more demanding requirements, and in particular Steam/Proton, would still want `--device=all`, to talk to `/dev/hidraw*` for lower-level control where possible.

One fundamental issue with opening up general access to USB is that USB is a connectivity technology, not an area of functionality. On the laptop where I'm typing this, yes, USB access gives you access to devices that are physically plugged into an external-facing USB port - but it also gives you access to the SD-card reader and the webcam built into the laptop itself, which happen to be connected to the CPU via internally-wired USB controllers. A lot of laptops, embedded devices and even desktops have a similar setup, because USB is an easy thing for manufacturers to connect up, and good enough for most "slow" devices.

**Comment by rmader** [comment]
> If we want a semi-big hammer to give games with simple requirements access to game controllers without always opening up _all_ of `/dev`, then I think a `--device=input` that means `/dev/input/*` would be better for this than `--device=usb`. That would also let them talk to Bluetooth controllers, such as PS3/PS4/PS5 gamepads and Wii/Switch controllers, which is probably desirable.

This sounds like a reasonable option to me - IIUC it would be enough for many common (legacy) games and browsers. I see there's also https://github.com/flatpak/xdg-desktop-portal/issues/536, however given that it might only be needed for X11 applications, I wonder if a `--device=input` (plus maybe `--device=fallback-input`?) might be the easier way forward.

> I know that doesn't solve access to e.g. Yubikeys, but I think those are really a separate feature request anyway.

Agreed. Looks like there's https://github.com/flatpak/flatpak/issues/2764 for it.

> Games and game-adjacent libraries with more demanding requirements, and in particular Steam/Proton, would still want --device=all, to talk to /dev/hidraw* for lower-level control where possible.

I see, maybe this can be solved in https://github.com/flatpak/xdg-desktop-portal/issues/611 eventually

**Comment by rmader** [comment]
Another reason why we might *want* to have a `--device=usb` option is that it would imply `--nodevice=usb` as well IIUC. So we could have `--device=all` combined with `--nodevice=usb`, which would tighten the sandbox for those running a recent version of Flatpak.
A case where this would make sense would IMO be when this is paired with a `--nodevice=video` option, giving/denying access to `/dev/video*` and `/dev/v4l`. IIUC this would allow applications to shut down camera access - arguably a big privacy win. WDYT?

**Comment by smcv** [comment]
We cannot implement `--device=all --nodevice=video` in the way you suggest, if `video` means `/dev/video*`.

The bind-mounts used to implement `--device` are static, and are done at application launch. We can either bind-mount whole directories, or individual device nodes.

Concretely, suppose you launch a Flatpak app at a time when you have two camera devices available, `/dev/video0` and `/dev/video1`.

If we implemented `--device=all --nodevice=video` as bind-mounting all of `/dev`, but then mounting a "whiteout" over `/dev/video0` and `/dev/video1`, then that would give users a false sense of security: if they subsequently plug in a USB webcam `/dev/video2`, the application would gain access to that new device, because it would appear in `/dev` and we would not have an opportunity to mount a "whiteout" over it.

Conversely, if we implemented `--device=all --nodevice=video` as bind-mounting each device and each subdirectory in `/dev` individually, and they plug in a new raw HID device (`/dev/hidraw*`), then we would not have an opportunity to make that device appear in the application's `/dev`.

The only classes of device for which we can have selective availability without sacrificing hotplug are those that live in a subdirectory, such as GPUs (`/dev/dri/*`), evdev and legacy input (`/dev/input/*`), and ALSA audio (`/dev/snd/*`); or those that do not really support multiple hot-pluggable instances anyway, such as legacy OSS audio (`/dev/dsp`, `/dev/adsp`).

**Comment by kontomondo** [comment]
One approach might be combining usb access with filtering, for example:
1. Allow only specified devices id (`vendorId:deviceId`)
`--device=usb-filter --usb-filter-ids=1234:5678,2345:6789`
2. Allow all except the specified devices id
`--device=usb-all --nodevice=usb-filter --usb-filter-ids=1234:5678,2345:6789`
3. Allow only the specified classes (eg. chip/smartcard, webcam), going by https://www.usb.org/defined-class-codes
`--device=usb-filter --usb-filter-interface-class=11,14`
4. Allow all except the specified classes (eg. webcam)
`--device=usb-all --nodevice=usb-filter --usb-filter-interface-class=14`

This would allow for a finer control over the usb devices, where you can include only the access needed down to concrete device ids if needed.

**Comment by smcv** [comment]
> Allow only specified devices id

This is likely to be unimplementable within Flatpak: it has the same practical problems [outlined](https://github.com/flatpak/flatpak/issues/4405#issuecomment-916716062) [previously](https://github.com/flatpak/flatpak/issues/4405#issuecomment-917650757).

If you want fine-grained control over USB access, a better direction would be a portal: https://github.com/flatpak/xdg-desktop-portal/issues/227

**Comment by kontomondo** [comment]
@smcv ah, thank you for educating me on this, indeed the portal makes a lot more sense.

**Comment by smcv** [comment]
> maybe flatpak could [have] rules to ask udev to create a /dev/flatpak (only accessible to its flatpak group) with some folders for device type, such as /dev/flatpak/joystick, use the hwdb rules setup I proposed to configure udev so it creates/removes a symlink to the actual devices

No, sharing symlinks with a container doesn't work like that: the container will see a dangling symlink, pointing to a file that doesn't exist in the sandbox.

**Comment by MateusRodCosta** [comment]
> > maybe flatpak could [have] rules to ask udev to create a /dev/flatpak (only accessible to its flatpak group) with some folders for device type, such as /dev/flatpak/joystick, use the hwdb rules setup I proposed to configure udev so it creates/removes a symlink to the actual devices
> 
> No, sharing symlinks with a container doesn't work like that: the container will see a dangling symlink, pointing to a file that doesn't exist in the sandbox.

@smcv What then if, instead of being a folder full of symlinks to actual devices, `/dev/flatpak/joysticks` is some kind of "fake" device that allows the flatpak sandbox to interact with it to get access to the real devices and some other flatpak tool outside the sandbox manages actual access?
You would give the sandbox that fake device but the sandbox would know how to use it, udev plus some type of "flatpak device managing tool" would work outside the sandbox. 

Would that be something that can be done? Since the problem seems to be that symlinks won't work but a device will, maybe creating a fake device that can act as some sort of translation layer will...
