### ISSUE TITLE
[Bug]: tui utils like whiptail and dialog don't work without --devel arg

### ISSUE THREAD

**Issue by Ratevandr** [flatpak/flatpak#4503]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.

### Flatpak version

1.12.2

### What Linux distribution are you using?

Debian

### Linux distribution version

11

### What architecture are you using?

x86_64

### How to reproduce

1. Build flatpak with whiptail
2. Using whiptail or dialog in flatpak, without --devel mode
3. In the case of the dialog, the application crashes. Whiptail simply does not display anything.

### Expected Behavior

The interface is displayed and the application is running.

### Actual Behavior

The interface is not displayed and the application does not work.

### Additional Information

Can I fix this on my own? For example, how I can make the application start by default with the key --devel?

**Comment by smcv** [comment]
`--devel` does various miscellaneous things, and it isn't immediately clear which one is making the difference:

* by default it uses a Sdk runtime instead of a Platform runtime;
* it allows a few extra system calls that are not normally allowed (`personality(2)`, `ptrace(2)`, `perf_event_open(2)`;
* it sets some environment variables, notably `LC_ALL=en_US.utf8`

If you run your app without `--devel`, but with the SDK instead of Platform runtime (for example `--runtime=org.freedesktop.Sdk//21.08`), does that work around this crash?

Or, if you run your whiptail/dialog command with `LC_ALL=en_US.utf8`, does that work around this crash?

**Comment by Ratevandr** [comment]
I got the next backtrace:
#0  0x00007ffff7f94ba6 in waddch () from /usr/lib/x86_64-linux-gnu/libncurses.so.6
#1  0x000055555557dde8 in dlg_attr_clear (win=0x5555555cca50, height=36, width=155, attr=<optimized out>) at util.c:247
#2  0x000055555558000b in dlg_clear () at util.c:255
#3  init_dialog (input=<optimized out>, output=0x7ffff7df8440 <_IO_2_1_stderr_>) at util.c:438
#4  0x000055555555c274 in main (argc=<optimized out>, argv=<optimized out>) at dialog.c:2055

**Comment by Ratevandr** [comment]
I have compiled dialog as follows:

```
./configure --prefix=/app/ --enable-nls --with-ncursesw --disable-rpath-hack
make -j1
make install
```

And everything worked fine!
