### ISSUE TITLE
[Feature request]: Ask for permissions when necessary with a pop-up window

### ISSUE THREAD

**Issue by raploz** [flatpak/flatpak#4528]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

Canonical is implementing a feature to Snap similar to Android and iOS where instead of selecting sandbox permissions using the software center or command-line tools (or in the case of Flatpaks, Flatseal), a pop-up dialog will appear and ask the user for the necessary permissions whenever access is needed. This can apply to accessing paths (like partitions) and hardware (like camera, microphone, and GPS). A Canonical developer confirmed they're working on that feature [HERE](https://discourse.ubuntu.com/t/your-comments-and-feedback-on-the-desktop-experience-and-the-community-contributor-experience/24742/107?u=raploz)

In order to stay competitive with Snaps and to improve user experience, it's important to have a similar feature for Flatpaks in the future. According to the comment linked above, Canonical is also working on changes to the Linux kernel, and getting Flatpak developers involved could lead to a superior solution that could work for both parties.

**Comment by refi64** [comment]
Doesn't Flatpak already kind of do this? In particular, for filesystem and camera access.

**Comment by mwleeds** [comment]
Yes, Flatpak already has interactive permission dialogs in the form of portals, such as for the file chooser dialog. Snap uses the same filesystem access portal as Flatpak and I would hope that the planned portals described above would also be made in the xdg-desktop-portal project so they can be shared between sandboxing systems. But it would be great to hear more from Canonical on whether that's the case and what they're plans are so we can work together to make more portals.

cc @anonymouse64

**Comment by anonymouse64** [comment]
Portal support is definitely still part of the story for desktop applications and we're not working on a separate portal support AFAIK, but what I was referring to was support in AppArmor specifically to be able to prompt to a user space application (in this case snapd), whether a given application should be allowed access to a given resource (typically file). This would work for daemons/services as well as terminal applications and also of course desktop applications. Snapd would possibly map the underlying resource access to a specific interface and ask the user via a dialog of some sort if they want that interface connected (i e. permission granted like on Android), or possibly for things like file access anywhere in $HOME, just ask the user if they want the app to be able to read/write the given file.

That's all I can comment on at this point and I really don't know how well flatpak integrates with AppArmor, so I don't know how reusable our work would be for flatpak.

**Comment by smcv** [comment]
> what I was referring to was support in AppArmor specifically to be able to prompt to a user space application (in this case snapd), whether a given application should be allowed access to a given resource (typically file)

Flatpak does not rely on any particular LSM. This is a design goal, in order to be able to provide the same behaviour on systems that use AppArmor (used by default on Debian, Ubuntu, openSUSE), systems that use SELinux (used by default on the Red Hat family), systems that use SMACK (I'm not sure whether there are any non-embedded examples), and systems that do not use a "big" LSM at all (including Debian, Red Hat, etc. when their default LSMs are disabled).

I worked with AppArmor in a previous project, and my other concern about having app frameworks prompt for fine-grained accesses as a result of AppArmor mediation would be that AppArmor is a really low-level interface, with semantics that do not necessarily map well to user-comprehensible permissions.

**Comment by smcv** [comment]
At a higher level, in general the approach taken in Flatpak and its use of portals is that we are trying hard to avoid the [dancing pig problem](https://en.wikipedia.org/wiki/Dancing_pigs): if the user is prompted for permission to do something while they are trying to carry out a particular action (or perhaps just because the app has promised them an amusing animation), then *of course* they are going to give that permission, even if it has a serious negative impact on their system integrity, confidentiality or availability, because they will perceive the prompt as interfering with what they are trying to achieve. This is why we try to make the permissions grant implicit in asking the user a question that they need to answer *anyway*, for example presenting a typical "File → Open" dialog and implicitly giving the app permission to read the file they choose.

Of course, not all portals have an obvious decision point like that, and so sometimes a request for permission (maybe with a "remember this" checkbox) is going to be the least-bad thing we can do - for example in <https://github.com/flatpak/xdg-desktop-portal/issues/649> and <https://github.com/flatpak/xdg-desktop-portal/issues/536>.

I don't think it's necessarily very useful to treat this as a feature request that can be tracked and eventually closed, because it's really broad - I fully expect that we'll be improving how Flatpak handles permissions for years to come (and other app frameworks like Snap and Android are in a similar situation). Having a permission prompt for a *specific permission* is maybe a more useful granularity for feature requests. For instance, "I want to mediate access to input devices" is an actionable feature request for which it's more achievable to say whether it has been implemented or not.

In Flatpak, that sort of feature request generally needs to happen in portals rather than in Flatpak itself, because Flatpak is not really in a position to prompt for anything - it is not a GUI.
