### ISSUE TITLE
[Feature request]: filesystem name mangling

### ISSUE THREAD

**Issue by dsvi** [flatpak/flatpak#4543]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

What do you think about reconsidering practice of filesystem names mangling for flatpak apps? The fact that a flatpak app, even when seeing user files, seeing them by weird paths, and that paths are not the same for another app.
Which makes drag&drop and copy&paste and other forms of user data sharing not possible between flatpak apps.
Even worse, the path changes after reboot. So when, for example, you have allowed (through flatseal) the Goldendict, to use some directory with dictionary files at your home, after reboot you have to repeat it again, since the old path is not valid anymore.
It also may be problematic if you try to flatpak an IDE, which expect to see it's toolsets under certain paths

And what is the reason for that mangling? File access by a sandboxed app is already well controlled.

**Comment by mwleeds** [comment]
It would be helpful if you could be more specific about which file paths you're talking about. To the best of my knowledge, there are two ways Flatpaks can access files on the host outside the app's own XDG dirs: the document portal and being granted access to a directory via `flatpak override` or Flatseal or a permission granted at build time (all three of which affect the same set of permissions).

In the portal case you're right the path is mangled but if that's what this issue is about it's probably a duplicate of https://github.com/flatpak/xdg-desktop-portal/issues/475

In the case of permissions granted to the application, in most cases the path is not mangled, e.g. `/home/Pictures` is the same inside and outside the Flatpak, with some exceptions like `/usr` and `/etc` which appear under `/run/host/` to the Flatpak, since `/usr` in the sandbox is already used by the app's runtime and I assume similar logic applies to `/etc`.

**Comment by dsvi** [comment]
For example, for goldendict at flathub, i have added through flatseal a path to my dictionaries at:

_Persistent
List of homedir-relative paths created in the sandbox_

the path was `~/foo/bar` but appeared to the app as
`/run/user/1000/foo/dsbf20e9/bar`
When i have selected it through filechooser of the app. That `dsbf20e9` was also changing after each reboot.

P.S. I think it was my mistake. When i have now added it through Filesystem/Other files, it worked. Pathnames were not mangled.
So i guess the `Persistent` is for some other purpose, even though it's not really that persistent.

**Comment by smcv** [comment]
> Persistent
> List of homedir-relative paths created in the sandbox

Yes, "persistent" paths are not the feature you thought they were: they are not a way to access parts of your home directory.

Instead, it's a way to make apps be able to read/write their own private files by using paths in `$HOME`. For example, the game OpenArena reads and writes `~/.openarena/` (it doesn't use the [XDG basedir spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)). By default, the `~/.openarena` in the sandbox is on a `tmpfs`, so changes do not persist between runs of the same application. Configuring OpenArena with `--persist=.openarena` makes it a persistent on-disk path (technically it's an alias for `~/.var/app/ws.openarena.OpenArena/.openarena`), so that it can save its settings into `~/.openarena` during one session and reload them from `~/.openarena` during the next session.

However, making the private, app-specific `~/.openarena` persist between runs of OpenArena does not give the app access to your "real" `~/.openarena` that would be used by a non-Flatpak installation from your OS.

**Comment by smcv** [comment]
> the path was ~/foo/bar but appeared to the app as /run/user/1000/foo/dsbf20e9/bar

This is a path that comes from the file-chooser portal. It is not technically possible to make it appear to the app as `~/foo/bar` without breaking other features.

**Comment by dsvi** [comment]
Ok thanks!
