### ISSUE TITLE
[Bug]: flatpak-spawn command envs not available

### ISSUE THREAD

**Issue by Murmele** [flatpak/flatpak#4562]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.

### Flatpak version

1.12.2

### What Linux distribution are you using?

Ubuntu

### Linux distribution version

20.04.3

### What architecture are you using?

x86_64

### How to reproduce

1. Run flatpak application `flatpak run --talk-name=org.freedesktop.Flatpak <application_id>`
2. Enter flatpak environment `flatpak enter <application_id> sh `
3. Test setting environment variable `flatpak-spawn --host --env=TEST=HELLO echo env`
4. Test echoing the environment variable: `flatpak-spawn --host --env=TEST=HELLO echo $TEST` 

### Expected Behavior

Step 3 should show the list of all environment variables including "TEST"
Step 4 should show "HELLO"

### Actual Behavior

Step3 shows "TEST" environment variable - OK
Step4 does not show "HELLO" - NOT OK

### Additional Information
"--talk-name=org.freedesktop.Flatpak" must be enabled for the application, otherwise it is not possible to use flatpak-spawn --host

**Comment by smcv** [comment]
> `flatpak-spawn --host --env=TEST=HELLO echo $TEST`

This evaluates `$TEST` inside the sandbox, not on the host, so it will be using the value of `$TEST` that is active inside the sandbox at the time that you ran `flatpak-spawn`. It's the same as if you ran

```
env TEST=HELLO echo $TEST
```

on the host.

If, instead, you run

```
flatpak-spawn --host --env=TEST=HELLO sh -c 'echo $TEST'
```

then that will print `HELLO`, the same as if you ran `env TEST=HELLO sh -c 'echo $TEST'` on the host.

> `flatpak-spawn --host --env=TEST=HELLO echo env`

I don't think this is really what you did, because it will print the literal string `env`. I think you meant:

```
flatpak-spawn --host --env=TEST=HELLO env
```

for which the expected result is that the output includes `TEST=HELLO`.

**Comment by Murmele** [comment]
@smcv Hello, thank you for your explanation! What does the option -c mean?

**Comment by smcv** [comment]
Sorry, this is a bug tracking system, not a technical support forum.

(Hint: https://www.google.com/search?q=%22sh%20-c%22)
