### ISSUE TITLE
[Feature request]: Add support for RISC-V 64 (RV64GC) via a standard architecture identifier

### ISSUE THREAD

**Issue by ShadowJonathan** [flatpak/flatpak#4594]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

I'd like to request architecture support for RISC-V, specifically RV64GC, as that's the most popular and widely-compatible form of the architecture at the moment.

---

A little more detail; RISC-V is a modular ISA, meaning that it only has a mandatory base, and everything else is an extension. RV64GC is basically "RISC-V 64-bit, extensions `G` and `C`", with the `G` extension being a shorthand for some other extensions;
- `M` (integer multiplication and division)
- `A` (atomics)
- `F` (single-precision floats)
- `D` (double-precision floats)
- "`Zifencei`" ("Fence" instruction)
- "`Zicsr`" (CSR instructions)

And the `I` base integer instructions (which are always required)

The `C` instruction is for "compressed" instructions, making the most popular integer operations 16-bits (instead of 32-bit)

---

I'd suggest to name this arch `riscv64gc`.

---

#### A note for the future

Soon enough the `V` extension will be ratified and available in CPUs, allowing SIMD-like Vector operations.

When that happens, an increase in interest in a `riscv64gcv` architecture might appear, as the vector operations provide much-wanted extra speed.

A note regarding that; any application compiled for `riscv64gc` can run on `riscv64gcv`, but not vice versa, this is effectively a similar situation as `i386` being able to run on `amd64`, but not vice versa.

Note: Unlike x86, 32-bit versions of RISC-V-compiled programs are not automatically compatible with 64-bit versions.

---

RISC-V is an open-source ISA, and i'd love for flatpak to add support for it, to make it possible to run programs on an as-least proprietary system as possible :)

The RISC-V ISA Manual is readable [here](https://five-embeddev.com/riscv-isa-manual/), with sources [here](https://github.com/riscv/riscv-isa-manual)

**Comment by smcv** [comment]
> A note regarding that; any application compiled for riscv64gc can run on riscv64gcv, but not vice versa, this is effectively a similar situation as i386 being able to run on amd64, but not vice versa.

This seems more like the relationship between ARMv7 and ARMv5, or i686 and i586: both ISAs are fundamentally the same, but one has more instructions in its baseline than the other.

What is the Linux architecture name (`uname -m`) for these various riscv64 variants? Do they all have the same `uname -m`, or different?

The way Linux distributions have generally handled this is to choose a baseline for each ISA (or sometimes more than one baseline for each ISA), and say that for anything in their distribution, CPUs above the baseline are supported and CPUs below the baseline are not. For example, the baseline for Debian `armhf` is ARMv7 with VFP hardware floating point, and the baseline for Debian `i386` is a specific model of AMD Geode (which is basically Intel i686, but with one instruction missing).

Flatpak runtimes work similarly: whatever baseline has been chosen for the `gcc` in the freedesktop.org SDK, that's effectively going to be the baseline for all Flatpak apps built against that SDK.

Flatpak currently classifies architectures by doing the equivalent of `uname -m`, with some normalizations (`arm*` -> `arm`, `i?86` -> `i386`), so if you ask to install `com.example.Foo//stable` on a machine with `uname -m` -> `i586`, Flatpak will actually try to install `com.example.Foo/i386/stable`.

**Comment by smcv** [comment]
For comparison, according to <https://wiki.debian.org/RISC-V>, the `riscv64` Debian architecture uses the RV64GC baseline.

**Comment by smcv** [comment]
Flatpak does not actually contain very much architecture-specific code, so building Flatpak for riscv64 probably already works, without anyone with Flatpak commit access having to do anything. The main architecture-specific requirement is that `libseccomp` needs to be ported to each new new architecture, but it seems like that has already been done for riscv64.

According to <https://buildd.debian.org/status/package.php?p=flatpak>, the Debian `flatpak` package is already building successfully on riscv64 and passing unit tests. So this issue can probably already be closed?

Flatpak is a "federated" system which can install from multiple locations, similar to apt, dnf/yum/zypp, and Android `.apk`. However, most Flatpak apps are on Flathub: if Flatpak is like `.apk`, then Flathub is a bit like Google Play Store.

Having riscv64 infrastructure for Flathub would be a feature request for Flathub, not for Flatpak itself. The main thing that will be difficult (and expensive!) there is that someone will need to provide physical, virtual or emulated riscv64 machines that can do the actual app builds. At the moment, Flathub only has x86_64 and aarch64 machines.

**Comment by smcv** [comment]
> For comparison, according to https://wiki.debian.org/RISC-V, the `riscv64` Debian architecture uses the RV64GC baseline.

More specifically:

> The Debian port uses RV64GC as the hardware baseline and the lp64d ABI (the default ABI for RV64G systems).
>
> Making the C extension a part of the default hardware baseline for general-purpose binary Linux distributions has been agreed upon between Fedora porters, Debian porters and members of the RISC-V foundation. According to the chairman of the board of the RISC-V foundation, the foundation will provide "a profile for standard RISC-V Unix platforms that will include C as mandatory".

Binary Linux distributions like Debian and Fedora will probably want to handle the `V` extension in the same way they handle every other CPU extension, like NEON on ARM, Altivec on PowerPC, SSE on i386, and AVX2 on x86_64, which is:

* if the extension is not in the baseline for a particular version, then applications can only use that extension's instructions after checking CPU feature flags at runtime and finding that it does exist on this CPU;
* eventually, when the extension is widespread enough, the next version of the distro will raise its baseline to include that extension, apps can start using it unconditionally, and users of older CPUs need to choose: either upgrade their hardware, or stay on an older version of the distribution

I suspect that Flatpak app sources like Flathub will do the same.

**Comment by ShadowJonathan** [comment]
Ah, thank you!

> * if the extension is not in the baseline for a particular version, then applications can only use that extension's instructions after checking CPU feature flags at runtime and finding that it does exist on this CPU;

Agreed, I recently saw an example of this developing on rust's `portable-simd` standard library feature, which'd automatically switch to SIMD instructions, or emulated ones, depending on the CPU arch the program is then-presently running on.

> Having riscv64 infrastructure for Flathub would be a feature request for Flathub, not for Flatpak itself.

Thanks for clarifying that, I guess my issue is destined for Flathub.

---

I'll close this issue, but I have one last question @smcv; Is there anywhere where i might be able to file an issue to settle on either `riscv64gc` or `riscv64` for it's official arch identifier?

**Comment by smcv** [comment]
> Is there anywhere where i might be able to file an issue to settle on either riscv64gc or riscv64 for it's official arch identifier?

That's something for this repository; reopening for now.

The architecture identifier is whatever the Linux kernel puts in the `machine` member of `struct utsname` when we call `uname`, unless you open a merge request here that adds it as a special case (similar to the ones used for `i586` → `i386`, `armv7hl` → `arm`, and little-endian `mips` → `mipsel`).

Note that if you add a special case, then that will break compatibility between the Flatpak packages already built by Debian's `riscv64` port, and new Flatpak packages. As such, we should only do this if there is genuinely a really good reason for it. If the Linux kernel has chosen a reasonable string for the `(struct utsname).machine`, then I think we should use that as-is.

Similarly, by default Flatpak will not allow any cross-architecture packages to be installed. If there are "multilib" situations that are expected to work, like `i386` user-space on `x86_64` kernels or `arm` user-space on `aarch64` kernels, then Flatpak will need a special case to allow that.

In general, Flatpak has an architecture identifier for each interoperating ABI, the same as Debian architectures and most Linux kernel architectures. When I say "interoperating ABI", I mean: can you link together `libfoo.so.0` built for the "old" ISA and `libbar.so.1` for the "new" ISA into the same executable's process space, and have them successfully call functions in each other? If you can, then the "old" and "new" ISAs have the same ABI.

For example, `x86_64` is not the same ABI as `i386`, because they disagree on fundamental things like how many bits in a `long` and how many arguments can be passed in registers. An `x86_64` kernel happens to be able to run `i386` Flatpak apps, but they are not "equal".

However, all `x86_64` CPUs are the same ABI: two libraries can call each other's functions, regardless of whether one library requires SSSE3 and the other does not, because they agree on things like how many bits in a `long` is and how to put arguments in registers/on the stack. Flatpak and the kernel would call both libraries `x86_64`, and Debian would call them both `amd64`, even though one of them requires SSSE3 and one doesn't.

We probably don't want to have different architecture identifiers for `riscv64gc` and `riscv64gcv` and `riscv64gcvomgwtfbbq`, the same way we don't have different architectures for `x86_64`, `x86_64+avx2+ssse3` and `x86_64+avx2+ssse3+cx16+sgx+ssse4.1+whatever_intel_thinks_of_next` - that would scale really badly. For riscv64 to be practically useful, distributions will have to decide on a reasonable, interoperable baseline - and from what both you and the Debian riscv64 porters have said, it seems that RV64GC is a good value for that baseline.

If someone does a 32-bit RISC-V ABI that is practically useful, then we *would* want to separate `riscv32` from `riscv64`.

**Comment by ShadowJonathan** [comment]
Note: `riscv32` is practically an entirely different instruction set, and not interoperable with `riscv64` like `x86` would be.

---

I currently have no idea how the linux kernel handles or differentiates between different riscv64 versions, the problem could be it tags it at once, while it could be `RV64IMAC`, another popular combination. Unfortunately i can't contribute much to that, so i'll leave it here and open the other issue at flathub, thanks for your help!

**Comment by smcv** [comment]
> I currently have no idea how the linux kernel handles or differentiates between different riscv64 versions

Since you're asking other people to do an unknown amount of work to support new architectures, I assume you already have at least a qemu-emulated riscv64 machine where you can answer this question by running `uname -m`.

**Comment by ShadowJonathan** [comment]
Will do, I currently dont have this setup ready, but i'll put it on the todo list 👍

**Comment by ShadowJonathan** [comment]
I started a Linux RISCV64 machine via [this](https://github.com/janvrany/riscv-debian/tree/linux-5.6) method, and although it didn't properly finish the rootfs, it did boot properly.

The `uname -m` just reported "`riscv64`", while the machine was running `RV64GC`, so i'm assuming this is the baseline for that architecture.

---

Though, RISCV is looking to standardise the extensions required for "rich OS stacks", and they provide a complete set of mandatory extensions for such a "profile" [here](https://github.com/riscv/riscv-profiles/blob/master/profiles.adoc#71-rva22u64-profile). so it's safe to say that this could be the baseline for `riscv64`.

The profile also calls `V` as a supported optional extension, I'm going to guess that support will be handled the same way AVX-512 is handled; detect functionality at runtime, and take advantage if it does.

**Comment by smcv** [comment]
> The `uname -m` just reported "`riscv64`"

Then this architecture's name in Flatpak is `riscv64`.
