### ISSUE TITLE
Multiple branches of application overwrite each other desktop launcher

### ISSUE THREAD

**Issue by Barthalion** [flatpak/flatpak#460]
I have two manifests for one project. One builds it from the git master branch (and has `branch` set to `master`), the other uses latest stable release (`"branch": "stable"`). Both are correctly built and exported into one repository.

Now, if user attempts to install development version of the app, and then install stable one, only one desktop launcher is accessible. As I understand, `desktop-file-name-suffix` affects only `Name` field of the launcher, while in fact both flatpaks ship the same file, overwriting each other (as I verified in `.local/share/flatpak/exports/share/applications`). I guess that's not by design, and user could expect to have possibility to easily switch between multiple branches.

I'm using flatpak 0.8.0.

**Comment by alexlarsson** [comment]
You can install multiple versions of the same app-id at the same time, but only one can be "current", which means its "exported files" (including desktop files, icons, dbus service files, etc) are exported to the global scope (ie. only one is visible by the desktop). You can manually start the individual versions with flatpak run, or you can change which one is current using flatpak make-current.

If you really want to have both visible in the UI you need to rename one of them.
For instance, my nightly builds of gimp are called org.gimp.GimpDevel to avoid a conflict with org.gimp.Gimp. However, when you do this, make sure you also edit the desktop file so that the name (and possibly icon) are different for the two version, or things will be very confusing.

**Comment by Barthalion** [comment]
Right, I found make-current in the documentation after filling this issue. Also reading more about how flatpak works it makes perfect sense now. Thanks for explanation.
