### ISSUE TITLE
[Bug]: Global Flatpak overrides (e. g. --nofilesystem=home) can be circumvented by manifests specifying explicit paths (e. g. --filesystem=~/.ssh)

### ISSUE THREAD

**Issue by esjarc** [flatpak/flatpak#4654]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.

### Flatpak version

1.12.2

### What Linux distribution are you using?

Fedora Silverblue

### Linux distribution version

35

### What architecture are you using?

x86_64

### How to reproduce

1. Set a global override to deny access to certain directories: `flatpak override --nofilesystem='home' --nofilesystem='host' --system`
2. Install a Flatpak application that requests access to a path within one of the blacklisted directories, e. g. [Minigalaxy](https://flathub.org/apps/details/io.github.sharkwouter.Minigalaxy) requests access to `--filesystem=~/GOG Games:create`.
3. Open the Flatpak application and try to access said path or run `flatpak info --show-permissions io.github.sharkwouter.Minigalaxy`

### Expected Behavior

The application should not be able to create and access the directory if access to the parent directory (in this case my home folder) has been denied. Therefore the application should place its folder within their `~/.var/app/appid/` path.

### Actual Behavior

The application has granted itself permission to create and access an arbitrary file or folder (`~/GOG Games`) in my home directory, even though a global override disallows access to `home` and `host`.

### Additional Information

Unfortunately applications can gain access to arbitrary directories, even if access to the parent directory has been denied by a Flatpak override, by explicitly specifying the paths in their manifest. As far as I see it, this makes the global `home` or `host` override completely useless, as applications can still silently (e. g. when GNOME Software updates the Flatpak automatically) gain access to any arbitrary directory on my computer, including write access to my bashrc/zshrc (= leaving the sandbox), by adding a filesystem permission to their manifest.

If this is behaviour is not a bug, but intentional: [How](https://reddit.com/r/flatpak/comments/rvqhd3/) can someone prevent applications from creating, accessing, reading and modifying arbitrary directories? If there is no way to achieve this, would it be possible to add said functionality to Flatpak (e. g. something like `nofilesystem=~/*`)? How would one deal with exceptions in this case, e. g. allowing access to `xdg-documents`, while denying access to the rest of `home`?

**Comment by mwleeds** [comment]
There is already a patch that will fix this behavior, and it will be merged soon.

**Comment by mwleeds** [comment]
In the future please report security sensitive issues privately, as detailed here: https://github.com/flatpak/flatpak/blob/master/SECURITY.md

**Comment by esjarc** [comment]
> There is already a patch that will fix this behavior, and it will be merged soon.

Thank you for fixing this issue!

> In the future please report security sensitive issues privately,

Thanks for reminding me and sorry for reporting it publicly, I will do better next time!
(I thought about reporting it privately, but as it had already been posted on reddit, I didn't consider it necessary.)

**Comment by mwleeds** [comment]
Fixed by https://github.com/flatpak/flatpak/commit/445bddeee657fdc8d2a0a1f0de12975400d4fc1a

**Comment by smcv** [comment]
> The application should not be able to create and access the directory if access to the parent directory (in this case my home folder) has been denied

This was actually not how it was meant to work. In general, `--nofilesystem=x` only cancels out a previous `--filesystem=x`: it deliberately did not cancel out `--filesystem=x/y`.

Otherwise, if an app asks for access to something like `~/Documents` in its manifest, you would find that it was not possible to do potentially useful things like `flatpak override --nofilesystem=~/Documents --filesystem=~/Documents/zoom` to give it access to a single subdirectory instead of the whole of the requested directory.

However, the solution that was chosen (while under embargo) for https://github.com/flatpak/flatpak/security/advisories/GHSA-8ch7-5j3h-g4fx in 1.12.3 and 1.10.6 was to special-case the `home` and `host` keywords so that **those**, and **only** those, act as an override. See the release notes and documentation for the new semantics.

> How would one deal with exceptions in this case, e. g. allowing access to xdg-documents, while denying access to the rest of home?

That's a good question. The current answer is to use absolute paths like `--filesystem=/home/me/Documents` in your overrides: unlike the app maintainer, you know the path to your documents directory. This will take precedence over `--nofilesystem=home`, although not `--nofilesystem=host` (I think).

If you have a better design, please propose it as an enhancement on a separate issue.

**Comment by Erick555** [comment]
It's worth noting that discarding filesystem access wouldn't result in placing `~/GOG Games` or `~/.ssh` under `~/.var/app/appid/` but they will be placed in private tmpfs instance in sandbox which will be gone after app is closed therefore breaking app functionality. You would need to add `--persist=xxx` option additionally.

**Comment by smcv** [comment]
> However, the solution that was chosen (while under embargo) for [GHSA-8ch7-5j3h-g4fx](https://github.com/flatpak/flatpak/security/advisories/GHSA-8ch7-5j3h-g4fx) in 1.12.3 and 1.10.6 was to special-case the `home` and `host` keywords so that **those**, and **only** those, act as an override. See the release notes and documentation for the new semantics.

This caused regressions, and was reverted in the 1.12.4 and 1.10.7 releases, returning `--nofilesystem=host` and `--nofilesystem=home` to the meanings that they had in 1.12.2.

Instead, a new `--nofilesystem=host:reset` option disables filesystem permissions from the app manifest or a lower-precedence layer of overrides (which is identical to the changed meaning of `--nofilesystem=host` in 1.12.3).

There is currently no `--nofilesystem=home:reset` equivalent, because it was not practical to implement that in a completely safe way, which could lead to users of that option being given a false sense of security.

**Comment by smcv** [comment]
> applications can still silently (e. g. when GNOME Software updates the Flatpak automatically) gain access [...] by adding a filesystem permission to their manifest

Sorry, you will need to take that up with the maintainers of the application that carries out automatic updates (and if you believe it is a security vulnerability, please report it privately to start with). The `flatpak(1)` CLI is careful to avoid updating apps that have gained new permissions without asking the user first, but other UIs like GNOME Software make their own UX decisions which are not under our control.

Flatpak has many permissions that can be granted, or not granted, to an app, some of which can be used to escape the sandbox. In many cases, Flatpak cannot know whether a particular permission is a sandbox escape or not, because it allows communication with interfaces on the host system, and in general it is not possible to know whether those interfaces allow arbitrary code execution or not.

**Comment by mwleeds** [comment]
GNOME Software does have a policy of not automatically updating Flatpaks which have new permissions in the update. If you discover that it's not following that policy, please report the bug [here](https://gitlab.gnome.org/GNOME/gnome-software/-/issues).
