### ISSUE TITLE
[Feature request]: How-to use systemd-run with memory limitation on flatpak apps

### ISSUE THREAD

**Issue by ruanformigoni** [flatpak/flatpak#4659]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

Hi,

So for context, I use `zram` to reduce the memory usage on some apps, basically the ram itself is used as swap, only it is compressed to fit. For example, if you wanted to open brave with memory limitations, you would do:

`systemd-run --user -G -p MemoryHigh=1G /usr/bin/brave-browser-stable %U `

And around 1G of usage, the pages start to be compressed in memory. The thing is that with flatpak, if you do something like:

`systemd-run --user -G -p MemoryHigh=1G flatpak run --branch=beta --arch=x86_64 com.brave.Browser`

The memory limitation seems to apply only to the flatpak run command, and not the actual application opened by it, is there a way to prepend this command the binary?

Edit 1:

If you go to `files/share/applications/app.desktop` you can modify the desktop entry to run with systemd-run, but the program stops working.

**Comment by smcv** [comment]
`flatpak run` tries to put the app process in a scope such as (in your case) `app-com.brave.Browser-*.scope`, with `*` replaced by an arbitrary suffix. This means that anything you apply via `systemd-run` won't work, but instead you can create a file like `~/.config/systemd/user/app-flatpak-com.brave.Browser-.scope.d/memory.conf` (the trailing `-` immediately before `.scope.d` is intentional) with contents like

```
[Scope]
MemoryHigh=1G
```

and those `systemd.resource-control(5)` parameters will apply to all instances of that app.

**Comment by ruanformigoni** [comment]
It worked perfectly, thank you!
