### ISSUE TITLE
"Failed to write file “/run/user/1000/.flatpak/3739882875/info.W6K0G1”: write() failed: No space left on device" but I have 190 GB free space...

### ISSUE THREAD

**Issue by RDKRACZ** [flatpak/flatpak#4726]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/master/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.4

### What Linux distribution are you using?

Clear Linux

### Linux distribution version

Linux clearlinux 5.16.5-1120.native #1 SMP Tue Feb 1 10:03:19 PST 2022 x86_64 GNU/Linux

### What architecture are you using?

x86_64

### Expected Behavior

Flatpaks should run and install fine because there is plenty of space on the disk

### Actual Behavior

When trying to run Dialect
`Failed to write file “/run/user/1000/.flatpak/3739882875/info.W6K0G1”: write() failed: No space left on device`

When trying to use ProtonUp-Qt 
`[Errno 28] No space left on device`

**Comment by smcv** [comment]
> Failed to write file “/run/user/1000/.flatpak/3739882875/info.W6K0G1”: write() failed: No space left on device

Something (probably not Flatpak) has filled up `/run/user/1000` (`$XDG_RUNTIME_DIR`), which is an in-memory filesystem, typically limited to 10% of the amount of RAM you have (so that a misbehaving program can't cause it to fill up RAM completely). Please check what files and directories exist in `/run/user/1000`, and report this as a bug in whatever component filled it up.

Running out of space in `$XDG_RUNTIME_DIR` will affect lots of things, not just Flatpak.

The intended use of `/run/user/*` is that only inter-process communication sockets and small files (a few K) are written there.

> because there is plenty of space on the disk

This particular write is going to an in-memory location, not to your disk.

**Comment by xpufx** [comment]
tmpfs           3.1G  2.0M  3.1G   1% /run

and I just started having the same issue today after installing and removing a bunch of flatpaks.

**Comment by smcv** [comment]
> tmpfs 3.1G 2.0M 3.1G 1% /run

`/run/user/1000` (or whatever directory is appropriate) is usually a separate tmpfs with its own independent size limit.
