### ISSUE TITLE
[Feature request]: URI to launch installer for a FlatPak

### ISSUE THREAD

**Issue by imciner2** [flatpak/flatpak#4745]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

I think it would be useful if FlatPak could expose a URI (such as `flatpak://`) that could be used to trigger the installation of a FlatPak using an appropriate installer (e.g. through either Gnome Software or the actual `flatpak` command). This would be useful for download sites that provide the name of FlatPaks that live in a repo (such as the FlatHub site), since currently you have to copy and paste a command into the terminal to install the FlatPak. Instead, this would allow a link on the site to trigger the installation program for the user.

**Comment by smcv** [comment]
This already exists, and even better, it's done with a MIME type rather than defining an entire URL scheme.

For example, on https://flathub.org/apps/details/com.valvesoftware.SteamLink you'll see that the `[Install]` button points to https://dl.flathub.org/repo/appstream/com.valvesoftware.SteamLink.flatpakref, which is of the type documented in `flatpak-flatpakref(5)`.

GNOME Software and KDE Plasma Discover (with the Flatpak plugin for each) support the appropriate MIME type.

> currently you have to copy and paste a command into the terminal to install the FlatPak

`flatpak(1)` is a CLI program, which does not have a graphical user interface and is not appropriate to be a MIME type or URL scheme handler. To install Flatpak apps in a user-friendly way, use a package-management application that supports installing Flatpak apps, such as GNOME Software or Plasma Discover.

**Comment by razzeee** [comment]
Unfortunately this isn't that user friendly anymore, as all browsers I know of, now only download that file and then expect you to open it / choose the handler you want it to be handled by.

I tested a bit with https://www.freedesktop.org/software/appstream/docs/sect-AppStream-Misc-URIHandler.html#spec-asuri-button which works, but might show apps that are not flatpaks, doesn't handle branches etc.
But the user experience coming from a webpage was way nicer.

So right now I'm inclined to say, we would want something like a `flatpak://` uri (but with branches and a repo to install if needed ideally)
