### ISSUE TITLE
[Feature request]: Separate icon per-program for apps that launch smaller programs, like Steam -> games

### ISSUE THREAD

**Issue by RushingAlien** [flatpak/flatpak#4751]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

Hello. This is quite a minor issue, just would like people to know. Apps such as Steam or Bottles will only show the Steam Icon on all running process under it.
Usually, when running a game in Steam, the game shows its own icon in taskbar/dash/task manager.

But it is not the case with Steam Flatpak as per https://github.com/flathub/com.valvesoftware.Steam/issues/855#issuecomment-1012325196.

Is this a limitation in Flatpak's design, or is it some other deal?

### Attachements 

![Bottles Flatpak](https://user-images.githubusercontent.com/80886145/154271495-c55998de-54cc-40e9-9828-1c2225d3b15e.png)
![Steam Flatpak](https://user-images.githubusercontent.com/80886145/149373587-36f46ffa-3d24-43df-88f3-761a7fb07c26.png)

**Comment by RushingAlien** [comment]
#https://github.com/flathub/com.valvesoftware.Steam/issues/855#issuecomment-1012325196.

**Comment by smcv** [comment]
This is working as designed, although the design is not ideal for things like Steam.

Flatpak puts a security boundary between each app, and can tell which app each process belongs to. For example, everything you run through Steam is counted as part of Steam.

Steam is strange from a Flatpak perspective, because it isn't really an app: it's really an app framework, with its own smaller apps (mostly games) included in it. However, there is no security boundary between Steam and each game, and as far as the Flatpak app framework is concerned, they are all equivalent.

**Comment by RushingAlien** [comment]
I have friends who use KDE, and flatpak bottles and steam there seems to show independent icons.
![gambar](https://user-images.githubusercontent.com/80886145/158878774-e3939d7f-00da-4566-87d9-fbe85e3ebc2d.png)

**Comment by smcv** [comment]
> I have friends who use KDE, and flatpak bottles and steam there seems to show independent icons.

This probably means they are using X11 rather than Wayland, and their compositor/window manager is trusting the application. GNOME uses Wayland by default, which provides stronger sandboxing (better isolation between apps), and one of the costs of this is that it doesn't let apps say "this is my icon" and trust that they are telling the truth.

In the protocols traditionally used with X11, the icon is whatever the app says it is, so a Steam game could set its icon to something you will trust (maybe Firefox) and the window manager will obediently put a Firefox icon on it. This is good if you want different smaller programs to have different icons, but it is not so good if you want to be sure that you are typing your bank account password into Firefox and not into a game that is pretending to be Firefox.

**Comment by smcv** [comment]
The decision about what icon to display is really up to the compositor/window manager (in your case GNOME Shell) rather than the app framework. If GNOME Shell wanted to let apps choose their own icons, then there could be a protocol by which the app communicates its desired icon to GNOME. However, I suspect the GNOME Shell maintainers don't want to do that, because of the concern about one app pretending to be another.

**Comment by RushingAlien** [comment]
Ah, I understand, thanks.
