### ISSUE TITLE
[Feature request]: flatpak run command does not use polkit

### ISSUE THREAD

**Issue by jaudiger** [flatpak/flatpak#4757]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

I want to grant additional permission to my user when running a program. Here I'm trying to run Wireshark, and my current user belongs to the group `wireshark` which in turn provides the ability to record packets on the network interfaces.

 I was looking to add a new polkit rule which could apply on to explicit grant the permission when the current user belongs to the right group:

```bash
flatpak run org.wireshark.Wireshark
```

But I didn't a such action ID to attach my rule. But maybe I'm not looking in the correct direction.

If you have an other idea, I would like to test it.

**Comment by smcv** [comment]
Sorry, Flatpak is designed to give the program you're running *fewer* privileges than ordinary user processes.

Applying *more* privileges would require making `flatpak run` into a security boundary, which would require auditing it all to prevent a malicious user from using it to elevate their privileges, and then distrusting the user in all subsequently-added features - that's a heavy maintenance cost.

> my current user belongs to the group wireshark which in turn provides the ability to record packets on the network interfaces

Not exactly. If your system works the way Debian does, then your current user belongs to the group `wireshark`, which is the only group that is allowed to run `/usr/bin/dumpcap`; and `dumpcap` is setcap `cap_net_admin,cap_net_raw=eip`, which is a more limited form of being setuid root. Having access to the `CAP_NET_ADMIN` and `CAP_NET_RAW` capabilities is what gives `dumpcap` the ability to spy on network interfaces, and then Wireshark runs `dumpcap`.

Flatpak runs programs under `bubblewrap`, which uses the `NO_NEW_PRIVS` process flag to make sure processes inside the sandbox can't become privileged by running a setuid or setcap executable. That means Wireshark inside the sandbox would be unable to gain those capabilities by running `dumpcap`, even if your system copy of `dumpcap` was visible to it.

`NO_NEW_PRIVS` is quite an all-or-nothing mechanism. We have to use it, because otherwise various sandbox escapes would be possible; but then it turns off *all* new privileges, even the ones that might not actually be possible to use in a sandbox escape.

**Comment by rusty-snake** [comment]
Related:
- https://github.com/flathub/org.wireshark.Wireshark/issues/4
- https://github.com/flathub/org.wireshark.Wireshark/issues/27

The wireshark flatpak is ATM (and likely for a long time?) only useful to inspect pcap files captured via tshark, tcpdump, ….

**Comment by smcv** [comment]
> The wireshark flatpak is ATM (and likely for a long time?) only useful to inspect pcap files captured via tshark, tcpdump, ….

Yes. Flatpak is not designed to give programs additional privileges: indeed, it's designed to give programs *fewer* privileges (sandboxing). If this means programs that want additional privileges have reduced functionality when packaged as Flatpak apps, then those programs are going to have reduced functionality, and their maintainers will have to choose which is better: providing a Flatpak app with reduced functionality, or not providing a Flatpak app.

A portal-based interface with a more-privileged service on the host and a less-privileged GUI app in the Flatpak sandbox, as discussed on https://github.com/flathub/org.wireshark.Wireshark/issues/4 already, is likely to be the only way this can fit into the way Flatpak works.

**Comment by jaudiger** [comment]
Thanks for the explanation @smcv. I completly understand the design choice to enforce the security of the Flatpak applications. I think we can just close this issue.

**Comment by Xyndra** [comment]
This is nice and all, but there are certain flatpaks that handle data which, I personally at least, really do not like being in the hand of just about anyone without asking for a password. For example, a notes app where I write private entries. It would be really nice if I could restrict this to require authorization, even if it isn't passed through to the application

**Comment by rusty-snake** [comment]
@Xyndra where are the notes stored? In a local file that you can access with every other program?

Such authorization must be provided by the app to encrypt data or store it on a server (which takes the authentication).

**Comment by smcv** [comment]
> there are certain flatpaks that handle data which, I personally at least, really do not like being in the hand of just about anyone without asking for a password. For example, a notes app where I write private entries

If a malicious user is logged in to your computer as you, and has the opportunity to change configuration, then that is usually "game over" from a security point of view: they have all the same privileges that you do, and can set up a back door that will let them back in later. To prevent this, use a screen lock (screensaver with a password), or log out.

If you want strong separation between desktop environments of different privilege levels, and you are willing to sacrifice some convenience to achieve it, then you could create two user accounts and switch between them by logging out and back in, or by using "fast user switching" (Power icon → Switch User in GNOME, or the equivalent feature in some other desktop environments). Yes, this is inconvenient, but any level of isolation less than this is just going to be "security theatre" that does not protect you from a knowledgeable attacker.

One way to partially protect private data is to encrypt it. However, if you encrypt it, you will need to decrypt it later, most likely by typing a password. If an attacker has previously modified your desktop environment configuration to include a keylogger (perhaps by attaching debugging tools), then they have your password, and they can decrypt the data later.

Solving this is not a design goal for Flatpak, and Flatpak cannot protect you from actions taken by a more-privileged (non-sandboxed) program. From Flatpak's point of view, the desktop environment and non-sandboxed apps (desktop environment/window manager/app launcher, file manager, text editor, terminal, etc.) are the [trusted computing base](https://en.wikipedia.org/wiki/Trusted_computing_base) for your session. Sandboxed Flatpak apps cannot access files outside their sandbox (unless they have been configured with sandbox-escaping parameters like `--filesystem`), but non-sandboxed apps like your file manager are outside Flatpak's control, and can access files "owned" by Flatpak apps. Those non-sandboxed apps can also impersonate Flatpak apps, or gain control over Flatpak apps.

If you think about it for a while then you'll realise that this is the only possible design, because Flatpak itself is just another ordinary program in your session, so it cannot possibly have special powers that your other non-sandboxed apps do not have - and you start it from your desktop environment's app menu (or from your terminal), so if an attacker has subverted your desktop environment or your terminal, you have already lost. Prompting for a polkit password is not useful if the attacker has had the opportunity to gain control over the program that prompts for the password.

**Comment by Xyndra** [comment]
> If a malicious user is logged in to your computer as you, and has the opportunity to change configuration, then that is usually "game over" from a security point of view: they have all the same privileges that you do, and can set up a back door that will let them back in later. To prevent this, use a screen lock (screensaver with a password), or log out.

Yeah sure but it isn't someone trying to hack me, I just use my laptop at some places like my school for example, and I don't want people messing with my data when I go a few steps away. I am not scared that they want to hack me or something, but they might go through my files.

> If you think about it for a while then you'll realise that this is the only possible design, because Flatpak itself is just another ordinary program in your session, so it cannot possibly have special powers that your other non-sandboxed apps do not have - and you start it from your desktop environment's app menu (or from your terminal), so if an attacker has subverted your desktop environment or your terminal, you have already lost. Prompting for a polkit password is not useful if the attacker has had the opportunity to gain control over the program that prompts for the password.

I just don't want it to be accessible easily, and Polkit helps by simply asking for a password, which others don't have even if I leave my laptop for a few seconds whilst still being logged in
