### ISSUE TITLE
[Feature request]: Flatpak apps on Android. 

### ISSUE THREAD

**Issue by Mesum-Hussain** [flatpak/flatpak#4766]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

I know it's a weird request, but I was wondering if it's possible to do that (as Alpine is supported and makes me hopeful about Android support). Besides there would be a lot of benefits of having this feature as I will explain below. 

It would be really wonderful to have this feature as the tech industry is leaning more and more towards 2 in 1 devices and and both Android and iOS are optimising for Desktop mode, and having the ability to use Linux apps on Android would be really powerful feature to have in a hand held tablet. If Flatpak apps becomes capable of running on Android, then perhaps some community members might be able to make a store app to sideload Flatpak apps on Android (or perhaps F-droid could host them). 
Besides, because both Gnome and KDE are working on making apps responsive so that they can work on Linux phones, my idea seems more practical to achieve once most of the apps becomes responsive. I don't really trust Linux handheld devices to become usable any time soon (or become usable at all), so it would be great to have an Android tablet which is capable of running Linux apps while Linux tablets catch up. Besides I think it's a much better idea to run Linux apps natively on Android tablet rather than running Android apps in a VM like Waydroid/Anbox in a Linux tablet, because millions of closed source Android apps aren't becoming native to Linux ever, but the community can port open source Linux apps to Android if the option is available. Would also be really beneficial for the mainstream popularity of open source Linux apps as there wouldn't be options like Adobe apps or other propitiatory Windows/Mac exclusive apps which are reluctant to port to Linux, and people would have to use what's available (open source Linux apps).    

I genuinely think handheld computing is going to be the future, and this is going to be a worthwhile project to take up. Besides, if Flatpak decide to take up this project, then perhaps AOSP maintainers might consider to make changes to enable Flatpaks to run on Android and who knows, even Google might consider integrating Linux apps into the Play Store.....After all it will be very beneficial to leverage pre-made desktop apps (like Apple is doing for iPad) to provide a wonderful 2 in 1 experience......And Linux app are the best option for doing so, because there is a possibility to be able to run them natively as opposed to Windows app which would require a VM or a compatibility layer for sure (which I am assuming will be very difficult, seeing WINE)! 

I am expecting this to be accomplish-able till 5 years down the line. 
And I am getting so excited thinking of the possibility of being able to run my PC games on an Android tablet through Proton (which will probably improve so much till the time this goal is achieved). 
Also optimistic because of the ARM revolution brought by Apple, so that means Android tablets will come with more powerful ARM chips a few years down the line.

Hope the maintainers consider my request.

Thanks!

**Comment by smcv** [comment]
This is really more like a feature request for Android OS vendors than a feature request for Flatpak. Flatpak needs to run at the OS level, and cannot simply be installed onto Android as an app; so it would be up to an OS vendor (perhaps an AOSP-based Android variant) to add Flatpak to their OS, if they want to do that. If your OS vendor has no interest in supporting that, then you will not get that feature, however much anyone else might want it.

If an OS vendor *does* want to do that, then it's going to need a lot of design and implementation work, which would need to be driven by people who want this, have a lot of knowledge of the relevant OS designs, and have a lot of time available to make it all fit together. The assumptions made by apps designed for Android and apps designed for desktop Linux are very different, so an Android-based OS that wanted to support apps originating from desktop Linux would have to provide a Wayland- or X11-compatible display server, a PulseAudio-compatible audio server, a D-Bus session bus, and so on - the same sort of scope as Waydroid/Anbox, but in reverse.

**Comment by Mesum-Hussain** [comment]
> This is really more like a feature request for Android OS vendors than a feature request for Flatpak. Flatpak needs to run at the OS level, and cannot simply be installed onto Android as an app; so it would be up to an OS vendor (perhaps an AOSP-based Android variant) to add Flatpak to their OS, if they want to do that. If your OS vendor has no interest in supporting that, then you will not get that feature, however much anyone else might want it.
> 
> If an OS vendor _does_ want to do that, then it's going to need a lot of design and implementation work, which would need to be driven by people who want this, have a lot of knowledge of the relevant OS designs, and have a lot of time available to make it all fit together. The assumptions made by apps designed for Android and apps designed for desktop Linux are very different, so an Android-based OS that wanted to support apps originating from desktop Linux would have to provide a Wayland- or X11-compatible display server, a PulseAudio-compatible audio server, a D-Bus session bus, and so on - the same sort of scope as Waydroid/Anbox, but in reverse.

I understand. I have just issued a feature request in AOSP issue tracker too. I hope that they show some interest in it. But having this feature in Android, I think would be very beneficial for Android in the long run as Linux gaming is also going to improve a few years down the line which they could easily take advantage of to get an edge over iPad. People might prefer Android tablets merely because of gaming in the future probably, if they successfully implement this feature. I mean just imagine being able to play all your favourite PC games on your Android phone/tablet. Looks a great selling point to me at least.

**Comment by scientiac** [comment]
I wast thinking about the same thing and came here to check if it was a thing and the first issue I see is "Flatpak on Android".  (Is this 'Deja Vu'?)

I think android tablets would have a much better experience if they could run a 'Desktop App' and might as well come to be on power with the Ipad OS. Things could actually be done with a tablet. 

Softwares like gimp, libre office, krita, kdenlive will also come to the spotlight as there will (probably) be no other apps good enough to compete with them with an android base.

I don't see Samsung " not wanting " the flatpak support if it could make their tablets more usable then ever. I have tried using pure linux OS on my "originally" android device 'with halium(UBport's Ubuntu Touch)' and they seem to lack many things and I keep comming back to custom ROMs.

Testing this with the (AOSP project)Lineage OS could be benificial because they got a very large list of supported devices as well if it ever become a thing.

**Comment by smcv** [comment]
I'm closing this feature request, because it is not really actionable for the Flatpak maintainers. We do not have the resources to go and modify Android distributions to be technically able to run Flatpak, and then do the necessary politics to get vendors to actually include it.

This does not mean we don't want this feature: if an Android OS vendor is interested in modifying their OS to include Flatpak, we are happy to review merge requests for adjustments to make it fit better. However, an Android OS vendor would need to be the one driving that work: it is them, not us, that is in control of the overall design of the Android OS.

I think you are seriously underestimating the amount of work that would be required to implement this feature. ChromeOS is a lot closer to desktop Linux than Android is, and has had a lot of engineering effort put into the Crostini container framework - and even then, ChromeOS can only run Flatpak with specially-adjusted Crostini settings.

> I don't see Samsung " not wanting " the flatpak support

If you are a Samsung product manager, you're very welcome to assign engineers to work on this, but if you are a customer who is saying "wouldn't it be nice if...", the answer is: yes, it would be nice, but no, we cannot make it happen.

**Comment by likeadragonmaid** [comment]
[Reference](https://issuetracker.google.com/issues/220468330)

**Comment by Mesum-Hussain** [comment]
> [Reference](https://issuetracker.google.com/issues/220468330)

Yeah that's also opened by me

**Comment by kevATin** [comment]
Android 16 is allegedly going to get support for Linux apps- including graphical ones. 
Is this going to change anything for this issue/flatpaks?
