### ISSUE TITLE
Why do I introduce multiple modules into my project? Only the first module can be loaded and other modules stop working?

### ISSUE THREAD

**Issue by GZYangKui** [flatpak/flatpak#4863]
![2022-04-19 17-21-26屏幕截图](https://user-images.githubusercontent.com/40876227/163972685-cc77e4b9-6feb-4d8b-8753-e2490e85bac5.png)
![2022-04-19 17-24-03屏幕截图](https://user-images.githubusercontent.com/40876227/163973129-7c87704f-f6db-45ae-b15c-1f9e7415169a.png)
 The above prompt "stopping at module flatpak_mysql" does not give the specific reason why it stops, but I put the module in the first item and it can be loaded normally. Through many tests, I come to the conclusion that only the first item will be loaded, and other items will not be loaded. Why?

**Comment by smcv** [comment]
Screenshots of a subset of your code do not tell us what you have done, or why you have done it.

It looks as though you have run `flatpak-builder --stop-at ...`, which asks it to stop building at a particular module so that you can debug it. If you do that, then ... of course it's going to stop there, because you have asked it to do so.

This is an issue tracker for Flatpak bugs and feature requests, not a technical support service. We do not have enough time or developers to provide personal support for everyone who is trying to build a Flatpak app.
