### ISSUE TITLE
[Decentralization]: Support for worldwide mirrors

### ISSUE THREAD

**Issue by itsnotsaved** [flatpak/flatpak#4874]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

- I open this issue in flatpak repository instead [flathub](https://github.com/flathub/linux-store-frontend) because you need to improve flatpak software for that. If necessary, I can create a copy of this issue in flathub repository.
- I know flatpak is designed without assuming that there is a single, central, canonical repository but practically entire flat project is just a centralized app store for daily users like play store or else. download from central (or known people manged) servers or visit to central web page,  We shouldn't literally argue with that but we need a centralized repository for linux softwares because FOSS developers dont have marketing departments.
- I know flatpak support for host own repository https://docs.flatpak.org/en/latest/publishing.html but again, If it flathub related reason then it will be better try to address why they host own repositories and offer very convenient ways to work with flathub

Both snap and flatpak have ignored mirroring part when develop the project and e.g. flatpak develop with particular view-point and rely on it although aware that will be a centralized app store.

**Feature Request**
Support for worldwide mirrors and let interested parties to join for host as for distros,
https://www.debian.org/mirror/list https://launchpad.net/ubuntu/+archivemirrors https://archlinux.org/mirrors/status/

Basic benefits:

**reduce maintain cost..
(1) Individuals or workplaces/offices don't need connect to centralized servers/environtment or connect to overseas servers
(2) Top download speed; this cannot achieve using CDN (there're some reports about slow download speed in china etc but this problem have for many other countries)
(3) Some own hosted repositories (even big projects) really too slow as useless than to flathub then they can come to flathub
and more..

Server side, You can follow convenient mechanism to support this facility easily. 
Client side, Mirrors list can update with each flatpak version, and user can configure mirror server using flatpak CLI.
// `flatpak configure server` --> display available countries --> select country --> display available mirrors --> select --> done

Similar feature already listed on snap
![image](https://user-images.githubusercontent.com/73447325/170854243-63e6a0d8-cee2-4762-bb37-5acde4b3840b.png)

**Comment by tyleraharrison** [comment]
Bump

**Comment by maulvi** [comment]
bump

**Comment by TCB13** [comment]
Yet another bump. More than allow for mirrors Flatpak should have a decent and supported way of downloading flatpaks and dependencies from the hub and some way install them offline from those static. Much like AppImages but obviously better cause it would be Flatpak.

There's no reason not to have this, it would make everyone's life easier for a ton of situation. This isn't a new concept either, Windows, macOS and Linux all have ways to install stuff offline. To be frank Windows and and macOS have the most portable solution for that but under Linux one can still mirror, download and archive `apt` repositories and packages for offline usage and it works transparently.

In Debian, Jigdo can be even used to create ISO files containing the entire repository - those can be later used to install a system 100% offline and/or be used as `apt` sources as one would use the online repository.

**Comment by rezad1393** [comment]
> Yet another bump. More than allow for mirrors, Flatpak should have a decent and supported way of downloading flatpaks and dependencies from the hub and some way install them offline from those static files. Much like AppImages but obviously better cause it would be Flatpak.
> 
> There's no reason not to have this, it would make everyone's life easier for a ton of situations. This isn't a new concept either, Windows, macOS and Linux all have ways to install stuff offline. Windows and and macOS have the most portable solution for that but under Linux one can still mirror, download and archive `apt` repositories and packages for offline usage and it works transparently.
> 
> In Debian, Jigdo can be even used to create ISO files containing the entire repository - those can be later used to install a system 100% offline and/or be used as `apt` sources as one would use the online repository.

using ipfs would help a lot.
I have no idea why more projects dont use this as backup of mirrors.
helps with integrity  too.


about that offline download I remember when I first got linux, not having internet was very hard for me and so I have to get packages from somewhere that had net and then put them on my pc and update it. so I understand the need for that.

but mirrors are more important for me as I live in Iran and having mirrors that can be hosted in my country would help a lot with speed and cost.

**Comment by planetoryd** [comment]
> I have no idea why more projects dont use this as backup of mirrors.

Incompetence

**Comment by TCB13** [comment]
> about that offline download I remember when I first got linux, not having internet was very hard for me and so I have to get packages from somewhere that had net and then put them on my pc and update it. so I understand the need for that.
> 
> but mirrors are more important for me as I live in Iran and having mirrors that can be hosted in my country would help a lot with speed and cost.

If things are done properly (like Debian does) offline download and mirrors are the same feature.

**Comment by rezad1393** [comment]
> If things are done properly (like Debian does) offline download and mirrors are the same feature.

again, I prefer ipfs because it is agnostic of files that are hosted.

if urls for files to download are like: https://someplace-maybe-like-dl-flathub-com/ipfs/ipfs-hash 
then it doesn't matter where I get this file. it also has integrity check built-in.
I can even use my own ipfs (self-hosted) and use it for my own or pin files and help other near me in my city or country.


I understand debian does stuff but that is an old way of just mirroring.
even arch has that (maybe even better with tiered mirrors)

my suggestion is that flathub gets a overhaul that moves to ipfs system for distributing files (with a http gateway) so that others can just use it directly or if they have issues just use another ipfs mirror.

that way of course is not perfect. for example I don't know if webmaster stuff (number of downloads of an update) can be easily done vs lagacy http way, but I think it is worth it.
maybe as a backup (secondary mirror) it can be done. but it needs work to be done and it is not trivial. it is not that hard if server that runs the host in under your control but it is not easy either.

a private torrent tracker (KG) had its screenshot hosting confiscated (or server got messed up,I dont remember) and now they use ipfs for screenshot hosting because it has a number of benefits.

1-it make backup very easy.  almost too easy.
2- if a host goes down (http gateway of  their personal ipfs) then the urls of images on their torrent pages just need a simple domain update and the address part after domain will remain the same.
3- users can host the images and help them (they actually encourage this)


my rant here is done.

**Comment by TCB13** [comment]
> I understand debian does stuff but that is an old way of just mirroring.

No, it isn't just "the old way of mirroring" it is a way of mirroring that ensure it will survive the most harsh scenarios like a country blocking all mirrors, a protocol or cutting internet access completely. It is designed to allow fallback to fixed media that can be shared by any means. It also uses a trivial format that can be easily converted and used in multiple ways.

**Comment by rezad1393** [comment]
> > I understand debian does stuff but that is an old way of just mirroring.
> 
> No, it isn't just "the old way of mirroring" it is a way of mirroring that ensure it will survive the most harsh scenarios like a country blocking all mirrors, a protocol or cutting internet access completely. It is designed to allow fallback to fixed media that can be shared by any means. It also uses a trivial format that can be easily converted and used in multiple ways.

I am not that familiar with it to refute you but I read mirror page on debian and didnt see word changing stuff you say.
it is good that it workd with sneakernet but still ipfs's main advantage is that it is not location addressable but content addressable so it is ideal for static files you want to distribute.
kinka like bittorrent but the new version fo bittorrent.

**Comment by planetoryd** [comment]
@TCB13 I interpreted your words as "if integration with IPFS is done properly, offline download and mirrors are the same feature". 

That is true, because IPFS is content-addressed and does NOT care whereever you get the data from. And it IS secure, more secure than  your average package manager logic (which often uses outdated ciphers, and git which uses sha1). 

There is no place for traditional mirroring here. Just do an overhaul

**Comment by rezad1393** [comment]
> @TCB13 I interpreted your words as "if integration with IPFS is done properly, offline download and mirrors are the same feature".
> 
> That is true, because IPFS is content-addressed and does NOT care whereever you get the data from. And it IS secure, more secure than your average package manager logic (which often uses outdated ciphers, and git uses sha1).
> 
> There is no place for traditional mirroring here. Just do an overhaul

exactly.
it is not just ipfs. any thing that makes it that cares that you get a file and not where you get it is way better than mirroring.
mirroring has its own benefits but if it was on me I would have used something like ipfs as the main and mirror as backup or vice-versa. 

like bittorrent that has webseeds too.

but I understand that mirroring the traditional way (just an https domain to mirror) is needed right now so maybe this is for later because if we want to implement ipfs we need to change some of the internal parts of flatpak/hub.
for example it no longer can be https://dl-somesites-com/flatpak/runtimes/whateverelse/mainbranch-version/file-version.pkg or something like that. it needs to be like https://dl-somesites-com/ipfs/ipfs-hash-of-the-file

so the version and so on go away. so it needs to internally map the runtimes/whateverelse/mainbranch-version/file-version.pkg which is an address with ipfs-hash-of-the-file.
it needs a mechanism for that, that I have not seen before implemented so it not just as easy as switching from on domain to another.

I think I no longer want to force it untill devs themself decide to do this.

**Comment by hfiguiere** [comment]
Flatpak doesn't implement software store. Flathub does. Flathub has mirrors and CDN.

**Comment by beedell-roke** [comment]
> [`#issuecomment-1937380557`](https://github.com/flatpak/flatpak/issues/4874#issuecomment-1937380557)

@hfiguiere, yet @itsnotsaved certainly possesses rationale (albeit not sufficiently elaborated) that causes them to believe that this is a problem caused by Flatpak, rather than Flathub, per [`#issue-1222192834`](https://github.com/flatpak/flatpak/issues/4874#issue-1222192834:~:text=i%20open%20this%20issue%20in%20flatpak%20repository%20instead%20flathub%20because%20you%20need%20to%20improve%20flatpak%20software%20for%20that.%20if%20necessary%2C%20i%20can%20create%20a%20copy%20of%20this%20issue%20in%20flathub%20repository):

> I open this issue in flatpak repository instead [flathub](https://github.com/flathub/linux-store-frontend) because you need to improve flatpak software for that. If necessary, I can create a copy of this issue in flathub repository.

Consequently, do you believe that this is solely within the purview of Flathub? If so, has anyone refiled this there?

**Comment by afzl-wtu** [comment]
Very Slow speed in Pakistan. I have good internet connection. But on flatpak I am getting 18KB /s. Shame on flatpak Management. I need days to download 400 mb flatpak files.

**Comment by beedell-roke** [comment]
@afzl-wtu, do you also see this with Fedora's flatpak repository? If not, perhaps refile at Flathub's GitHub repository, linking this issue.

**Comment by afzl-wtu** [comment]
I am on arch linux. How fo I use fedora repo. Does it contain all packages?
