### ISSUE TITLE
[Feature request]: Need a way to disable systemd-resolved forwarding to avoid DNS leaks

### ISSUE THREAD

**Issue by vmedea** [flatpak/flatpak#4876]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

org.freedesktop.Platform 21.08 started shipping a new `nsswitch.conf` that enabled use of systemd-resolved (see discussion https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1420). This causes the DNS configured in `/etc/resolv.conf` to be ignored in favor of a system-wide resolver, no matter what is configured in `/etc/nsswitch.conf`. 

Normally this is not a problem, but when running a flatpak application in a network-sandboxed environment this provides a way to bypass the configured DNS server (even if otherwise completely isolated from host networking), resulting in DNS leaks when used with a VPN.

It would be great to either have

-  a permission to prevent forwarding the `systemd-resolved` socket inside (suggested by nanonyme in the linked issue) \*
-  flatpak adhering to the policy configured in `/etc/nsswitch.conf`

\* I have tried passing `--system-no-talk-name=org.freedesktop.resolve1` to `flatpak run` and it did not work to block access to the service. This is because there's also a varlink socket `/run/systemd/resolve/io.systemd.Resolve`, for which a bind-mount was added in https://github.com/flatpak/flatpak/commit/e5da98ff4b12a080044d58b4cd2fb4edb4491132.  It would make sense for a permission to block both entry points.

**Comment by Derisis13** [comment]
Could this be the reason my flatpak browser is not using my local dns server? It's really inconvenient since I use local dns records to get ssl certs working on my lan as hairpin-nat is not working with my ISP provided router. 

Local dns servers are also used to filter ads (eg pihole) or increase privacy with recursive lookups (eg unbound). Systemd-resolved is notorius for bypassing the dhcp advertised dns server, so there should be a way to turn it off.

**Comment by Derisis13** [comment]
Could this be the reason my flatpak browser is not using my local dns server? It's really inconvenient since I use local dns records to get ssl certs working on my lan as hairpin-nat is not working with my ISP provided router. 

Local dns servers are also used to filter ads (eg pihole) or increase privacy with recursive lookups (eg unbound). Systemd-resolved is notorius for bypassing the dhcp advertised dns server, so there should be a way to turn it off.

**Comment by jackmaninov** [comment]
Just stumbled across this issue while hunting down why Brave in flatpak was leaking DNS. An enhancement would be most appreciated.

**Comment by nanonyme** [comment]
@Derisis13 I would note that systemd-resolved is an optional system component. I'm curious what that bypassing advertised DNS server is about since that has *always* worked for me. Do you have some issues filed?

**Comment by Derisis13** [comment]
I was wrong when I thought it bypasses the local DNS, it probably just caches some results, and since I carry my laptop around a lot, it could have done that.
On the other hand how is systemd-resolved optional? I have it turned off the os level but I don't know what goes inside the container.

**Comment by vmedea** [comment]
> On the other hand how is systemd-resolved optional? I have it turned off the os level but I don't know what goes inside the container.

If you turn it off at the OS level, the container will not be able to reach it (and fall back to normal DNS lookup) so it should be ok.

**Comment by nanonyme** [comment]
> > On the other hand how is systemd-resolved optional? I have it turned off the os level but I don't know what goes inside the container.
> 
> If you turn it off at the OS level, the container will not be able to reach it (and fall back to normal DNS lookup) so it should be ok.

Exactly, the container does *not* run systemd-resolved. It has glibc resolver library that uses varlink socket mounted from *host*. If you don't have systemd-resolved on host, then this does nothing.

**Comment by nanonyme** [comment]
Basically if granularity is desired, there could be a permissions for mounting the varlink socket. Is is *not* possible to manage this with D-Bus permissions as @vmedea noted because this is not about D-Bus at all. Modern resolver will never use the D-Bus socket, that was a feature in very old versions of systemd. There would definitely be something like --share=systemd-resolved for the socket. (whether or not it is the default, it would at least allow you to be able to do --unshare=systemd-resolved)

**Comment by mcatanzaro** [comment]
> It would be great to either have
> 
> a permission to prevent forwarding the systemd-resolved socket inside (suggested by nanonyme in the linked issue) *

So I think an --unshare=systemd-resolved permission would be OK, but let's make sure the new permission is really needed. Normally flatpaks want to use the same DNS configuration as the host system. The permission you request would make sense if (a) you have systemd-resolved enabled on the host system (otherwise, nss-resolve would be a no-op and you would have no problem), and (b) you want to not use it only for the flatpak application. But I'm not sure that actually matches your situation? Because it sounds like you have changed the _host_ /etc/resolv.conf and you are expecting your flatpak app to follow your host configuration? Is that correct?

 * If so, then honestly it sounds like a configuration error rather than a use case for a new permission. Either disable systemd-resolved on the host system, or else configure it to send DNS queries to wherever you want them to go. If you've changed host /etc/resolv.conf to not point to systemd-resolved, and changed host /etc/nsswitch.conf to not use nss-resolve, then there's surely no reason to leave systemd-resolved running? Turning it off would stop the nss-resolve in the sandbox from doing anything.
 * If not, then you're trying to apply special DNS policy only to the flatpak app. In this case, you surely have some sort of setup for customizing the /etc/resolv.conf inside the flatpak container, yes? Is there a reason you cannot develop something similar for /etc/nsswitch.conf?

> flatpak adhering to the policy configured in /etc/nsswitch.conf

I don't think this is safe. The host /etc/nsswitch.conf might not work in the flatpak environment. For this to work reliably, Flatpak would need to know about every possible NSS module, including both normal stuff like sssd and weirder stuff like nss. Currently none of that is going to work inside flatpak. I think it's not worth pursuing this. (Even if we did want to do this, flatpak doesn't control the /etc/nsswitch.conf shipped by the runtime, so we'd be in the wrong issue tracker.)

**Comment by vmedea** [comment]
I'm fine with closing this, I don't have this particular issue anymore. I guess my goal here was to warn people of this potential DNS leak gotcha.

Disabling sytemd-resolved on the host seemed overkill because the restriction is only for the applications running in the specific isolated sandbox namespace. Applications outside it can use the systemd service as they like.

What i have done to work around this is bind-mount an empty directory to `/run/systemd/resolve` inside the sandbox. It's more thorough anyway.

**Comment by nanonyme** [comment]
Ok. This can be revisited in context of unprivileged network namespaces in case that ever gets implemented. Currently the benefit of this is very limited.
