### ISSUE TITLE
[Feature request]: In memory deduplication when sharing runtimes

### ISSUE THREAD

**Issue by dcermak** [flatpak/flatpak#4997]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

In case this feature is already implemented, please disregard this issue.

This issue arose after the discussion on the openSUSE mailing list, when users on low-end system raised concerns that their machines will not be able to run flatpak'd applications as they would not utilize the memory deduplication of shared libraries when launched by multiple different flatpaks (provided that these share a common runtime).

Would it be possible to add memory deduplication for shared runtimes? If yes, any rough idea how that could be implemented?

**Comment by mwleeds** [comment]
Shared libraries used by multiple processes already use the same physical memory, and this is an OS feature not a Flatpak feature. Also worth noting that the entire runtime is not loaded into memory, only the parts that are used by the app.

Here's a proof of the de-duplication:
1. Launch GNOME Boxes and GNOME Builder as flatpaks, both of which use the GNOME 42 runtime.
2. Find the parent process of the one reported by `flatpak ps` for Boxes, perhaps using `pstree -p`
3. Check the RSS and PSS columns in the output of `pmap -X`:
```
↳ pmap -X 31894 | grep libpango-1
         Address Perm    Offset Device   Inode      Size    Rss    Pss Referenced Anonymous LazyFree ShmemPmdMapped FilePmdMapped Shared_Hugetlb Private_Hugetlb Swap SwapPss Locked THPeligible Mapping
    7fda2f368000 r--p  00000000  00:19 1196784        76      0     0          0         0        0              0             0              0               0    0       0      0           0 libpango-1.0.so.0.5000.8
    7fda2f37b000 r-xp  00013000  00:19 1196784       220    212   106        204         0        0              0             0              0               0    0       0      0           0 libpango-1.0.so.0.5000.8
    7fda2f3b2000 r--p  0004a000  00:19 1196784       104      4     2          4         0        0              0             0              0               0    0       0      0           0 libpango-1.0.so.0.5000.8
    7fda2f3cc000 r--p  00063000  00:19 1196784        16     16    16         16        16        0              0             0              0               0    0       0      0           0 libpango-1.0.so.0.5000.8
    7fda2f3d0000 rw-p  00067000  00:19 1196784         4      4     4          4         4        0              0             0              0               0    0       0      0           0 libpango-1.0.so.0.5000.8
```
(I added back the column headings to the grep output.) You can see Rss for one of the segments is 212 and Pss is 106, implying there's one other process sharing that segment.
3. Close Builder so only Boxes is using that library and try `pmap` again:
```
↳ pmap -X 31894 | grep libpango-1
         Address Perm    Offset Device   Inode      Size    Rss    Pss Referenced Anonymous LazyFree ShmemPmdMapped FilePmdMapped Shared_Hugetlb Private_Hugetlb Swap SwapPss Locked THPeligible Mapping
    7fda2f368000 r--p  00000000  00:19 1196784        76      0      0          0         0        0              0             0              0               0    0       0      0           0 libpango-1.0.so.0.5000.8
    7fda2f37b000 r-xp  00013000  00:19 1196784       220    212    212        204         0        0              0             0              0               0    0       0      0           0 libpango-1.0.so.0.5000.8
    7fda2f3b2000 r--p  0004a000  00:19 1196784       104      4      4          4         0        0              0             0              0               0    0       0      0           0 libpango-1.0.so.0.5000.8
    7fda2f3cc000 r--p  00063000  00:19 1196784        16     16     16         16        16        0              0             0              0               0    0       0      0           0 libpango-1.0.so.0.5000.8
    7fda2f3d0000 rw-p  00067000  00:19 1196784         4      4      4          4         4        0              0             0              0               0    0       0      0           0 libpango-1.0.so.0.5000.8
```
Note that Rss and Pss for the same segment are both 212, because the memory is no longer being shared by another process.

Rss = Resident set size = the amount of the mapping that is currently resident in RAM (from kernel docs)
Pss = "The "proportional set size" (PSS) of a process is the count of pages it has
in memory, where each page is divided by the number of processes sharing it.
So if a process has 1000 pages all to itself, and 1000 shared with one other
process, its PSS will be 1500." (from kernel docs)
