### ISSUE TITLE
[Feature request]: add the ability to offload apps

### ISSUE THREAD

**Issue by ba-batz** [flatpak/flatpak#5038]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

the ability to offload apps would truly set flatpak and linux appart from other package managers and windows!

if you are not familiar with the concept of offloading it works like this:
when you offload an app you don't delete their save files and configs, but you delete the app itself witch gets re-downloaded from the internet, if you want to use it again.

**Comment by rusty-snake** [comment]
> the ability to offload apps would truly set flatpak and linux appart from […] windows!

And why is that good/wanted? (OT question to think about)

> when you offload an app you don't delete their save files and configs,

`--delete-data` is not enabled by default, see `man flatpak-uninstall` for details.

**Comment by tinywrkb** [comment]
I don't see this happening.  

1. Flatpak does not and should trigger updates or set policies for application management decisions (should an app be replaced with another from a different repo). This should be manage by the desktop environment, and based on setting pre-determined shipped with the distro or by the user. So Flatpak should not decide to remove apps.  
Just the fact that Flatpak does not manage update scheduling should tell you that the feature you're asking for will not likely to be implemented.
3. Nothing stopping developers of desktop environments to implementing this. You should report this in your desktop environment bugtracker.
4. No one will benefit from this except for a handful of users with very limited storage space. This type of feature will lead to excessive disk operations and network traffic. Flatpak updates are very minimal due to dedup, but full installations are not, especially when taking into account runtimes and extensions, which other platform do not have.

**Comment by mwleeds** [comment]
As @rusty-snake said, you can already "offload" a Flatpak by removing it with `flatpak uninstall` and omitting the `--delete-data` option.
