### ISSUE TITLE
[Feature request]: platform extension

### ISSUE THREAD

**Issue by q962** [flatpak/flatpak#5041]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

I noticed this extension point

````
[Extension org.freedesktop.Sdk.Extension]
subdirectories = true                    
directory = lib/sdk                      
no-autodownload = true                   
add-ld-path = lib                        
version = 21.08                          
````

Why doesn't the platform have relevant extension points?

An application may depend on a program unless it self-contains all required dependencies.
How can I provide the dependency if it is not included? Use flatpak-spawn?

solution:
Using the `flatpak run --runtime` option, setting it to the Sdk solved my problem.

idea:
My idea is to fill in the required extensions in app.yaml (editable after installation) and install them together at install time. Appends the specified extension at startup. The base extension must be attached.

Another idea, build an app that can run in runtime/sdk/app at the same time.
This avoids installing the same program repeatedly.

All of these require applications to be as independent as possible and not to conflict with other applications.

---

is it possible?

**Comment by tinywrkb** [comment]
I suggest that you get more familiar with Flatpak packaging, because there are implications to your suggestion.

1. This has more to do with the runtime, not Flatpak, and Flatpak already provides a `platform-extensions` property that does something else. This is a runtime policy first, so whatever Flatpak limitations exist, they are less of importance, and you should ask the runtime maintainers about this.
2. `add-ld-path` was wrong for `Sdk.Extension` and it's definitely wrong here. The `subdirectories` property mounts everything that match the `[Extension name] as a prefix, and having also `add-ld-path` means unpredictable behavior. Thankfully, most of these extensions also set `LD_LIBRARY_PATH` in their `enable.sh`.
3. I suspect that no who matter wants this. Who's going to manage all these extensions with the strict ABI requirements of the runtime? We don't have to follow these requirements when maintaining an SDK extension or base application, which is why these are prevalent.
4. For the most part, regular application extensions already answer this use case. In fact, we're already using extensions like `org.freedesktop.Platform.ffmpeg-full` and `org.freedesktop.Platform.GL32.default`.  
I suggest instead to focus on fixing the limitations of regular application extensions.
  * Not being able to automatically package from an SDK extension a non-SDK extension, like what's already possible when building a runtime. This is a flatpak-builder issue, though it's related to the runtime's packaging policies.  
  I refrain from calling the non-SDK extension a Platform extension to not imply that the extension would be mounted to the runtime, but it basically what I mean.
  * Extension is not available during the apply_extra step. For example, I wanted to create a Wine prefix in `/app/extra` and install an application to it with a Wine extension.  
  Another possible scenario would be patching a proprietary application using tools available in an extension. I had to do this once, and it made more sense to package the needed tools with the application.

I do agree that it would be nice to have runtime mounted extensions for SDK and Platform runtimes with similar paths. Just try building Qt modules or any of the Python bindings for Qt, and you'll hit issues that only happen when packaging for Flatpak.

**Comment by q962** [comment]
Reply 1. If everyone provided the runtime, the space would skyrocket and it would turn into an escape platform. So relying on the runtime provided by default is a good option.

Reply 2. Information from `flatpak info org.freedesktop.Sdk//21.08 -m`
I also don't think add-ld-path is a good option.

Reply 3. Sorry, I didn't understand what you said. Packaging restrictions make it harder for maintainers?

Reply 4. Yes, that's what I want, but that's about it. These extension points are targeted, not general extension points. Like `[Extension org.freedesktop.Sdk.Extension]`, I can create a directory under this directory to store my application. And my app doesn't conflict with any other program.
But this is a stupid idea. Many developers don't provide binary packages themselves now. They can of course create packages that won't conflict with other applications. But they don't, so why fantasize about them doing such a thing for flatpak?

Doing this does change how flatpak is done.

No contact with QT, python. Many issues are complex and the documentation is unclear. Like I can't read the flatpak documentation. There is a lot of content, but basically only one sentence. So far I don't understand how the build system works. I still choose buildsystem=simple.

There are many options in the flatpak configuration file that cannot be explained in one sentence.

Let's continue to see how the Extension develops. 

:)

**Comment by smcv** [comment]
Platform extensions are not really a feature, but instead they are something lower-level than that: they're a possible implementation that can be used to provide features.

We should not implement low-level features speculatively: Flatpak is already not straightforward to understand, and it's already limited by the amount of time maintainers can spend on it. Every new feature makes it harder to understand and more expensive to maintain.

If we add new features, then it should be because there is some higher-level use-case that justifies why those features are needed, and why the current feature-set is not enough to satisfy that use-case.

**Comment by q962** [comment]
Does an app with plugin functionality require the functionality I'm considering?

For example vscode, plugins may depend on node, pyhton, ruby, java, ....

You don't include them, you can only use it via flatpak-spawn .

Does vscode run on Platform or SDK? Are there any points that can be extended?

Yes now flatpak more I say it's really a bit hard

**Comment by tinywrkb** [comment]
> Reply 3. Sorry, I didn't understand what you said. Packaging restrictions make it harder for maintainers?

You need to comply with [this](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/wikis/ABI%20stability) if you want to have an extension mount on the Platform runtime.  
It's less time-consuming to update libraries to new releases, than having to dig in the log, look for security related fixes and cherry-pick them.

**Comment by tinywrkb** [comment]
@q962

Any development related application should define the SDK as the runtime, and then all the SDK extensions would be available. This is what vscode is doing, like other IDEs.  
Look at the [ide-flatpak-wrapper](https://github.com/flathub/ide-flatpak-wrapper), it can automatically source `enable.sh` of SDK extensions if you set an environment variable.

**Comment by q962** [comment]
But vim runs on the platform, so you need to manually set the runtime.
Can I specify a certain version of the extension?

Can an extension run as an app? For example, I encapsulate a simple program, such as astyle, into a vscode service (sdk), but the program can also serve the host. what should I do? Recompile once? For flatpak astyle only differs at runtime.

**Comment by tinywrkb** [comment]
@q962 I suggest asking this kind of questions somewhere else, not here in the bugtracker to avoid spamming subscribers. A better place for this is the [#flatpak](https://matrix.to/#/#flatpak:matrix.org) matrix channel or [r/flatpak](https://www.reddit.com/r/flatpak) subreddit.

To answer your last post, the vscode app supports `com.visualstudio.code.tool.` extensions, so you can package whatever you need as an extension.  
Another option is drop [host-spawn](https://github.com/1player/host-spawn) somewhere accessible to the sandbox, override `PATH` to its location, and create a symlink to it with the host executable name that you want to launch.
You can also add a terminal profile for launching a shell session on the host. For example

```
  "terminal.integrated.profiles.linux": {
    "Flatpak: Bash": {
      "path": "bash",
      "args": ["-i"],
      "overrideName": true
    },
    "Host: Bash (flatpak-spawn)": {
      "path": "/usr/bin/flatpak-spawn",
      "args": ["--env=TERM=vscode", "--host", "/usr/bin/bash", "-i"],
      "overrideName": true
    },
    "Host: ZSH (flatpak-spawn)": {
      "path": "/usr/bin/flatpak-spawn",
      "args": ["--env=TERM=vscode", "--host", "/usr/bin/zsh", "-i"],
      "overrideName": true
    },
    "Host: Bash (flatpak-spawn pty)": {
      "path": "/usr/bin/flatpak-spawn",
      "args": ["--env=TERM=vscode", "--host", "script", "--quiet", "/dev/null"],
      "overrideName": true
    },
    "Host: Bash (host-spawn pty)": {
      "path": "host-spawn",
      "args": ["/usr/bin/bash"],
      "overrideName": true
    },
    "Host: ZSH (flatpak-spawn pty)": {
      "path": "/usr/bin/flatpak-spawn",
      "args": ["--env=TERM=vscode", "--env=SHELL=zsh", "--host", "script", "--quiet", "/dev/null"],
      "overrideName": true
    },
    "Host: ZSH (host-spawn pty)": {
      "path": "host-spawn",
      "args": ["/usr/bin/zsh"],
      "overrideName": true
    }
  },
  "terminal.integrated.defaultProfile.linux": "Flatpak: Bash",
```

And you can also drop a statically linked executable. For example, I have a [dedicated SDK extension](https://github.com/tinywrkb/flatpaks/blob/master/org.freedesktop.Sdk.Extension.devenv/org.freedesktop.Sdk.Extension.devenv.yaml) to set a working environment in the sandbox similar to what I have set on my host, is enabled with `ide-flatpak-wrapper`, and build everything I need as statically linked executables.

**Comment by q962** [comment]
@tinywrkb 

I think this is a feature request. You think the settings are bug.

You didn't understand what I meant, maybe my description wasn't clear enough. sorry.
