### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Motherboard** [flatpak/flatpak#5057]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.7

### What Linux distribution are you using?

Manjaro Linux

### Linux distribution version

5.15.60-1-MANJARO

### What architecture are you using?

x86_64

### How to reproduce

1. Install zoom, skype, freeorion, flatseal, unciv, colobot, hyperrogue. 
2. Update said applications for a while
3. type `find /var/lib/flatpak/ -xtype l -print `
4. observe the plethora of broken links, and repo dir is ~8Gb (even though these sum up to much less on install).
5. type `flatpak uninstall --unused`
6. type `flatpak repair`
7. re-check for broken links, and notice nothing has changed. 
8. re-check size of repo dir, and notice nothing has changed.

### Expected Behavior

I would expect flatpak uninstall --unused and flatpak repair to remove all broken links. I currently have more than 9000 broken links in the repo dir.

### Actual Behavior

It says there's nothing to uninstall or repair, does nothing.

**Comment by hzulla** [comment]
Can see similiar behaviour on Ubuntu 22.04. Lots of broken symbolic links found with `find /var/lib/flatpak/ -xtype l -print`.

Out of curiousity, looked at one of the files found that way. It is:

```
lrwxrwxrwx 1 root root 24 Aug  8 21:08 /var/lib/flatpak/repo/objects/07/bde2739cfa814e3265a0d225c4666a3e7540a162edfd68a3d9f0f74cc3cb1f.file -> libpango-1.0.so.0.5000.8
```

However, if I look for the target file, it is found here:

```
/var/lib/flatpak/runtime/org.gnome.Platform/x86_64/42/e461129c14120dcf8801bf1bb25257a651cee3f2fd0ebd1a31c1d51db1da9e9c/files/lib/x86_64-linux-gnu/libpango-1.0.so.0.5000.8
```

What's going on here?

**Comment by smcv** [comment]
Because the title of the original bug report was empty, it is not clear what the original issue reporter thought was the significant part of this issue.

> observe the plethora of broken links

The internal structure of a libostree repository is an implementation detail of Flatpak/libostree, and they are not meant to be navigated as ordinary filesystem directories. It is not a bug for them to contain broken symlinks, as long as the Flatpak sandbox that results from actually running an app works correctly.

If you have not observed a Flatpak app behaving incorrectly, then the broken symlinks are not a bug. Changing the repository storage format to avoid broken symlinks in the repository would result in Flatpak apps taking up more space, and taking longer to start.

> repo dir is ~8Gb (even though these sum up to much less on install)

8GB according to what measurement?

libostree repositories and checkouts make heavy use of hard links to the same file for deduplication, which means that if you use a method of measurement that counts hard links multiple times, the Flatpak directory will appear to be very large. That doesn't necessarily mean that it *is* very large.

For example, in my test installation, `du -sh ~/.local/share/flatpak` (which does its best to count the space that is actually used on-disk) reports 6.9G, but `du -shl ~/.local/share/flatpak` (which counts hard-linked files multiple times) reports 14G.

If you are installing Flatpak apps system-wide (which is the default) then the space used will be in `/var/lib/flatpak` rather than `~/.local/share/flatpak`, but the principle is the same.

**Comment by hzulla** [comment]
> It is not a bug for them to contain broken symlinks

Okay, thanks for clarification.
