### ISSUE TITLE
[Feature request]: Pipewire permission

### ISSUE THREAD

**Issue by ilya-fedin** [flatpak/flatpak#5130]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

A plenty of libraries (OpenAL, SDL) already support PipeWire sound output, however there's still no `--socket=pipewire` permission in flatpak

**Comment by Erick555** [comment]
Doesn't pipewire re-use pulseaudio socket?

**Comment by ilya-fedin** [comment]
Only for the pulseaudio compatibility layer. Native pipewire protocol uses its own socket.

**Comment by Erick555** [comment]
It seems that pipewire developers had [different plans](https://github.com/flatpak/flatpak/pull/1020) for flatpak support instead of using socket.

**Comment by ilya-fedin** [comment]
Were these plans realized? :thinking:

**Comment by smcv** [comment]
I believe the Pipewire socket is always `$XDG_RUNTIME_DIR/pipewire-0` in practice, and apps can get access to that with `--filesystem=xdg-run/pipewire-0`. We only need a special `--socket` permission in cases where it's more complicated to find the correct socket (take a look at the implementation of X11 and PulseAudio socket discovery and you'll realise why they need a `--socket`).

If something more extensive is needed, please open a merge request that implements the way you think it ought to work.

**Comment by ilya-fedin** [comment]
Doesn't -the `-0` mean there could be `-1`, `-2`, etc?

**Comment by orowith2os** [comment]
> Doesn't -the -0 mean there could be -1, -2, etc?

In practice, this is very rarely the case. Even if things like the Wayland socket can be different, PipeWire rarely is. Even when several compositors are running under a user, they all use the same PipeWire server. And PipeWire doesn't have all the different implementations of Wayland, so you don't have to deal with potential implementations using a different socket.

**Comment by ilya-fedin** [comment]
There's a new problem due to new flathub site: it doesn't understand that the permission is for pipewire and marks application as potentially unsafe
![изображение](https://github.com/flatpak/flatpak/assets/17829319/4534a11a-67f9-4071-b6ee-ca2c12a8140a)

**Comment by orowith2os** [comment]
@ilya-fedin not exactly wrong, but not right either - an issue should be filed on https://github.com/flathub/website and probably GNOME Software about making the PipeWire permission a bit clearer, if possible. (Can access audio and video devices without permission, more or less)

**Comment by hfiguiere** [comment]
There is a pipewire permission as answered.

**Comment by Jusix** [comment]
Please reopen, with latest update the permission is missing again.

**Comment by Omnifarious** [comment]
One big reason for Pipewire support is that Pipewire is needed for screen or window capture on Wayland. And things like Zoom need this to function properly. From the issue that was already linked to, it sounds like there's a plan for a more complex, but more secure interface between flatpak's and pipewire that allows hiding certain pipewire things from a flatpak. This seems very nice.

Unfortunately, because window and screen capture are so important for Zoom, I'm left either running Zoom as an RPM, which is _much_ less secure, or I'm stuck using OBS' virtual camera feature and letting OBS do the compositing for the screen share.

The latter seems like a winner, but has a massive disadvantage in that Zoom doesn't know a screen share is going on and can't inform meeting participants or treat the screen share using different compression techniques (like lowering the frame rate, or (and I don't think it currently does this) using lossless compression techniques that work very well for windows of text andoor large amounts of a single color) than is used for regular video. Also, the whiteboard features that let other people draw on screen shares don't work.
