### ISSUE TITLE
"Refresh of version 41"

### ISSUE THREAD

**Issue by mewcrazy** [flatpak/flatpak#5143]
Hello,

Recently I'm getting package updates from Flatpak (actually in Discover; KDE Neon) which say "Refresh of version X" - In Google I can't seem to find anything, except my own forum post. 

Are those "updates" normal? I mean the version hasn't changed in weeks or months sometimes. Yet I'm getting a push for an package update. How secure is Flatpak? It almost seems like a hack, probably cause by WebRPC.

I'd love to hear y'all opinions.

**Comment by stephen304** [comment]
Also came across this and was confused, searching for flatpak "refresh of version" only turns up this issue - it would be great if there was some explanation somewhere of what this means. I just updated EasyEffects from 6.x to 7.0, then after got an update to "Refresh of version 7.0", so I had to immediately update again.

**Comment by smcv** [comment]
The string "Refresh of version" does not come from Flatpak. It seems to be the description used by Discover when an app or runtime gets updated without changing the user-facing version number: <https://sources.debian.org/src/plasma-discover/5.26.0-2/libdiscover/resources/AbstractResource.cpp/?hl=266#L266>. The Flatpak tool is not responsible for how the authors of Discover have chosen to present this information.

For instance, if EasyEffects 7.0 is rebuilt with a newer compiler, or if it depends on some library that is not part of the runtime and gets rebuilt to pick up a new version of that library with a bug fix, then it seems correct for its version number not to change: EasyEffects itself was version 7.0 before, and it is still version 7.0 now. Whether/when that happens is up to the maintainer of the app or runtime that is being updated, and the Flatpak downloading tool does not have control over how maintainers choose to maintain their apps.

> How secure is Flatpak?

The Flatpak tool whose issues are tracked here downloads and runs apps and runtimes provided by some repository (often Flathub, but not always). It uses PGP signatures and TLS to check that the apps you downloaded are the same version that the repository maintainer published, so that download path should be as secure as any other well-written software downloader, as long as the repository is operated properly.

The repository maintainer chooses what they are willing to publish and sign, so repository maintainers are responsible for securing their own infrastructure: if they publish and sign an app or runtime that they should not have published, the Flatpak tool can't magically distinguish between that and a legitimate update from the same repository. Only use Flatpak repositories that you trust, such as Flathub.

All of this is very similar to the security mechanisms used in OS-level package managers like Debian's `apt` and Fedora's `dnf`.

Flatpak is a bit more secure than OS-level package managers because Flatpak apps are sandboxed, so as long as an updated app has the same permissions as the previous version, even if the updated version is malicious, it cannot do anything that its permissions don't allow. If the new version is asking for more permissions than the old version, a UI for installing Flatpak apps should ideally tell you that and give you the opportunity to refuse. The `flatpak` command-line interface does this, but I don't know whether Discover does the same (again, the maintainers of Flatpak are not responsible for Discover's UI choices).

**Comment by ghtesting2020** [comment]
Created a KDE ticket for this because i was concerned with all of these refreshes. turns out they were new versions lol

https://bugs.kde.org/show_bug.cgi?id=464128
