### ISSUE TITLE
Data consume

### ISSUE THREAD

**Issue by N00BH8** [flatpak/flatpak#5156]
I install gimp from flatpak on kali linux, its 126,6 MB download size but its spend More than 1,1GB data!!!, what the heck is goin here,,, any one can explain???!!!

**Comment by Mikenux** [comment]
This is due to the installation of gimp and its runtime (and locales). 

In a terminal:
- `flatpak info org.gimp.GIMP`: 365.1 MB when installed.
- `flatpak info org.gnome.Platform//42`: 760.3 MB when installed.
- `flatpak info org.gnome.Platform.Locale//42`: 35 MB (french) when installed.
- Total: 1,160.4 MB
