### ISSUE TITLE
Support lib linkage to lib64/ or other arch-specific directory

### ISSUE THREAD

**Issue by Jehan** [flatpak/flatpak#519]
Some software would install their lib in lib64/ (on a 64-bit system) by default.
For instance I installed Jasper 2.0.10 in a flatpak and that's what it does. But then GIMP configure uses a AC_CHECK_LIB() test and could not find libjasper because of this.

`.flatpak-builder/build/gimp-4/config.log` shows:

> configure:27703: checking for jas_init in -ljasper
> configure:27728: gcc -o conftest -O2 -g -Wall -Wdeclaration-after-statement -Wmissing-prototypes -Werror=missing-prototypes  -Wmissing-declarations -Winit-self -Wpointer-arith  -Wmissing-format-attribute -Wformat-security -Wlogical-op -Wtype-limits -fno-common -fdiagnostics-show-option -Wreturn-type    -L/app/lib  conftest.c -ljasper  -ljpeg  >&5
/usr/lib/gcc/x86_64-unknown-linux/5.2.0/../../../../x86_64-unknown-linux/bin/ld: cannot find -ljasper
> collect2: error: ld returned 1 exit status
> configure:27728: $? = 1

That was easy enough to bypass by passing to the cmake build:

> "config-opts": [ "-DCMAKE_INSTALL_LIBDIR=lib" ],

Yet as a general idea, it would be good if lib64/ had been in the link search path inside the flatpak build environment. This is kind of a common use case.

**Comment by alexlarsson** [comment]
This is up to each runtime/sdk to decide, just like it is for any distribution. However, I will not do this for the freedesktop one because I think continuing support for /lib64 when it is not needed is merely going to cause confusion (by splitting the libraries in two locations. All modules that do this by default has a way to override this because many other setups don't have lib64 either.

**Comment by Jehan** [comment]
Ok.
