### ISSUE TITLE
[Feature request]: A new approach to sandboxing

### ISSUE THREAD

**Issue by monkeyt00l** [flatpak/flatpak#5197]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

The sandboxing feature of flatpak keeps receiving criticism due to its approach to label partial isolation as sandboxing, especially due to the expectations users connect with that term.
The most recent [analysis](https://hanako.codeberg.page/) demonstrates quite casually how to break out of ~~any~~ ten popular, official flatpak app on flathub with nothing more then long known weaknesses. 
It also mentioned some points on how flatpak could change its general sandboxing approach to avoid these issues:

**Instead of implying flatpak to be sandboxed by default, sandboxing as a security measure could be made into a feature that the user can activate, resulting in a container environment that restricts features, but actually provides meaningful protection.**

This of course would mean that in environments that for example use X11, the feature would not work at all and the user could receive a clear warning that the sandbox feature is not supported on X11 due to its security issues.

Flatpak apps should of course keep working on X11 but with a clear indication and documentation that it runs inside a partial container that does not provide sandbox protection.

Before anyone brings up flatseal and how to improve a flatpak sandbox after installation: This is not a real solution for anything, since it won't solve the common impression that the default flathub apps are secure (as in malware can't escape) and leaving the isolation of the sandbox to the user is a horrible approach to security.

The objective of this feature request is to suggest an effective sandbox in flatpak applications that can be used by average non technical users without manual adjustments.

**Comment by tupacase** [comment]
> The most recent analysis demonstrates quite casually how to break out of any popular, official flatpak app on flathub with nothing more then long known weaknesses.

No, it demonstrates how *ten* of these apps have static permissions that allow a sandbox escape (which is well known and hardly needed an “analysis” to demonstrate). *Ten* apps is not the same as “any popular, official flatpak app on flathub”. There are more than ten “popular, official” apps on Flathub and many of these apps (how many depends on your exact definition of “popular”) do not have permissions that allow a sandbox escape without exploiting a zero-day vulnerability.

There have been a few vulnerabilities in the past that allowed breaking out of the default Flatpak sandbox and they were classified as high severity vulnerabilities, for example CVE-2021-41133, CVE-2021-21381 and CVE-2021-21261.

Where the Flatpak website claims that the Flatpak sandbox is secure by default, it is talking about the sandbox with no static permissions, with no additional options given to `flatpak run`. That is what is meant by *default*.

> sandboxing as a security measure could be made into a feature that the user can activate, resulting in a container environment that restricts features, but actually provides meaningful protection

This feature exists, as that’s what the `--sandbox` option does. Instead of running an app with `flatpak run appid`, you can run it with `flatpak run --sandbox appid` to ensure that no holes are poked in the sandbox and the app is fully restricted regardless of any static permissions defined in its manifest. (If the app is a graphical app, this also ensures that it will not launch, because the Flatpak sandbox does not give access to the Wayland or X11 socket by default.)

> This is not a real solution for anything, since it won't solve the common impression that the default flathub apps are secure

Some of them are. Some of them are not. There will be people with incorrect impressions about things no matter what anyone does. That some people have some incorrect impressions about things hardly warrants entirely changing Flatpak’s approach to sandboxing (and no matter what change you did, there would still be people with incorrect impressions about things). If you want to be sure, you should assume that any app that has permissions other than `--socket=wayland` is insecure.

There are *many* apps on Flathub that have no static permissions other than `--socket=wayland`, `--socket=fallback-x11`, `--share=ipc` and `--device=dri`. On a Wayland system, I’m not aware of a way to escape the sandbox with just these permissions. However, I could be wrong, maybe there is a way to escape the sandbox with just these permissions (and without a zero day). And I would not consider `--device=dri` secure even if it does not allow escaping the sandbox. If you remove `--socket=fallback-x11`, `--share=ipc` and `--device=dri`, most of these apps will still work (some require `--device=dri`, but most don’t) and they will be secure (as always, except for zero days). Many apps that have other permissions could still work with just `--socket=wayland`, often with some tradeoffs.

**Comment by monkeyt00l** [comment]
> > The most recent analysis demonstrates quite casually how to break out of any popular, official flatpak app on flathub with nothing more then long known weaknesses.
> 
> No, it demonstrates how _ten_ of these apps have static permissions that allow a sandbox escape

Please allow me to correct and rephrase this:
**Among the ten popular flatpak apps that were tested, none implemented a sandbox that was not trivial to escape.**

I will add that after looking through flathub manifests, I was also unable to find a single flatpak that did not have any of the issues that lead to sandbox escape, but that isn't really the issue here. The problem is that users expect flathub apps to be effectively sandboxed, and therefore I would suggest a clear feedback to those users that indicate when that is actually the case.


> Where the Flatpak website claims that the Flatpak sandbox is secure by default, it is talking about the sandbox with no static permissions, with no additional options given to `flatpak run`. That is what is meant by _default_.

Maybe I am misunderstanding this sentence, but it sounds like you are saying that flatpaks sandbox is secure by default because of some arbitrary definition of default that has nothing to do with how flatpak is commonly used. The official instructions on how to use flatpak apps is to execute something like: `flatpak run org.videolan.VLC`
And this isn't sandboxed at all.

> > sandboxing as a security measure could be made into a feature that the user can activate, resulting in a container environment that restricts features, but actually provides meaningful protection
> 
> This feature exists, as that’s what the `--sandbox` option does. Instead of running an app with `flatpak run appid`, you can run it with `flatpak run --sandbox appid` to ensure that no holes are poked in the sandbox and the app is fully restricted regardless of any static permissions defined in its manifest. (If the app is a graphical app, this also ensures that it will not launch, because the Flatpak sandbox does not give access to the Wayland or X11 socket by default.)

Thank you for pointing out this option, I was not aware of it.
However this is hardly what I am suggesting since it does block things like wayland and therefore isn't really useable for most flatpak apps.

Perhaps there could be a sandbox definition of flatpak manifests that simply make sure there is no X11 or host/home fiel permissions in addition to any other known sandbox escape path.
And whenever a manifest fullfills these conditions, it is confirmed as sandboxed while otherwise there would be a warning message saying that it is not sandboxed.

**Comment by Erick555** [comment]
> However this is hardly what I am suggesting since it does block things like wayland and therefore isn't really useable for most flatpak apps.

Additional permissions are added only when some app functionality needs them therefore removing any permissions removes app functionality. It would be a bug in the app if that wasn't the true. Shipping semi-functional, demo apps isn't what most developers maintainers may want but it's their choice not flatpak.

**Comment by monkeyt00l** [comment]
> > And whenever a manifest fullfills these conditions, it is confirmed as sandboxed while otherwise there would be a warning message saying that it is not sandboxed.
> 
> AFAIK this is exactly how Gnome Software presents flatpak apps. Generally app store frontends are responsible for correct app presentation - if they show each flatpak as sandboxed then it's something to improve there. Flatpak is just packaging format.
> 
> When user installs app through flatpak cli then it will explicitly list all permissions app does have (as chosen by app developer/maintainer) and there won't be any word about _sandbox_.
> 
> I don't see anything in your proposal that needs changes in flatpak. Maybe some documentation needs to be clarified?

Basically there are two suggestions:

1. Make sure the user knows that sandboxing in flatpak is not always effective by default. Making this more clear in the documentation is a start, but most users don't really read it. While the flatpak project page does not advertise flatpak as providing a sandbox anymore, this is the most common narrative when flatpak is discussed and advertised among users. There are quite a lot users advertising their self improved flatpak "sandboxes" while running it on X11 because they believe it would actually help to isolate it a little bit, even though that would be just security theater in reality. 
While this isn't the fault of flatpak I think flatpak should make sure that users are aware that real sandboxing in flatpak isn't really feasible yet when it comes to most applications that are expected to run with their full functionality and instead provide some kind of verification.
Having a sandbox indication on Gnome Software is god, but their assessment is completely broken as well. I just checked the flatpak apps that had ineffective sandboxes according to the linked article and all of them are listed as sandboxed in gnome software. 
To solve this, I would like to see a minimal sandbox requirement definition coming from flatpak, that other projects like Gnome software could use.
Something like a simple manifest check:

```
if (has X11 access) || (has $HOME file access) || (has full device access)
then 
    print "This flatpak is not sandboxed! "
else
    print "No severe weaknesses were detected in the sandbox of this flatpak, this is not a confirmation the sandbox is secure"
```


2. Provide an optional sandbox mode that does possibly only provide a semi-functional application but actually enforces a real sandbox environment.
The optimal way to do this would be via a second "sandbox" manifest that can be activated from within the application.
For example in Adobe PDF Reader there is such an option that disables PDF scripting, network access and media files.
In flapaks like Evince there could e a similar button as part of the interface saying "run sandboxed" which would reload the flatpak app with the actual sandbox manifest, blocking everything that is known to lead to sandbox escape by default.
This would also be a clear indicator for the user that the default app isn't suitable to "see what this malware file does"

**Comment by mwleeds** [comment]
- The Flatpak CLI is for advanced users.
- If you find any issue with GNOME Software's presentation of Flatpak sandboxing, please report a bug here: https://gitlab.gnome.org/GNOME/gnome-software
- If you want to discuss adding sandboxing information on the Flathub website, this would be a good place to start: https://discourse.flathub.org/
- If you want to sandbox an app further than its packagers did, Flatseal or the Flatpak CLI provide ways of doing this.
