### ISSUE TITLE
[Feature request]: Trusted Desktop / Guest Mode?

### ISSUE THREAD

**Issue by nintyfan** [flatpak/flatpak#5221]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

Many years ago, I proposed guest mode to KWin, where KWin will disable/hide windows belongs to not secure apps. At that moment, it has many minuses. Bu now, we could integrate it with flatpak.

Former idea requires:
1. User click start guest mode (or similar)
2. Each window of app, which did not register as secured will be hidden
3. Starting new app will requires providing password
4. Opening Open/Save dialog will requiring password
5. Close guest mode will require password

But, previous idea was not fully secure. We can implement guest mode using for flatpak and made requirement that user could use only flatpak apps in this mode.

So:
1. There will exist separated (form normal) set of privileges, called guest privileges. Each app will contains list of guest privileges along app privileges
2. When switching to guest mode, each non-desktop window will be hidden, but user (in guest mode) see information about app running in normal mode and can allow access for guest mode for selected app. User must provide password in this case.
3. Each --filesystem privileges do not have any manner in guest mode - each filesystem was added by filesystem flag gets unmounted, but filesystems marked as non-unmount in guest mode. I do  not known if unmounting fs mounted in sandbox is possible. I think this would not broke app - if app open some file, it has file description and each file needed by app should be packaged. User could, of course mark mount point as accessible in guest mode, if they want.
4. Starting app outside sandbox (no manner if normal app or flatpak) will require password
5. Open/Save file dialog requires password to shown. If user do not provide password, app will be informed user cancel open/save operation.
6. User could exist guest mode by providing passeord

Use case will be, for example, sharing Steam games. Some friend could met with us, we can launch flatpaked Steam, and go do guest mode. We can still listen music, but guest could use our flatpaked Steam to playing games.

**Comment by smcv** [comment]
> Use case will be, for example, sharing Steam games. Some friend could met with us, we can launch flatpaked Steam, and go do guest mode. We can still listen music, but guest could use our flatpaked Steam to playing games.

Honestly, I'd suggest implementing that by adding a second user ID that has access to all your games (`guest` or `gamer` or something like that), logging out from your main user ID, and logging in as the guest user ID to play games; or by using "fast user switching" to put your main user ID's session in the background and switch to the guest user's session. That way, you get the security model that everything is forbidden unless specifically allowed, enforced by the well-understood Unix user-ID-based permissions model that has existed since the 1980s.

Running Steam as a Flatpak app is never going to have sandboxing as strong as we would ideally like, because Steam is a storefront/launcher for arbitrary games rather than being an "app" in the sense that Flatpak really intends, so it needs to have every permission that would be necessary for any of the games it can launch.

What you suggest here would be implementable, but would require a significant amount of work, with careful coordination between Flatpak, xdg-desktop-portal and the compositor. I can't speak for the compositor maintainers, but I don't think the Flatpak and xdg-desktop-portal maintainers have enough time available to do this on any reasonable timescale, so the detailed design and implementation would have to be done by someone who prioritizes it higher (maybe you). Even then, getting it reviewed and merged would be relatively time-consuming for those projects' maintainers, and keeping it working and secure it would increase the maintenance burden for Flatpak in future, so we would have to think very carefully about whether that's a responsibility we are able to accept.

The UX that you suggest also sounds quite similar to the UX you can already have with "fast user switching", so I don't think it necessarily provides enough benefit to be worth its significant cost.

**Comment by nintyfan** [comment]
I have some projects to maintain. If I found time, I would try to implement this.

But the idea is still good, event taking in mind of different user profile. Currently it's hard to share some data with other users under GNU/Linux. By implementing this, we could add path with our holidays photos to flatpak program and mark it as accessible by guests. We now ran program, switch to guest mode and mark this program as permitted to shown window in guest mode (and provide password to do this). Now, our friend could see all of photos from our holidays, but nothing else.

As I said, I will try to implement this in free time, if I found it.
Thanks!

**Comment by mwleeds** [comment]
> As I said, I will try to implement this in free time, if I found it. Thanks!

Please remember that for any significant feature, implementation is only the first step. It would also need code review time from qualified people as well as maintenance over time. So I would advise against proceeding ahead with implementation without having a plan for code review and maintenance (and design for that matter).

Dropping a link to a related feature, GNOME kiosk mode: https://gitlab.gnome.org/GNOME/gnome-kiosk
