### ISSUE TITLE
[Bug]: flatpak --gl-drivers doesn't show user-installed drivers

### ISSUE THREAD

**Issue by orowith2os** [flatpak/flatpak#5229]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.1

### What Linux distribution are you using?

Fedora Linux

### Linux distribution version

37

### What architecture are you using?

x86_64

### How to reproduce

1. Enable Flathub Beta as user
2. install org.freedesktop.Platform.GL.mesa-git
3. run `flatpak --gl-drivers`

### Expected Behavior

`flatpak --gl-drivers` would show default, host, and mesa-git

### Actual Behavior

`flatpak --gl-drivers` only shows default and host

### Additional Information

`flatpak --gl-drivers` doesn't seem to show installed org.freedesktop.Platform.GL extensions when they're installed as a user. Additionally, maybe it shouldn't show `host` unless the files for it actually *exist* in the appropriate directories?

**Comment by orowith2os** [comment]
Tested using a custom org.freedesktop.Platform.GL extension installed as a user, it indeed does not show user gl extensions.

**Comment by mwleeds** [comment]
I don't know much about how Flatpak uses GL drivers, but looking at the [implementation](https://github.com/flatpak/flatpak/blob/7a99c82900ea0e529335efae9e5210fe3366de46/common/flatpak-utils.c#L557) of `flatpak --gl-drivers` it doesn't look at installed flatpaks at all; it only checks the `FLATPAK_GL_DRIVERS` environment variable as well as `/sys/module/nvidia/version` which exposes what nvidia driver the kernel has loaded.

The description of the `--gl-drivers` option is "Print active gl drivers and exit", so that would also point to the expected behavior being that it looks at the kernel drivers. The `org.freedesktop.Platform.GL` extensions are userspace libraries rather than kernel drivers (which are managed by your OS rather than Flatpak).

**Comment by orowith2os** [comment]
Testing gl-drivers again with a manually set FLATPAK_GL_DRIVERS, it seems to behave differently from how I'd expect it.

I have Lutris running with `FLATPAK_GL_DRIVERS=asahi`
Bottles with `mesa-git`
Other apps with `default`

If I set FLATPAK_GL_DRIVERS *before* `--gl-drivers` it shows what the var is set to, but it shows that even if the extension is invalid (not installed or not available).
![image](https://user-images.githubusercontent.com/93224879/210155381-b8b912dc-660b-4f0d-b728-c084c0ceca4d.png)

Wouldn't it be appropriate to have it view all the available FLATPAK_GL_DRIVERS opts and list all inactive and active ones?
