### ISSUE TITLE
Packaging apps with a systemd service or unix deamon running in backend

### ISSUE THREAD

**Issue by adityashah1212** [flatpak/flatpak#524]
This is more of a question than an issue, is it possible to package apps with a systemd service or unix deamon running in the backend, something like teamviewer?

**Comment by alexlarsson** [comment]
Its possible to package something that a systemd service could run, but there is nothing that lets you automatically do that from the flatpak. You have to manually set up the systemd service file or equivalent. This is on purpose, because setting up such services requires root privileges, which is not something we want to grant flatpaked apps.

**Comment by cz172638** [comment]
not true, i have systemd units for user.
for testing and development purposes i have postgresql instances running under my userid to avoid messing with sudo etc.

[https://github.com/zoqaeski/systemd-user-units ](https://github.com/zoqaeski/systemd-user-units )
[https://www.freedesktop.org/software/systemd/man/systemd.unit.html](https://www.freedesktop.org/software/systemd/man/systemd.unit.html)
(Table 2.  Load path when running in user mode (--user). )
