### ISSUE TITLE
[Bug]: on Arch, installing and removing GNOME UI results in parental controls (malcontent) errors

### ISSUE THREAD

**Issue by StandingPadAnimations** [flatpak/flatpak#5264]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.1

### What Linux distribution are you using?

Arch Linux

### What architecture are you using?

x86_64

### How to reproduce

1. Remove GNOME using `sudo pacman -R gnome`
2. Run a Flatpak app with `flatpak run ---`
3. Recieve the following error: `error: Not allowed to query parental controls data for user 1000`

### Expected Behavior

To be able to use Flatpak without needing GNOME

### Actual Behavior

Flatpak seems to complain about the lack of parental control data

### Additional Information

* No parental controls have ever been set, which makes this all the more confusing
* Using the Hyprland window manager (the reason why I'm removing GNOME)
* Distro is technically EndeavorOS with GNOME preinstalled, but it's extremely close to Arch (only adds some extra mirrors and preinstalled apps)

**Comment by smcv** [comment]
This sounds as though you previously had libmalcontent and all of its supporting files installed, but removing GNOME had the side-effect of removing libmalcontent's polkit rules?

If that's the case, please talk to your distro's Flatpak packager: it should be given enough dependencies to make it work on non-GNOME desktops.

**Comment by smcv** [comment]
> No parental controls have ever been set, which makes this all the more confusing

Flatpak can't know that unless it asks the system service that would responsible for storing those rules if you had them.

**Comment by io7m** [comment]
I ran into this on Arch. For what it's worth, a workaround is:

```
$ sudo pacman -S malcontent
```

`malcontent` is the package that contains the actual policy files, for whatever reason.

**Comment by EntityinArray** [comment]
i don't want malcontent on my system, i never had it prior to installing gnome and everything worked fine.
if malcontent is not available, apps should start
parental controls should only block something if it's explicitly known that it needs to be blocked. if it's unknown, parental controls disengage

**Comment by pwithnall** [comment]
> This sounds as though you previously had libmalcontent and all of its supporting files installed, but removing GNOME had the side-effect of removing libmalcontent's polkit rules?
> 
> If that's the case, please talk to your distro's Flatpak packager: it should be given enough dependencies to make it work on non-GNOME desktops.

Indeed, this sounds like an Endeavour/Arch packaging bug.

**Comment by snake-scaly** [comment]
There is a single line in the `flatpak run` manual:

> If parental controls support is enabled, flatpak will check the current user’s parental controls settings, and will refuse to run an app if it is blocklisted for the current user.

However I couldn't find any information about how flatpak is detecting this support. I know that you can install flatpak on a minimal Arch installation, and it will work. However after installing and then removing Gnome, flatpak now refuses to work without these two files:

```
/usr/share/polkit-1/actions/com.endlessm.ParentalControls.policy
/usr/share/polkit-1/rules.d/com.endlessm.ParentalControls.rules
```

I suspect that something got configured somewhere and now got stuck.

**Comment by pwithnall** [comment]
> I know that you can install flatpak on a minimal Arch installation, and it will work. However after installing and then removing Gnome, flatpak now refuses to work without these two files:
> 
> ```
> /usr/share/polkit-1/actions/com.endlessm.ParentalControls.policy
> /usr/share/polkit-1/rules.d/com.endlessm.ParentalControls.rules
> ```

That sounds like a packaging issue, please file a bug against Arch.

**Comment by snake-scaly** [comment]
I cannot file a bug against Arch until I understand what the packaging issue is, exactly. Why flatpak works without these files on a clean install? What causes it to suddenly need them?

**Comment by StandingPadAnimations** [comment]
> > I know that you can install flatpak on a minimal Arch installation, and it will work. However after installing and then removing Gnome, flatpak now refuses to work without these two files:
> > ```
> > /usr/share/polkit-1/actions/com.endlessm.ParentalControls.policy
> > /usr/share/polkit-1/rules.d/com.endlessm.ParentalControls.rules
> > ```
> 
> That sounds like a packaging issue, please file a bug against Arch.

I don't think so. The missing files relate to GNOME Parental controls, and Arch doesn't change configs willy nilly (without creating a pacnew file)

**Comment by StandingPadAnimations** [comment]
Here's the PKGBUILD files for malcontent (Gnome parental controls) and Flatpak respectively:
- https://gitlab.archlinux.org/archlinux/packaging/packages/malcontent/-/blob/main/PKGBUILD
- https://gitlab.archlinux.org/archlinux/packaging/packages/flatpak/-/blob/main/PKGBUILD

On first skim through malcontent's PKGBUILD, nothing seems like it would cause a conflict

**Comment by snake-scaly** [comment]
For reference, here's an issue I filed against the malcontent package. https://gitlab.archlinux.org/archlinux/packaging/packages/malcontent/-/issues/1

**Comment by StandingPadAnimations** [comment]
I think there's some leftover malcontent config that Flatpak sources for some reason; that's my only guess at this point

**Comment by hfiguiere** [comment]
File a new issue instead of piggybacking on closed one.

**Comment by hfiguiere** [comment]
then let's reopen it.

**Comment by pwithnall** [comment]
@snake-scaly did you restart your computer (or `accounts-daemon.service`) since uninstalling GNOME? If you do, does the error from `flatpak run` go away?

**Comment by EntityinArray** [comment]
> @snake-scaly did you restart your computer (or `accounts-daemon.service`) since uninstalling GNOME? If you do, does the error from `flatpak run` go away?

No, it keeps returning `error: Not allowed to query parental controls data for user 1000` when running any app via `flatpak run`
Launching apps via dekstop environment fails silently which confused me initially

**Comment by pwithnall** [comment]
What files are in `/usr/share/accountsservice/interfaces/`?

**Comment by pwithnall** [comment]
> No, it keeps returning `error: Not allowed to query parental controls data for user 1000`
> when running any app via `flatpak run`

Presumably you mean “yes I have restarted, but the error is still present” rather than “no I haven’t restarted and the error is still present”?

**Comment by smcv** [comment]
Arch's tendency to have each source package build fewer, larger binary packages is probably contributing to this, if not the root cause.

malcontent has a GUI part (which depends on Flatpak libraries), and a non-GUI part including a library (which Flatpak depends on). If the packages aren't split, then this is a circular dependency.

In e.g. Debian and Fedora, the malcontent source package builds more, smaller binary packages, which makes the dependencies linear: GUI -> GUI library -> Flatpak -> non-GUI library.

**Comment by pwithnall** [comment]
Having dug into it a bit more, I’m not entirely sure about the packaging files split. malcontent is designed so that if the accountsservice files aren’t installed, it will return an error saying that parental controls is disabled (which flatpak ignores and moves on from). If the accountsservice files *are* installed, the polkit files *must also* be installed, otherwise the error mentioned here is raised, and flatpak (correctly) fails closed.

Both the Debian and Arch packaging do the same thing, in that they ship the accountsservice *and* polkit files in the GUI package for malcontent. Doing that, or shipping them both in the library package, would be fine. The thing to avoid is shipping them separately.

One thing I’ve spotted which could definitely cause this issue is that accountsservice [doesn’t watch for changes to the set of installed extension interfaces](https://gitlab.freedesktop.org/accountsservice/accountsservice/-/blob/main/src/daemon.c?ref_type=heads#L872) (the files in `/usr/share/accountsservice/interfaces`). So if those files are installed before boot, then accountsservice loads (as it does on every boot), then those files are removed (by uninstalling GNOME or whatever), accountsservice will continue to advertise those interfaces to libmalcontent. polkit, though, *does* watch for changes to its installed set of policies. So after the uninstall, polkit will return a permissions error, and this bug will be hit.

That should be fixed by restarting accountsservice, though. That’s what I’m trying to establish with my last few questions.

**Comment by snake-scaly** [comment]
@pwithnall I feel really stupid now. For me, a system restart after removing `malcontent` did indeed fix the problem. I can only guess that that accountsservice thing didn't get restarted when the malcontent package was removed.

**Comment by pwithnall** [comment]
Thanks for the confirmation. I’ll talk to the accountsservice maintainers and see what kind of fix they’d be happy with in accountsservice.

I think this means it’s not actually a packaging bug in Arch — although Arch probably could work around the issue (for now) by restarting `accounts-daemon.service` in the post-install and post-remove scripts for the `malcontent` package.

**Comment by snake-scaly** [comment]
I'm pretty sure that's a responsibility of a package post-transaction script to restart all affected daemons. So yes, likely a malcontent packaging issue, but not the one I suspected.

**Comment by pwithnall** [comment]
Closing as fixed by either/a combination of https://gitlab.freedesktop.org/accountsservice/accountsservice/-/merge_requests/148 and/or changing the Arch packages to restart `accounts-service.daemon` on install/removal of `malcontent`.

**Comment by ValdikSS** [comment]
Please reopen.

I'm running Fedora 43.
What I did:

* While using KDE, installed `gnome-shell` to debug an unrelated issue (see which packages have been installed)
* After debugging the issue, reverted everything I've installed: `dnf history rollback 803`
* Flatpak applications no longer work

Exactly 50 previously not installed packages have been installed on step 1, then uninstalled on step 3.

[installed.txt](https://github.com/user-attachments/files/28234586/installed.txt)  
[removed.txt](https://github.com/user-attachments/files/28234585/removed.txt)

Including:
* malcontent
* malcontent-control
* malcontent-ui-libs

Fixed by rebooting.
