### ISSUE TITLE
[Bug] `flatpak list` crashes if there is invalid syntax in overrides

### ISSUE THREAD

**Issue by ratijas** [flatpak/flatpak#5293]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1:1.15.1-1

### What Linux distribution are you using?

Arch Linux

### Linux distribution version

6.1.9-arch1-1

### What architecture are you using?

x86_64

### How to reproduce

1. Mess up with override config file
2. Run `$ flatpak list`

### Expected Behavior

```
Core was generated by `flatpak list'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055ffc9412544 in flatpak_deploy_get_deploy_data (error=<optimized out>, cancellable=<optimized out>, required_version=<optimized out>, deploy=<optimized out>) at ../flatpak/common/flatpak-dir.c:1477
1477      return flatpak_load_deploy_data (deploy->dir,
[Current thread is 1 (Thread 0x7f8264687a40 (LWP 65321))]
```

This is the error that `flatpak list` blows up with.

Flatpak crashes when parsing malformed app config override. For example, using KDE's new (and not yet ironed out) Flatpak permissions KCM, I somehow ended up with the following config:

![image](https://user-images.githubusercontent.com/6737986/217115371-5750f2c9-ba09-452f-bd95-e7b6a841b211.png)

The bug is gone as soon as I remove the offending override file from `$HOME/.local/share/flatpak/overrides/`.

For now I will remove env editing from our config page from public access until it is fixed at least on our side. But ideally Flatpak should also work on robustness, as to not let users shot themselves so easily.

### Actual Behavior

Shouldn't crash, and should provide sensible diagnostics.

### Additional Information

Originally posted in https://github.com/flatpak/flatpak/issues/4908, but I was advised to reopen as a new issue.

**Comment by smcv** [comment]
```
#0  0x000055ffc9412544 in flatpak_deploy_get_deploy_data (error=<optimized out>, cancellable=<optimized out>, required_version=<optimized out>, deploy=<optimized out>) at ../flatpak/common/flatpak-dir.c:1477
```

There's a more useful backtrace in #5292.

**Comment by smcv** [comment]
> ideally Flatpak should also work on robustness

Merge requests are extremely welcome if this is something you're able to help with.

**Comment by smcv** [comment]
I've stolen the title from my duplicate report #5292 (which I opened at about the same time) since this seems to be specific to `flatpak list`: as described in #5292, `flatpak info` and `flatpak run` seem to handle the error correctly.

(Of course it would be more useful if they included the filename with the invalid overrides in the error message: merge requests for that also very welcome.)

**Comment by ratijas** [comment]
> Merge requests are extremely welcome if this is something you're able to help with.

Sure, whenever I get some free time after working on KDE front-end for it 🙃

It still has long ways to go, to be honest

**Comment by smcv** [comment]
> For example, using KDE's new (and not yet ironed out) Flatpak permissions KCM, I somehow ended up with the following config: [not a valid GKeyFile]

Do KDE libraries have an equivalent of GLib's GKeyFile, which is a slight generalization of `.desktop` syntax to cover all the syntactically compatible freedesktop-adjacent file formats like D-Bus `.service`, Telepathy `.manager`, Flatpak metadata and overrides, and so on?

If they don't, I'd suggest adding one and using that, or even just using the C API of GLib's GKeyFile directly (since Flatpak depends on GLib, you are always going to have at least an indirect GLib dependency in a UI frontend for Flatpak, so you might as well get some value out of it).

That way, writing out new overrides will either result in either valid syntax or a crash, but definitely not a syntactically invalid file.
