### ISSUE TITLE
[Feature request]: Flatpak should have parameters for target Flatpak version and a minimum Flatpak version just like Android

### ISSUE THREAD

**Issue by MysteriousOrb2000** [flatpak/flatpak#5297]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

In the Android app development world, apps have a **minSdkVersion** and **targetSdkVersion**. The **minSdkVersion** is the minimum Android OS version that is able to run the app with its bare-essential functions intact while **targetSdkVersion** is the Android version where the developer has developed the app to run well as expected on that Android version (or newer). Example would be an app that targets Android 13 while allowing installation on Android 4.1 as the minimum; although the app may not be able to take advantage of some features introduced since Android 10, it still can function properly on the older versions.

_See reference for more details:_ https://developer.android.com/guide/topics/manifest/uses-sdk-element

With Flatpaks being universal and many distros shipping either current or older versions of Flatpak for variety of reasons (e.g. LTS distrobutions), having this two parameters would help the user and developers understand how the apps might run. For example, let's say in the future that Flatpak version 1.30 has some feature or APIs that allow you to spoof something for security reasons and does not have any mitigations for Flatpak versions before 1.16 to run correctly at all, the maintainer could add the parameter where the minimum flatpak version is 1.16 and the app can take advantage of features introduced in newer versions up to 1.30 since the app targets it.

**Comment by smcv** [comment]
Google/Android controls their entire platform as a monolithic thing, and can represent it as a single number. In Flatpak-world, because it's a community project and we don't have armies of programmers employed to work full-time on it, responsibility for the equivalent of the Android platform SDK functionality level is divided between several projects.

The closest equivalent of the Android SDK version is a mixture of the runtime (which is chosen by the app developer and they always get the branch they wanted, no minimum/target negotiation needed); the Flatpak version (chosen by the OS distributor/integrator), and the portals' versions (also chosen by the OS distributor/integrator).

Apps can specify a minimum Flatpak version if they need a particular feature, and older Flatpak will refuse to install them. I think Steam does this, for instance.

Apps can't currently specify a minimum portal version, although in practice the portals are correlated with the Flatpak version (if your Flatpak version is 2 years old then probably so are your portals).

Apps can't currently specify a target Flatpak version, because Flatpak doesn't currently have any mechanisms for behaving like an older version for backwards compatibility. Likewise for portals.

> the app can take advantage of features introduced in newer versions up to 1.30 since the app targets it

At the moment, apps can take advantage of any new features they know about, however new the feature is, because we've generally just given every app that "new" behaviour. For instance, Flatpak 1.12.x introduced a shared `/tmp` and `$XDG_RUNTIME_DIR` for all instances of the same app, and all apps get that behaviour, whether they have asked for it or not.

The only time that's not desirable is if the "new" behaviour is better in the abstract, but is an incompatible change that can break old apps that are assuming the "old" behaviour. As far as I know, we've never added a feature like that, other than perhaps `fallback-x11` (which was represented as a special permission flag that acts as a weaker version of `x11`, meaning it already has a way for apps that support both Wayland and X11 to opt-in to allowing the X11 socket to be disabled when Wayland is available, without needing a numeric feature level).

If we add a feature in future that needs an opt-in and can't easily be represented by an existing construct like a permission, then the time we add that feature would also be the time to add a mechanism for apps to opt-in to the new behaviour; and until that happens, there's little point in speculatively adding that mechanism, and a risk that if we spend our limited time on adding it, it'll either not be useful or be actively counterproductive.

If you have a feature in mind that would need a more involved compatibility negotiation mechanism, please ask for that feature - adding the compatibility negotiation mechanism would be a prerequisite for it, and having a concrete example of why something is necessary often results in a better design.

> some feature or APIs that allow you to spoof something for security reasons

If something is done for security reasons, then we generally have to do it for all apps or not at all. If there was an unintended sandbox escape (or some other security vulnerability) which was fixed in 1.30, but apps could disable the fix by claiming to have been developed for Flatpak 1.28, then malicious apps would surely just say "I target Flatpak 1.28" and do what they want to do, leaving everyone vulnerable? That's not what we want.
