### ISSUE TITLE
[Bug]: Steam fails to launch because a global override for .themes and .icons exist, despite app override removing access

### ISSUE THREAD

**Issue by thatLeaflet** [flatpak/flatpak#5322]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.1

### What Linux distribution are you using?

Fedora Silverblue

### Linux distribution version

37

### What architecture are you using?

x86_64

### How to reproduce

1. Create global override for ~/.themes and ~/.icons
2. Create app override for Steam that removes access to ~/.themes and ~/.icons
3. Restart computer
4. Launch Steam from terminal using `flatpak run com.valvesoftware.Steam`

### Expected Behavior

Since Steam fails to launch with access to ~/.themes and ~/.icons, one would assume that removing its ability to access those overrides with app-specific ones would stop the issue.

### Actual Behavior

Steam still fails to launch. Flatpak creates a dummy/broken symlink to ~/.themes, which still causes Steam to fail to launch due to an error that states, "bwrap: Can't make symlink at /var/home/evan/.themes: File exists".

### Additional Information

![Screenshot from 2023-02-25 15-56-26](https://user-images.githubusercontent.com/80165419/221379248-2eb537dc-2485-46f5-8b7b-be4f4b020a2b.png)

This screenshots show off a few details. In the terminal, it shows my global override giving all flatpaks access to ~./themes; it also shows my app overrides for Steam, which shows that I blocking it access to ~/.themes; you can see the error message that shows when I try to run Steam. In my file manager, you can see the .themes file that is preventing Steam from launching. If I delete this file, I can then launch Steam. However, it repopulates after a reboot.

**Comment by smcv** [comment]
The output of `flatpak run -vv com.valvesoftware.Steam` would probably be useful here (as a gist or text file rather than as a screenshot, please).

**Comment by thatLeaflet** [comment]
[Gist where I have global overrides set for ~/.themes and ~/.icons, but no app overrides set for Steam](https://gist.github.com/thatLeaflet/02eb9e2bdd9e4f5bdab207be29fd2da9).

[Gist where I have global overrides set for ~/.themes and ~/.icons, and with two app overrides set for Steam that should remove access to ~/.themes and ~/.icons](https://gist.github.com/thatLeaflet/5ff6ca4646dab597d288b88495c96e15).

**Comment by smcv** [comment]
Ah, I see what has happened here. Flatpak interprets `!~/.themes` as a request to specifically hide the contents of `~/.themes` (not just ignore the global override, but replace it with a different override) and so it tries to mount an empty `tmpfs` over the top. But `~/.themes` is a symbolic link, so Flatpak tries to mount the `tmpfs` on the target of the symbolic link instead, and re-create the symbolic link itself, at which point you get a conflict with Steam's `--persist=.`.

With only the global override:

```
F: Trying to export read/write: /var/home/evan/.themes
F: /var is not a symlink
F: /var/home is not a symlink
F: /var/home/evan is not a symlink
F: /var/home/evan/.themes is a symlink, resolved to /var/home/evan/.local/share/themes
F: Trying to export the target instead: /var/home/evan/.local/share/themes
F: Trying to export read/write: /var/home/evan/.local/share/themes
```

or with the per-app override as well:

```
F: Trying to replace with tmpfs: /var/home/evan/.themes
F: /var is not a symlink
F: /var/home is not a symlink
F: /var/home/evan is not a symlink
F: /var/home/evan/.themes is a symlink, resolved to /var/home/evan/.local/share/themes
F: Trying to export the target instead: /var/home/evan/.local/share/themes
F: Trying to replace with tmpfs: /var/home/evan/.local/share/themes
```

This is essentially the same issue as #1971 and #2387, and like those, implementing https://github.com/containers/bubblewrap/issues/549 and then making use of it in Flatpak would probably be at least a 90% solution.

You can probably work around this by changing your global overrides to `--filesystem=xdg-data/themes` and `--filesystem=xdg-data/icons`, and your Steam overrides (if you still want them and they are not just a workaround for the same issue) to `--nofilesystem=xdg-data/themes` and `--nofilesystem=xdg-data/icons`.

Or if you're editing the configuration file directly, those would be spelled `xdg-data/themes` and `!xdg-data-themes`, and the same for icons.

You might also want to make the global overrides read-only instead of read/write (`xdg-data/themes:ro` and the same for icons)

**Comment by thatLeaflet** [comment]
Thanks for the help! It seems that setting the global overrides using xdg-data/themes and xdg-data/icons bypasses the issue because the .themes and .icons files are not being created in the Steam folder, so Steam has no issue with the folders already existing.

And given that those two other issues exist, I guess it's safe to close this issue.
