### ISSUE TITLE
how do I copy a directory using type:dir?

### ISSUE THREAD

**Issue by chaogamer** [flatpak/flatpak#5333]
I'm trying to do so, but for some reason I'm getting an error saying the directory is not found, despite it being the correct name, there is not enough resources to help me through with type:dir

So how do I copy a directory?

Here's my code btw

`app-id: org.sixtyninestudios.kublitruntime: org.freedesktop.Platformruntime-version: '22.08'sdk: org.freedesktop.Sdkcommand: Kublitfinish-args:   - --share=ipc  - --socket=x11 # <-- Godot needs X11  - --socket=pulseaudio  - --device=drimodules:  - name: Kublit    buildsystem: simple    build-commands:      - install -D KublitRelease.x86_64 /app/bin/Kublit/KublitRelease.x86_64      - install -Dm644 Getris-master * -t /app/bin/Kublit/Getris-master/    sources:      - type: file        path: KublitRelease.x86_64      - type: dir        path: Getris-master`

**Comment by smcv** [comment]
Sorry, this is an issue tracker for improving Flatpak itself, not a forum for giving advice on packaging your own software. https://discourse.flathub.org/ is probably a better place to ask this sort of thing (but it seems to be broken today).

The text you pasted is a flatpak-builder manifest, so if you think there is a bug in how it has been interpreted, that should be reported to https://github.com/flatpak/flatpak-builder rather than here.
