### ISSUE TITLE
Discuss how to package Rust/Cargo applications (and other non-standard build systems)

### ISSUE THREAD

**Issue by moosingin3space** [flatpak/flatpak#536]
When I read the documentation for `flatpak-builder`, I see that it wants a project to support the Build API. Rust applications that build with Cargo don't fit as nicely into this mold. I'm curious what the expectation is for a non-standard build system. Should the build system be extended to produce Flatpaks itself, or should `flatpak-builder` be extended to support arbitrary build systems, in a similar manner to Arch Linux `PKGBUILD`s?

**Comment by alexlarsson** [comment]
Oh, the build api just makes it easier to build with f-b, you can build whatever you want if you add a custom makefile. Alternatively we're making that not required by https://github.com/flatpak/flatpak/pull/516

**Comment by TingPing** [comment]
The "Build API" should probably not be mentioned in the first place, it is extremely autotools specific and even already Flatpak supports CMake and Meson.

**Comment by moosingin3space** [comment]
So, regarding Rust/Cargo specifically, we need:
- The ability to run `cargo fetch` or `cargo vendor` or something *outside* the sandbox, so all dependencies can be fetched.
- Run `cargo build --release` *inside* the sandbox
- `cp` some files around to fit the structure of a flatpak

Is all this possible with `flatpak-builder`? 

I'm also interested in packaging Servo, which has a more complicated build system. The system in #516 will support this sort of packaging?

**Comment by alexlarsson** [comment]
Its not generally possible to run something outside the sandbox like that. The whole point of the build is that we have all the build dependencies inside the runtime, and don't rely on host side tooling. You can however, disable the network sandboxing for a particular module, so that you can run something that downloads dependencies. (At least unless you specify --sandbox to flatpak-builder.)

Still, while this works, it doesn't really match how flatpak-builder normally works. Normally the json specifies the source up to sha256sums of every piece of sourcecode, and flatpak verifies that, so that the build is completely reproducible.

**Comment by lilianmoraru** [comment]
I've also hit this issue today.

**Comment by daa84** [comment]
And how about build tools? If i want to download rustc/cargo for build how to do this?

**Comment by alexlarsson** [comment]
This issue was moved to flatpak/flatpak-builder#15
