### ISSUE TITLE
[Bug]: Flatpak uses llmvpipe instead of i915g on Intel iGPUs as of branch 22.08

### ISSUE THREAD

**Issue by HeteroChromia420** [flatpak/flatpak#5384]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

Flatpak 1.14.4

### What Linux distribution are you using?

Debian

### Linux distribution version

Unstable

### What architecture are you using?

x86_64

### How to reproduce

Install org.freedesktop.Platform.GlxInfo (Branch 22.08)
execute "flatpak run org.freedesktop.Platform.GlxInfo -B" on affected hardware (Being intel iGPUs using the "i915g" driver)

### Expected Behavior

glxinfo printing out the proper intel GPU info, instead of llvmpipe

### Actual Behavior

errors out with the following error, then falls back to llvmpipe:
libGL error: MESA-LOADER: failed to open i915: /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/i915_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/GL/default/lib/dri, suffix _dri)
libGL error: failed to load driver: i915

**Comment by orowith2os** [comment]
The Mesa builds in 22.08 don't provide the i915 driver, since it was removed when mesa-amber was branched. I'll look into getting mesa-amber into the runtime.

https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/freedesktop-sdk-21.08.17.1/elements/extensions/mesa/mesa.bst#L48

https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/freedesktop-sdk-22.08.9/elements/extensions/mesa/mesa.yml#L39

**Comment by orowith2os** [comment]
Upstream issue: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1573

**Comment by orowith2os** [comment]
I closed the upstream issue in favor of submitting something to Flathub. Will provide further information when I submit a package.

**Comment by HeteroChromia420** [comment]
in the meanwhile i just dragged and dropped the 21.08 branch's .so files for the legacy i915 driver. it isn't a perfect solution, more of a band-aid at the moment.

**Comment by smcv** [comment]
The contents of a runtime extension are chosen by the runtime extension maintainers, not by Flatpak, and there is no code change that can be made in Flatpak to make a driver exist if the runtime extension maintainers haven't packaged it, so I'm closing this issue. Flatpak seems to be doing the right thing here (it's downloading the `GL.default` extension), but the bug is that there is no driver for older Intel GPUs in the 22.08 version of the `GL.default` extension. That would be an issue to report to https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues rather than here.

I'm surprised that the 22.08 runtime doesn't enable Mesa's `i915g` driver - it's using the same major version of Mesa as Debian unstable, which *does* enable the `i915g` driver. Enabling that driver might be a relatively simple solution?

**Comment by smcv** [comment]
I reported https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1577 to get this tracked in the right place.

**Comment by HeteroChromia420** [comment]
thanks for forwarding this to the right place, i wasn't sure where to report this one :sweat_smile:
