### ISSUE TITLE
[Bug]: Flatpak MIME handler is preferred over system's

### ISSUE THREAD

**Issue by brccabral** [flatpak/flatpak#5403]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.7

### What Linux distribution are you using?

Ubuntu

### Linux distribution version

Linux ubuntu 5.19.0-41-generic #42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### What architecture are you using?

x86_64

### How to reproduce

1. Set Firefox to handle http/https
```
xdg-mime default firefox.desktop x-scheme-handler/http
xdg-mime default firefox.desktop x-scheme-handler/https
```
2. Install Brave as Flatpak
3. Query the default mimetype
```
xdg-mime query default x-scheme-handler/https
```
4. It reads `com.brave.Browser.desktop`, not `firefox.desktop`
5. Set again Firefox to handle http/https
```
xdg-mime default firefox.desktop x-scheme-handler/http
xdg-mime default firefox.desktop x-scheme-handler/https
```
6. Querying the default still responds as `com.brave.Browser.desktop`
```
xdg-mime query default x-scheme-handler/https
```

### Expected Behavior

The default handle from the system should have priority over Flatpak.

### Actual Behavior

Flatpak handle get priority over the system, it should not be.

**Comment by smcv** [comment]
This is controlled by the [freedesktop.org MIME apps specification](https://specifications.freedesktop.org/mime-apps-spec/mime-apps-spec-latest.html).

What is in each of the files listed in the table in <https://specifications.freedesktop.org/mime-apps-spec/mime-apps-spec-latest.html#file>?

**Comment by smcv** [comment]
I can reproduce this in a virtual machine with an Ubuntu 22.04 live image, and it looks as though `xdg-mime` might be doing the wrong thing.

Steps:

* Add `universe` to all entries in `/etc/apt/sources.list`
* Initial state:
    * `XDG_CURRENT_DESKTOP` is `ubuntu:GNOME`
    * `XDG_CONFIG_HOME` is unset (so the default will be used, `~/.config`)
    * `XDG_CONFIG_DIRS` is `/etc/xdg/xdg-ubuntu:/etc/xdg`
    * `XDG_DATA_HOME` is unset (so the default will be used, `~/.local/share`)
    * `XDG_DATA_DIRS` is `/usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop`
    * `find ~/.config /etc ~/.local/share /usr/local/share /usr/share /var/lib/snapd/desktop -name '*mimeapps.list'` returns:
        * `/usr/share/applications/gnome-mimeapps.list`: configures
            * `x-scheme-handler/http=firefox-esr.desktop;firefox.desktop;`
            * `x-scheme-handler/https=firefox-esr.desktop;firefox.desktop;`
        * `/usr/share/gdm/greeter/applications/mimeapps.list`: not used in a normal desktop session
    * `find ~/.config /etc ~/.local/share /usr/local/share /usr/share /var/lib/snapd/desktop -name '*defaults.list'` (a legacy filename) returns:
        * `/etc/gnome/defaults.list`
            * `x-scheme-handler/http=firefox.desktop;`
            * `x-scheme-handler/https=firefox.desktop;`
        * `/usr/share/applications/defaults.list`
            * `x-scheme-handler/http=firefox.desktop;`
            * `x-scheme-handler/https=firefox.desktop;`
* `sudo apt update`
* `sudo apt install flatpak`
* `flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo`
* `export XDG_DATA_DIRS=$HOME/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}`
* `flatpak install com.brave.Browser`, accept, wait for it to install
* `find ~/.config /etc ~/.local/share /usr/local/share /usr/share /var/lib/snapd/desktop /var/lib/flatpak -name '*mimeapps.list'` returns the same files as before
* `/usr/share/applications/gnome-mimeapps.list` still lists `firefox-esr.desktop` and `firefox.desktop` for `x-scheme-handler/http` and `x-scheme-handler/https`
* similarly the `*defaults.list` files are the same as before

**Comment by brccabral** [comment]
This command
```
XDG_UTILS_DEBUG_LEVEL=2 xdg-mime query default x-scheme-handler/https
```
Returns 
```
Checking /home/brccabral/.config/mimeapps.list
Checking /usr/share//applications/gnome-mimeapps.list
Checking /home/brccabral/.local/share/applications/gnome-defaults.list and /home/brccabral/.local/share/applications/gnome-mimeinfo.cache
Checking /home/brccabral/.local/share/applications/defaults.list and /home/brccabral/.local/share/applications/mimeinfo.cache
Checking /home/brccabral/.local/share/flatpak/exports/share/applications/gnome-defaults.list and /home/brccabral/.local/share/flatpak/exports/share/applications/gnome-mimeinfo.cache
Checking /home/brccabral/.local/share/flatpak/exports/share/applications/defaults.list and /home/brccabral/.local/share/flatpak/exports/share/applications/mimeinfo.cache
Checking /var/lib/flatpak/exports/share/applications/gnome-defaults.list and /var/lib/flatpak/exports/share/applications/gnome-mimeinfo.cache
Checking /var/lib/flatpak/exports/share/applications/defaults.list and /var/lib/flatpak/exports/share/applications/mimeinfo.cache
Checking /usr/local/share//applications/gnome-defaults.list and /usr/local/share//applications/gnome-mimeinfo.cache
Checking /usr/local/share//applications/defaults.list and /usr/local/share//applications/mimeinfo.cache
Checking /usr/share//applications/gnome-defaults.list and /usr/share//applications/gnome-mimeinfo.cache
Checking /usr/share//applications/defaults.list and /usr/share//applications/mimeinfo.cache
com.brave.Browser.desktop
```

The `query` is reading `mimeinfo.cache` files.

**Comment by smcv** [comment]
I now see what is happening here.

Ubuntu 22.04 does not install anything named `firefox.desktop` or `firefox-esr.desktop`. Instead, it installs Firefox as a Snap app, `firefox_firefox.desktop`. So this is not Flatpak's MIME handler being preferred over the system's: it's a MIME handler from one non-system app framework (Flatpak) being preferred over one from another non-system app framework (Snap).

The fact that Ubuntu doesn't install anything named `firefox.desktop` or `firefox-esr.desktop` means that its configuration for what is the default browser is ineffective. You can see this more clearly by running `gio mime`, a more verbose implementation of essentially the same thing as `xdg-mime`:

```
ubuntu@ubuntu:~$ gio mime x-scheme-handler/http
Default application for “x-scheme-handler/http”: com.brave.Browser.desktop
Registered applications:
	com.brave.Browser.desktop
	firefox_firefox.desktop
Recommended applications:
	com.brave.Browser.desktop
	firefox_firefox.desktop
```

So, Ubuntu has preinstalled `firefox_firefox.desktop` as part of a Snap, you have installed Brave as a Flatpak app, and the system defaults tell us that neither `firefox_firefox.desktop` nor `com.brave.Browser.desktop` should be preferred as the system default browser. The result is that implementations of the MIME handler spec (like `xdg-mime` and `gio mime`) are asked to choose one of the two non-preferred browsers as found in `mimeinfo.cache`, essentially arbitrarily. I suspect that the reason Brave is "winning" here is simply that `com` < `firefox` in alphabetical order.

Running `xdg-mime default firefox.desktop x-scheme-handler/http` writes out per-user configuration to prefer `firefox.desktop`, but like the system defaults, this is ineffective, because you don't have a `firefox.desktop` so the system cannot prefer it. Again, it falls back to choosing Brave or Firefox-as-Snap, essentially arbitrarily.

Running `xdg-mime default firefox_firefox.desktop x-scheme-handler/http` **does** prefer Firefox, by writing this into `~/.config/mimeapps.list`:

```
[Default Applications]
x-scheme-handler/http=firefox_firefox.desktop
```

and that works: I can run `xdg-open http://example.com` and get Firefox, while `xdg-open https://example.com` opens it in Brave. (Obviously, in reality you would want to set both handlers to the same thing!)

If you want Firefox-as-a-Snap to be reliably the default, you should set `firefox_firefox.desktop` as the default browser. Nothing in the OS knows that you expect `firefox.desktop` to be the same thing as `firefox_firefox.desktop`; they have different names and are therefore different.

If Ubuntu wants Firefox-as-a-Snap to be the default if installed, then they should probably add it to the configuration that controls system-level defaults alongside `firefox-esr.desktop` and `firefox.desktop`.

Or, if Ubuntu wants Firefox-as-a-Snap to be considered to be the same app as `firefox.desktop`, then the Snap app needs to provide it under that name.

**Comment by smcv** [comment]
Honestly, this seems to be more like an Ubuntu bug than anything else - they're preinstalling a browser but not setting it as default.

**Comment by brccabral** [comment]
OK, thank you for checking. I have removed Brave from "/var/lib/flatpak/exports/share/applications/mimeinfo.cache" and now I get firefox.desktop, but I didn't try setting to firefox_firefox.desktop.
Thanks
