### ISSUE TITLE
How can an application inside flatpak get access to run host programs

### ISSUE THREAD

**Issue by alex0618sh2** [flatpak/flatpak#5435]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

Hello.
I need help

My application is a bash script, it must use the iptables program in its work
If iptables is compiled inside flatpak, then it works but not correctly, because it cannot load kernel modules.
Is it possible to tell flatpak (sandbox) to grant access to iptables. Ie that my programmma could freely use the iptables of the host?

At the moment, I can get an application running that accesses iptables, calls it, and everything works great.
i build it like this: 
`sudo flatpak-builder --system --install --force-clean build-dir org.flatpak.MyApp.yml`
and run:
`sudo -i flatpak run --usr-path=/usr org.flatpak.MyApp`
this all works in Ubuntu 22.04.1 LTS:
flatpak --version Flatpak 1.12.7

`.......
app-id: org.flatpak.MyApp
runtime: org.freedesktop.Platform
runtime-version: '22.08'
sdk: org.freedesktop.Sdk
command: MyApp
finish-args:
  - --share=ipc
  - --socket=x11
  - --socket=wayland
  - --share=network
  - --filesystem=host-os
  - --filesystem=/home
  - --filesystem=/tmp
  - --filesystem=/etc
  - --socket=system-bus
  - --socket=session-bus
  - --device=all
  - --env=LD_LIBRARY_PATH=/app/lib:/app/usr/lib:/app/lib/x86_64-linux-gnu:/lib:/usr/lib:/usr/lib/x86_64-linux-gnu
  - --env=PATH=/app/bin:/app/sbin:/app/usr/bin:/app/usr/sbin:/app/usr/local/sbin:/app/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin.......
  - --env=XDG_DATA_DIRS=/usr/local/share:/usr/share:/app/share
  - --talk-name=org.freedesktop.Flatpak
  - --allow=devel
.......................`

The problem is that if I remove --usr-path=/usr from the application launch command, 
then the application stops working because there is no access to iptables. I also found that 
when running with --usr-path=/usr - on systems such as debian 12 and Centos 9 - the application stops working completely.

What do I need to tell flatpak so that my program can work freely with the host's iptables and run with the command?:
`sudo -i flatpak run org.flatpak.MyApp`

**Comment by JakobDev** [comment]
You can execute any commands on the host by running `flatpak-spawn --host <command>` inside the Flatpak. Your Flatpak needs the `--talk-name=org.freedesktop.Flatpak` Permission to use this feature.

**Comment by alex0618sh2** [comment]
> 
I have it enabled `--talk-name=org.freedesktop.Flatpak`
`flatpak-spawn --host <command>` - does not work.
So there are no other options? Except how to work with this command `flatpak-spawn --host <command>`

Here is the error message I am getting: `Cant find bus: Cannot autolaunch D-Bus without X11 $DISPLAY`
If I manage to fix this, will I be able to work with the iptables of the host from the bash script of my program, thanks to this command (flatpak-spawn --host <command>)?

**Comment by smcv** [comment]
If you are doing highly-privileged, system-level things like running `iptables`, please consider whether Flatpak is the right tool for the job.

> ```
> sudo -i flatpak run --usr-path=/usr org.flatpak.MyApp
> ```

Flatpak and Flatpak apps are not really intended to be run as root.

`flatpak-spawn` relies on being able to talk to the current user's session bus. When you run in `sudo -i`, you don't have a session bus available, so that won't work.

If you build and run the Flatpak app as an ordinary user (not root), then you could use `flatpak-spawn --host -- sudo iptables ...` to run iptables as root on the host system, if allowed by the app's permissions and the user's ability to run sudo.

Obviously, this is a sandbox escape - you are running arbitrary code outside the app's sandbox - and user interfaces for running Flatpak apps will quite rightly flag your app as dangerous. If that's what you're doing, what benefit are you or your users getting from Flatpak?

> `--socket=system-bus --socket=session-bus`

This gives your app unrestricted access to the machine's system bus and the user's session bus, which is another dangerous permission. `--socket=session-bus` is "more powerful" than any number of `--talk` options.

> when running with --usr-path=/usr - on systems such as debian 12 and Centos 9 - the application stops working completely

Flatpak is not designed to be run like this. `--usr-path` is not for ordinary Flatpak apps borrowing the host system's `/usr`! It's intended for apps that set up their own isolated directory to be used as `/usr`, like Steam's container runtime.

Flatpak has two purposes: sandboxing, and providing a stable library stack as the sandboxed app's `/usr`. You've given your app a sandbox escape, which defeats sandboxing, and you're trying to use the host system's `/usr`, which defeats any attempt to use a stable library stack. If you do both of these, then there is literally no point in using Flatpak: you might as well just publish a shell script.

**Comment by alex0618sh2** [comment]
Thank you for your reply

**Comment by hfiguiere** [comment]
was answered
