### ISSUE TITLE
[Bug]: flatpak apps no longer run in Ubuntu

### ISSUE THREAD

**Issue by inwaar** [flatpak/flatpak#5462]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.4

### What Linux distribution are you using?

Ubuntu

### Linux distribution version

22.04.2

### What architecture are you using?

x86_64

### How to reproduce

flatpak run com.google.Chrome

### Expected Behavior

Opened browser window

### Actual Behavior

The app cannot be run.
```
лип 01 12:24:59 thinkq systemd[2880]: Started app-flatpak-com.google.Chrome-7814.scope.
лип 01 12:24:59 thinkq audit[7818]: AVC apparmor="DENIED" operation="userns_create" class="namespace" info="User namespace creation restricted" error=-13 profile="unconfined" pid=7818 comm="flatpak-bwrap" requested="userns_create" denied="userns_create"
лип 01 12:24:59 thinkq kernel: audit: type=1400 audit(1688203499.296:155): apparmor="DENIED" operation="userns_create" class="namespace" info="User namespace creation restricted" error=-13 profile="unconfined" pid=7818 comm="flatpak-bwrap" requested="userns_create" denied="userns_create"
```

### Additional Information

I've recently upgraded Ubuntu and no apps installed via flatpak work anymore.

Based on https://www.mail-archive.com/kernel-packages@lists.launchpad.net/msg487469.html I turned off this kernel param
```
sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
```
And everything work now.
But I'm not sure if this is a correct way to fix, perhaps it is not a good way and make the system less secure?
Is this something to be addressed to flatpak to be fixed?

**Comment by AsciiWolf** [comment]
This should probably be reported [on Launchpad](https://launchpad.net/ubuntu/+source/flatpak/+bugs) instead since it is a downstream issue.

**Comment by MikeNavy** [comment]
Hi,

From your log, it seems that an apparmor profile blocks the use of flatpaks (it blocks "flatpak-bwrap")

Flatpaks don't use apparmor, and neither flatpak framework nor flatpak applications should be apparmored.

With the following command 
`sudo aa-status`
check the enforced apparmor profiles, and disable or put in complain mode the one preventing the use of flatpaks.

NB: you can update your flatpak framework with this PPA: 
https://launchpad.net/~flatpak/+archive/ubuntu/stable

Regards,

MN

**Comment by smcv** [comment]
> From your log, it seems that an apparmor profile blocks the use of flatpaks (it blocks "flatpak-bwrap")

Flatpak relies on the ability to create new user namespaces, and if Ubuntu's kernel is going to prevent Flatpak from creating new user namespaces, then there is nothing that Flatpak can do about this. It looks as though Ubuntu have decided to mitigate some attacks by making the `unconfined` profile be partially confined, which makes its name rather misleading. This is also likely to affect Steam, Chromium, podman, and various other things that use bubblewrap or similar user-namespace-based mechanisms.

Please talk to Ubuntu's support channels for AppArmor and the kernel - it will probably be better if support requests come from Ubuntu users, rather than from Flatpak maintainers who don't use Ubuntu.

If there is some text that we can add to https://github.com/flatpak/flatpak/wiki/User-namespace-requirements to document what is required to be able to run Flatpak, tested suggestions are welcome.
