### ISSUE TITLE
[Bug]: QStandardPaths: wrong permissions on runtime directory /run/user/1000, 0755 instead of 0700

### ISSUE THREAD

**Issue by UserStillLoading** [flatpak/flatpak#5494]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.10.8

### What Linux distribution are you using?

ChromeOS

### Linux distribution version

Linux penguin 5.10.114-16025-ge75506b9d98e #1 SMP PREEMPT Sat Jul 16 18:54:29 PDT 2022 x86_64 GNU/Linux

### What architecture are you using?

i386

### How to reproduce

1. I installed flatpak using the tutorial on https://flathub.org/setup/Chrome%20OS
2. I installed OBS using `flatpak install flathub com.obsproject.Studio`
3. Tried to run using `flatpak run com.obsproject.Studio`

### Expected Behavior

Open OBS, maybe? I haven't used Linux before.

### Actual Behavior

QStandardPaths: wrong permissions on runtime directory /run/user/1000, 0755 instead of 0700

### Additional Information

I don't know what architecture or Linux distribution version I have.
I haven't used Linux much before. Actually take out the "much". I haven't used Linux before.

**Comment by smcv** [comment]
> QStandardPaths: wrong permissions on runtime directory /run/user/1000, 0755 instead of 0700

This is #3397 and was fixed in flatpak 1.14.x.

> 1.10.8

This version is old and no longer supported.

> ChromeOS

Sorry, the Flatpak developers don't use ChromeOS and can't provide detailed support for it, so I don't know where you can obtain a newer version of Flatpak for that platform. Perhaps try talking to whatever support channels ChromeOS provides for their "Linux development environment" container?

What ChromeOS refers to as "Linux development environment" is some sort of container environment, probably based on Debian or Ubuntu, but I don't know which version of Debian or Ubuntu it's based on, or whether it's possible to get a newer container.

If it's a Debian 11 'bullseye' container, then adding Debian `bullseye-backports` apt sources will provide a newer version of Flatpak. Sorry, I don't really have enough time available for working on Flatpak to be able to spend it on guiding new Linux users through that process. If there is a ChromeOS support channel that you can talk to, referring them to this comment might be helpful.
