### ISSUE TITLE
[Feature request]: Add ability to disable the "virtual" path `/app`

### ISSUE THREAD

**Issue by rdbo** [flatpak/flatpak#5516]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

Some applications parse `/proc/<pid>/maps` to do certain operations. For Flatpak apps, this doesn't work very well, because Flatpak creates a "virtual" path `/app` to refer to the directory where the application is installed. Example of the `/proc/<pid>/maps` of a Flatpak app:
```
563eab00b000-563eab0cb000 r--p 00000000 fd:00 15742257                   /app/bin/someapp
563eab0cb000-563eab62a000 r-xp 000c0000 fd:00 15742257                   /app/bin/someapp
563eab62a000-563eabb5a000 r--p 0061f000 fd:00 15742257                   /app/bin/someapp
563eabb5a000-563eabb93000 r--p 00b4e000 fd:00 15742257                   /app/bin/someapp
563eabb93000-563eabb94000 rw-p 00b87000 fd:00 15742257                   /app/bin/someapp
563eabb94000-563eabb95000 rw-p 00000000 00:00 0 
563eac6d5000-563eacc9b000 rw-p 00000000 00:00 0                          [heap]
```
It shows `/app/bin/someapp` instead of `/home/some_user/.var/app/com.test.Test/bin/test` for example.
Parsing the `/proc/<pid>/maps` file is very useful for automating tasks related to the process modules. E.g one could write a shell script that reads the paths from the `/proc/<pid>/maps` and dumps their debug symbols or something like that.
Since my question of "how to resolve the real path of /app" didn't get any answers on Discourse (https://discourse.flathub.org/t/resolve-real-path-of-app-from-proc-pid-maps/5101), I assume this is not possible.
So my request is: add an option (maybe a flag when running the `flatpak run` command) to disable `/app` "virtualization". Why? Because it messes up the `/proc/<pid>/maps` file which is used for many different reasons.

**Comment by smcv** [comment]
Rewriting the filesystem namespace to put the app in `/app` and the runtime in `/usr` is a key part of how Flatpak works, and Flatpak apps are allowed to assume that `/app` and `/usr` are suitable paths for the app to hard-code. (This makes packaging some apps and libraries for Flatpak much, much simpler than for example Snap, which does not allow the app to make a similar assumption.)

If you are writing debugging tools that parse `/proc/PID/maps`, you need to be aware that paths in there might not be in the root filesystem of the initial namespace: this is equally true for modern container frameworks (Flatpak, Snap, Podman, Docker, etc.) or the older `chroot` mechanism. On Linux, `/proc/PID/root` is a "magic symlink" that points to the process's view of the root filesystem.

> add an option (maybe a flag when running the flatpak run command) to disable /app "virtualization"

Sorry, no, that would be an incompatible interface change that will break valid assumptions made by existing apps.

If we added that option anyway, the next thing you would do, after updating your debugging tool, would be to come back asking for an option to disable the similar "virtualization" of `/usr` - and that is *definitely* something we can't do, because it would break valid assumptions made by literally every app (like `/bin/sh` and `/lib64/ld-linux-x86-64.so` being the ones from the app's runtime). If you can adapt your debugging tool to cope with `/usr` being virtualized in this way, then adapting it to cope with `/app` being similarly virtualized is a straightforward extension of that.

**Comment by rdbo** [comment]
@smcv I did not know about `/proc/<PID>/root`, that should be enough for my purposes. Also, very fair points about disabling the "virtualization", I see why it's not feasible. Thanks for your response.
