### ISSUE TITLE
[Bug]: /app/share/runtime/locale has invalid mtime when provided by locale extension

### ISSUE THREAD

**Issue by mfschumann** [flatpak/flatpak#5542]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.4

### What Linux distribution are you using?

Fedora Silverblue

### Linux distribution version

38

### What architecture are you using?

x86_64

### How to reproduce

1. Install a flatpak along with its Locale extension
2. Run the flatpak
3. Run `flatpak enter id.of.flatpak-app ls -la /app/share/runtime/locale`

### Expected Behavior

The folder `/app/share/runtime/locale` and its contents should have a valid mtime (the build time of the app).

### Actual Behavior

The mtime of `/app/share/runtime/locale` and all of its contents is shown as `1 Jan 1970`.

### Additional Information

I maintain a flatpak (eu.betterbird.Betterbird on flathub) that shows the modification time of installed language packs to the user. As the language packs are shipped as locale extensions the modification time always shows as `1 Jan 1970` which is misleading.

I found that when populating `/app/share/runtime/locale` during build of the flatpak, the mtime is fine, whereas in the sandbox of the installed flatpak, it is invalid. This indicates that the mtime must be reset either when the locale extension is created by flatpak-builder or when the locale is installed into the flatpak's sandbox.

**Comment by nanonyme** [comment]
This sounds normal, mtime belongs to metadata that gets normalized for file deduplication in ostree.

**Comment by mfschumann** [comment]
It's good that we understand what's the reason for the behavior. But is there anything that can be done about it?

**Comment by nanonyme** [comment]
Not really

**Comment by nanonyme** [comment]
What are you actually trying to do?

**Comment by mfschumann** [comment]
I maintain a flatpak (eu.betterbird.Betterbird on flathub) that shows the modification time of installed language packs to the user. As the language packs are shipped as locale extensions the modification time always shows as 1 Jan 1970 which is misleading.

**Comment by smcv** [comment]
Sorry, this is working as designed. Flatpak intentionally resets the mtime of basically all files to 1970-01-01, to maximize file reuse: if you rebuild a locale extension with no functional changes, we want the files in that locale to be literally identical to the files in the previous version (not just similar, and not just the same bytes, but identical metadata as well) so that they don't take up new space on disk and don't require re-downloading.

If you want a last-update time to be recorded in the language pack, it will need to be in the file content itself, not the filesystem-level metadata. If you do that, please make it be the date/time when the actual source data changed, not the time of the most recent automated rebuild (and preferably, also try to avoid the [automated no-changes updates](https://github.com/flatpak/flatpak/commit/27b11b93c2a80a91c9461bc6c7f5e9a201406041) that are common in gettext-based projects, and only update the date/time for "real" changes made by a human with a text editor).

**Comment by mfschumann** [comment]
Thank you for explaining the rationale behind the behavior. I understand that it makes sense to reset the mtime and that the app should not rely on mtimes of files in the flatpak sandbox. We'll implement a fix on the app side then.

**Comment by nanonyme** [comment]
The easy solution would be to simply hide the timestamp as meaningless if UX allows for it.
