### ISSUE TITLE
[Feature request]: Release flatpak to support appstream v1.0.0

### ISSUE THREAD

**Issue by nanonyme** [flatpak/flatpak#5587]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

Please make a development release, then stable release of flatpak. appstream v1.0.0 is out and current flatpak versions do not support it.

**Comment by nanonyme** [comment]
The relevant PR was https://github.com/flatpak/flatpak/pull/5473

**Comment by smcv** [comment]
Releasing a stable 1.16.x is not necessarily the answer here, if that's what you meant: I think #5473 is small enough to backport to 1.14.x after it has been in a 1.15.x release (and I don't want to do new stable-branch releases too often, because having multiple stable-branches concurrently supported makes it significantly more time-consuming to deal with CVEs or other high-severity issues, which is particularly important if we're as short of maintainer time as we seem to be).

I was really hoping that https://github.com/flatpak/flatpak/pull/5577 would get reviewed in time to be in the next development and stable releases.

**Comment by nanonyme** [comment]
Yeah, I was kind of suspecting it's too early for 1.16.x. It looks like freedesktop-sdk is using 1.15.x atm (yes, blergh, it was supposed to switch to stable once 1.16.x is out) so simply development tag is enough from our point of view. For distros, that 1.14.x backport sounds awesome.

**Comment by nanonyme** [comment]
There's no excessive rush about this at the moment, I just noticed last tag was half a year ago.

**Comment by smcv** [comment]
I'm trying to release Flatpak 1.15.6 today. It has been on my list for months, but my list is not short.

If you would like to speed up future releases, one good way to do it would be to test current git and report any showstoppers or regressions, such as #5588 which I found while attempting to do today's release.
