### ISSUE TITLE
[Question]: What is the recommend method to have LD_PRELOAD honored by flatpak applications?

### ISSUE THREAD

**Issue by qoijjj** [flatpak/flatpak#5617]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

There is a partially related comment I made here: https://github.com/flatpak/flatpak/issues/5575#issuecomment-1837706101

But that doesn't fully capture the question. The question is, what is the method recommended by flatpak officially to have LD_PRELOAD honored by flatpak applications?

**Comment by adrelanos** [comment]
Specifically this would be useful to LD_PRELOAD [hardened_malloc](https://github.com/GrapheneOS/hardened_malloc), a security-focused general purpose memory allocator.

**Comment by adrelanos** [comment]
related:
[Flatpak Request for hardened_malloc](https://discourse.flathub.org/t/flatpak-request-for-hardened-malloc/5593)

**Comment by smcv** [comment]
The recommended method is "don't". Any native code that exists on the host system OS distribution can legitimately have dependencies on libraries in the host system OS distribution that do not exist, or exist but are too old or incompatible, inside the Flatpak runtime.

If you want to inject arbitrary code into programs running inside the Flatpak sandbox (whether that's a hardened, instrumented or otherwise modified malloc(), some other LD_PRELOAD module like faketime, a Vulkan layer like MangoHUD, or any other similar thing) then it needs to be compiled against the Flatpak runtime's dependency libraries and shipped as a Flatpak extension. An extension is a special runtime that acts like a plugin for other apps and runtimes.

**Comment by qoijjj** [comment]
@smcv Thanks again. I'll be pursuing the extension route. To be clear though, in this specific case the hardened_malloc lib doesn't depend on anything else so for this specific use case it works fine. But I understand why this may well not be the case for other libraries.

**Comment by hfiguiere** [comment]
question answered
