### ISSUE TITLE
[Bug]: Can't run newly installed app from Launcher until full restart: "the name is not activatable"

### ISSUE THREAD

**Issue by php4fan** [flatpak/flatpak#5662]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.6

### What Linux distribution are you using?

Manjaro Linux

### What architecture are you using?

x86_64

### How to reproduce

1. I installed https://flathub.org/apps/org.telegram.desktop
2. I typed Telegram into the Application launcher
3. a result showed up called "Telegram Desktop" with the Telegram icon, so I clicked it

### Expected Behavior

It should run the app. I should not need to log out and in, and even less to reboot.

### Actual Behavior

I got this stupid error:

![image](https://github.com/flatpak/flatpak/assets/13969584/b3d8fa64-0d2c-4e45-98aa-4054574803c2)

which is impossible to make sense of.

I could run the app with no issue from a terminal with `flatpak run`.

Then I logged out and in, and I would still get the same error.

Then I rebooted, and then it worked from the launcher as expected.

**Comment by JakobDev** [comment]
Looks like a Telegram bug

**Comment by php4fan** [comment]
> Looks like a Telegram bug

I don't think so.

It seems to have something to do with the Launcher's ability to find a flatpak app after installing it but before reboot.

From what I've read many people seem to accept as a given, that when you install a flatpak app, you need to log out and in before you can access it through the Launcher. That would already be unacceptable, but in my case it wasn't enough, I had to reboot.

What I'm not sure of is whether the issue is in KDE's mechanism for finding applications in general, or in Flatpak's way to interface with it.

Also I'm now wondering whether this happens only for the very first app you install with flatpak, or with each one. If it's only the first one it's less serious, but still not ok.

**Comment by chrisawi** [comment]
The `org.telegram.desktop` flatpak installs a .desktop file in a flatpak exports directory that has `DBusActivatable=true`. That makes the launcher activate it over D-Bus instead of executing it directly. For that, telegram ships a dbus service file in another exports directory.

Flatpak adds e.g. `/var/lib/flatpak/exports/share` to `XDG_DATA_DIRS` so that both of those directories are seen by the system.

Had you recently installed flatpak itself? If so, you must have at least logged out afterward or KDE wouldn't have been able to see the desktop entry in the first place. But if you didn't reboot after installing flatpak, it's possible that the dbus daemon might have persisted, and thus still wouldn't have flatpak's `XDG_DATA_DIRS` set. That would explain the error message in your screenshot.

**Comment by mcatanzaro** [comment]
Duplicate of #3342
