### ISSUE TITLE
[Bug]: Error: While opening repository /home...: opening repo: openat(config): No such file or directory

### ISSUE THREAD

**Issue by sagewilde** [flatpak/flatpak#5689]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.7

### What Linux distribution are you using?

Ubuntu

### Linux distribution version

Kubuntu 22.04 (6.5.0-17-generic), updated today

### What architecture are you using?

i386

### How to reproduce

1. Attempt to follow the install directions from [the website](https://flatpak.org/setup/Kubuntu) to the letter on a fresh, brand-new install of Kubuntu.
2. `sudo apt install flatpak`
3. `flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo`
4. Reboot PC
5. `flatpak update`

### Expected Behavior

Update, or display other output.

### Actual Behavior

`error: While opening repository /home/<user>/.local/share/flatpak/repo: opening repo: openat(config): No such file or directory`

### Additional Information

CD'ing to the `share` directory and doing `sudo rm -rf /flatpak/repo.` and then doing `flatpak list` failed. 

Doing `flatpak repair --reinstall-all` and `flatpak repair --system` yielded `pruning objects`. `--reinstall-all` had an output `Reinstalling appstream.` `flatpak list`, failed, same error. check `/flatpak/repo`. Has contents.

`sudo apt remove --purge flatpak` deletes the library.  `flatpak` is still in `/.local/share`. Attempt to `sudo rm -rf flatpak`, and `ls` to check if it's gone. `sudo apt install --fix-missing flatpak` yields no returned entry in `/share`. 

`sudo apt install flatpak` yields results. `flatpak --installations` shows `/var/lib/flatpak`. 

Try doing the `--remote-add` again, and then `flatpak update`. Successful update. `flatpak list` yields full results.

Just wanted to post this here, in case someone is in my exact shoes and checks here for a solution. I think I successfully debugged it. How did it work?

**Comment by chrisawi** [comment]
Flatpak defaults to acting on the system installation, so your `flatpak remote-add` command added the Flathub remote there (`/var/lib/flatpak`).

It does automatically establish the user installation with an ostree repo consisting of some empty directories and the repo configuration file (`~/.local/share/flatpak/repo/config`). Removing that file triggers the behavior you saw.

I don't know why flatpak (or libostree) failed to write `config`, but this seems unrecoverable except by removing the entire `repo` directory so flatpak can recreate it. That appears to be how you fixed it.

P.S. There's no need to use `sudo` when working with files in your home directory, and `/flatpak/repo` is an absolute path. You should have used `rm -r flatpak/repo`.

See also https://github.com/flatpak/flatpak/issues/3585

**Comment by sagewilde** [comment]
> Flatpak defaults to acting on the system installation, so your `flatpak remote-add` command added the Flathub remote there (`/var/lib/flatpak`).
> 
> It does automatically establish the user installation with an ostree repo consisting of some empty directories and the repo configuration file (`~/.local/share/flatpak/repo/config`). Removing that file triggers the behavior you saw.
> 
> I don't know why flatpak (or libostree) failed to write `config`, but this seems unrecoverable except by removing the entire `repo` directory so flatpak can recreate it. That appears to be how you fixed it.
> 
> P.S. There's no need to use `sudo` when working with files in your home directory, and `/flatpak/repo` is an absolute path. You should have used `rm -r flatpak/repo`.
> 
> See also #3585

I was confused by it too. It seems like this has been an issue since at least 2016 (as far as I could find.) Are there any theories for why it fails to write to config? 

Like I said, I kind of debugged this one by myself just out of sheer frustration, and wanted to file it here so people could reproduce the error and the fix by themselves. That way, it's a little more searchable for people in the future. Thank you for adding the explanation, btw. I guarantee, it's helpful.

**Comment by chrisawi** [comment]
> So, to recap, `sudo apt remove --purge flatpak` and `rm -r ~/.local/share/flatpak`, followed by a reinstall through `sudo apt install flatpak` allows the config file to be rewritten with `--remote-add`. Right?

There's no need to touch the flatpak package, nor do you need to re-add the remote in the system installation. Just `rm -r ~/.local/share/flatpak/repo`, and then any flatpak command that needs it to be present will recreate it. If you had added the remote with `--user`, then you would need to re-add it, as well as install any apps.

Looking through older issue reports, there seems to be some confusion between two similar-looking error messages: `openat(config): No such file or directory` and `opendir(objects): No such file or directory`. The latter is one of the empty directories created as part of the repo. I don't think either of these scenarios are common, and I suspect they're often caused by user error. One user was deleting all empty directories inside their home directory, for example.

I think the only improvement for those cases is to make `flatpak repair --user` give an informative error message, and possibly offer to erase the installation with an additional flag.

**Comment by sagewilde** [comment]
> I think the only improvement for those cases is to make `flatpak repair --user` give an informative error message, and possibly offer to erase the installation with an additional flag.

Ah, I see. Thanks! I'll go ahead and close this, then.

**Comment by smcv** [comment]
> There's no need to touch the flatpak package, nor do you need to re-add the remote in the system installation. Just `rm -r ~/.local/share/flatpak/repo`, and then any flatpak command that needs it to be present will recreate it.

If there is an actionable Flatpak issue here at all, then that issue is this:

Flatpak has multiple installation locations: one in `~/.local/share/flatpak` for `--user`, one in `/var/lib/flatpak` for `--system` (the default for most commands), and potentially more with local configuration.

If you don't have a `--user` installation *at all*, and you try to install an app or runtime with `--user`, Flatpak will automatically create a `--user` installation to put the app or runtime in. This already works (if it didn't, then using `--user` on a fresh installation couldn't work).

However, if you somehow have *some but not all* of the files and directories needed for a fully working `--user` installation - for example if you have `~/.local/share/flatpak/repo/` but it doesn't contain the file `~/.local/share/flatpak/repo/config`, or perhaps if you have `~/.local/share/flatpak/repo/` but not `~/.local/share/flatpak/repo/objects/` - then Flatpak doesn't automatically recover from all possible combinations. Some combinations of absent + present are treated as a corrupted installation that causes an error, rather than being silently re-created.

For directories that can validly be empty (like `objects/`), this is a simple matter of programming, and Someone™ could contribute a pull request to make Flatpak re-create the empty directory automatically if desired. I made some changes in this direction back in 2022 (#4732). This doesn't *necessarily* need to be a `flatpak repair` thing, it could potentially just be done automatically by all Flatpak commands that want to touch the user installation: ideally, `flatpak repair` would be something that only needs to be run in rare situations where data corruption is suspected, like `git fsck`.

However, for the `~/.local/share/flatpak/repo/config` file, as said on #3585, Flatpak can't know what the content of that file ought to be. It could re-initialize it with defaults as though it was a freshly created repository, but that won't necessarily be consistent with any other pre-existing contents of `~/.local/share/flatpak/repo`; and if that file has been deleted, then any information that is stored in it (selected languages, remotes, etc.) has already been lost (the data loss has already happened and we can't magic it back into existence).

**Comment by louisremi** [comment]
I've just had the same problem and solved it by `cd ~/.local/share` then `sudo rm -rf flatpak`.
The error message is cryptic. It'd be great if flatpak was able to detect the its installation is borked and provided instructions on how to fix it
