### ISSUE TITLE
[Feature request]: Add functionality to easily backup installed apps

### ISSUE THREAD

**Issue by deadmeu** [flatpak/flatpak#5714]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

I'm not sure if this is possible using `flatpak build-bundle` but I was not able to achieve it.

I'm interested in backing up some Flatpaks which are no longer being hosted on Flathub for archival purposes, so that they may later be reinstalled. It would be really great if this was easy to do using a Flatpak command without having to manually copy files from the filesystem which may mess with the internal Flatpak package state.

**Comment by chrisawi** [comment]
Flatpak single-file bundles can be used for archiving apps, but there are a number of limitations that reduce their utility:

* A .flatpak bundle only contains the app itself without any extensions, including .Locale. It's not even possible to export them separately:
https://github.com/flatpak/flatpak/issues/165
* It doesn't work with apps that use `extra-data`, and it doesn't warn you if you try to do that:
https://github.com/flatpak/flatpak/issues/1334
* It doesn't include any dependencies. This is mostly a concern for very long-term archival; I'd expect Flathub to retain old runtimes for a long time. It's also not great for the somewhat distinct use case of distributing an app offline (sideloading).

Flatpak has a [more sophisticated alternative](https://docs.flatpak.org/en/latest/usb-drives.html) in `flatpak create-usb`. It is particularly well-suited for offline distribution, but it could also be used for archiving. Of the above list, it only has the `extra-data` limitation: https://github.com/flatpak/flatpak/issues/969

`flatpak build-bundle` is a pretty low-level command. It requires the path to the repo of the installation containing the app, e.g. `/var/lib/flatpak/repo`, and you typically need to specify the branch because it defaults to `master`. The [man page](
https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-build-bundle) has examples at the bottom that demonstrate how to use it. The more prominent [web documentation](https://docs.flatpak.org/en/latest/single-file-bundles.html) is less helpful here because the examples are focused on publishing from a dedicated repo rather than exporting from a flatpak installation.

**Comment by chrisawi** [comment]
> I tried to run `flatpak create-usb` as well, but had some issues and couldn't figure out if it could output to a file rather than a USB drive.

It can output to any directory.

If you'd like assistance with either of those commands, please feel free to make a post on the Flathub Discourse: https://discourse.flathub.org/
