### ISSUE TITLE
Exporting from a build server to a repository server?

### ISSUE THREAD

**Issue by Jehan** [flatpak/flatpak#572]
Since I see that flatpak is really decentralized repo-like, with commits and branch and stuff… do you have a procedure to sync several repositories on different machines?

Basically I'd like to build the software on a machine, but this will likely be a different machine which will serve the repository. So what's the recommended method?
It would be interesting for instance to `build-export` into a remote server through ssh. Or else to build-export locally, but have the public-facing server sync which the repo on the build server (so since that's all commits, that would be similar to running some kind of `flatpak pull` from the public server, which would pull all new commits).

**Comment by jscurtu** [comment]
Buld it on the build machine and simply rsync the repo folder to the repository (server).

**Comment by alexlarsson** [comment]
See this blog for some thoughts about this:
https://blogs.gnome.org/alexl/2017/02/10/maintaining-a-flatpak-repository/

**Comment by directhex** [comment]
I'll chime in here, since I'm doing this.

My CI machines run:

```
flatpak-builder --force-clean --repo=repo monodevelop com.xamarin.MonoDevelop.json
flatpak build-bundle repo/ md.flatpak com.xamarin.MonoDevelop
```

to generate an installer bundle, which is uploaded to an Azure storage container.

Then, in a subsequent CI job, the bundle is downloaded to the repository server (which has `flatpak` and `ostree`, but not `flatpak-builder`), and the following script runs:

```
flatpak build-import-bundle --ref=app/${PKGNAME}/x86_64/${RELEASE} --gpg-sign=D3D831EF --update-appstream -v --ostree-verbose /srv/www/mono/repo/flatpak flatincoming/*.flatpak
flatpak build-sign --gpg-sign=D3D831EF /srv/www/mono/repo/flatpak ${PKGNAME} ${RELEASE}
```

`${PKGNAME}` and `${RELEASE}` are provided by CI job parameters, and correspond to the fully qualified Flatpak app name, and release branch name, correspondingly (e.g. "com.xamarin.MonoDevelop" and "alpha"). Re-running the same job with the same input but different branchname works for promoting a release between branches.

You'll need to learn some `ostree` commands to initialize an empty repo & make tweaks at that end - try `ostree init --mode=archive-z2 --repo=. -v`

**Comment by matthiasclasen** [comment]
I think this has probably been obsoleted by more recent work on flat-manager.
