### ISSUE TITLE
this is actually a clarification how to use host driver in flatpak --gl-drivers (for use in a patched mesa nvidia or whatever) (no documentation)

### ISSUE THREAD

**Issue by beh-10257** [flatpak/flatpak#5731]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.5

### What Linux distribution are you using?

NixOS

### Linux distribution version

6.8.0

### What architecture are you using?

x86_64

### How to reproduce

I want to use host driver like configure it in a way that let me just use my installed patched mesa locally
basically I want to remove the sandbox for the driver and ignore runtimes and be like just use my native drivers
I don't want it to be portable I just want to test my patches with steam without nuking the sandbox

like there is this article about how to do this with nvidia https://blog.tingping.se/2018/08/26/flatpak-host-extensions.html
i basically wanna use that host feature for my patched mesa

sorry if this is a duplicate or something but yeah just like I want access to files from sandbox why not access an important part of my system as well drivers

**Comment by smcv** [comment]
> basically I want to remove the sandbox for the driver and ignore runtimes and be like just use my native drivers

This is not possible to do reliably within the design of Flatpak. Your native drivers can legitimately depend on runtime libraries from your host system (glibc, libstdc++, libdrm, etc.) that are newer than the ones provided by the runtime, which will cause the drivers to fail to load.

This only works for the Nvidia proprietary drivers because Nvidia were careful to compile their proprietary driver blobs in a very old distribution (I don't think they document which one, but my guess would be a very old version of CentOS/RHEL, Debian or Ubuntu).

The closest you can get to this with Flatpak would be to apply your Mesa patches to https://gitlab.com/freedesktop-sdk/mesa-git-extension/ and use that.

Or, you could try compiling Mesa manually in a sufficiently old environment and constructing an unmanaged extension from the results.

I don't think any of the Flatpak developers have enough time available to guide you through the process of doing this, but if someone wants to write documentation and provide a merge request to add that documentation, they're welcome to do so. Good luck!

**Comment by beh-10257** [comment]
ok gonna look into patching the runtime since the features I am patching already depend on newer stuff 
gonna need to learn buildstream I guess
thanks a lot either way
