### ISSUE TITLE
[Bug]: missing desktop icons xfce

### ISSUE THREAD

**Issue by Smuuuko** [flatpak/flatpak#5733]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.7

### What Linux distribution are you using?

Linux Mint

### Linux distribution version

Linux Mint 21.3 xfce 4.18

### What architecture are you using?

x86_64

### How to reproduce

1. Open xfce menu
2. Right click on Application
3. Click Add to Desktop

### Expected Behavior

Proper icon should be present on desktop

### Actual Behavior

Flatpak application's icon is missing
![flatpak missing icons](https://github.com/flatpak/flatpak/assets/64784695/ff53fcf4-5e42-4b44-b315-59aedc01f068)

### Additional Information

non-flatpak icons aren't missing 
at xfce subreddit I was told this bug is not related to xfce, but flatpak

**Comment by chrisawi** [comment]
This seems like an XFCE issue to me. The desktop entry is functioning correctly in the menu, so flatpak must be exporting it and the icon.

What does `ls -l ~/Desktop/eu.vcmi.VCMI.desktop` say?

**Comment by Smuuuko** [comment]
> This seems like an XFCE issue to me. The desktop entry is functioning correctly in the menu, so flatpak must be exporting it and the icon.
> 
> What does `ls -l ~/Desktop/eu.vcmi.VCMI.desktop` say?

lrwxrwxrwx 1 lenovo lenovo 87 mar 19 18:18 /home/lenovo/Desktop/eu.vcmi.VCMI.desktop -> ../../../app/eu.vcmi.VCMI/current/active/export/share/applications/eu.vcmi.VCMI.desktop

**Comment by Smuuuko** [comment]
i see this issue is similar to #1658 and in the next release should be fixed [pull #577](https://github.com/containers/bubblewrap/pull/577)

**Comment by chrisawi** [comment]
Ah, Whisker Menu copies the desktop entry, but flatpak exports are relative symlinks, so it ends up only copying a now-broken symlink.

This was recently fixed by resolving the symlink first: https://gitlab.xfce.org/panel-plugins/xfce4-whiskermenu-plugin/-/issues/122

That's not an ideal solution because it will break if the app's active branch is changed (e.g. with `flatpak make-current`), and in general it won't track changes to the desktop entry. I would have preferred to see it make a symlink rather than copy the real file.

> i see this issue is similar to https://github.com/flatpak/flatpak/issues/1658 and in the next release should be fixed (https://github.com/containers/bubblewrap/pull/577)

That's unrelated. This issue is purely about how your desktop environment interacts with the exported .desktop file. That issue involves how flatpak's sandbox handles symlinks.

---

Until you get that update, you can try making a symlink yourself:

    rm ~/Desktop/eu.vcmi.VCMI.desktop
    ln -s /var/lib/flatpak/exports/share/applications/eu.vcmi.VCMI.desktop eu.vcmi.VCMI.desktop

If that doesn't work, you can copy it from `/var/lib/flatpak/app/eu.vcmi.VCMI/current/active/export/share/applications/eu.vcmi.VCMI.desktop` instead (which is what Whisker Menu now does).

**Comment by Smuuuko** [comment]
Thank you for your time and help
