### ISSUE TITLE
[Feature request]: a better design flatpak

### ISSUE THREAD

**Issue by userforsource** [flatpak/flatpak#5777]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

In which we can have apps like apk no need to install dependency runtimes.
Like what we use in android just grab a apk which is around 25mb and install that is all but in flatplak app is 25mb and runtime is 400mb.
I was kind of annoy with this and after some search on internet i find a good blog.
And the issues that it have pointed out i also have same.
https://tesk.page/2022/05/16/response-to-flatpak-is-not-the-future/
This does not looks like the future. Is there a plan for future to have a more robust flatpak.
Flatpak should have a future plan which will improve. Mainly it will make it like what we see in apk/aab in android os.

**Comment by hfiguiere** [comment]
Basically what is something different.

**Comment by userforsource** [comment]
> Basically what is something different.

Yes point no 8
We need it to make it as a android apk like system.

**Comment by Mikenux** [comment]
@userforsource:

Do you know that you are referring to an article and exactly to the right point which partially addresses your issue?

As noted in this article, runtimes allow for having the correct and working dependencies on each system, because each Linux distribution does not have the same versions of dependencies (and those are not necessarily built the same way, e.g. optimizations). Regarding Android, I suppose it is a more fixed and controlled system, which allows apps to be lighter in size.
