### ISSUE TITLE
Confusing duplicated output in "flatpak list"

### ISSUE THREAD

**Issue by csoriano1618** [flatpak/flatpak#578]
I installed builder from flatpak (provided personally) and flatpakref (the one in the flatpak website).

Flatpak list outputs:
org.gnome.Builder
org.gnome.Builder

And flatpak remove org.gnome.Builder removes only one, leaving one in there and not able to remove it (unless using flatpak remote-remove).
Maybe it should say the remote in each case, or some way to distinguish them?

**Comment by csoriano89** [comment]
adding a comment, I actually cannot manage to know how to delete that second instance of gnome-builder, since flatpak uninstall org.gnome.Builder outputs:
[gnome@localhost Downloads]$ flatpak uninstall org.gnome.Builder
error: org.gnome.Builder master not installed

And [gnome@localhost Downloads]$ flatpak info org.gnome.Builder
app/org.gnome.Builder/x86_64/master org.gnome.Builder-2-origin eb61579b32554bb506636543e5d209acd64a632baba67fbbeaedce37017d4057

In case this matters for this issue.

**Comment by alexlarsson** [comment]
Add -d for more info. However, your issue is probably fixed as flatpak list gives more output by default on master.

**Comment by alexlarsson** [comment]
One is probably per user and has to be uninstalled as flatpak --user uninstall org.gnome.Builder

**Comment by csoriano89** [comment]
Yes that seems to be the error.

**Comment by mwleeds** [comment]
`flatpak list` now specifies what installation each thing is in
