### ISSUE TITLE
[GNOME-Nightly] Nautilus Cannot Open Files With Eye Of GNOME or Gedit

### ISSUE THREAD

**Issue by Saroufim** [flatpak/flatpak#579]
I'm not really sure if this is the right place to file this bug. Please point me in the right direction if I'm mistaken. 

Nightly Nautilus doesn't seem to be able to open files with Eye of GNOME or Gedit. It cannot see other flatpak or native apps besides gnome-software. It also doesn't show a GTK portal like Epiphany does which asks you to select the app you'd like to export the link to.

**Comment by TingPing** [comment]
Opening files is #543

Opening URLs is simply it not using the correct API (`gtk_show_uri()`)

**Comment by alexlarsson** [comment]
CC @csoriano89 
Yeah, nautilus as a flatpak currently does not use any portals or anything like that, so it isn't able to spawn other apps. Also, the way nautilus works makes this tricky. A regular app can use the openuri portal to just open a ui dialog asking what app to open with, but nautilus has in-line menus for picking what app to open with, etc, which you cannot do via a portal. It just doesn't fit well for being sandboxed.

I think we consider the flatpaked nautilus more to be a way to test it, than the version most people would use.

**Comment by csoriano89** [comment]
Yeah, I actually would like to push the Flatpak nautilus as far as possible without losing what we think should have.
I'm actually not sure we should continue not using portals for applications inside nautilus, rather than the menu option "open in a different app". I believe the portals UI is just better than anything we can came up with for Nautilus.
However, as Alex said, Flatpaked Nautilus is and will be for the near future only for testing and developing (knowing the drawbacks of using it). I will try to make that clearer somehow.

**Comment by Mikenux** [comment]
@smcv: I think this can be closed. Nautilus is able to open files in other apps.
