### ISSUE TITLE
[Bug]: Regression in 1.15.x when `WAYLAND_DISPLAY` is forwarded from gpg to pinentry

### ISSUE THREAD

**Issue by orionn333** [flatpak/flatpak#5863]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.8

### What Linux distribution are you using?

Fedora Silverblue

### Linux distribution version

40 (Kinoite)

### What architecture are you using?

x86_64

### How to reproduce

1. Run `echo $WAYLAND_DISPLAY`.
2. Run `ls $XDG_RUNTIME_DIR/<wayland-display>` or, if the value returned on step 1 is a path, `ls <wayland-display-path>`.  
3. Run `flatpak run --command=bash <application-id>` to enter the container.
   `<application-id>` must be an app with the `--socket=wayland` permission.
4. Run `echo $WAYLAND_DISPLAY` *inside the container*.
5. Check for the existence, inside the sandbox, of a symlink *on the same path* as the host Wayland display socket, pointing to the sandbox display socket (i.e. repeat step 2 *inside the container* with the value from the step 1).
6. Exit the container.
7. Compare the obtained values for `WAYLAND_DISPLAY`.

### Expected Behavior

The Wayland private socket at host path `$XDG_RUNTIME_DIR/.flatpak/wl/wayland-<XXXXXX>` is bound to the sandbox path `/run/flatpak/<wayland-display>`.  
Like in prior versions of Flatpak, a symlink should be created inside the sandbox *on the same path* as the host Wayland display socket. Said symlink should point to the sandbox socket *(e.g. if* `WAYLAND_DISPLAY=wayland-0` *then, inside the sandbox,* `/run/user/<user-id>/wayland-0` *would point to* `/run/flatpak/wayland-0`*).*

The value of the `WAYLAND_DISPLAY` env. var. inside the sandbox *remains the same* on the host.

### Actual Behavior

The Wayland private socket at host path `$XDG_RUNTIME_DIR/.flatpak/wl/wayland-<XXXXXX>` is bound to the sandbox path `/run/flatpak/<wayland-display>`.

Unlike prior versions, **no symlink is created**, and the value of `WAYLAND_DISPLAY` inside the sandbox *is modified* to be the location of the sandbox socket (`WAYLAND_DISPLAY=/run/flatpak/<wayland-display>`).

### Additional Information

This started happening on Flatpak [1.15.6](https://github.com/flatpak/flatpak/releases/tag/1.15.6) because of PR [#4920](https://github.com/flatpak/flatpak/pull/4920).

Kleopatra Flatpak is affected (see [issue #56](https://github.com/flathub/org.kde.kleopatra/issues/56)), as it makes use of a gpg-agent daemon running at host level.
When invoking pinentry-qt, it cannot open the Wayland display socket because it inherits the environment variable `WAYLAND_DISPLAY=/run/flatpak/<wayland-display>`, set to this value in the sandbox.
The rest of env. variables are the ones passed to gpg-agent and not the ones from inside the sandbox, but if `WAYLAND_DISPLAY` is modified inside it, pinentry-qt ***is*** called with the modified env. variable.
Since `/run/flatpak/<wayland-display>` does *not* exist on the host, it fails to open the socket.

If the value of `WAYLAND_DISPLAY` remained the same inside the sandbox (e.g. wayland-0), ***and*** the necessary symlink was created, Qt would be able to open the host-level socket (usually at `$XDG_RUNTIME_DIR/wayland-0`) and pinentry-qt would successfully be executed when called from the Kleopatra flatpak.

Even though without the whole “Wayland security context” mechanism, *keeping* `WAYLAND_DISPLAY`'s
value the same *and creating the aforementioned symlink* was the previous behaviour.

**Comment by swick** [comment]
That is indeed a change in behavior but using the environment from inside a flatpak to launch something on the host isn't what I would call a supported use case.

**Comment by Erick555** [comment]
As flatpak exposes `--socket=gpg-agent` option therefore apps communicating through that socket I would call a supported case which is available in stable version that predates wayland security context feature. It's unfortunate that `WAYLAND_DISPLAY` is inherited from flatpak but if it used to work then breaking it is regression that renders gpg-agent support semi-useless.

**Comment by orionn333** [comment]
It is also worth noting that the gpg binary running inside the sandbox ***explicitly*** passes, [among other env. vars.](https://github.com/gpg/gnupg/blob/d78131490edd7f7db142702b8144bc30e65dbd8d/common/session-env.c#L73), `WAYLAND_DISPLAY`, `DISPLAY` and `XAUTHORITY` to pinentry [through gpg-agent](https://github.com/gpg/gnupg/blob/d78131490edd7f7db142702b8144bc30e65dbd8d/agent/call-pinentry.c#L215).  
The *session-env.c* file in which those env. vars. are listed, [dates back from 2009](https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=commit;h=f6f5430e5014f90b685420447dffe89b220e2663), and the transfer of environment variables [was first implemented on 2007](https://github.com/gpg/gnupg/commit/55ba204bfa848c2e591a29fedc9f103103493a57).

With the current version of Flatpak, any application that wants to use gpg would have to keep a host-agnostic GnuPG setup with its own gpg-agent daemon and pinentry binary (which implies not using the host `~/.gnupg` folder, and is not practical for the user). Otherwise, if the app could talk to the host gpg-agent, gpg would pass the display-related sandbox env. vars. to the host pinentry, which would fail to run.

If the existence of the `--socket=gpg-agent` permission implies that communication of a Flatpak with the host gpg-agent is a supported use case, then: Would also not be supported as a use case the graphical execution of pinentry through gpg-agent on any Flatpak? Becasue, if not *(and as @Erick555 said)*, communication with gpg-agent would be limited to a marginal no. of operations.

I am not knowledgeble enough about Flatpaks, so sorry for any wrong assumptions I might be making, but, while keeping the work already done on the Wayland security context: Could it be a non-disruptive fix to create (as stated on the issue description) a symlink on the expected location in the sandbox and not modify the display variable? (Talking about `WAYLAND_DISPLAY` here, as I have not researched nor tested with X11).

**Comment by twelho** [comment]
This seems to be the exact issue that all Flatpak'ed JetBrains IDEs are also facing with commit signing. `pinentry` fails if the Wayland socket is enabled due to the internal `WAYLAND_DISPLAY=/run/flatpak/...`. If the Wayland socket is disabled, the app sees `WAYLAND_DISPLAY=wayland-0` and `pinentry` as invoked on the host by the gpg-agent on the host (which is smart, we don't want to leak `~/.gnupg` nor the `pinentry` passphrase to a potentially unsafe Flatpak app) starts working again. As soon as JetBrains [rolls out Wayland support](https://blog.jetbrains.com/platform/2024/07/wayland-support-preview-in-2024-2/) more broadly, this is going to become an issue.

**Comment by smcv** [comment]
> Could it be a non-disruptive fix to create (as stated on the issue description) a symlink on the expected location in the sandbox and not modify the display variable?

Perhaps. Please could someone affected by this issue try it, and send a merge request?

The way to achieve this would be to:

* try to use the same Wayland socket basename in `flatpak_run_add_wayland_security_context_args()` that we inherit from the parent process's `WAYLAND_DISPLAY` if it matches `wayland-*` and doesn't contain `/`, instead of hard-coding `wayland-0`, the same way that the older `flatpak_run_add_wayland_args()` code path already does;
* make `flatpak_run_add_wayland_security_context_args()` call `flatpak_bwrap_add_runtime_dir_member()` for that socket, the same way that the older `flatpak_run_add_wayland_args()` code path already does;
* set `WAYLAND_DISPLAY` to the basename of the socket

**Comment by smcv** [comment]
> the gpg binary running inside the sandbox explicitly passes, [among other env. vars.](https://github.com/gpg/gnupg/blob/d78131490edd7f7db142702b8144bc30e65dbd8d/common/session-env.c#L73), WAYLAND_DISPLAY, DISPLAY and XAUTHORITY to pinentry [through gpg-agent](https://github.com/gpg/gnupg/blob/d78131490edd7f7db142702b8144bc30e65dbd8d/agent/call-pinentry.c#L215).

This is potentially helpful if gpg and pinentry are both running on the same machine or in the same system-level container but with different environment variables, but it's actively harmful in a per-app sandbox environment where the correct values for these environment variables inside the sandbox might be wrong or meaningless outside.

I assume that JetBrains and Kleopatra have to compile and bundle a copy of gpg as part of their Flatpak app?

If they do, another way to avoid this issue would be to patch their included copy of gpg so that it avoids forwarding those environment variables to pinentry, either unconditionally (non-upstreamable) or if `access ("/.flatpak-info", F_OK)` succeeds (possibly upstreamable, I don't know how receptive gpg upstream are to this sort of thing).

**Comment by Erick555** [comment]
> I assume that JetBrains and Kleopatra have to compile and bundle a copy of gpg as part of their Flatpak app?

gpg is part of the runtime.

**Comment by smcv** [comment]
> gpg is part of the runtime.

Oh, if that's the case, then the it's the runtime maintainers who could make it not forward these variables.

**Comment by smcv** [comment]
> if that's the case, then the it's the runtime maintainers who could make it not forward these variables

→ https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1767

**Comment by Justinzobel** [comment]
Looks to have been fixed and pushed into main and I assume available in Flatpak 1.16.0, does anyone have this version and can test?
