### ISSUE TITLE
[Feature request]: application can't be ported to flatpak as this is less secure?is not secure as per the app dev why not fix this issue

### ISSUE THREAD

**Issue by olumolu** [flatpak/flatpak#5879]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a feature request that matches the one I want to file, without success.

### Suggestion

https://github.com/uazo/cromite/issues/1259
Fix this issue so cromite can be used 5tt5444_in 0

**Comment by Mikenux** [comment]
Please specify what is missing. I doubt anyone will start reading lots of comments on different issues to figure out what is missing.

**Comment by olumolu** [comment]
![Screenshot_20240726-110918~2](https://github.com/user-attachments/assets/e4f4e762-b267-4c23-91ec-0a08a9d3f7f0)

**Comment by chrisawi** [comment]
Flatpak cannot allow apps to create namespaces directly because this could be used to escape the sandbox. Flatpak does allow the creation of sub-sandboxes via the spawn portal, which is what the Chromium flatpak sandbox patch and Zypak rely on to make Chromium-based apps work with flatpak.

It has been claimed that the Chromium sandbox set up by that patch (or Zypak) is less secure than the native version, but without a lot of detail or corroboration. If that is indeed the case, it should be brought to the attention of the appropriate project with specific evidence (https://github.com/flathub/org.chromium.Chromium/ or https://github.com/refi64/zypak).

There's nothing for flatpak itself to do here. If it turns out that there's a deficiency in the portal, an issue can be opened at that point.

**Comment by smcv** [comment]
> If it turns out that there's a deficiency in the portal, an issue can be opened at that point

... but bear in mind that issues asking for new portal features might also have to be closed as "not planned" if the desired feature is impossible to achieve, or if the desired feature would introduce a security vulnerability.

> It has been claimed that the Chromium sandbox set up by that patch (or Zypak) is less secure than the native version

There is security, and there is security. There is really no such thing as a piece of software being secure or insecure in the abstract: it can only be secure or insecure against a specific threat model. We often say "secure" as a shorthand for "secure against the threat model that everyone is taking for granted", but when we get into conversations about different threat models, that's not good enough.

When using Flatpak (when not using "powerful" sandboxing parameters like `--filesystem=host`), the threat model we are usually thinking about is that the attacker has provided you with a malicious or compromised app, and Flatpak aims to prevent the attacker from escaping from the Flatpak sandbox and damaging the integrity or confidentiality of the host system. Let's call this threat model A.

When a web browser like Chromium has internal sandboxing, the threat model is that the attacker has compromised a subprocess of the browser (for example the web renderer that is responsible for processing HTML from `attacker.example.com`), and the browser aims to prevent the attacker from using that subprocess to gain control over the browser's main process and damage the integrity or confidentiality of the other websites you use. Let's call this threat model B.

Flatpak does make it more difficult to set up internal sandboxing to protect against threat model B, because if it allowed the obvious mechanisms to work, then a malicious or compromised app would be able to use those mechanisms to escape from the Flatpak sandbox, which would mean that Flatpak had failed to protect against threat model A. This is not ideal, but it's a price we have to pay for protecting against threat model A.

As @chrisawi said, the "sub-sandbox" protocol (`org.freedesktop.portal.flatpak`) is our way to protect against threat model B without compromising threat model A.
