### ISSUE TITLE
can't read gnome-nightly repo "GPG verification enabled, but no summary signatures found"

### ISSUE THREAD

**Issue by est31** [flatpak/flatpak#588]
doing this with flatpak `0.6.11` (the latest one in Ubuntu 16.10):
```
flatpak remote-add gnome-nightly https://sdk.gnome.org/gnome-nightly.flatpakrepo
flatpak remote-ls gnome-nightly
```

Yields in the error message:

```
Fehler: GPG verification enabled, but no summary signatures found (use gpg-verify-summary=false in remote config to disable)
```

This message also appears when I want to install from that remote.

The [website](http://flatpak.org/runtimes.html) told me to do a slightly different command but that one failed. Any help would be appreciated.

**Comment by alexlarsson** [comment]
0.6.11 is kind of old. I recommend using a 0.8.x stable series. In fact, i believe yakkety is getting an update to this: https://bugs.launchpad.net/ubuntu/+source/flatpak/+bug/1656712
Alternatively you can use the PPA.

In particular, what has changed since 0.6.11 is the simple support for flatpakrepo urls like the above.
However, it should still work with 0.6.11, you just have to use a different commandline args. Something
like:
```
flatpare remote-delete gnome # Drop your old one
wget https://sdk.gnome.org/gnome-nightly.flatpakrepo
flatpak remote-add --from gnome gnome-nightly.flatpakrepo
```

**Comment by est31** [comment]
@alexlarsson that worked. Thanks!
