### ISSUE TITLE
[Bug]: "Can't make symlink at /home/me/.local: destination exists and is not a symlink" with Heroic Launcher

### ISSUE THREAD

**Issue by Wilhelm-Lee** [flatpak/flatpak#5887]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.9

### What Linux distribution are you using?

Arch Linux

### Linux distribution version

6.6.42-1-lts

### What architecture are you using?

x86_64

### How to reproduce

`flatpak -v run com.heroicgameslauncher.hgl`

### Expected Behavior

flatpak should be able to run the programme specified.

### Actual Behavior

flatpak got some error output, indicating invalid environment or functioning failure.

### Additional Information

However, regarding possible errors, since this is the first time I've used flatpak to install and run a program, it's still confusing to understand the output of the errors flatpak encountered.

Here's the error message:
```
$ flatpak -v run com.heroicgameslauncher.hgl

F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/william/.local/share/flatpak
F: Opening user flatpak installation at path /home/william/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Skipping parental controls check for app/com.heroicgameslauncher.hgl/x86_64/stable since parental controls are disabled globally
F: Opening user flatpak installation at path /home/william/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/23.08/64a85d9703e16a360fb65aeb40382183be68836567e2a3a9455f70b2a26a568f/files/lib32 does not exist
F: Cleaning up unused container id 2467579934
F: Cleaning up per-app-ID state for com.heroicgameslauncher.hgl
F: Allocated instance id 1075777699
F: Add defaults in dir /com/heroicgameslauncher/hgl/
F: Add locks in dir /com/heroicgameslauncher/hgl/
F: Can't get document portal: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
F: Xdg dir xdg-documents is $HOME (i.e. disabled), ignoring
F: Allowing wayland access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Running 'bwrap --args 45 -- xdg-dbus-proxy --args=47'
F: Running 'bwrap --args 45 -- heroic-run'
bwrap: Can't make symlink at /home/william/.local: destination exists and is not a symlink
```

And as you can see, at the end of that message, it printed out a determining description for the error.

As it says, the ~/.local exists, for not being a symlink.

And here's the actual file type description:
```
$ file ~/.local
/home/william/.local: symbolic link to /external/.local/
```

I'm not sure if the symbolic linking to another unexpected destination for flatpak to handle is the key factor which caused the error to occur, but it is also obvious to notice that wherever this symlink is connected to, the error output for saying "destination exists and is not a symlink" is false.

Now here's some of outputs by running other commands from flatpak:
```
$ flatpak list

Heroic Games Launcher       com.heroicgameslauncher.hgl           v2.14.1                  stable      system
BlackBox translations       com.raggesilver.BlackBox.Locale                                stable      system
Freedesktop Platform        org.freedesktop.Platform              freedesktop-sdk-23.08.21 23.08       system
i386                        org.freedesktop.Platform.Compat.i386                           23.08       system
Mesa                        org.freedesktop.Platform.GL.default   22.1.7                   22.08       system
Mesa                        org.freedesktop.Platform.GL.default   24.1.3                   23.08       system
Mesa (Extra)                org.freedesktop.Platform.GL.default   24.1.3                   23.08-extra system
Mesa                        org.freedesktop.Platform.GL32.default 24.1.3                   23.08       system
Intel                       org.freedesktop.Platform.VAAPI.Intel                           22.08       system
openh264                    org.freedesktop.Platform.openh264     2.1.0                    2.2.0       system
gnome platform translations org.gnome.Platform.Locale                                      43          system
```
```
$ flatpak info com.heroicgameslauncher.hgl

Heroic Games Launcher - An Open Source Epic Games, GOG and Amazon Prime Games
Launcher.

          ID: com.heroicgameslauncher.hgl
         Ref: app/com.heroicgameslauncher.hgl/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: v2.14.1
     License: GPL-3.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 446.5 MB
     Runtime: org.freedesktop.Platform/x86_64/23.08
         Sdk: org.freedesktop.Sdk/x86_64/23.08

      Commit: 98c3061dec4b0cc2b25e885482ff09592631f497aa40072c16a24191f4a6ea07
      Parent: 2174c57155d99855a5af612af07509780785a1e36e0499392ad699686e92e86c
     Subject: Update manifest for UMU support (8f1d12c4)
        Date: 2024-07-26 12:16:37 +0000
```

**Comment by smcv** [comment]
> I'm not sure if the symbolic linking to another unexpected destination for flatpak to handle is the key factor which caused the error to occur, but it is also obvious to notice that wherever this symlink is connected to, the error output for saying "destination exists and is not a symlink" is false.

Because Flatpak operates in two different worlds (inside and outside the sandbox), it's common for filesystem paths to be confusing, because it isn't always obvious whether the path that is meant is inside or outside the sandbox.

This error message is coming from bubblewrap (a low-level tool that Flatpak uses) rather than from Flatpak itself, which makes it difficult to improve, because bubblewrap has much, much less context available to it than Flatpak.

So, you're sort of right, but you're also sort of wrong. Outside the sandbox, `/home/william/.local` exists and *is* a symlink. But, inside the sandbox, something (possibly something specific to Heroic Launcher) has created that path as *not* a symlink - probably a directory.

I suspect this is because Heroic Launcher's [manifest](https://github.com/flathub/com.heroicgameslauncher.hgl/blob/master/com.heroicgameslauncher.hgl.yml) has ` --persist=.`, which frequently has subtle and unintended interactions with `--filesystem` in the presence of symlinks.

Looking at the number of "powerful" permissions that Heroic Launcher has, and in particular the number of other components whose app-specific state it can make arbitrary edits to, it doesn't look as though it was really designed with sandboxing in mind. There is a limit to how well this can ever work in a Flatpak app.

`flatpak run -v -v com.heroicgameslauncher.hgl` might provide more information about what is happening here.

> /home/william/.local: symbolic link to /external/.local/

If you are offloading filesystems to an external location because you have run out of space on your root HDD/SSD, I would always recommend using a bind-mount instead of a symlink. If you do that, it will probably resolve this.

Because Heroic Launcher has `--persist=.`, you might need to remove `~/.var/app/com.heroicgameslauncher.hgl/.local` to fully recover from this.

**Comment by Wilhelm-Lee** [comment]
Fine, I'll try to get this issue put up again at bubblewrap if there's need.

For now, I'll just close this issue here because, as you described, there aren't many things we can do about on flatpak, and with those difficulties unsolved, it makes this approach to use Epic Launcher on Linux is just a bit too tricky and lengthy.

Anyway, thanks for giving so much help and explaining everything to me, much appreciated.

**Comment by smcv** [comment]
> I'll try to get this issue put up again at bubblewrap if there's need

bubblewrap probably cannot produce a better error message either, because it simply doesn't have enough information.

Reopening this to close it as "not planned", which seems more accurate than "resolved".
