### ISSUE TITLE
[Bug]: org.freedesktop.Sdk 24.08 has no full OpenGL (dev) support

### ISSUE THREAD

**Issue by Schildkroet** [flatpak/flatpak#5940]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.14.6

### What Linux distribution are you using?

Ubuntu

### Linux distribution version

24.04

### What architecture are you using?

x86_64

### Expected Behavior

I can build/compile applications with OpenGL support.

### Actual Behavior

Build/Compile/configuration of app with OpenGL fails due to missing/wrong OpenGL libraries:
```
checking for OpenGL headers... found in /usr/include
checking for GL/gl.h... yes
checking for GL/glu.h... yes
checking for pkg-config... (cached) /usr/bin/pkg-config
checking for GL... yes
checking for pkg-config... (cached) /usr/bin/pkg-config
checking for GLU... checking for gluBeginCurve in -lGLU... no
checking elsewhere... no
checking for pkg-config... (cached) /usr/bin/pkg-config
checking for MesaGL... checking for glEnable in -lMesaGL... no
checking elsewhere... no
configure: error: OpenGL libraries not available
```

Build/Compile was working fine with **23.08**
Error only occured after **changing** Sdk to 24.08

### Additional Information

Sdk 23.08 works as expected. Error was introduced with 24.08

**Comment by smcv** [comment]
Flatpak does not control the contents of any specific runtime. https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues is the issue tracker for `org.freedesktop.Sdk`.

Having said that, I'm pretty sure `org.freedesktop.Sdk//24.08` does have full OpenGL support: if it didn't, they wouldn't be able to compile, e.g., GTK.

If you report this to freedesktop-sdk, they will probably want to see your app's `configure.ac`, Flatpak manifest and `config.log`, not just a snippet of output.

> `checking for GLU`

This is a separate utility library, not part of "core" OpenGL, and might have been excluded intentionally. If this isn't part of the 24.08 SDK but you still need it, then you'll need to compile your own from your Flatpak manifest.

For example https://github.com/flathub/shared-modules includes https://github.com/flathub/shared-modules/blob/master/glu/glu-9.json, and https://github.com/flathub/org.bzflag.BZFlag is an example of a game that uses it.

> `checking for MesaGL... checking for glEnable in -lMesaGL... no`

`libMesaGL.so` doesn't generally exist on modern desktop OSs either, so your build system should hopefully be able to use `libGL.so.1` instead of this.
