### ISSUE TITLE
Consider whether to turn off Wayland security-context integration in 1.16.x

### ISSUE THREAD

**Issue by smcv** [flatpak/flatpak#6019]
The Wayland security context mechanism has a known regression for some apps, #5863. I've sent a PR to #6018, but I'm not in a position to test it.

If we have a known regression when using the Wayland security context mechanism, and nobody among the maintainers who can be responsible for maintaining (testing/reviewing) that code path, then I think we should consider turning it off by default (`value: 'disabled'` instead of `'auto'`) before we branch for 1.16.0.

**Comment by swick** [comment]
I would like to keep it around for a bit longer because it is in active use to prevent access  to privileged wayland protocols from flatpak apps. In the long term I'd like to get rid of the security context and ideally use a cgroup xattr mechanism which should work for wayland, dbus, pipewire, varlink and anything else really.

**Comment by smcv** [comment]
> it is in active use to prevent access to privileged wayland protocols from flatpak apps

In what desktop environment(s)? Is there a way that Flatpak maintainers can confirm that this functionality has not regressed?

> In the long term I'd like to get rid of the security context and ideally use a cgroup xattr mechanism which should work for wayland, dbus, pipewire, varlink and anything else really

Is this a new feature of recent kernels, or an as-yet-hypothetical feature of future kernels, or something like that?

Historically, the only things we have been able to rely on to identify the originator of a AF_UNIX connection securely have been:

* `SO_PEERCRED` or `SCM_CREDENTIALS` uid, primary gid and pid
    * but it is not possible to use the pid to look up additional information in `/proc` in a race-free way, partly [because `execve()` of a more-privileged binary preserves the pid while elevating the apparent credentials](https://gitlab.freedesktop.org/dbus/dbus/-/issues/108), and partly because pid reuse is a thing
* `SO_PEERSEC` Linux security context (which in many ways is the ideal tool for security labelling, but Flatpak intentionally does not use this because, unlike e.g. Snap, Flatpak does not want to rely on use of a specific "big" LSM like AppArmor)
* `SO_PEERGROUPS` supplementary groups
* `SO_PEERPIDFD` pidfd (in sufficiently recent kernels)

Flatpak's current technique for D-Bus is to use a trusted (non-attacker-controlled) xdg-dbus-proxy to avoid the race conditions inherent in looking up additional information about a pid (in our case `/proc/$pid/root`) from `SO_PEERCRED`: we can avoid the `execve()` problem because we trust xdg-dbus-proxy not to do that, and we can avoid the pid reuse problem because the attacker (a malicious or compromised app) is not able to choose the precise timing with which xdg-dbus-proxy will exit. But obviously that scales poorly, because we don't want to have 3 D-Bus proxies, a Wayland proxy, a Pipewire proxy, some arbitrary number of Varlink proxies and so on.

**Comment by swick** [comment]
> In what desktop environment(s)?

Sway for example: https://github.com/swaywm/sway/blob/1d783794b508e529bdc665296d690057c93997df/sway/server.c#L134. The implementation of the security context is in wlroots: https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/types/wlr_security_context_v1.c

> Is there a way that Flatpak maintainers can confirm that this functionality has not regressed?

Yes. Run sway (just in your graphical session will create a nested instance) and make sure it's on the socket wayland-1:
```bash
WAYLAND_DISPLAY=wayland-1 WAYLAND_DEBUG=1 adwaita-1-demo 2>&1 | grep zwlr_screencopy_manager_v1
WAYLAND_DISPLAY=wayland-1 flatpak run --command=bash org.gnome.clocks -c "env WAYLAND_DEBUG=1 adwaita-1-demo" 2>&1 | grep zwlr_screencopy_manager_v1
```

**Comment by swick** [comment]
> Is this a new feature of recent kernels, or an as-yet-hypothetical feature of future kernels, or something like that?

This requires
1. pidfd to prevent the fd passing exec confusion and pid reuse attacks
2. xattrs on cgroups

The idea is to use `SO_PEERPIDFD` from the connection, walk the cgroup path of the peer until one finds the first matching cgroup name and/or xattrs and protect that lookup by checking the pidfd still resolves to the same pid after the lookup.

Using cgroups and xattrs on cgroups with flatpak currently is safe because we do not mount `/sys/fs/cgroup/`, giving it not way to change that information. In the future flatpak and/or bwrap could even start mounting `/sys/fs/cgroup/` after unsharing the cgroupns (there are a few unpleasant details but nothing too bad).

**Comment by smcv** [comment]
Now that #6018 has landed, resolving the known regression, I think we can leave the security-context integration enabled by default.
