### ISSUE TITLE
[Bug]: `sudo flatpak install` does not issue `applications installed by Flatpak may not appear on your desktop until the session is restarted`

### ISSUE THREAD

**Issue by davidhedlund** [flatpak/flatpak#6027]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.12.7-1ubuntu0.1

### What Linux distribution are you using?

Other (specify below)

### Linux distribution version

5.15.0-126-generic

### What architecture are you using?

x86_64

### How to reproduce

Note, to reproduce this issue you must create a new user and log in for the first time. You can use a distro that supports live mode to do this.

# --user (control)
```
$ flatpak --user install [ANYAPPID]
Note that the directories 

'/var/lib/flatpak/exports/share'
'/home/blues/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.
```

# sudo (issue)
```
$ sudo flatpak install [ANYAPPID]
```

## Expected behaviour

```
$ sudo flatpak install [ANYAPPID]
Note that the directories 

'/var/lib/flatpak/exports/share'
'/home/blues/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.
```

**Comment by smcv** [comment]
I don't think this is going to be implementable. `sudo` resets environment variables and starts a new PAM session, so `sudo flatpak install` does not know what environment variables were set in your session as the ordinary user, and in particular cannot know whether they already contain the necessary directories for Flatpak.

**Comment by davidhedlund** [comment]
> I don't think this is going to be implementable. `sudo` resets environment variables and starts a new PAM session, so `sudo flatpak install` does not know what environment variables were set in your session as the ordinary user, and in particular cannot know whether they already contain the necessary directories for Flatpak.

Thank you very much for quick reply.

**Comment by davidhedlund** [comment]
I updated the top post.

**Comment by davidhedlund** [comment]
> > I don't think this is going to be implementable. `sudo` resets environment variables and starts a new PAM session, so `sudo flatpak install` does not know what environment variables were set in your session as the ordinary user, and in particular cannot know whether they already contain the necessary directories for Flatpak.
> 
> I updated the top post. `flatpak install --system` does not cause this issue, only `sudo flatpak install`. So sudo should not be used with flatpak.

Should this be documented? If so, it could also be included that the `--system` flag helps avoiding the need for distribution-specific privilege escalation commands like "sudo" or "su".

**Comment by smcv** [comment]
> `flatpak install --system` does not cause this issue, only `sudo flatpak install`.

I think you're perhaps seeing more complexity here than really exists. `--system` is the default, so `flatpak install` is exactly equivalent to `flatpak install --system`, and `sudo flatpak install` is exactly equivalent to `sudo flatpak install --system`.

Running flatpak in the default `--system` mode installs apps system-wide (for all users). If you are an unprivileged user, it uses `polkit` to ask a privileged system service to do the actual installation. If you are root (possibly via sudo), it does the actual installation directly.

> So sudo should not be used with flatpak.

I would say it's more like this general rule: sudo should only be used with *any* command (flatpak-related or otherwise) if you understand the implications of doing that.

For Flatpak, one of the more minor implications of using sudo is that it cannot see whether your user session is correctly configured to be able to launch Flatpak apps easily, because after using sudo, it is no longer in your user session.

Some of Flatpak's subcommands should never be wrapped with sudo (notably `flatpak run`), some subcommands will work fine (for example `sudo flatpak override` to configure overrides that apply to all users by default), and some will work but will not necessarily do what you expect (for example `sudo flatpak install --user` would install the app for root only, which makes sense when you think about it, but is very unlikely to be what anyone actually intended).

**Comment by smcv** [comment]
> Note, to reproduce this issue you must create a new user and log in for the first time.

On a correctly-configured distribution, this issue will only occur if you have only recently installed Flatpak.

If you have logged out and back in at least once since you installed Flatpak, or if you have rebooted at least once since you installed Flatpak, then the `XDG_DATA_DIRS` will usually have already been set up correctly by `/etc/profile.d/flatpak.sh`.

**Comment by davidhedlund** [comment]
> > Note, to reproduce this issue you must create a new user and log in for the first time.
> 
> On a correctly-configured distribution, this issue will only occur if you have only recently installed Flatpak.
> 
> If you have logged out and back in at least once since you installed Flatpak, or if you have rebooted at least once since you installed Flatpak, then the `XDG_DATA_DIRS` will usually have already been set up correctly by `/etc/profile.d/flatpak.sh`.

Thank you very much for this information.
