### ISSUE TITLE
Runtime without gpg failed to install

### ISSUE THREAD

**Issue by biji** [flatpak/flatpak#61]
I try to install runtime from https://community.kde.org/Flatpak but failed

flatpak --version
flatpak 0.6.2

flatpak remote-add kde http://distribute.kde.org/flatpak-testing/ --no-gpg-verify
flatpak install kde org.kde.Platform

error: GDBus.Error:org.freedesktop.DBus.Error.Failed: Error pulling from repo: Can't pull from untrusted non-gpg verified remote

**Comment by alexlarsson** [comment]
Yeah, the system installs don't support policykit raised privileges for non-gpg-signed repos, because there is no way without that to protect you against MITM attacks, so how do you know that its safe?

You can work around this by doing
```
sudo flatpak install kde org.kde.Platform
```
However, i've told @AleixPol to add signatures to it, so hopefully this will solve itself.

**Comment by biji** [comment]
Ok it work using sudo
thanks
