### ISSUE TITLE
allow exporting a whole directory

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/flatpak#630]
I was looking at making help work in flatpak applications. For that, it would be useful if we could export a whole directory tree below a root that has the application id as prefix, as in

/usr/share/help/org.gnome.Recipes

It seems that the current code in flatpak_export_dir insists on having the app-id as prefix on each individual file

**Comment by alexlarsson** [comment]
I worry about opening up what is being exported more, because there are a lot of things on the host that read files in XDG_DATA_DIRS with full trust of it. For instance, application or even shell plugins/extensions. Its not hard to get remote execute if you can put anything there. The current naming limit somewhat minimizes this, but even it its not necessarily 100% secure.

Even in the very specific case of allowing exports of yelp docs, what if there is an exploit in the yelp index reader? Then loading yelp gets the app out-of-sandbox execution.

**Comment by matthiasclasen** [comment]
ok, fair enough.

Lets hold off on this and try to make yelp work inside the platform runtime instead.
