### ISSUE TITLE
Warn if an updated Sdk is available when using flatpak-builder

### ISSUE THREAD

**Issue by bochecha** [flatpak/flatpak#655]
Today @csoriano89 tried building the Nautilus master bundle, which builds tracker from master.

At some point, tracker master added a new dependency on libseccomp.

I added libseccomp to the fdo Sdk back in December 2016, to fix the build of Nautilus and other apps using tracker.

So this morning, @csoriano89 tried building Nautilus master locally, but he had an old version of the Sdk installed, one which didn't contain libseccomp, and his build failed.

Maybe `flatpak-builder` could have quickly checked that an updated Sdk was available, and warned about it?

Alternatively, maybe `flatpak-builder` could automatically update the Sdk?

**Comment by csoriano89** [comment]
The problem is basically if the dep is added to the SDK, doesn't make sense for the maintainer to add it on the manifest. But then the app fails to build until the SDK is updated locally, and there is no way for the application to say "we depend on this SDK which added this new dependency" since additions to the SDK doesn't make the SDK bump versions.

What I can think of is to add micro version to the SDK so the app can say "you need at least this version of the SDK that added this new dependency".

**Comment by matthiasclasen** [comment]
I think it would be good for the manifest to have a way to specify a minimum commit id to use, if that makes sense.

**Comment by csoriano89** [comment]
Good idea, microversions are just a burden for Alex and other contributors. Commit id would be a good solution.

**Comment by alexlarsson** [comment]
Commit id of what? The git repo? Its hard to verify that, as you can't compare it with "less-than".

**Comment by alexlarsson** [comment]
This issue was moved to flatpak/flatpak-builder#22
