### ISSUE TITLE
Can Flatpak conflict with other installed isolation Frameworks?

### ISSUE THREAD

**Issue by HulaHoopWhonix** [flatpak/flatpak#66]
Can you add to the FAQ the answer to the question of whether Flatpak will be compatible/stackable with other desktop app isolation frameworks like Firejail?

We are looking at integrating Firejail into Debian and want to make sure no conflicts happen when Flatpak ships by default.

Also what happens if a program wrapped in Flatpak is also launched in Firejail concurrently?

https://firejail.wordpress.com/

**Comment by alexlarsson** [comment]
In general unprivileged container systems can't stack, because anything running inside the sandbox has no privileges do set up a sandbox, nor does it have the ability to in any way raise its privileges. For instance, firejail can never work inside flatpak, because it is setuid, and the same is true in the other case, at least if you use the setuid mode of flatpak (*maybe* you can get it to work with the unprivileged user namespaces mode of flatpak with a very lenient configuration of firejail).

However, what is the point of even trying this? Doing the same thing twice will not make anything more secure, and its not like shipping flatpak by default implies running every app as a flatpak.

**Comment by alexlarsson** [comment]
@jimmac Could you add a mention of this in the FAQ?

**Comment by matthiasclasen** [comment]
added a question for it in https://github.com/flatpak/flatpak.github.io/pull/61
