### ISSUE TITLE
Expose ostree rollback functionality in libflatpak API

### ISSUE THREAD

**Issue by Sesivany** [flatpak/flatpak#664]
OSTree supports rollback and after a discussion with a couple of people I think rolling back an application update is a valid use case even for average users. App managers such as Software or Discover could do it directly through OSTree, but it'd be much better for them to access it through libflatpak.

**Comment by alexlarsson** [comment]
We could add a commit id argument to flatpak_installation_update pretty easily, as its already there on the lower levels (for `flatpak update --commit=COMMIT`). 

However, the larger question is about listing remote history for a ref so that you can expose version rollback in a nice way. This needs work.

**Comment by matthiasclasen** [comment]
I discussed with Richard recently the idea of making gnome-software keep a log of all commits of an app that have been deployed. But he correctly pointed out that it would be nice to keep this information at a lower level, so we can provide the same functionality in the commandline tools.

**Comment by matthiasclasen** [comment]
I think flatpak_transaction_update has a commit argument that covers this. There's a flatpak history command incoming that will fill in more pieces of the puzzle
