### ISSUE TITLE
Allow to install a flatpak on a custom path (eg. external drive)

### ISSUE THREAD

**Issue by tesfabpel** [flatpak/flatpak#68]
Please allow to install a flatpak on a custom path (eg. external drive)...
Maybe then, the folder in ~/.local/share/flatpak/app/<appname>/<version> could be replaced with a symlink...

**Comment by alexlarsson** [comment]
That doesn't work. The way the ostree setup requires the entire ~/.local/share/flatpak structure to be on the same filesystem (for hardlinks to work). However, that the entire thing can obviously be a symlink if you want.

**Comment by tesfabpel** [comment]
That's sad... :(
Installing a large flatpak app like would be 0 A.D. or other big apps like games into a SSD where space is limited could be a problem...
Anyway really good work! :+1: 
I think this project will really help Linux adoption! :)

**Comment by NullTheSecond** [comment]
Yeah, I simply cannot use large applications on GNU/Linux as my SSD cannot store that much data.

**Comment by alexlarsson** [comment]
What you could do is set up a separate "installation", see `man flatpak-installation`. You can then install a particular app to that installation: `flatpak install --installation=thename ...`

**Comment by aiamuzz** [comment]
I read somewhere that flatpak applications are distro-agnostic ... which i am assuming means the same application can run on all distros without a necessity to adapt to specific distro's ... which is definitely a much needed reprieve for developers ... without doubt !

Will the same **installed** flatpak application run on all distro's once its installed ?

if the latter is true ... then ... 

**Isnt it a good idea ... to have all the flatpack ecosystem on a disk other than the root partition ?**

I mean in an ideal world ... If flatpak is truly distro-agnostic (especially in the sense of running) then wouldn't it be better to have this flatpak-ecosystem on a separate partition(preferable the /home ) or even another ext partition ?

This would in the truest, realize its full potential don't you think ?

One can switch to as many distros as one may need with absolutely no worries about having to install their apps on each one of them as they are hopping around one distro to another.

I am sure we all agree that its such a pain to have to install All apps to a distro each time one hops ?

I am however not sure if the current architecture supports it but ... nevertheless shouldn't the USER's too have the same luxury as the Developers through flatpak of having to write code only once ... 

Write Code only once ... as well as ... Install App only-once ???

**Comment by alexlarsson** [comment]
That should be easy to setup either with a separate installation, or by just mounting /var/lib/flatpak from shared partition.

**Comment by aiamuzz** [comment]
@alexlarsson ...

Alex ... was that in response to my comment ?

let me make it clear ... i am not a geek ... just a super user of sorts ...

so are you saying if i copied /var/lib/flatpak to say /home/flatpak and put a symbolic link to the 'flatpak' folder at /var/lib ... the apps will install and update to the /home partition ... and ... Install-App-Only-Once-run-on-all-linux-distro's ... will fly through ?

**Comment by aiamuzz** [comment]
turns out the response wasn't for me ...

i tried making a copy of the flatpak in /home ... renamed the flatpak folder in /var/lib and placed a sym link in its place ... and to test this arrangement i installed DeepinCalendar(flatpak) ... the store installed it and shows up as installed ... BUT ... the app didn't install at the /home location ... further `flatpak list` returned blank ... no launcher icon for the flatpak version of the calendar app ... now i am stuck with a store that say it is installed but the calendar app is nowhere to be found ... 

I further compared the flatpak folder in both the locations ... and seems there are some sym links in the /var/lib version of the folder and the same are missing in the /home version of the folder ... Is this normal ...

**Comment by aiamuzz** [comment]
ok the problem turned out to be 'grsync' ... sym links weren't copied to the /home version of the flatpak folder.

I resync'd by checking the necessary option(to include sym links) ... and retried the earlier arrangement ... turns out its working (need to test further) ... for now ... `flatpak list` is returning the list of installed flatpak apps ... color picker worked ...

now i have a stale deepin calendar install ... in the deepin store ... hmmmm ... need to test another flatpak app

**Comment by aiamuzz** [comment]
ok ... installation working ... installed a simpla flatpak app ... and it installed at the /home version of the flatpak folder and the app's working too ...

However there are some permission dissimilarities ... as you can see in the pic below ...

![deepinscreenshot_select-area_20171121184744](https://user-images.githubusercontent.com/3283676/33074601-beac6ce2-ceec-11e7-9b18-6d3e280186cf.png)

the previously installed apps permissions are user ... whereas the newly installed app in this new arrangement is owned by 'root' ... i did not use `sudo` to install this app ... just the command flatpak install `flatpak install com.github.dahenson.agenda.flatpakref` ... but the app has gotten installed with 'root' as the owner.

do i need to change the previous apps ownership permissions too ... to that of 'root' ?

**Comment by LorenzoAncora** [comment]
> What you could do is set up a separate "installation", see man flatpak-installation. You can then install a particular app to that installation: flatpak install --installation=thename ...
> That should be easy to setup either with a separate installation, or by just mounting /var/lib/flatpak from shared partition.

@alexlarsson nobody should need to create a new partition table or alter the logical filesystem hierarchy because an application does not allow users to specify where to save their files. This is not the correct solution: in the first place, why should I need to call the sysadmin to do such a trivial change? Why the user cannot specify the installation path directly in the CLI? :-/

This is a serious problem, in a classic multi-partition setup I can install _at most_ two or three flatpaks simultaneously because after I run out of inodes: for users who already have a large number of files to manage, Flatpak can easily make the creation of new files impossible, because the system indicates that the disk space is exhausted even if the storage capacity is not.

I believe the UX should be more guided: for example, if the end-user runs out of inodes the newly downloaded files should be uninstalled immediately after printing a friendly error message, because otherwise **the user won't be able to save his/her work easily and discovering the cause is hard (few users know the meaning of "inode" and the commands to investigate)**.
I - as an end-user - when I want to install a program I want to do it **quickly** and **intuitively**, without having to consult 32 scattered manual pages and without having to use commands like `df --inodes -h` in the fear that the inodes will run out.

---

PS: **Debian users with the same problem** will find the documentation in Flatpak 1.2.3 or better (the current release 0.8.9 from Debian stable does not contain the correct documentation): visit `/usr/share/doc/flatpak/flatpak-docs.html#flatpak-installation` with your web browser for the unified docs.

**Comment by refi64** [comment]
I have quite a few Flatpaks and files, without running out of inodes. The amount of files Flatpak saves shouldn't really be much, if at all, higher than a normal package. Sure your filesystem wasn't somehow with an incredibly low inode limit?

**Comment by LorenzoAncora** [comment]
> I have quite a few Flatpaks and files, without running out of inodes. The amount of files Flatpak saves shouldn't really be much, if at all, higher than a normal package. **Sure your filesystem wasn't somehow with an incredibly low inode limit?**

@refi64 TY but sadly, there is no standard that says which inode number is considered "incredibly low". 
I use a **standard fs hierarchy configured automatically** by the Debian installer in line with the FHS (as indicated by the Linux Foundation), **corroborated by LVM** as in all modern distributions for business use. My `/home` uses EXT 4. **I have never had problems with inodes in twelve years** of use (and I have installed dozens of applications from source, even with myriads of small files), **only Flatpak seems to cause the exhaustion of inodes**.
I think the problem is that the runtimes downloaded to support the operation of many Flatpaks soon exhaust the inodes in `/var` (6G, 'news', 1,5M inodes) and `/home` (100G, 'largefiles', 101K inodes), also because the increase of the **space allocated through LVM does not necessarily correspond to the increase in inodes**: when Flatpak downloads the repos containing tons of small (often duplicated) files, this sometimes **prevents updating Debian and slows down the system** (which cannot create enough temporary files), besides being difficult to diagnose. **I needed to search and delete manually the downloaded Flatpak repositories to be able to save my documents in my own home folder**.

Most likely the problem does not show up on your machines because you have few personal and / or business files stored on the machine, but I believe the consumption of inodes is abnormal: I expect a similar problem from a database, certainly not from a package manager... :-/
In general having to partition is a tedious operation: **I believe that the end user should only wonder if the _disk space_ is enough**.

I think it's a structural problem of Flatpak, but I'm not the type that complains without proposing a solution: have you considered the possibility of automatically saving the downloaded repositories in independent disk images or uncompressed archives? In this way Flatpak could mount the archive (which would consume in the best case a single inode) and launch the program.
