### ISSUE TITLE
Flatpak 0.9.3 is giving me segmentation faults and other errors everywhere on Gentoo Linux

### ISSUE THREAD

**Issue by fusion809** [flatpak/flatpak#749]
Hi,

I installed Flatpak on Gentoo Linux using the [`flatpak-overlay`](https://github.com/fosero/flatpak-overlay) and while versions between 0.8 and 0.9 worked just fine since the update to 0.9.3 I get errors whenever I try to start a Flatpak, although installing Flatpaks returns no such error. At first I got segmentation faults, for details see fosero/flatpak-overlay#7, but now I get the errors like:

```bash
Can't mkdir /home/fusion809/.config/dconf: No such file or directory
```

for org.gnome.gedit and org.gnome.Builder. While MonoDevelop gives the error:

```bash
Can't mkdir parents for /home/fusion809/.local/share/flatpak: No such file or directory
```

is it relevant that my `~/.local` directory is a symlink to `/data/.local`? 

Thanks for your time,
Brenton

**Comment by fusion809** [comment]
Ah it is related to my symlinking to /data, install the Flatpak as root and running as root causes everything to run fine.

**Comment by pythoneer** [comment]
Is there any follow up on this "problem"? I have the same issue with Builder and i am also symlinking my `~/.local` directory. Is this not supported by Flatpak? I am just wondering because "just" installing as root does not look like the right solution to me. 

Either way i can't get Builder(nightly) to run, it does not matter if i install it as "root" or --user and i get this `../.local/share/flatpak` and `../.config/dconf` error regardless. Is the a Problem based on how Builder is packaged or how Flatpak is handling symlinks?
