### ISSUE TITLE
Exporting multiple .desktop files

### ISSUE THREAD

**Issue by casept** [flatpak/flatpak#750]
I'm creating a flatpak package for openMW, a reimplementation of the morrowind game engine. Upstream ships two desktop files and corresponding icons - one launches the game, the other one launches a level editor.I'm trying to create a package which contains both the game and the editor, as that's how upstream does things.
Unfortunately, simply specifying multiple `rename-desktop-file` and `rename-icon` lines seems to cause all but the last one to be ignored. I know I could split the editor into a separate manifest, however having to install two packages would confuse users, waste disk space and require me to build all dependencies (including Qt4 and other libraries with build times in the hours) twice. Is it at all possible to have one package export multiple .desktop files/icons?

**Comment by matthiasclasen** [comment]
First of all, if you want to do this, all the files that get exported must have the app id as prefix, so you can do something like:
$appid.desktop - for the game itself
$appid.Editor.desktop - for the editor

If your situation is more complicated, I think you can do the renaming yourself, using a post-install script, instead of relying on the rename-desktop-file or rename-icon convenience shortcuts.

**Comment by manuq** [comment]
Isn't LibreOffice flatpak doing something like this already for Calc, Writer?

**Comment by alexlarsson** [comment]
Closing since this got a reply
