### ISSUE TITLE
symlinking /etc/resolv.conf is unreliable

### ISSUE THREAD

**Issue by MetricMike** [flatpak/flatpak#759]
Hey!

I noticed an odd case (https://github.com/tiliado/nuvolaplayer/issues/329) when running DNSMasq on my laptop and then trying to use a flatpak app that makes calls out to the public internet. If my laptop's `/etc/resolv.conf` looks like:

```bash
#/etc/resolv.conf
nameserver 127.0.0.1
```
Then any flatpak app I run will be cut off from the network (since there is no DNS service running inside the flatpak environment listening on 127.0.0.1). Likewise, a privately addressed nameserver (like 192.168.118.30) will similarly isolate any flatpak environment I run.

Is there an option to instead direct a flatpak to use the host's DNS? Thanks!

**Comment by fenryxo** [comment]
More details:

* Runtime is org.gnome.Platform 3.22
* "finish-args" contains "--share=network"
* both [drill](https://www.nlnetlabs.nl/projects/ldns/) google.com and drill play.spotify.com return: `Error: error sending query: Could not send or receive, because of network error`
* WebKitGTK+ shows `Error resolving 'play.spotify.com': Temporary failure in name resolution`

I've built a simpler flatpak containing only drill for debugging. @MetricMike, could you verify that your issue is reproducible with this flatpak (just to be sure the issue is not in Nuvola's flatpak itself)?

```
# for others: flatpak remote-add --from nuvola https://dl.tiliado.eu/flatpak/nuvola.flatpakrepo
flatpak install [nuvola repo] eu.tiliado.debug.Drill
flatpak run eu.tiliado.debug.Drill play.spotify.com
```

For reference, drill.json for flatpak-builder is as follows:

```
{
  "id": "eu.tiliado.debug.Drill",
  "branch": "stable",
  "runtime": "org.gnome.Platform",
  "runtime-version": "3.22",
  "sdk": "org.gnome.Sdk",
  "command": "drill",
  "finish-args": [
    /* Needs to talk to the network: */
    "--share=network",
    /* We want bash! */
    "--env=SHELL=/bin/bash"
  ],
  "cleanup": [
    "/cache",
    "/man",
    "/share/man",
    "/lib/systemd",
    "*.la", "*.a"
  ],
  "modules": [
    {
      "name": "ldns",
      "config-opts": [
        "--sysconfdir=/app/etc",
        "--localstatedir=/app/var",
        "--disable-rpath",
        "-with-drill",
        "-disable-dane-verify",
        "-with-trust-anchor=/app/etc/trusted-key.key",
        "--disable-static"
      ],
      "sources": [
        {
          "type": "archive", 
          "url": "https://www.nlnetlabs.nl/downloads/ldns/ldns-1.7.0.tar.gz",
          "sha256": "c19f5b1b4fb374cfe34f4845ea11b1e0551ddc67803bd6ddd5d2a20f0997a6cc"
        }
      ]
    }
  ]
}
```

**Comment by alexlarsson** [comment]
I really don't understand this. If --share=network, then we're really using the same network setup in the sandbox and on the host. In particular, 127.0.0.1 should be the same loopback device and you should be able to talk to the dns masq server.

Can you strace the drill call and see exactly where it goes wrong?

**Comment by MetricMike** [comment]
Sorry for the delay - I tracked this down to a bad configuration between my local dnsmasq and systemd-resolved. My fault, sorry for the confusion!
