### ISSUE TITLE
Patch sources are not serialized to the generated manifest

### ISSUE THREAD

**Issue by bochecha** [flatpak/flatpak#780]
flatpak-builder helpfully writes in the build the manifest it actually used to build.

For example it contains the actual Git commit hash which was checked out for the build, even if that wasn't specified in the original manifest.

Similarly, `file` sources are base64-encoded and written into a data URL, making it easy to reproduce the build with just the built manifest.

Should `patch` sources be base64-encoded and written to a data URL as well?

**Comment by alexlarsson** [comment]
I actually dropped the base64-encoding of the file sources in master, because we have a better approach now, flatpak-builder --bundle-sources, which bundles everything (including archives, files and patches). base64-encoding a source file like that into the regular deployed app was never really great, as they could potentially be very large.
