### ISSUE TITLE
No such file or directory during build

### ISSUE THREAD

**Issue by plfiorini** [flatpak/flatpak#799]
My runtime builds a build system called qbs (http://doc.qt.io/qbs/) that is needed to build another module.
Probably not a relevant information, but: since it's a build system I indicate "cleanup-platform": ["*"]
The qbs module builds and install fine.

The problem happens when I build another module with qbs: qbs checks whether its plugins exist with stat which fails with "No such file or directory", however if I make a custom configure script for the module the files exist according to `ls`.

This happens with flatpak 0.9.3 on Arch Linux.

**Comment by alexlarsson** [comment]
Do you have a sample (ideally somewhat minimal) that exposes this issue?

**Comment by plfiorini** [comment]
@alexlarsson This is a copy of my runtime with only the bare minimum deps: https://github.com/lirios/flatpak-runtime/tree/test

The minimal manifest is `io.liri.Test.Sdk.json` that is based on an already built runtime that you can download from https://repo.liri.io/flatpak/liri.flatpakrepo otherwise `io.liri.Sdk.json.in` is based on the freedesktop runtime and builds only `qbs`, its dependencies and `fluid` that is the module using `qbs` to build. Needless to say the latter version takes longer to build.

Paths not found: `/usr/share/qbs` and `/usr/lib/qbs/plugins`

**Comment by alexlarsson** [comment]
Ah, this is an issue with qbs. It considers files with mtime 0 to not exist:
https://github.com/qt-labs/qbs/blob/aba193d23420777a309597fe64a9398076b6ff25/src/lib/corelib/tools/fileinfo.cpp#L338

However, ostree uses mtime 0 for all checkouts, in order to maximize sharing of objects. (i.e. two identical source files with different mtimes should result in the same hardlinked file in the ostree checkout).

This is not dissimilar to https://github.com/ninja-build/ninja/issues/1120 which i fixed with a simple patch in the runtime copy of ninja.

**Comment by plfiorini** [comment]
Oh right, at some point I made a patch that was printing the error with `perror` and seen a `No such file or directory` that fooled me, so I excluded `mtime 0` as a possible cause.

I patched `qbs` and the build seems fine. Thanks.

**Comment by Justinzobel** [comment]
Sorry to bring back a closed issue but this is still affecting flatpak-builder. @plfiorini was the patch you made sent upstream to qbs?

**Comment by plfiorini** [comment]
> Sorry to bring back a closed issue but this is still affecting flatpak-builder. @plfiorini was the patch you made sent upstream to qbs?

No I haven't and I won't because I don't use qbs anymore.
