### ISSUE TITLE
Fails on ZFS because of fallocate not being supported

### ISSUE THREAD

**Issue by emacsomancer** [flatpak/flatpak#802]
Is there a way to force flatpak to use `dd` instead of `fallocate`?  I am unable to install any flatpaks on a ZFS filesystem (on Linux).

**Comment by alexlarsson** [comment]
This seems to be from ostree, because flatpak never calls this itself. The only calls seem to be in _ostree_repo_open_content_bare() and create_regular_tmpfile_linkable_with_content().

 @cgwalters, is there any chance fallocate calls in ostree could be optional? A fallback could just use ftruncate() right?

**Comment by cgwalters** [comment]
There's one in libglnx too.  Hmm, but glibc has a fallback for this.  Are you not using glibc?  And is this a new kernel?  Can you try e.g.:

strace -f -o strace.log flatpak ...
and then:
`grep fallocate strace.log`?

**Comment by emacsomancer** [comment]
I'm using musl libc.

**Comment by cgwalters** [comment]
Right, compare:
http://git.musl-libc.org/cgit/musl/commit/src?id=1c76683cb4377a481dc1085b63170bb276512267
https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/unix/sysv/linux/posix_fallocate64.c;h=eb05f7c5d0631e288ce9a01ff19f92549fff5472;hb=HEAD

So...it looks like coreutils does silently ignore `ENOSYS` and `EOPNOTSUPP`, but e.g. systemd doesn't.  I suspect you're going to be hitting this in more places.

**Comment by emacsomancer** [comment]
So it's an edge case involving [+ZFS,-glibc,-systemd] ?

Where does the responsibility here lie, do you think?  With musl or with the init manager?

Interestingly, this is the first time I'm run into this issue, though admittedly I've only been running this system a couple of months.

(My current workaround for the flatpak issue is an ext4-formatted `.img`, mounted at `/var/lib/flatpak/` )

**Comment by alexlarsson** [comment]
Systemd is not involved in this particular case, just musl, but systemd will also run into similar issues.
Possible fixes are makeing musl posix_fallocate() have an ENOSYS/EOPNOTSUPP fallback, or finding every user in the world and adding the fallback to them. Since the later touches a lot of software, and is only needed for musl, i think the proper fix should go into musl.

**Comment by alexlarsson** [comment]
This is the fallback that glibc uses:
https://sourceware.org/git/?p=glibc.git;a=blob_plain;f=sysdeps/posix/posix_fallocate64.c

**Comment by richfelker** [comment]
The glibc "fallback" is dangerously buggy and the subject of a bug report that was closed as wontfix: https://sourceware.org/bugzilla/show_bug.cgi?id=15661

musl will obviously not be adopting the same.

posix_fallocate is permitted to fail, and must fail if it can't accomplish what it's specified to do on success. I'm not sure what flatpak needs from it; simply using ftruncate to set the file size to the desired length might suffice, or it might be necessary to perform writes on every block.

**Comment by cgwalters** [comment]
https://github.com/GNOME/libglnx/pull/52

**Comment by cgwalters** [comment]
Fixed by https://github.com/ostreedev/ostree/pull/970
