### ISSUE TITLE
[Help Wanted] Libreoffice+Flatpak are using 50% CPU

### ISSUE THREAD

**Issue by kotlinlearner** [flatpak/flatpak#813]
If I run Libreoffice in Flatpak, 50% of my CPU is used permanently by process /app/libreoffice/program/soffice.bin --splash-pipe=5; even while Libreoffice is running in background.

If I run Libreoffice "normally" it does not even use 1% of my CPU while running in background.

I am using Linux Mint 18 Xfce.

**Comment by alexlarsson** [comment]
@stbergmann Any idea?

**Comment by stbergmann** [comment]
That sounds like <https://cgit.freedesktop.org/libreoffice/core/commit/?id=a4740c8ea92cc50c1dc6e87d06db190800269a5d> "A slightly better DbusIpcThread [...] that doesn't burn CPU [...]", which should be fixed in LO 5.3.  Which version of the LO Flatpak are you using?  Does the problem go away if you upgrade to the latest version (currently LO 5.3.3, <http://www.libreoffice.org/download/flatpak/>)?

**Comment by kotlinlearner** [comment]
I am already using LO 5.3.3.2, the newest version.

Just in case this is important: I also tried it in a virtual machine and the same problem appeared.
In the VM it said that LO was using more than 100% of the CPU but the guest system's task manager said that the virtual machine was using a bit more than 50% so LO was using 50% of the real processor again.

![Screenshot](https://cloud.githubusercontent.com/assets/28926242/26735758/925e7a28-47c3-11e7-8d82-b10835419fbe.png)

**Comment by cmurf** [comment]
See also.
https://bugs.documentfoundation.org/show_bug.cgi?id=107970

I've attached strace, and some proc pid info. That's all based on Fedora 26 which has flatpak-0.9.4-1.fc26.x86_64.

**Comment by kotlinlearner** [comment]
Yes, I think that this is the same bug.
Thank you very much for your help!
Shall I close this issue then? Apparently it is LO's bug and not Flatpak's.
