### ISSUE TITLE
Graphical front-end to manage apps

### ISSUE THREAD

**Issue by Hocceruser** [flatpak/flatpak#859]
I would like a graphical front-end (GUI) to manage the flatpak apps, similar to the Android app settings.
Some ideas for it:

- list installed flatpak apps and show information about it

- update flatpak apps and maybe even install them (from the list which is also presented on your website or by typing in the URL of the .flatpak or .flatpakref file)

- see what permissions a flatpak app is using and some day also manage which permissions the apps are allowed to use

Flatpak's goal is to be easy-to-use and distibution-independent. Therefore, a graphical front-end which is standardized over all distros is needed.

**Comment by TingPing** [comment]
`gnome-software` is the most mature frontend. It wouldn't be overly difficult to pull that logic out into a smaller app that doesn't manage traditional packages too but one could argue that is just duplicated effort with more limited results.

**Comment by matthiasclasen** [comment]
the kde appstore (discover ?) also has flatpak support nowadays.

**Comment by alexlarsson** [comment]
Yeah, there is also another one for papyros.

**Comment by Hocceruser** [comment]
I know there are front-ends for _some_ distros or desktops (mostly a package manager which already was there before) but others do not support Flatpak.
What I would like is a standardized front-end for _all_ distros.

What about TingPing's idea to use the existing program gnome-software? The best solution would probably be to separate gnome-software into three packages: a front-end, a package for Flatpak support and a package for traditional packages support. I do not know if this is very easy to realize (for example, are the gnome developers going to want this?) but I know that Eclipse works in about this way.

**Comment by TingPing** [comment]
`gnome-software` is already distro agnostic, it leverages packagekit for supporting many package managers.

**Comment by hughsie** [comment]
> are the gnome developers going to want this

We designed gnome-software from the start to support this. Endless uses gnome-software in "only flatpak" mode with no PackageKit support at all.

**Comment by Hocceruser** [comment]
There is another problem: My distro's repository (Linux Mint which is derived from Ubuntu) contains only gnome-software 3.20.1. Flaptaks are only supported with gnome-software 3.22 and newer. Of course I could install it via another ppa but it shows that you can't really rely on the repositorys of different distros.

This is why I think that if you consider gnome-software as the standard tool to manage Flatpak via a GUI you should also have it in your Ubuntu ppa and make it an install-recommend of Flatpak.

**Comment by hughsie** [comment]
> My distro's repository contains only gnome-software 3.20.1

Do you really think building a whole new application is less work than updating a package?

> You should also have [gnome-software] in your Ubuntu ppa

Maintaining a downstream version of a software center is a ton of work and not something really in the scope of the flatpak project. I think you just need to get Linux Mint to update gnome-software.

**Comment by fenryxo** [comment]
Well, I used to recommend GNOME Software for flatpaks until I realized [how buggy it is](https://github.com/tiliado/nuvolaruntime/wiki/GNOME-Software#bugs). Don't get me wrong, I like GNOME Software, but I just cannot recommend it when WebKitGTK crashes because GNOME Software forgot to install nvidia GL extension.

**Comment by TingPing** [comment]
@fenryxo So we fix these issues, the same issues would happen in another `libflatpak` frontend...

**Comment by alexlarsson** [comment]
Bugs will be in any software, and most definately more of them if someone started over from scratch...

**Comment by diazbastian** [comment]
I know it's a closed ticket, but I think it makes all the sense in the world. A graphical application makes the end user's life easier and when talking about a "universal" distribution system applies to software that doesn't depend on the implementation of third parties.

For example, many distros offer their own software stores and can't always or want to include support for Flatpak like the Solus Software store and installing another software store -with everything that implies- is not attractive. Stores like KDE Discover or GNOME Software are fine, but in many cases they do more things than the user need, they feel very heavy and drag libraries of their desktop environment (something additional for environments like lxde, xfce, etc) or have problems that will not be resolved as soon as in [this case](https://bugs.launchpad.net/ubuntu/+source/gnome-software/+bug/1716409), which worsens the user experience.

Something like GDebi or [Eddy](https://github.com/donadigo/eddy) would be ideal, simple and lightweight to install with a couple of clicks Flatpak bundle or * .flatpakref downloaded from the web and only include the flathub repository to see a list of available applications. In my opinion, this would help to massify the use of applications in flatpak format, especially for users without much knowledge in the terminal and without obliging in many cases, to install something like gnome-software when a user can be happy with his favarite software manager (eg pamac).

**Comment by TingPing** [comment]
@diazbastian All of this logic is split into its own libraries, `appstream-glib` and `libflatpak` so it genuinely isn't that difficult to do and I'm sure some communities would value that work. It doesn't necessarily need to be a blessed project under flatpak though.

**Comment by diazbastian** [comment]
@ting I understand, although in my argument it is clear that the implementation of third parties doesn't work well, then why not at least add a label "Help is needed" or something similar in this ticket?

**Comment by TingPing** [comment]
> why not at least add a label "Help is needed" or something similar in this ticket?

Well because that implies this project wants help. I don't think `flatpak` wants any frontend beyond the cli one. Admittedly I don't know of a better place to open this discussion but maybe other software projects like xfce would want a minimal graphical manager?

**Comment by diazbastian** [comment]
> Well because that implies this project wants help. I don't think flatpak wants any frontend beyond the cli one

Ok, I understand, but I will give my point of view on the subject.
Although it is not part of the direct objectives of the project, it is not attractive for third-party developers that a "universal" distribution system only offers a CLI, since that implies that the user must have certain knowledge about the terminal, something that I believe it should be decreased (especially with flatpak the learning curve is greater than a traditional package manager or other alternatives like Snap or AppImages IMHO). The facilities of a universal distribution system should be for both the developer side and the user side to work.

> Admittedly I don't know of a better place to open this discussion but maybe other software projects like xfce would want a minimal graphical manager?

That would imply that XFCE only chose Flatpak to distribute desktop applications, directing their efforts for it, something I doubt, because usually a DE wants its software to be available by all possible means, similar to how the KDE project has expressed it.  

I admit that it is complicated to do something like this considering the few resources, especially when the efforts are directed to another place and that is fine, but being that the perspective is incomplete not considering this. The panorama doesn't change much for many users who previously had to resort to the terminal following instructions to run an *.sh file, run a *.bin or compile a tarball.

**Comment by TingPing** [comment]
> That would imply that XFCE only chose Flatpak to distribute desktop applications

Not necessarily. All of the major DEs have their own software store, small ones like xfce are the only one left who would be interested in something like this IMO.

**Comment by diazbastian** [comment]
> Not necessarily. All of the major DEs have their own software store, small ones like xfce are the only one left who would be interested in something like this IMO.

I wish it were that simple, but it is not. Only 2 DEs offer their own software stores, on the other hand, many distributions also offer their own well-integrated software stores. I don't think this situation is comparable to the search for a Wayland compositor, where small projects have to find their own solutions, as I said before, this is about the end user.
Why the flatpak project would not be interested in offering a "universal" graphic tool to install flatpak packages? It is not necessary that you answer the question.

**Comment by TingPing** [comment]
>  Only 2 DEs offer their own software stores

Solus and Mint have their own stores. KDE and GNOME have their own. That honestly covers a huge portion of users with xfce probably being the largest group not covered.

@diazbastian I'll play around with making a simple graphical frontend, I don't expect it to be that large and from there we can see.

**Comment by TingPing** [comment]
@diazbastian I can't help but feeling as I'm making this that it exactly duplicates GNOME-Software which got most things right, it just happens to come with traditional package management functionality too..

**Comment by hughsie** [comment]
Note, you can disable the packagekit functionality in gnome-software and make it 100% flatpak/snap -- for instance this is similar to what endless does.

**Comment by TingPing** [comment]
@hughsie It is a build time flag though, so if using a distro package a user cannot simply get a minimal gnome-software to just handle installing `.flatpakref` files.

**Comment by hughsie** [comment]
Depends on how mutable your `/` is... you can just delete the plugins in `/usr/lib64/gs-plugins-11/libgs_plugin_packagekit*.so`

**Comment by diazbastian** [comment]
> Solus, Mint, Deepin, and Elementary have their own stores. KDE and GNOME have their own. That honestly covers a huge portion of users with xfce probably being the largest group not covered.

Sure, but the point is that KDE Discover and GNOME Software are supposed to be the "distro-agnostic" alternatives. In the gnu/linux ecosystem there are more software stores distributed like Feren OS or even specific stores such as Nitrux OS that uses only AppImages, etc. This shows the great diversity and a great effort so that the developers of these systems include support for Flatpak in their stores (I proposed it naively for [my favorite software manager](https://github.com/timlau/yumex-dnf/issues/124)). Many other distros use a more traditional system to obtain and update software.

> I can't help but feeling as I'm making this that it exactly duplicates GNOME-Software which got most things right, it just happens to come with traditional package management functionality too.

I appreciate your good intentions, but I think the approach is very different. It's not about duplicating a software store (the model that uses GNOME-Software), but a classic software manager, like synaptic but simpler, that's why I mentioned the examples as GDebi or Eddy . @Hocceruser used a good metaphor mentioning Android, since it allows a very basic administration of software independently of the software store used in the system. Considering that most applications offer a *.flatpakref file that can be downloaded as a flathub from the web, a supposed graphical application would not have the need to show software available from a repository.  

Thanks for listening.

**Comment by Louny** [comment]
I really don't understand the negative and unsupportive comments the OP received. Currently this issue is somewhat blocking me to implement flatpak into my corporations Linux client infrastructure. There seem to be no projects understanding that some need this to be as simple as possible. In the same moment that flatpak delivers easy to install and easy to maintain apps, it's asks users to install them via the terminal.

**Comment by TingPing** [comment]
@Louny I mean, I looked into it and my genuine conclusion was "Well `gnome-software` already got this right". It can be built without all other backends and just manage Flatpaks if so desired.

**Comment by ManIVIctorious** [comment]
I am sorry to hijack this thread, but IMHO the most important part of the proposal hasn't been considered at all (the third point). I wouldn't consider installation and updating as very complicated but there is one big ticket all current graphical user interfaces are lacking:

I would really like to see an app like a "flatpak manager", which could list all installed flatpaks and would allow to manage their permissions (e.g. after clicking on the app). It would also be very nice it this would allow to set the used runtime and flatpak-extensions. E.g. this could enable the user to select a preferred gtk theme while more than one are installed.
Additionally a page showing all available permissions and which applications are using them would be highly appreciated.

I personally don't have any objections against the terminal and use it very often, but especially for the above mentioned points it is not very clear/discoverable

**Comment by TingPing** [comment]
> E.g. this could enable the user to select a preferred gtk theme while more than one are installed.

Well that has nothing to do with Flatpak, that is what `gnome-tweaks` or whatever sets. Flatpaked themes are just data it has nothing to do with settings.

> allow to manage their permissions

Been on the todo list of `gnome-software` for a while and indeed would be nice.

**Comment by jingle0927** [comment]
https://github.com/zwpwjwtz/FlatpakBuilder-qt

**Comment by matthiasclasen** [comment]
Most of these things (managing permissions) will be addressed soon in gnome-control-center and gnome-software.

See https://gitlab.gnome.org/GNOME/gnome-control-center/issues/230
and https://gitlab.gnome.org/GNOME/gnome-software/merge_requests/154

**Comment by aiamuzz** [comment]
I'am happy this conversation is taking place finally ...

a graphical flapak store is long overdue ... and the lack of one limits flatpak usage only to those linux users who are comfortable with working on the terminal.

I know this would elicit a response saying linux users almost all of them will be terminal literate ... if so then i would say that's a thing of the past !!!

After android/ios has picked up ... users by the hordes have turned computer literates overnight ... this android/ios generation now know that all they require is a device, a web browser, a file manager and apps( that do specific tasks) to run on a device ... which is the very definition of a computer.

This android/ios ecosystem has spawned new age linux distros that have adopted its UI/UX design ... and they are really catching on ... distro's like elementary, deepin, etc ... and this for the android/ios generation is a feeling of home only on a different league of device(which are full fledged computers)

**One cannot deny that the success of the android/ios ecosystem is only for their app stores** ... remember symbianOS ... they did not have a store ... but hey did have apps scattered all over the internet ... as a result those apps were within reach of only 'the brave' ... those that could scour the internet, discover and manually  downloaded and installed them on the symbianOS(i happened to be one of them ... believe me without a dedicated user friendly store its quite an effort finding apps and getting them on your symbian phones) ... i remember i had 5-8 other  symbian users besides me and none had apps beyond the preinstalled one's that came with their symbian phones) 

Currently i term flatpak / flathub in its 'CLI only' existence/attitude as those akin to symbian phones ... all these efforts of so many people being limited only to a few terminal literate's !!! **A wrong decisions for sure !!!** 

Its time for linux to shed their prejudices and open the flood gates to the users(hordes as i call them) who come from the ... **device - web browser - app store - that helps them get their job done !!!**

Hope to see a GUI flathub appstore soon ... from the conversation i can see we do have some options to jump start on this idea !!!

**Comment by aiamuzz** [comment]
> GNOME Software and KDE Discover have both supported Flatpaks for a while already.

@kirbyfan64 ... i know ... so does deepin store, they to have flatpak apps supported in it ... but these are all fragmented across distro's ... with some apps here and some apps there ... and this has its own flip sides ... i don't know about GNOME and KDE software stores but deepin has flatpak apps that can be counted on ones fingers ... 

i don't understand the flatpak teams push back or lack of seeing the need for a graphical frontend that we all see ... i am not discounting the fact that its an open source contribution based model that is resource thin ...

but a graphical frontend to manage everything the CLI does is a an undeniable requirement even if its later ... it has to see the light some day ... in the least it should be set as a necessary milestone instead of being termed as unnecessary  !!!

Just like how flatpak/flathub considers upstream involvement as the right way for app developer to adopt flatpak ... a graphical frontend for flatpak management connected to flathub by the flapak upstream will be the right way and can never be compared with the efforts of captive units found currently on KDE, GNOME or Deepin ... These units will always be a piece of the pie ... but never be the whole pie !

**Comment by aiamuzz** [comment]
anyways ... the strongest of argument has already been made by @diazbastian `https://github.com/flatpak/flatpak/issues/859#issuecomment-354920431` ... @alexlarsson ... seems to agree on [this](https://github.com/flatpak/flatpak/issues/859#issuecomment-311596977) ... and @hughsie seems to be suggesting a possible course [here] ...(https://github.com/flatpak/flatpak/issues/859#issuecomment-355110767) which supports/factors in alex's belief ... and ...  for a split second a flickering ray of hope seems to shin in from @TingPing [here ](https://github.com/flatpak/flatpak/issues/859#issuecomment-355094686) ...

@matthiasclasen ... has already been putting lot of sweat and blood on the CLI UI/UX ...

if only @TingPing ... worked on the flicker of hope and gave a shot at a grahical frontend to manage flatpak ... things could lead to a bright future for flatpak ecosystem !!!

**Comment by matthiasclasen** [comment]
If you want to work on a graphical flatpak frontend, that is your call.

The graphical frontends that we are working on have already been mentioned. You say they are fragmented, but then you suggest to add yet another. Not sure how that will make the fragmentation problem any better

**Comment by aiamuzz** [comment]
> If you want to work on a graphical flatpak frontend, that is your call.
this is exactly that will lead to more fragmentation ...

> The graphical frontends that we are working on have already been mentioned.
Oh you are doing this ? ... then that would end this discussion ... i seem to have missed the part where you've agreed on a graphical frontend (i hope you are not referring to the CLI UI/UX developement) 


> You say they are fragmented, but then you suggest to add yet another. Not sure how that will make the fragmentation problem any better

You may not be right ... on the fragmentation problem especailly if you(flatpak upstream) ventured into creating one ...any graphical frontends(non-CLI) you and your team make will never be fragmented ... in fact it will be the opposite ... it will consolidatory ... you forget your are the creators/makers of flatpak ... 

Any flatpak'd application would like to be hosted on your infrastructure first ... as a result the largest collection will be yours ... your will be anything but fragmented.

**Comment by matthiasclasen** [comment]
You're misunderstanding... I am GNOME

**Comment by teohhanhui** [comment]
GNOME Software has issues on Arch Linux, for example: https://wiki.archlinux.org/index.php/GNOME/Tips_and_tricks#Prevent_GNOME_software_from_downloading_updates

And its usefulness is doubtful when one is already using a graphical package manager like Pamac.

**Comment by matthiasclasen** [comment]
Nobody is stopping you from adding flatpak support to pamac. Just like we did to gnome-software and Discover

**Comment by mwleeds** [comment]
> I am sorry to hijack this thread, but IMHO the most important part of the proposal hasn't been considered at all (the third point). I wouldn't consider installation and updating as very complicated but there is one big ticket all current graphical user interfaces are lacking:
> 
> I would really like to see an app like a "flatpak manager", which could list all installed flatpaks and would allow to manage their permissions (e.g. after clicking on the app). It would also be very nice if this would allow to set the used runtime and flatpak-extensions. E.g. this could enable the user to select a preferred gtk theme while more than one are installed.
> Additionally a page showing all available permissions and which applications are using them would be highly appreciated.
> 

There is now a graphical application for managing flatpak permissions: https://flathub.org/apps/details/com.github.tchx84.Flatseal

**Comment by cayers71** [comment]
GUI for Flatpak - https://github.com/vinifmor/bauh

**Comment by mwleeds** [comment]
> GUI for Flatpak - https://github.com/vinifmor/bauh

Wow, looks like the implementation calls out to the Flatpak CLI for pretty much everything. I guess that's one way to maintain consistency with it! 😆

**Comment by tchx84** [comment]
> There is now a graphical application for managing flatpak permissions: https://flathub.org/apps/details/com.github.tchx84.Flatseal

To clarify, Flatseal only-goal is to provide the ability to manage permissions in a way that is accessible to _everyone_ by being independent of desktop environment and Linux distribution, just like any other Flatpak app.

I have made it very clear that Flatseal is not, and will not be, yet-another flatpak apps manager.

**Comment by ChrTall** [comment]
@mwleeds 
Could you explain how you would do that better instead? I always thought that GUI Frontends for Package Managers use the execute the CLI with Params if no library is available.
Or does Discover and Gnome Software use a common library that is also used by the apt / dnf CLI ?

**Comment by smcv** [comment]
> I always thought that GUI Frontends for Package Managers execute the CLI with Params if no library is available.

If there was no library available then they would have to, but Flatpak *does* provides a shared library, `libflatpak.so.0`. GNOME Software and Discover both use it.

The `flatpak` command-line tool is still necessary for *running* Flatpak apps (which is not part of the library for various reasons), but its package-manager-style functions like `flatpak install` will call into the same code that the library does (for technical reasons it's statically linked into the `flatpak` CLI tool rather than using the shared library).

>  Or does Discover or Gnome Software use a common library that is also used by the apt / dnf CLI ?

System-level package managers need to have a separation between the part that runs as root and the part that runs as an ordinary user, but they do this via IPC to the PackageKit service, not by running the `apt` tool. On apt systems, `apt` and PackageKit are both frontends for the `libapt-pkg` library. I don't know about dnf but I'm sure it's very similar.

**Comment by thierrybo** [comment]
> > GUI for Flatpak - https://github.com/vinifmor/bauh
> 
> Wow, looks like the implementation calls out to the Flatpak CLI for pretty much everything. I guess that's one way to maintain consistency with it! laughing

There is also App-outlet
https://github.com/app-outlet/app-outlet
