### ISSUE TITLE
No download of GL extension when installing runtime from a repository other than the gnome one

### ISSUE THREAD

**Issue by ghismary** [flatpak/flatpak#861]
I have a machine with proprietary nvidia driver:
`$ flatpak --version`
`Flatpak 0.8.5`
`$ flatpak --gl-drivers`
`nvidia-340-102`
`default`
`host`

If I add the gnome repository and install org.gnome.Platform runtime, the org.freedesktop.Platform.GL32.nvidia-340-102 runtime gets installed automatically as expected:
`$ flatpak --user remote-add --from gnome https://sdk.gnome.org/gnome.flatpakrepo`
`$ flatpak --user install gnome org.gnome.Platform//3.24`
`Installing: org.gnome.Platform/x86_64/3.24 from gnome`
`Installing: org.freedesktop.Platform.GL.nvidia-340-102/x86_64/1.4 from gnome`
`Installing: org.gnome.Platform.Locale/x86_64/3.24 from gnome`

However, if I add the gnome repository and the kderuntime one and install the org.kde.Platform runtime (that is based on the org.freedesktop.Platform runtime), without having installed the org.freedesktop.Platform or org.gnome.Platform runtimes, then the org.freedesktop.Platform.GL32.nvidia-340-102 runtime is not installed automatically:
`$ flatpak --user remote-add --from gnome https://sdk.gnome.org/gnome.flatpakrepo`
`$ flatpak --user remote-add kderuntime --from https://distribute.kde.org/kderuntime.flatpakrepo`
`$ flatpak --user install kderuntime org.kde.Platform//5.9`
`Installing: org.kde.Platform/x86_64/5.9 from kderuntime`
`Installing: org.kde.Platform.Locale/x86_64/5.9 from kderuntime`

It looks like the extension is not found if it is not available in the repository the current runtime is being installed from, even if the repository where it is located is in the list of remotes.

**Comment by alexlarsson** [comment]
Yeah, this is intentional, because we might have a lot of repositories configured, with not necessarily the same level of trust. Automatically installing a gl driver affecting every app just because you installed some 3rd party app from some 3rd party repo isn't a great idea.

It begins to be problematic when kde/gnome runtimes inherit from the freedesktop runtime though...

**Comment by ghismary** [comment]
The KDE runtime is just an example. My specific case regards the flatpak package of Linphone. I have created my own runtime based on the freedestkop runtime, but when I install it the GL driver does not get installed automatically.
This is not really acceptable for the user to install explicitely the freedesktop runtime before installing the Linphone application just for the GL extension to get installed.
My point of view would be that the freedesktop repository should be configured and trusted by default in flatpak and if some 3rd party repo relies on some freedestkop runtime they get installed correctly since they are trusted.
What would you suggest for me to solve this issue of users not being able to run the application because the GL extension did not get installed automatically?

**Comment by alexlarsson** [comment]
Why did you feel the need to create a runtime just to package an app? That is generally the wrong thing to do. For example, are you going to do continious security updates on that, in case of e.g. glibc CVEs?

**Comment by alexlarsson** [comment]
I sort of agree with the general issue of where to install extensions from though, but it has to be considered carefully, because it is hightly security sensitive.

**Comment by ghismary** [comment]
Ok, I am no longer creating my own runtime as this is not really necessary. Depending directly on the org.freedesktop.Platform runtime triggers the installation of nvidia driver when installing the application. So, problem solved for my specific use case. Thanks Alex!

**Comment by cmollekopf** [comment]
I'm a bit confused on how this should be handled. I'm building my own runtime too (it's basically a stripped down KDE runtime), and just received the first reports of the flatpak not working with nvidia.
As I understand this issue will persist no matter if I use the KDE runtime or my own. Is there any way I can fix it in my own repo with my own runtime? Or would you rather suggest to just use the freedesktop runtime directly and just building a giant application instead (qt and stuff)?

Also, for the time being, the workaround seems to be manually installing org.gnome.Platform ?

Thanks for any advice

**Comment by alexlarsson** [comment]
@cmollekopf Why are you creating your own runtime? That is almost never a good idea. It essentially turns you intro a distribution maintainer that has to do regular security updates to glibc and whatnot. Its not like your app will be smaller than if you just bundled qt anyway unless a lot of other apps use your runtime too.

But yeah, i think the origin issue is a real problem that has to be fixed.

**Comment by alexlarsson** [comment]
Here is the problem. Suppose you install the freedesktop runtime from flathub.org. This depends on e.g. a matching nvidia extension, which will be downloaded automatically from the same repo.

Suppose it downloaded gl drivers from *any* configured remote. Then, you want to play some game, so you add a remote that has it. Now, that remote might contain a custom nvidia driver version, which will be auto-downloaded and installed, and used for all apps that use the freedesktop runtime. This lets one repo control what code gets executed in essentially all apps. This is not great in terms of security, to say the least.

**Comment by cmollekopf** [comment]
Right, I initially did it because I started out with the kde runtime. But yeah, it occurred to me as well that just stuffing everything into the app would make more sense for this case. As far as I understand you that would also solve the nvidia driver problem (If I just directly depend on the freedesktop runtime and have everything else in the app) ?

As for the source problem; I should be able to host my own runtime and point to the relevant extension from another repo, just like I can for runtimes. If the extension also comes from my repo, then so be it I guess. That's just as legitimate as me providing a custom rpm for some library of the system. It's perfectly possible that this will end up breaking stuff, but that's really up to the person creating that repo then.

**Comment by alexlarsson** [comment]
Yes, you can just use the freedesktop runtime, and that will pick up the correct driver.

I guess if the runtime itself points to the "extension origin" then we're safer in the sense that only apps using that runtime will use the extensions, and it was vet:ed by the runtime author.

**Comment by cmollekopf** [comment]
Alright, thanks for the guidance =)
Yes, If only apps using that runtime end up using the same extension then that that solution is IMO exactly how it should work.

**Comment by cmollekopf** [comment]
@alexlarsson There is one more caveat with bundling the bulk of the libraries with the application though. Wouldn't this imply that if I create multiple versions of the flatpak (e.g. stable one and an unstable one), that each one would have to bundle all of the libraries? And isn't that the problem that the runtime system is solving? And if that's the case, why should I don't be building my own runtime (It's still based on the freedesktop one, so I should get those updates for free)?

**Comment by alexlarsson** [comment]
@cmollekopf No, the runtime is solving the problem of making application developers not have to maintain lowlevel core distribution stuff, making it possible to share that work among the community. Deduplication is solved by using ostree, see my recent blog post.

Basing your runtime on another runtime doesn't automatically solve your updates (although it does make it easier), you still have to monitor the base runtime and rebuild and push timely releases of your runtime when the base changes.

**Comment by cmollekopf** [comment]
While the deduplication by ostree is certainly helpful, it's more incidental that this happens to work when building separate versions of the same app. I think in my case it would be much better if I had a layer containing the libraries (which I rarely touch), and then a layer for the app (possibly with different versions). That way the deduplication is explicit. I would also prefer this because of the change management. It makes it abundantly clear which part is changing and which stays the same, and avoids running into a situation where different apps have subtle changes in the stack.

Anyhow, I have adjusted per your suggestion and am now building qt as part of the flatpak on top of the freedesktop runtime, which seems to work fine. I might revisit that change if better support for third party runtimes becomes available.

Thanks a lot for all the input provided.

**Comment by eszlari** [comment]
Is this related to https://github.com/flatpak/flatpak/issues/3094 ?
