### ISSUE TITLE
Bumblebee (optirun, primusrun) doesn't work with Flatpak

### ISSUE THREAD

**Issue by doraskayo** [flatpak/flatpak#869]
I've been testing the new Steam Flatpak with my Optimus setup, and I ran into a some issues. Most importantly, couldn't get it to play well with Bumblebee (either optirun or primusrun). Obviously, the sandboxed Steam doesn't have access to the primusrun or optirun executables, so I couldn't use the [official trick](https://support.steampowered.com/kb_article.php?ref=6316-GJKC-7437) of changing the games' launch settings to use `primusrun %command%`. So I tried the other trick that normally works; running Steam itself using optirun or primusrun, and expecting games that it launches to "inherit" the use of the discrete card. For that, I used `optirun -b primus flatpak run com.valvesoftware.Steam`. However, to my disappointment, it didn't work at all. In fact, Steam itself didn't seem to use the discrete GPU either, not just games. I confirmed this using the `org.freedesktop.GlxInfo` Flatpak.

I've ran quite a few commands in sequence and logged their output, in hopes it would help identify the issue. Let me know if you need me to test anything or run any other commands.

``` shell
[user@hostname ~]$ glxinfo | grep "renderer string"
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile
 
[user@hostname ~]$ primusrun glxinfo | grep "renderer string"
OpenGL renderer string: GeForce GT 750M/PCIe/SSE2
 
[user@hostname ~]$ optirun glxinfo | grep "renderer string"
OpenGL renderer string: GeForce GT 750M/PCIe/SSE2
 
[user@hostname ~]$ optirun -b none glxinfo | grep "renderer string"
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile
 
[user@hostname ~]$ optirun -b primus glxinfo | grep "renderer string"
OpenGL renderer string: GeForce GT 750M/PCIe/SSE2
 
[user@hostname ~]$ optirun -b virtualgl glxinfo | grep "renderer string"
OpenGL renderer string: GeForce GT 750M/PCIe/SSE2
 
[user@hostname ~]$ flatpak --version
Flatpak 0.9.6
 
[user@hostname ~]$ flatpak --gl-drivers
default
host
 
[user@hostname ~]$ primusrun flatpak --gl-drivers
default
host
 
[user@hostname ~]$ optirun flatpak --gl-drivers
nvidia-381-22
default
host
 
[user@hostname ~]$ optirun -b none flatpak --gl-drivers
nvidia-381-22
default
host
 
[user@hostname ~]$ optirun -b primus flatpak --gl-drivers
nvidia-381-22
default
host
 
[user@hostname ~]$ optirun -b virtualgl flatpak --gl-drivers
nvidia-381-22
default
host
 
[user@hostname ~]$ flatpak run --command=bash org.freedesktop.GlxInfo
bash-4.3$ glxinfo | grep "renderer string"
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile
bash-4.3$ exit
exit
 
[user@hostname ~]$ primusrun flatpak run --command=bash org.freedesktop.GlxInfo
bash-4.3$ glxinfo | grep "renderer string"
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile
bash-4.3$ exit
exit
 
[user@hostname ~]$ optirun flatpak run --command=bash org.freedesktop.GlxInfo
ERROR: ld.so: object 'libdlfaker.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libvglfaker.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libdlfaker.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libvglfaker.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
bash-4.3$ glxinfo | grep "renderer string"
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile
bash-4.3$ exit
exit
 
[user@hostname ~]$ optirun -b none flatpak run --command=bash org.freedesktop.GlxInfo
bash-4.3$ glxinfo | grep "renderer string"
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile
bash-4.3$ exit
exit
 
[user@hostname ~]$ optirun -b primus flatpak run --command=bash org.freedesktop.GlxInfo
bash-4.3$ glxinfo | grep "renderer string"
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile
bash-4.3$ exit
exit
 
[user@hostname ~]$ optirun -b virtualgl flatpak run --command=bash org.freedesktop.GlxInfo
ERROR: ld.so: object 'libdlfaker.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libvglfaker.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libdlfaker.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libvglfaker.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
bash-4.3$ glxinfo | grep "renderer string"
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile
bash-4.3$ exit
exit
```
```
OS: Arch Linux (25.6.17)
mesa: 17.1.3-1, lib32-mesa: 17.1.3-1
nvidia: 381.22-3, lib32-nvidia-utils: 381.22-1
bumblebee: 3.2.1-15
bbswitch: 0.8-68
primus: 20151110-7, lib32-primus: 20151110-3
virtualgl: 2.5.2-2, lib32-virtualgl: 2.5.2-2
flatpak: 0.9.6-1

Flatpak refs:
app/com.valvesoftware.Steam/x86_64/stable/07159702acb4770ea36d308748413e4ce27cd11f394e5a18c022a31a46864194
app/org.freedesktop.GlxInfo/x86_64/1.6/1b4e06c3d31be07894dd017011b7f1e11e978e807c71b32a3f808a6f844db0b6
runtime/org.freedesktop.Platform/x86_64/1.6/d59ac3d34995954d531c7027e6d62e0a350a29ae48fea4c4733ee26ab5a03957
runtime/org.freedesktop.Platform.GL.nvidia-381-22/x86_64/1.4/d62a785a5b8052cd8f87a381d5119d3fb6ae45424add71d86ef93fdaf23e79ed
runtime/org.freedesktop.Platform.GL32.nvidia-381-22/x86_64/1.4/aeebe06952b89df4064fe6c4cf61198aa26938238acadeb8b308e01f35ad678c
```

**Comment by alexlarsson** [comment]
Yeah, this clearly requires some research and work.

**Comment by GeorgesStavracas** [comment]
Recently I tried to run Steam with `DRI_PRIME=1`. I dropped into a Flatpak terminal:

`$ flatpak run --command=bash com.valvesoftware.Steam`

And ran:

`$ DRI_PRIME=1 /app/bin/steam`

Thre result was quite unexpected:
```
Couldn't find dpkg, please update steamdeps for your distribution.
Running Steam on org.freedesktop.platform 1.6 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
Installing breakpad exception handler for appid(steam)/version(1508910373)
libGL error: unable to load driver: nouveau_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: nouveau
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
```
MESA and Nouveau are part of the Freedesktop Platform. Indeed, I can find these files here:

```
$ ls /usr/lib/dri/
dummy_drv_video.so  i965_drv_video.so	nouveau_dri.so	      r200_dri.so  radeon_dri.so     swrast_dri.so
i915_dri.so	    intel-vaapi-driver	nouveau_vieux_dri.so  r300_dri.so  radeonsi_dri.so   vdpau_drv_video.so
i965_dri.so	    kms_swrast_dri.so	nvidia_drv_video.so   r600_dri.so  s3g_drv_video.so  vmwgfx_dri.so
```

**Comment by TingPing** [comment]
I mentioned similar problems to @valentindavid, I believe he found some solution.

**Comment by stratus-ss** [comment]
I'm quite interested in a solution for this as well. I am willing to help test

**Comment by Xiaoming94** [comment]
What is the status of this issue right now?

**Comment by JeffLabonte** [comment]
I am willing to help test as well!

**Comment by jenrik** [comment]
I have looked into getting bumblebee with primus as bridge to work with flatpak and this is what I have found so far. Bumblebee start a secondary X server, refered to as the accelerated X server, that has the the dedicated GPU loaded. When a program is loaded using `primusrun` or `optirun -b primus` it is started with the environment variable `LD_LIBRARY_PATH` set to point to the primus GLX wrapper library. The wrapper redirect GLX calls to the secondary X server and copies back the result to the primary X server, refered to as the displaying X server.

In order for primus to function we need to expose both the primary and secondary X server inside a flatpak such that things can be render on the secondary and copies over to the primary. Also the primus GLX wrapper library must be available inside the flatpak in order for it to be able to do anything. I think that can be done by creating a version of the `org.freedesktop.Platform.GL.nvidia-*-*` that additionally have the primus library. I'm not sure if the drivers for the integrated/primary GPU is needed, they might be necessary in order copy the rendered frame over to the primary X server.

Also bumblebee starts and stops the secondary X server on demand in order to save power. Primus signals the bumblebee daemon using a control socket so ideally we also have to expose that socket inside the flatpak. The control socket doesn't have to be exposed inside the flatpak by then we have to signal the daemon in another way, or disable the starting and stopping of the secondary X server by setting `KeepUnusedXServer=true` in `bumblebee.conf`.

Also I don't think the solution to get the virtualgl bridge to work is gonna be different from the solution to getting primus working.

**Comment by jenrik** [comment]
I have managed to monkey patch the secondary X11 server socket, the bumblebee daemon socket and primus' `libGL.so.1` into `org.freedesktop.GlxInfo`, where it succesfully ran `primusrun glxgears -info` and reported to render on my nvidia graphics card.
I tried the same on `com.valvesoftware.Steam` but that failed because the graphics libraries are arranged in a seemigly non-standard way. That should be fixable either by rearranging the graphics libraries, or configuring primus differently.
Also I need to have primusrun running outside the flatpak to start the secondary X11 server and have it create a socket that i can `bwrap --ro-bind` into the flatpak. A suboptimal solution to this might be to set `KeepUnusedXServer=true` in `bumblebee.conf`.

**Comment by jenrik** [comment]
`com.valvesoftware.Steam` is now succesfully running games using primus in my monkey patched setup. The trick to getting it to work was setting `PRIMUS_libGLa` and `PRIMUS_libGLd` in `primusrun` to the path of `libGL.so.1`.
The following games has been tested working

- Half-LIfe 2: Lost Coast
- Super Hexagon
- Team Fortress 2
- The Talos Principle (no noticeable performance difference)

I realized that both a 32 and 64 bit version of primus is needed to support all games.

**Comment by jenrik** [comment]
@tuxofil I have written a rough, WIP, and yet untested guide: https://gist.github.com/jenrik/f25946e9a023187fe4b391099853a3a7

**Comment by leinardi** [comment]
Hi, is there any news about this issue? This is currently affecting also [GWE](https://flathub.org/apps/details/com.leinardi.gwe).

**Comment by wallena3** [comment]
Hi, is there any news about this issue?

**Comment by saif-ellafi** [comment]
Hi, this issue still alive. I hope there exists interest in solving this problem.

**Comment by jenrik** [comment]
NVIDIA has officially released support for PRIME in their driver. This obsoletes the need for Bumblebee, and I there for no longer have any intention on working on Bumblebee support in Flatpak.
http://us.download.nvidia.com/XFree86/Linux-x86_64/435.21/README/primerenderoffload.html
Do be aware that as of writing this a lot of distros are shipping the latest long lived branch of the NVIDIA driver that doesn't yet have the new PRIME support, and that the required patches to Xorg probably isn't yet prevalent in packaged versions of the Xorg display server.

**Comment by MateusRodCosta** [comment]
Just tested the new PRIME Render Offload with Flatpak on Arch Linux.

With dolphin-emu I was able to: run without PRIME and dolphin-emu would detect the Intel iGPU on OpenGL and run with PRIME and dolphin-emu would detect the NIVIDA dGPU when running on OpenGL.
When selecting the Vulkan adapter, whether running with PRIME or not, both cards would appear as options.

So, IMO, this should be closed.

It might be that 435.21 is needed both on the host and on the runtimes though.

**Comment by EliaGeretto** [comment]
@MateusRodCosta Is the power management working correctly, though? Have you checked with `powertop` or a similar tool? Given what's written [here](http://download.nvidia.com/XFree86/Linux-x86_64/435.21/README/dynamicpowermanagement.html), I am worried dynamic power management works only with a Turing GPU or newer.

**Comment by saif-ellafi** [comment]
At least on my side, with a MSI GS65, I can't get the offload to work (tried Fedora and now Ubuntu 19.10 with the `On-demand` prime option). None of them work, sitting down on the desktop just draws all the battery. Bumblebee is still the only reliable option, other than switching on and off the device with a restart (Ubuntu's prime-select)

**Comment by EliaGeretto** [comment]
@saif-ellafi Are you following [these](https://rpmfusion.org/Howto/Optimus) instructions?

**Comment by saif-ellafi** [comment]
Yes, I have tried but no success. GPU is just always on as soon as X starts. Those docs are quite confusing though, I am not an expert on the matter. But just upgrading Xorg and enabling the power management doesn't just do the trick. Forcing enable PRIME synchronization doesn't work either.

I'll try again once I hop back onto Fedora, for now I was trying to get Ubuntu's newest `On-Demand` to work. But it doesn't do anything either.

**Comment by theferrit32** [comment]
I have used the PRIME support now a part of the NVIDIA driver but I also experience the issue where the card is powered on at full throttle the entire time even if there's nothing really going on in the system.  It's an issue with NVIDIA's driver based on which card you have, and I honestly don't expect much of NVIDIA at this point.  I'm not anticipating a driver fix to come from them, as they don't seem to care.  And they won't let the community have source access to the driver either, so I've given up and now just disable the NVIDIA card permanently and use Intel graphics, which for me is acceptable for what I do.

**Comment by MateusRodCosta** [comment]
Ok, so yes, the Nvidia dGPU is turned on all the time. The main issue which is of "being able to run flatpak with Nvidia on Optimus systems" is fixed though.

I run a MX150, which is a Pascal card, so on my system it's on all the time.

About whether to turn off the GPU:

You could try using the info on http://us.download.nvidia.com/XFree86/Linux-x86_64/435.21/README/powermanagement.html , which might be useful or might be useless since it's about disabling the Nvidia card on suspending/hibernating and turning it back on on resuming. Of course, it's not guaranteed to work and awful things could happen.

You could try doing `echo suspend > /proc/driver/nvidia/suspend` and `echo resume > /proc/driver/nvidia/suspend` and hope that it, respectively, disables or enables the Nvidia GPU.

This seems to be enough to unload the driver, since using the first command makes the Nvidia card unavailable to both GreenWithEnvy and Nvidia Settings. I do not guarantee that it will actually put the GPU at a lower clock rate, power it off or not explode, it might do the opposite of any of these.

Note also that that mechanism is intended to be used by, for example, systemd and be aware, again, that's it is intended for actual system suspending/hibernating and resuming.

**Comment by Magicrafter13** [comment]
Adding to the list, the flatpak version of Zoom doesn't work when I switch to my discrete graphics. Only with hybrid (and presumably integrated as well).

**Comment by MateusRodCosta** [comment]
I believe this can be closed?

Nvidia's PRIME Render Offload works pretty much fine as long as you're using a recent Nvidia driver and recent Xorg. It is also properly supported under Wayalnd and flatpak.

**Comment by Mikenux** [comment]
@GeorgesStavracas: Given the last comment, can this be closed?
