### ISSUE TITLE
Is there any tutorial about building a qt program?

### ISSUE THREAD

**Issue by MeowSprite** [flatpak/flatpak#875]
I cannot find a tutorial about packing a qt program. There is only a tutorial to build gnome dictionary.
http://docs.flatpak.org/en/latest/flatpak-builder.html#manifests
and I find some examples in the flathub. But they are all qt4 programs, and compile the Qt library from the source code.
Is there any way to install the binary Qt liberary in the SDK runtime or flatpak building dictionary?
Can I install the deb or rpm package?
Thanks!

**Comment by Barthalion** [comment]
Qt is available in [KDE runtime](https://community.kde.org/Guidelines_and_HOWTOs/Flatpak#KDE_Runtime). Obviously KDE apps are using these, but also [Telegram](https://github.com/alexlarsson/nightly-build-apps/blob/master/org.telegram.desktop.json).

Additionally I have added qt5-base to Flathub's [shared-modules](https://github.com/flathub/shared-modules) as I needed it for [mGBA](https://github.com/flathub/io.mgba.mGBA), but it's temporary solution and doesn't include every Qt5 library under the sun.

**Comment by alexlarsson** [comment]
For Qt5, using the kde runtime is the best approach, unless you need a custom qt build.

**Comment by rahmanshaber** [comment]
sorry for interruption.
I am not in KDE.i run xfce-desktop.
I need to package a qt-5 app .But not finding any tutorial about that.

**Comment by AsavarTzeth** [comment]
The [official documentation](http://docs.flatpak.org/en/latest/) is in my opinion a good tutorial. Read that and use the KDE Runtime and Sdk, as is documented [here](http://docs.flatpak.org/en/latest/available-runtimes.html#kde).

**Comment by rahmanshaber** [comment]
thanks for your information .
but KDE runtime needs a huge package and my app is not using any KDE package.
i need a way to packaging it without KDE.

**Comment by AsavarTzeth** [comment]
I assume you don't know how de-duplication solves most of this? You might find this [blog post](https://blogs.gnome.org/alexl/2017/10/02/on-application-sizes-and-bloat-in-flatpak/) interesting.

You are pretty much assuming the user will never install any run runtimes, or at the very least no Qt app that uses the kde one.

Also, since pretty much all other Qt applications will use that runtime it will more than likely be installed. If you ship your own Qt packages you might actually increase the storage requirements for most users, contrary to your goal.

**Comment by zwpwjwtz** [comment]
What about this : https://github.com/zwpwjwtz/FlatpakBuilder-qt
