### ISSUE TITLE
Plans to have a flatpak version of VSCode

### ISSUE THREAD

**Issue by Veske** [flatpak/flatpak#891]
Are there any plans to have the VSCode as a Flatpak application?

**Comment by TingPing** [comment]
Fun fact, vscode already has flatpak support in their build system: https://github.com/Microsoft/vscode/blob/d8df161717157e82f536181e956914e92e169731/build/gulpfile.vscode.linux.js#L21-L41

I don't know of anybody hosting these though, maybe MS will at some point. There has been [some work](http://blog.manuq.com.ar/posts/building-electron-apps-offline-for-flathub/) getting Electron apps building on [Flathub](https://flathub.org) so that is a possibility in the future.  There is still a few rough edges I've encountered with Electron such as trash support being broken.

**Comment by matthiasclasen** [comment]
I don't think there is anything for us to do here.

**Comment by Veske** [comment]
@TingPing Slack is also an Electron app and not coming until the support is there?

**Comment by TingPing** [comment]
@Veske Slack is proprietary so it doesn't involve building from source and is just rebundling their binary, so it should be much easier to package for flathub if somebody is interested.

Looks like some already exists:

- https://github.com/endlessm/slack-flatpak
- https://github.com/mattdangerw/flatpak-slack-app

**Comment by Veske** [comment]
Thanks. Amazing system this Flatpak. Maybe I can learn it fast enough to package it my self for flathub.

Btw... You guys are responsible for the http://flatpak.org/apps.html page also?   Why does it suggest to add separate repos for all the apps there if they are all available from flathub also.

**Comment by TingPing** [comment]
> Why does it suggest to add separate repos for all the apps there if they are all available from flathub also.

Well few reasons:

- That page predates flathub even existing
- Flathub doesn't automatically generate `.flatpakref` links for us
- It is a bit awkward to use `.flatpakref` files for flathub as we want users to have that repo configured normally

So its a bit of a problem that indeed needs to be cleaned up.
