### ISSUE TITLE
allow remote add to succeed when offline

### ISSUE THREAD

**Issue by ramcq** [flatpak/flatpak#917]
Updating the metadata at the end of adding a remote (https://github.com/flatpak/flatpak/blob/master/app/flatpak-builtins-add-remote.c#L365) means that it fails if we're offline, even if we have the .flatpakrepo file available. Unlike the other error cases in this function, which mean the operation really has messed up, the remote is actually usable even if the metadata update fails, because future operations will grab the summary and any new metadata - so we should change this to a warning to allow the operation to succeed when we're offline.

**Comment by matthiasclasen** [comment]
turns out the patch is not effective (but harmless). lets keep the issue open until we've got this fixed for real

**Comment by ramcq** [comment]
Now also catching resolver errors - that seems to work better! :)

**Comment by pwithnall** [comment]
This seems to break the `test-repo.sh` unit test: if the repo metadata *can* be downloaded, but then signature verification fails, `flatpak remote-add` will still return success. I’m taking a look.

**Comment by pwithnall** [comment]
Handling this in https://github.com/ostreedev/ostree/issues/1064.

**Comment by cgwalters** [comment]
I still think it'd be better for us to expose an API that makes `GNetworkMonitor` useful for this; gnome-software could use that to be a lot more intelligent.

**Comment by ramcq** [comment]
Unconvinced cat... 🐱 I don't like the approach of trying to couch this very objective problem of distinguishing a permanent failure from a transient failure by making life harder for the API user and trying to paper over it with heuristics. In a scenario where OStree's network accesses could also be satisfied by USB devices, LAN fetches, etc, and years of my life lost to network junk like NAT traversal, firewalls, mesh networks, etc, my lasting reflection is that with networking, until you actually do the thing, you don't know if it's going to work...

**Comment by pwithnall** [comment]
ostreedev/ostree#1064 fixed this for the `test-repo.sh` use case. I agree with Rob in that we should be distinguishing between different classes of failure using error codes (that’s what error codes are for); but gnome-software should also be using `GNetworkMonitor` to affect its behaviour at a high level so that it doesn’t go and try things which obviously won’t work. It does already have code which uses `GNetworkMonitor`, but I haven’t looked at it so don’t know how much cleverness is going on there. In any case, that’s something to look at in the fuzzy future, in another task.
