### ISSUE TITLE
Fonts under `/usr/local/share/fonts` are not recognized

### ISSUE THREAD

**Issue by amtlib-dot-dll** [flatpak/flatpak#924]
`/usr/share/fonts` are mapped into `/run/host/fonts`, but other places where users may put their proprietary fonts is not accessible inside the sandbox, rendering that LibreOffice cannot use Lucida Console if users copied the font file from their genuine Windows copy to `/usr/local/share/fonts`. Thank you.

**Comment by wolfv** [comment]
I also believe that the fonts in ~/.fonts are not mounted which can be a problem if the theme is using a font from ~/.fonts which is not available in the system fonts folder.

**Comment by amtlib-dot-dll** [comment]
@wolfv No, they are

**Comment by TingPing** [comment]
@amtlib-dot-dll The specific flatpak might have home access which would make `~/.fonts` work just by chance.

**Comment by amtlib-dot-dll** [comment]
Sorry, I thought that you meant `~/.local/share/fonts` 🙁 

--------
Isn't `~/.fonts` deprecated?

**Comment by alexlarsson** [comment]
ATM only /usr/share/fonts and ~/.local/share/fonts OR ~/.fonts (first found) are exposed in /run/host, and configured in the runtime fontconfig configuration.  I realize fonts could be installed in all kinds of places on the host, but I don't think it makes sense to add all kinds of dirs there. If you really need a font you can always put it in your homedir.

**Comment by wolfv** [comment]
ok, tbh I didn't know that ~/.local/share/fonts is a thing. will put my fonts there and then everything will probably work as expected.

Thanks!

**Comment by amtlib-dot-dll** [comment]
@alexlarsson I used to put all fonts from my Windows copy under `/usr/local/share/fonts` and I have to move them to `/usr/share/fonts` now. I think that according to [FHS](https://refspecs.linuxfoundation.org/fhs.shtml), `/usr/local/share/fonts` is where they should stay.

**Comment by Bananaman** [comment]
Look at https://github.com/flatpak/flatpak/blob/main/common/flatpak-run.c

According to the `add_font_path_args()` function, Flatpak nowadays maps a lot of font directories, including:

- `/usr/share/fonts -> /run/host/fonts`
- `/usr/local/share/fonts -> /run/host/local-fonts`
- `~/.local/share/fonts -> /run/host/user-fonts` (if that isn't found, it tries to map `~/.fonts -> /run/host/user-fonts` instead, which is yet another reason why everyone should stop using `~/.fonts`, `~/.themes` etc, since they are low-priority folders for Flatpak; the correct path is always `~/.local/share/whateverdir`).
