### ISSUE TITLE
Provide flatpak for Ubuntu LTS 14.04

### ISSUE THREAD

**Issue by JLuc** [flatpak/flatpak#956]
Ubuntu LTS is currently 14.04 and will be so until 2019

Could flatpak be provided for current Ubuntu LTS ?

**Comment by alexlarsson** [comment]
I believe its possible to create one (there was a 14.04 build at some point). However I don't really have time to do this.

**Comment by smcv** [comment]
> Ubuntu LTS is currently 14.04 and will be so until 2019

The most recent LTS is 16.04. 14.04 may well still be supported by Canonical, but it is not the current or recommended LTS release.

If you are in an environment that is so change-averse that you cannot upgrade from 14.04 to 16.04, then installing unofficial third-party builds of software for the host OS (including Flatpak) is probably not a great thing to be doing either...

The main issue in backporting Flatpak is its dependency on GLib. Flatpak 0.8.x officially requires GLib 2.44 (Ubuntu 15.04 or later). It is possible to backport it to GLib 2.42 (Debian 8) with the patches in <https://packages.debian.org/source/jessie-backports/flatpak>, so that would be a good starting point. I don't know whether anything else is needed to go back from 2.42 to 2.40 (which is in Ubuntu 14.04).

You are unlikely to get a particularly good experience by using Flatpak for typical desktop applications without xdg-desktop-portal-gtk, which in addition to GLib requires a recent GTK+ (significantly newer than Debian 8). Debian 9 and Ubuntu 17.04 are suitable, but running xdg-desktop-portal-gtk on older distributions like Debian 8 or Ubuntu 16.04 LTS would require additional backporting work. Ubuntu 14.04 is probably too old for backporting to be feasible.

**Comment by JLuc** [comment]
New Ubuntu 18.04 is LTS too
