### ISSUE TITLE
Support applications being renamed or deprecated/deleted

### ISSUE THREAD

**Issue by alexlarsson** [flatpak/flatpak#963]
Sometimes apps change names, or just get deleted. We need to support some kind of tombstone for these to warn users, or even automatically forward to the new one.

**Comment by ramcq** [comment]
I think we need two metadata entries - one is easy, a metadata on a "we're done here now, go somewhere else" commit which is essentially the same as: https://github.com/ostreedev/ostree/pull/874

However, to actually unpick this and eg preserve the per-app data, config, cache, etc, we need a way for flatpak run to also pick up and move the data belonging to a certain app (even if this is the first time the user has run the new app, and the old one was removed by another user / on the system repo / etc). So we have an additional requirement for metadata that flatpak run can find on a deployed app in order to recognise it's old name and move it before proceeding. Not sure where this would best go - as:former-app-ids in the deploy file?

**Comment by pwithnall** [comment]
> Not sure where this would best go - as:former-app-ids in the deploy file?

Be careful about the trust here. If an arbitrary malicious app can say its `as:former-app-ids` contains `com.someotherapp.ContainsAllYourSecrets`, installing it and running it will give it access to things it shouldn’t have access to. Since trust is already established in the old installed app, it’s probably better to point to the new app from there, rather than pointing to the old app from the new one.

**Comment by ramcq** [comment]
So this can't be a property defined by the new app, it needs to be local state which is created when the app ID is changed? That feels like it would require a lot of plumbing between pulling and deploying to make happen, but I could have another poke around.

**Comment by pwithnall** [comment]
It could be a property defined by the new app, but you’d need to sign it with the key from the old app, and keep the key binding information (remote config, GPG keys) around from the old app so you know they’re still trusted. That’s probably complex.

Handling the old app pointing to the new one should be easy if the new app is installed in the same transaction as the old one is updated and the tombstone found, right? Is there some reason you were thinking of porting the old app’s data on first run of the new app?

**Comment by ramcq** [comment]
> Is there some reason you were thinking of porting the old app’s data on first run of the new app?

The system apps can be updated behind the user's back - even when the user's ~ is not even mounted/available unless they are logged in. So "flatpak run" has to be able to put this back together and move the user's app data if needed.

**Comment by alexlarsson** [comment]
Minimal support for this is in, but the rename support is not handled yet.

**Comment by mwleeds** [comment]
We have had support for marking apps end-of-life or end-of-life-rebase for years now, so I think we can close this.
