### ISSUE TITLE
FAQ: can flatpak reuse shared libraries of a given version across applications?

### ISSUE THREAD

**Issue by cirosantilli** [flatpak/flatpak#984]
This what I wanted to find at: http://flatpak.org/faq.html

I'm asking this to decide if this is disk usage efficient enough to be worth me looking into it further :-)

**Comment by TingPing** [comment]
Not sure if that FAQ is intended for users or developers but: Yes applications depend upon runtimes which are shared libraries among other things.

**Comment by Hi-Angel** [comment]
@TingPing I am interested in this as a user — I wouldn't like to have a packaging system that can't reuse already existing dependencies, and given the hype around flatpack this is the first question I'd ask.

**Comment by TingPing** [comment]
@Hi-Angel At the end of the day Flatpak is a bundling system, it shares what it can but if you fear bundling you won't be happy anyway.

**Comment by Hi-Angel** [comment]
@TingPing well, let me put another way: I'm personally okay with HDD space it might take for different versions of libraries. I'm not okay though with RAM space for the case when multiple apps are using a library of same version. You said that it does share them, which is nice :)

**Comment by TingPing** [comment]
@Hi-Angel If it is the *exact* same version of the library no extra ram should be used.

**Comment by Hi-Angel** [comment]
@TingPing what about such a use-case: let's say, a flatpack Firefox depends on libFOO, and comes bundled with it. However the out-of-flatpack system already have apps using this exact version of libFOO, which is installed out of flatpack. When Firefox starts, will it duplicate libFOO in RAM or not?

I imagine this to be extremely common, because there always would be packages installed with native package manager.

**Comment by TingPing** [comment]
> When Firefox starts, will it duplicate libFOO in RAM or not?

This is more of a general Linux question and I'm not certain. I am confident few to no distros actually have upstream bundled libs and even Flatpak avoids upstream bundled binaries when possible so this exact situation simply doesn't happen 

> I imagine this to be extremely common, because there always would be packages installed with native package manager.

I actually don't think it is that common. If you look at distros you have LTS like Ubuntu which has far older libraries, you have rolling like Arch which have newer libraries, and there is some extremely narrow in between where there will be overlap in exact version matches.

**Comment by alexlarsson** [comment]
> When Firefox starts, will it duplicate libFOO in RAM or not?

The kernel will only avoid in-ram duplication if the file is the same inode. This is true for library files shared between apps and runtimes in a single flatpak installation (i.e. all --user, or all --system installs). However, it will not be shared with libraries that are on the host, even if the files happen to be identical.

**Comment by brianjmurrell** [comment]
As I understand it, a Flatpak runtime comes with the complete, soup-to-nuts set of libraries that it needs, all the way down to and including glibc.

Given what @alexlarsson says, that means that there **will** be in-RAM duplication of many libraries which might even be at the same version when the "system" (non-flatpak distributed -- RPM for example) starts it's applications and then when Flatpak bundled applications start running and use either their bundled versions of such libraries and/or the Flatpak runtime's bundled libraries.

Moreover, I would suspect that if you were to want to run applications from several different Flatpak runtimes (i.e. some GNOME, some KDE), you would get further in-RAM duplication of libraries which again could actually all be at the same version.

Is my understanding correct?

**Comment by matthiasclasen** [comment]
Identical files between different runtimes and apps in the same installation are hardlinked, so they will get deduplicated by the kernel. That is not true between runtimes/apps and the host system. But any duplications there would be considered accidental, it is expected that the host system may have wildly different versions, say GNOME 3.30 apps on RHEL7...

**Comment by brianjmurrell** [comment]
Right, but if the runtime and the system have duplicate (in terms of ABI compatibility) versions of say glibc, there is a lost opportunity to use one single shared copy in RAM, correct?

glibc being of course just one example of a library that could be shared between system and a runtime but wouldn't be.

**Comment by TingPing** [comment]
> Right, but if the runtime and the system have duplicate (in terms of ABI compatibility) versions of say glibc, there is a lost opportunity to use one single shared copy in RAM, correct?

`glibc` is very likely the *only* time this is true but yes.

**Comment by AstroDrabb** [comment]
Does a flatpak attempt to load from the system library path first and then its own packaged libraries? This would be a simple way to not load identical libraries from different paths.

**Comment by refi64** [comment]
It can't load from the system path because it uses different libraries than the system does.

**Comment by matthiasclasen** [comment]
nothing actionable here

**Comment by brianjmurrell** [comment]
@TingPing said:
> glibc is very likely the only common case this is true but yes sometimes.

How about the entire GNOME stack?

**Comment by TingPing** [comment]
> How about the entire GNOME stack which I have installed through rpm/yum.

Did we really need to bump this discussion?

Plenty of libs in the GNOME runtime will not match the ABI of GNOME libs on your host.

If you hate bundling don't use Flatpak.

**Comment by matthiasclasen** [comment]
You can use flatpak even if you hate bundling. The runtime split is about preserving the isolation, while mitigating the worst duplication of bundling.

**Comment by TingPing** [comment]
They have been complaining on this issue for an entire year, clearly they conceptually disagree with all duplication in which case they will never be satisfied with flatpak.

**Comment by brianjmurrell** [comment]
In all honesty, duplication is not the main reason I avoid flatpak.  It's a reason but it's much lower in importance to the security problems I see.

The main reason is the shifting of managing dependency vulnerability updates from distro-responsible maintainers to every individual software developer/packager.

Yes, I understand that the run-times provide the benefit of the distro-responsible dependency maintainers by focusing the responsibility of updating run-times when a vulnerability is discovered.  But that only works for things in the run-times.

It's all of the bundled dependencies that flatpak'd packages need that are not part of the run-time, or are of a version that is incompatible with the run-time supplied version.

As a user, I now have to depend on and trust the maintainer (who is probably the developer) of a flatpak'd package to update his package because he noticed (not sure how -- did he join the mailing list of every one of his dependencies?) one of his dependencies has a vulnerability in it.  And I have to have that same level of trust in every flatpak'd package that bundled the same vulnerable dependency.

So now as a user, I have to trust that all developers of packages that have flatpak'd them are paying attention to the release streams of **all** of their bundled dependencies and are promptly rebuilding and releasing new versions of their flatpak'd applications.

To be pessimistically (but pragmatically) honest, I don't have a high level of confidence that all of those developers are actually doing that.

So as a user, while I understand that the flatpak philosophy on all of that is that that is a "packager problem" (i.e. and not a flatpak problem), ultimately it is flatpak that is enabling this kind of bad behaviour and doing nothing for me as a user to try to resolve or mitigate it, or even know when it's happening.  I won't have any clue how many flatpak installed applications I have installed have vulnerable dependencies bundled with them.

That said, this is probably material for a different ticket.  Or no ticket, since everywhere I read about it, it keeps being written off as a "packager problem" and not a flatpak problem.

**Comment by TingPing** [comment]
@brianjmurrell Yeah this discussion here is not going to result in change really, you can't both bundle and be a distro. I will just say that the idea that distros are magically more secure is misplaced. Debian stable is "secure" because they respond to reported security issues. That means all unreported security issues that were fixed by updates are simply vulnerabilities. The developer being in charge does bring downsides but it also brings upsides in that they can move fast with updates since they do not worry about ABI of other programs.

**Comment by brianjmurrell** [comment]
But do I even know which dependencies are bundled with the flatpaks I have installed, so that I can do my own personal audit?

But even better, why can't the flatpak "infrastructure" detect this situation?  Platforms like GitHub will tell a developer when a project they have bundled (for certain bundling platforms) has security vulnerabilities in it.  Why can't/shouldn't flatpak be able to do the same for the end user (assuming they can't float this back upstream to the flatpack packager even)?

Something like "Hey <end-user> you have a flatpak for package foo installed and it has a bundled component bar which is known to be insecure.  Do you want to remove foo?".

**Comment by matthiasclasen** [comment]
"vulnerable -> remove" is a bit too simple.

Flatpak has a sandbox that limits what application (and bundled) code can do, so weather a vulnerability can be exploited may have different answers depending on whether you run the code on the host or in a flatpak.

But yes, there is active cve monitoring for supported runtimes, and they do get updated.

**Comment by brianjmurrell** [comment]
> "vulnerable -> remove" is a bit too simple.

Shouldn't that be a decision left to the user to make?  A reasonable default of course, for those that don't choose otherwise is good, but ultimately what should be done with applications that have been determined by the flatpak "infrastructure" to be vulnerable due to obsolete dependencies should be up to the user.

> Flatpak has a sandbox that limits what application (and bundled) code can do, so weather a vulnerability can be exploited may have different answers depending on whether you run the code on the host or in a flatpak.

Except that my reading seems to indicate that the application controls whether it's sandboxed or not (never trust the client!) and most applications are opting out, probably for the same reasons that they are flatpaking (bundling) in the first place -- because it's the "least hassle".

> But yes, there is active cve monitoring for supported runtimes, and they do get updated.

The runtimes is not what I am worried about.  I have a relatively much higher confidence that the security of the runtime is being paid attention to.  It's the security of the bundled dependencies in every flatpak'd package that I am most concerned about.

**Comment by damianatorrpm** [comment]
@everyone Sorry for posting in this thread.
@brianjmurrell 

> The runtimes is not what I am worried about. I have a relatively much higher confidence that the security of the runtime is being paid attention to. It's the security of the bundled dependencies in every flatpak'd package that I am most concerned about
Fedora has it's own flatpak repo by the way 
https://blog.fishsoup.net/2018/12/04/flatpaks-in-fedora-now-live/
flatpak remote-add fedora oci+https://registry.fedoraproject.org

If one is truly worried about that you can use only flatpaks that are actually build out of distro-packages.
